import {ROLES,ROLE_MAP,MACHINES,SYMBOLS,FURNITURE,CLOTHES,ACCESSORIES,CATALOG,BY_ID,THEMES,RELEASE} from './data.mjs';
import * as store from './store.mjs';
import {beginSpin,settle,toyReroll} from './slots.mjs';
import {canPlace,supports,move} from './room.mjs';
const $=s=>document.querySelector(s),root=$('#app'),dialog=$('#dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>n.toLocaleString('zh-TW');
let recovery=false,page='welcome',selectedRole='joy',machine='classic',busy=false,operation=false,draft=null,draftRole=null,draftBaseline=null,selected=null,undo=[],redo=[],shopFilter='furniture',shopTheme='all',previewItem=null,lastResult=null,lastGrid=null,activity='',pose='stand',photoMode=false,aidTimer=null,aidClicks=0,aidStart=0;
const imgCache=new Map();
function picture(src,alt,cls=''){return `<img src="${src}" alt="${esc(alt)}" class="${cls}" draggable="false">`}
function button(label,action,extra='',cls=''){return `<button type="button" class="wood-button ${cls}" data-action="${action}" ${extra}>${label}</button>`}
function avatar(role,s=store.get(),cls=''){const r=ROLE_MAP[role],o=s.outfits[role];return `<div class="avatar ${cls} ${pose==='dance'?'dancing':''}">${picture(o.suit==='original'?r.original:r.outfit,r.name,'body-art')}${o.accessory?picture(BY_ID[o.accessory].art,BY_ID[o.accessory].name,'worn '+o.accessory):''}</div>`}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200)}
let audio;function sound(win=false){if(!store.get().settings.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();[0,1,2].slice(0,win?3:1).forEach((v,i)=>{const osc=audio.createOscillator(),g=audio.createGain();osc.type='sine';osc.frequency.value=(win?520:300)*[1,1.25,1.5][i];g.gain.setValueAtTime(.035,audio.currentTime+i*.1);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+i*.1+.16);osc.connect(g);g.connect(audio.destination);osc.start(audio.currentTime+i*.1);osc.stop(audio.currentTime+i*.1+.2)})}catch{}}
function modal(title,content){dialog.innerHTML=`<div class="modal-top"><h2>${title}</h2>${button('關閉','close-dialog','','small')}</div>${content}`;if(!dialog.open)dialog.showModal()}
function confirmAction(title,message,label,fn){modal(title,`<p>${message}</p><div class="actions">${button('取消','close-dialog')}${button(label,'confirm','','primary')}</div>`);dialog.querySelector('[data-action="confirm"]').onclick=async()=>{dialog.close();await guarded(fn)}}
async function guarded(fn){if(operation)return;operation=true;try{await fn()}catch(e){toast(e.message||'操作無法完成')}finally{operation=false;}}
function header(s){const r=ROLE_MAP[s.role];return `<header class="topbar"><a href="../../index.html?view=game-hub" class="back-link" aria-label="返回網站遊戲大廳">‹ CxQ</a><button class="identity" data-action="characters">${picture(r.original,r.name)}<span>${r.name}<small>更換夥伴</small></span></button><div class="wallet">${picture('art/coin.webp','金幣')}<b>${number(s.coins)}</b><small>金幣</small></div>${button('設定','settings','','small')}</header>`}
const navs=[['town','小鎮'],['arcade','拉霸館'],['home','小屋'],['wardrobe','衣櫃'],['shop','商店']];
function nav(){return `<nav class="bottom-nav" aria-label="遊戲導航">${navs.map(([id,name])=>button(name,'navigate',`data-page="${id}" ${busy?'disabled':''}`,page===id?'active':'')).join('')}</nav>`}
function heading(kicker,title,desc){return `<div class="section-heading"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${desc}</p></div>`}
function welcome(s){return `<main class="welcome"><div class="welcome-art">${picture('art/cover.webp','童話角色在幸運小鎮購物、玩拉霸與布置小屋')}</div><div class="welcome-copy"><span class="eyebrow">CxQ · 製作中｜可遊玩</span><h1>幸運小鎮</h1><p>轉出驚喜，布置你的小日子。</p><div class="actions">${s.started?button(`和${ROLE_MAP[s.role].name}繼續生活`,'continue','','primary'):button('開始生活','characters','','primary')}${s.started?button('選擇其他夥伴','characters'):''}${button('存檔與備份','saves')}</div><p class="fine">10 位夥伴 · 6 種機台 · 自由布置與換裝<br>只有金幣一種貨幣，已購物品永久保留。</p><a href="../../index.html?view=game-hub">返回 CxQ 遊戲大廳</a></div></main>`}
function characters(s){const r=ROLE_MAP[selectedRole];return `<main class="character-page">${heading('MEET YOUR COMPANION','今天想和誰一起生活？','10 位夥伴自由選擇；金幣共用，各自保存小屋與穿搭。')}<div class="character-layout"><section class="character-preview illustrated-panel">${avatar(r.id,s)}<div><span class="eyebrow">${r.title}</span><h2>${r.name}</h2><p>${r.desc}</p><small>${esc(s.rooms[r.id].name)} · ${s.rooms[r.id].items.length} 件家具</small>${button(`和${r.name}一起出門`,'enter',`data-role="${r.id}"`,'primary')}</div></section><div class="role-grid">${ROLES.map(x=>`<button class="role-card ${r.id===x.id?'selected':''}" data-action="select-role" data-role="${x.id}" aria-pressed="${r.id===x.id}">${picture(x.original,x.name)}<b>${x.name}</b><small>${x.title}</small></button>`).join('')}</div></div></main>`}
function town(s){const wish=BY_ID[s.wishes[0]];return `<main>${heading('A LITTLE LUCK, A LITTLE LIFE',`${ROLE_MAP[s.role].name}，歡迎回家`, '去遊戲館轉出驚喜，再把喜歡的東西帶回家。')}<section class="town-scene">${picture('art/town.webp','小鎮廣場，遊戲館、家居店、服飾店與小屋','scene-backdrop')}<div class="town-character">${avatar(s.role,s)}</div>${[['arcade','幸運遊戲館','town-arcade'],['home','回自己的小屋','town-home'],['shop','家具與服飾','town-shop'],['wardrobe','換一套新衣','town-clothes']].map(([p,n,c])=>button(n,'navigate',`data-page="${p}"`,c)).join('')}</section><div class="town-bottom"><section class="paper"><span class="eyebrow">MY LITTLE WISH</span><h2>下一個小願望</h2>${wish?`<div class="wish-preview">${picture(wish.art,wish.name)}<div><b>${wish.name}</b><p>${number(s.coins)}／${number(wish.price)} 金幣</p><progress max="${wish.price}" value="${Math.min(s.coins,wish.price)}"></progress></div></div>${button('去看看','navigate','data-page="shop"')}`:'<p>到商店把喜歡的物品加入願望清單。</p>'+button('逛逛商店','navigate','data-page="shop"')}</section><section class="paper"><span class="eyebrow">TODAY IN TOWN</span><h2>今天的小日子</h2><p>已旋轉 ${number(s.stats.spins)} 次 · 最大獎 ${number(s.stats.biggest)} 金幣</p><div class="actions">${button('生活委託','tasks')}${button('生活補助','aid')}${button('收藏與相簿','collection')}</div></section></div></main>`}
function arcade(s){return `<main>${heading('THE LUCKY ARCADE','每一台，都有不同的驚喜','所有角色都能玩所有機台。選你喜歡的節奏，不必先解鎖。')}<div class="machine-grid">${MACHINES.map(m=>`<button class="machine-card ${m.theme}" data-action="open-machine" data-machine="${m.id}">${picture(`art/machine-${m.id}.webp`,m.name)}<span class="machine-copy"><small>${m.tag}</small><strong>${m.name}</strong><span>${m.desc}</span><b>每次 ${m.cost} 金幣 · 進入機台 →</b>${s.stats.visited.includes(m.id)?'<i>已體驗</i>':''}</span></button>`).join('')}</div><div class="inline-note">金幣低於 100 時，可到櫃台完成小幫忙領補助。${button('遊戲館櫃台','aid','','small')}</div></main>`}
function reels(g,m){return `<div class="reels" style="--columns:${m.cols};--rows:${m.rows}" aria-label="拉霸結果">${g.flat().map((v,i)=>`<div class="reel-cell" data-index="${i}">${picture(SYMBOLS[v].art,SYMBOLS[v].name)}</div>`).join('')}</div>`}
function machinePage(s){const m=MACHINES.find(x=>x.id===machine),p=s.pending?.machine===machine?s.pending:null,g=p?.grid||lastGrid||Array.from({length:m.rows},()=>Array.from({length:m.cols},(_,i)=>i%6));return `<main class="play-page ${m.theme}"><div class="play-top">${button('‹ 返回機台館','navigate','data-page="arcade"')}<div><span class="eyebrow">${m.tag}</span><h1>${m.name}</h1></div>${button('玩法與獎勵','rules')}</div><div class="machine-layout"><section class="machine-stage machine-${m.id} ${busy?'spinning':''}" aria-busy="${busy}">${picture(`art/machine-${m.id}.webp`,m.name+'機台','cabinet-art')}<div class="reel-window ${m.cols===3?'three':''}">${reels(g,m)}</div></section><aside class="companion-panel">${avatar(s.role,s)}<div class="speech">${esc(busy?'轉輪正在轉動，驚喜馬上揭曉…':lastResult?.note||m.desc)}</div>${m.id==='garden'?`<label>花園成長 ${s.progress.garden}/18<progress value="${s.progress.garden}" max="18"></progress></label>`:''}${m.id==='photo'?`<label>相簿收集 ${s.progress.photo}/12<progress value="${s.progress.photo}" max="12"></progress></label>`:''}</aside></div><section class="spin-controls paper"><div class="result-display" role="status">${lastResult?`本次獲得 <strong>${number(lastResult.win)}</strong> 金幣`:`每次旋轉 ${m.cost} 金幣`}</div>${p?.phase==='choice'&&!busy?`<p>目前可得 ${p.win} 金幣。選一軸保留，或直接收獎。</p><div class="actions">${[0,1,2].map(i=>button(`保留第 ${i+1} 軸`,'toy-keep',`data-keep="${i}"`)).join('')}${button('直接收獎','toy-collect','','primary')}</div>`:`<div class="actions">${p?.phase==='ready'&&!busy?button('接續結算','resume-spin','','primary'):button(busy?'正在旋轉…':s.coins<m.cost?'金幣不足':'開始旋轉','spin',busy||s.coins<m.cost?'disabled':'','primary spin-button')}${s.coins<m.cost?button('申請生活補助','aid'):''}${button(s.settings.fast?'速度：快速':'速度：標準','toggle-setting','data-setting="fast" '+(busy?'disabled':''))}</div>`}<p class="fine">純金幣遊戲 · 結果與扣款先儲存，再播放動畫 · 中途離開可接續結算</p></section></main>`}
function home(s){const room=draft||s.rooms[s.role];return `<main class="home-page ${photoMode?'photo-mode':''}"><div class="home-heading">${heading('A HOME OF YOUR OWN',esc(room.name),draft?'拖曳家具或選取後點格子移動；方向鍵也可微調。選桌椅後加入小物，可放上桌面或座位。':'點家具，和夥伴一起過個舒服的小日子。')}<div class="actions">${draft?button('套用布置','save-room','','primary')+button('取消','cancel-room'):button('布置小屋','edit-room')+button('拍照','photo')+button('房間設定','room-settings')}</div></div><div class="room-canvas-wrap"><canvas id="room-canvas" width="1200" height="800" tabindex="0" aria-label="小屋，選取家具可互動或移動"></canvas><div class="room-caption">${esc(activity||`${ROLE_MAP[s.role].name}正在小屋裡休息。`)}</div></div>${draft?`<section class="edit-tray paper"><div class="actions">${button('左右轉向','rotate-item',!selected?'disabled':'')}${button('收回','remove-item',!selected?'disabled':'')}${button('撤銷','undo',undo.length?'':'disabled')}${button('重做','redo',redo.length?'':'disabled')}</div><div class="inventory-strip">${FURNITURE.filter(i=>s.owned[i.id]).map(i=>{const used=room.items.filter(p=>p.item===i.id).length,available=s.owned[i.id]-used;return `<button class="inventory-item" data-action="place-item" data-item="${i.id}" ${available<1?'disabled':''}>${picture(i.art,i.name)}<span>${i.name}</span><small>可放 ${available}</small></button>`}).join('')}</div><p class="fine">不同角色可使用同一收藏；同一房間的數量不能超過已購件數。布置按「套用」才儲存。</p></section>`:`<div class="home-tools paper"><div class="actions">${button('讓夥伴跳舞','pose','data-pose="dance"')}${button('安靜休息','pose','data-pose="rest"')}${button('站起來','pose','data-pose="stand"')}${button('去買家具','navigate','data-page="shop"')}</div></div>`}</main>`}
function wardrobe(s){const o=s.outfits[s.role],r=ROLE_MAP[s.role];return `<main>${heading('YOUR OWN LITTLE STYLE','今天想穿什麼？',`${r.name}的衣櫃。穿搭獨立保存，購買後隨時更換。`)}<div class="wardrobe-layout"><section class="dressing-room">${picture('art/room.webp','小屋試衣角落','scene-backdrop')}${avatar(s.role,s)}<div class="dressing-name">${r.name}<small>${o.suit==='original'?'原始造型':'居家新衣'}</small></div></section><section class="paper"><h2>服裝</h2><div class="wardrobe-items"><button class="item-card ${o.suit==='original'?'selected':''}" data-action="wear" data-item="original">${picture(r.original,'原始造型')}<b>原始造型</b></button>${CLOTHES.filter(i=>i.role===s.role).map(i=>`<button class="item-card ${o.suit===i.id?'selected':''}" data-action="${s.owned[i.id]?'wear':'product'}" data-item="${i.id}">${picture(i.art,i.name)}<b>${i.name}</b><small>${s.owned[i.id]?'點擊換穿':i.price+' 金幣・試穿購買'}</small></button>`).join('')}</div><h2>配件</h2><div class="wardrobe-items accessories">${button('卸下配件','wear','data-item="none"')}${ACCESSORIES.map(i=>`<button class="item-card ${o.accessory===i.id?'selected':''}" data-action="${s.owned[i.id]?'wear':'product'}" data-item="${i.id}">${picture(i.art,i.name)}<b>${i.name}</b><small>${s.owned[i.id]?'點擊配戴':i.price+' 金幣'}</small></button>`).join('')}</div><div class="actions">${button('儲存這套穿搭','save-preset')}${button('去小屋拍照','navigate','data-page="home"')}</div><div class="presets">${o.presets.map((p,i)=>button(`穿搭 ${i+1}`,'load-preset',`data-index="${i}"`)).join('')}</div><p class="fine">最多保存 4 套，保存第 5 套會替換最舊的一套。新衣為每個角色個別製作，保留角色外形特徵。</p></section></div></main>`}
function shop(s){const items=CATALOG.filter(i=>i.kind===shopFilter&&(shopTheme==='all'||i.theme===shopTheme||i.role===shopTheme));return `<main>${heading('BRING SOMETHING NICE HOME','小鎮選物店','家具、服裝與配件都能直接用金幣購買，不需要抽到指定物品。')}<div class="shop-tabs">${[['furniture','家具'],['outfit','角色新衣'],['accessory','配件']].map(([id,n])=>button(n,'shop-filter',`data-filter="${id}"`,shopFilter===id?'active':'')).join('')}<label class="filter-label">${shopFilter==='furniture'?'風格':'適用角色'}<select id="shop-theme"><option value="all">全部</option>${(shopFilter==='furniture'?[['living','奶油日常'],['forest','森林花園'],['rose','草莓午茶'],['night','星月晚安']]:shopFilter==='outfit'?ROLES.map(r=>[r.id,r.name]):[]).map(([id,n])=>`<option value="${id}" ${shopTheme===id?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="catalog-grid">${items.map(i=>`<button class="item-card" data-action="product" data-item="${i.id}">${picture(i.art,i.name)}<b>${i.name}</b><small>${i.kind==='furniture'?`${i.w}×${i.h} 格 · ${i.action}`:i.role?'適用：'+ROLE_MAP[i.role].name:'10 位夥伴通用'}</small><strong>${number(i.price)} 金幣</strong><span>${s.owned[i.id]?'已擁有 '+s.owned[i.id]+(i.kind==='furniture'?' 件':''):'查看與預覽'}${s.wishes.includes(i.id)?' · 願望中':''}</span></button>`).join('')}</div></main>`}
function render(){const s=store.get();root.innerHTML=recovery?`<main class="recovery-page paper"><h1>先找回你的生活紀錄</h1><p>偵測到存檔受損，而且目前沒有有效的本機備份。原始資料已保留，不會自動以新紀錄覆蓋。</p><p>請匯入之前下載的 JSON 備份。</p><div class="actions">${button('開啟備份與匯入','saves')}${button('下載受損紀錄','export-damaged')}</div></main>`:page==='welcome'?welcome(s):header(s)+(page==='characters'?characters(s):page==='town'?town(s):page==='arcade'?arcade(s):page==='machine'?machinePage(s):page==='home'?home(s):page==='wardrobe'?wardrobe(s):shop(s))+nav()+`<footer class="save-line">本機已儲存 · ${new Date(s.savedAt).toLocaleTimeString('zh-TW')} ${button('備份','saves','','text-button')}</footer>`;document.body.classList.toggle('reduced',!!s.settings.reduced);if(page==='home'){const canvas=$('#room-canvas');canvas.setAttribute('aria-busy','true');bindRoom(canvas);requestAnimationFrame(()=>drawRoom());}if(page==='shop')$('#shop-theme').onchange=e=>{shopTheme=e.target.value;render()};}
async function navigate(next){if(busy||store.get().pending)throw Error('請先完成旋轉。');if(draft){confirmAction('離開布置？','這次尚未套用的變更會取消。','取消變更並離開',async()=>{draft=null;selected=null;page=next;render()});return;}activity='';photoMode=false;pose='stand';page=next;render();window.scrollTo({top:0,behavior:'instant'})}
function product(id){const s=store.get(),i=BY_ID[id];previewItem=i;const owned=s.owned[id]||0;modal(i.name,`<div class="product-layout"><div class="product-visual">${i.kind==='outfit'?`<div class="avatar">${picture(i.art,i.name,'body-art')}</div>`:picture(i.art,i.name)}</div><div><p>${i.kind==='furniture'?`${i.w}×${i.h} 格 · 可互動：${i.action}`:i.role?`專為${ROLE_MAP[i.role].name}製作的居家服。`:'10 位角色都能配戴。'}</p><h3>${i.price} 金幣</h3><p>目前有 ${number(s.coins)} 金幣${s.coins<i.price?`，還差 ${i.price-s.coins}。`:'。'}${owned?` 已擁有 ${owned} 件。`:''}</p><div class="actions">${button(i.kind!=='furniture'&&owned?'已擁有':s.coins<i.price?'金幣不足':'購買','buy',`data-item="${id}" ${s.coins<i.price||(i.kind!=='furniture'&&owned)||owned>=50?'disabled':''}`,'primary')}${button(s.wishes.includes(id)?'移出願望':'加入願望','wish',`data-item="${id}"`)}${i.kind==='furniture'?button('放進小屋預覽','preview-room',`data-item="${id}"`):''}</div></div></div>`)}
function roomItemSize(p){const i=BY_ID[p.item];return {w:i.w,h:i.h}}
function emptySpot(room,item){for(let y=0;y<room.size;y++)for(let x=0;x<room.size;x++){const p={uid:crypto.randomUUID(),item,x,y,flip:false};if(canPlace(room,p))return p}return null}
function remember(){undo.push(structuredClone(draft));if(undo.length>30)undo.shift();redo=[]}
function imageLoaded(src){if(!imgCache.has(src)){const i=new Image();const p=new Promise((resolve,reject)=>{i.onload=()=>resolve(i);i.onerror=()=>reject(Error('素材載入失敗：'+src))});i.src=src;imgCache.set(src,p)}return imgCache.get(src)}
const floor={x:130,y:390,w:940,h:325};
function roomRect(p,room){if(p.onTop){const parent=room.items.find(x=>x.uid===p.onTop),b=roomRect(parent,room);return {x:b.x,y:b.y-b.h*.52,w:75,h:85}}const size=roomItemSize(p),small=['tea','flower','cushion','pillow','clock','basket','toy-bear','plant'].includes(p.item),scale=small?.7:1;return {x:floor.x+(p.x+.5*size.w)/room.size*floor.w,y:floor.y+(p.y+.8*size.h)/room.size*floor.h,w:Math.max(100,size.w/room.size*floor.w*.9)*scale,h:Math.max(135,size.h/room.size*floor.h*3.15)*scale}}
let drawToken=0;
async function drawRoom(canvas=$('#room-canvas'),room=draft||store.get().rooms[store.get().role],preview=null){if(!canvas)return;const token=++drawToken,s=store.get(),ctx=canvas.getContext('2d'),r=ROLE_MAP[s.role],o=s.outfits[s.role];const items=preview?[...room.items,preview]:room.items;try{const [bg,body,...arts]=await Promise.all([imageLoaded(THEMES.find(t=>t.id===room.theme).art),imageLoaded(['rest','sit','tea','read','draw','eat'].includes(pose)&&!draft?'art/sit-'+(o.suit==='original'?'':'outfit-')+s.role+'.webp':o.suit==='original'?r.original:r.outfit),...items.map(p=>imageLoaded(BY_ID[p.item].art))]);if(canvas===$('#room-canvas')&&token!==drawToken)return;ctx.clearRect(0,0,1200,800);ctx.drawImage(bg,0,0,1200,800);if(draft){ctx.strokeStyle='#8f735650';ctx.lineWidth=2;for(let i=0;i<=room.size;i++){const x=floor.x+i/room.size*floor.w,y=floor.y+i/room.size*floor.h;ctx.beginPath();ctx.moveTo(x,floor.y);ctx.lineTo(x,floor.y+floor.h);ctx.stroke();ctx.beginPath();ctx.moveTo(floor.x,y);ctx.lineTo(floor.x+floor.w,y);ctx.stroke()}}
 const entries=items.map((p,i)=>({p,art:arts[i]})).sort((a,b)=>((a.p.onTop?room.items.find(x=>x.uid===a.p.onTop):a.p).y+roomItemSize(a.p.onTop?room.items.find(x=>x.uid===a.p.onTop):a.p).h+(a.p.onTop?.01:0))-((b.p.onTop?room.items.find(x=>x.uid===b.p.onTop):b.p).y+roomItemSize(b.p.onTop?room.items.find(x=>x.uid===b.p.onTop):b.p).h+(b.p.onTop?.01:0)));for(const {p,art} of entries){const b=roomRect(p,room),scale=Math.min(b.w/art.width,b.h/art.height),w=art.width*scale,h=art.height*scale;ctx.save();ctx.translate(b.x,b.y);if(p.flip)ctx.scale(-1,1);ctx.drawImage(art,-w/2,-h,w,h);ctx.restore();if(draft&&p.uid===selected){ctx.strokeStyle='#ce7456';ctx.lineWidth=4;ctx.strokeRect(b.x-b.w/2,b.y-b.h,b.w,b.h)}if(preview?.uid===p.uid){ctx.strokeStyle='#7b9963';ctx.lineWidth=4;ctx.strokeRect(b.x-b.w/2,b.y-b.h,b.w,b.h)}}
 const selectedItem=items.find(p=>p.uid===selected),anchor=selectedItem?.onTop?items.find(p=>p.uid===selectedItem.onTop):selectedItem,b=anchor&&!draft?roomRect(anchor,room):{x:700,y:700};if(anchor&&!draft&&!['chair','sofa','bed','stool','ottoman','cushion'].includes(anchor.item))b.x+=b.w*.65;let height=['rest','sit','tea','read','draw','eat'].includes(pose)?220:250,width=height*body.width/body.height;ctx.save();if(pose==='dance')ctx.translate(0,-12);ctx.drawImage(body,b.x-width/2,b.y-height,width,height);if(o.accessory){const acc=await imageLoaded(BY_ID[o.accessory].art);const size=o.accessory==='accessory-bow'?65:55;const ax=b.x+(o.accessory==='accessory-bag'?width*.22:0),ay=b.y-height*(o.accessory==='accessory-bow'?.82:.36);ctx.drawImage(acc,ax-size/2,ay-size/2,size,size)}ctx.restore();if(photoMode){ctx.fillStyle='#fff9ed';ctx.fillRect(30,740,1140,40);ctx.fillStyle='#715649';ctx.font='20px sans-serif';ctx.fillText(`CxQ 幸運小鎮 · ${r.name} · ${room.name}`,50,768)}canvas.setAttribute('aria-busy','false');
 }catch(e){toast(e.message)}}
function bindRoom(canvas){let down=null;const point=e=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left)/b.width*1200,y:(e.clientY-b.top)/b.height*800}};const hit=q=>{const room=draft||store.get().rooms[store.get().role];return [...room.items].sort((a,b)=>b.y-a.y||Number(!!b.onTop)-Number(!!a.onTop)).find(p=>{const b=roomRect(p,room);return q.x>b.x-b.w/2&&q.x<b.x+b.w/2&&q.y>b.y-b.h&&q.y<b.y})};canvas.onpointerdown=e=>{down=point(e);const p=hit(down);if(p){selected=p.uid;drawRoom()}canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=e=>{const q=point(e),room=draft||store.get().rooms[store.get().role],distance=down?Math.hypot(q.x-down.x,q.y-down.y):0;if(draft){const p=room.items.find(x=>x.uid===selected);if(p&&((distance>12)||!hit(q))){const next={...p,x:Math.floor((q.x-floor.x)/floor.w*room.size),y:Math.floor((q.y-floor.y)/floor.h*room.size)};if(canPlace(room,next)){remember();move(draft,p,next)}else toast('這裡放不下，請選空位。')}render()}else{const p=hit(q);if(p){selected=p.uid;const i=BY_ID[p.item];activity=`${ROLE_MAP[store.get().role].name}：${i.action}。`;pose=/休息|小憩|放鬆/.test(i.action)?'rest':/茶/.test(i.action)?'tea':/閱讀/.test(i.action)?'read':/畫/.test(i.action)?'draw':/點心/.test(i.action)?'eat':i.id==='record'?'dance':'stand';store.change(s=>{resetDay(s);s.tasks.interactions++}).then(()=>{sound();render()}).catch(e=>toast(e.message))}}down=null};canvas.onkeydown=e=>{if(!draft||!selected||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const p=draft.items.find(x=>x.uid===selected),next={...p,x:p.x+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),y:p.y+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)};if(canPlace(draft,next)){remember();move(draft,p,next);render();requestAnimationFrame(()=>document.querySelector('#room-canvas')?.focus())}};}
async function animatePending(){const p=store.get().pending;if(!p)return;machine=p.machine;page='machine';busy=true;render();const settings=store.get().settings,delay=settings.reduced?80:settings.fast?180:460;for(const frame of p.frames){const el=$('.reel-window');if(el)el.innerHTML=reels(frame,MACHINES.find(m=>m.id===machine));sound();await new Promise(r=>setTimeout(r,delay));}busy=false;lastGrid=p.grid;if(p.phase==='ready'){await settle(store);lastResult={win:p.win,note:p.note};sound(p.win>0);if(p.win>=50)toast(`獲得 ${p.win} 金幣！可以去看看願望清單。`)}render()}
function resetDay(s){const day=Math.floor((Date.now()-new Date().getTimezoneOffset()*60000)/86400000);if(s.tasks.day!==day)s.tasks={day,interactions:0,claimed:[]}}
function tasks(){const s=store.get(),same=s.tasks.day===Math.floor((Date.now()-new Date().getTimezoneOffset()*60000)/86400000),claimed=same?s.tasks.claimed:[],n=same?s.tasks.interactions:0;const list=[['spin','體驗生活的驚喜','累積旋轉 5 次',s.stats.spins>=5,40],['visit','逛逛不同機台','體驗 3 種機台',s.stats.visited.length>=3,50],['life','陪夥伴過日子','今天與家具互動 3 次',n>=3,30]];modal('小鎮生活委託',`<p>每日可各領一次；沒有連續登入要求。前兩項依累積體驗判定。</p>${list.map(([id,title,desc,ok,reward])=>`<div class="task-row"><div><b>${title}</b><small>${desc} · ${reward} 金幣</small></div>${button(claimed.includes(id)?'已領取':ok?'領取':'尚未完成','claim-task',`data-task="${id}" ${claimed.includes(id)||!ok?'disabled':''}`)}</div>`).join('')}`)}
function aid(){const s=store.get(),left=Math.max(0,180000-(Date.now()-s.aidAt));if(s.coins>=100){modal('遊戲館櫃台',`<p>金幣低於 100 枚時，可以完成一件小幫忙，補到 300 枚。</p><p>目前有 ${s.coins} 枚，先繼續享受小鎮生活吧。</p>`);return}if(left){modal('櫃台正在準備金幣袋',`<p>還有 <b>${Math.ceil(left/1000)}</b> 秒可再申請。離線時間也會計入。</p><p>這段時間可以布置、換裝或拍照。</p>`);return}modal('幫個小忙，繼續玩吧',`<p>完成約 20 秒的小幫忙，金幣將從 ${s.coins} 補到 300。完成後冷卻 3 分鐘。</p><div class="actions">${button('整理三個抱枕','aid-start','data-job="cushion"')}${button('照顧三盆植物','aid-start','data-job="plant"')}</div>`)}
function startAid(job){aidClicks=0;aidStart=Date.now();modal(job==='plant'?'幫植物喝點水':'整理休息區',`<p>點選三個${job==='plant'?'盆栽':'抱枕'}，再等櫃台備好金幣袋。</p><div class="aid-objects">${[0,1,2].map(i=>`<button data-action="aid-click" data-index="${i}" aria-label="${job==='plant'?'澆水':'整理'}第 ${i+1} 個">${picture(`art/furniture-${job}.webp`,job==='plant'?'盆栽':'抱枕')}</button>`).join('')}</div><p id="aid-progress">已完成 0／3</p>${button('領取金幣','aid-claim','disabled','primary')}`);clearInterval(aidTimer);aidTimer=setInterval(()=>{if(!dialog.open){clearInterval(aidTimer);return}const sec=Math.max(0,Math.ceil((20000-(Date.now()-aidStart))/1000));const el=$('#aid-progress');if(el)el.textContent=`已完成 ${aidClicks}／3 · ${sec?'金幣袋準備中 '+sec+' 秒':'金幣袋已備好'}`;const b=dialog.querySelector('[data-action="aid-claim"]');if(b)b.disabled=aidClicks<3||sec>0},500)}
function settings(){const s=store.get();modal('小鎮設定',`<div class="setting-list">${[['sound','音效'],['fast','快速旋轉'],['reduced','減少動態效果']].map(([id,n])=>`<label>${n}<input type="checkbox" data-setting="${id}" ${s.settings[id]?'checked':''}></label>`).join('')}</div><div class="actions">${button('存檔與備份','saves')}${button('回到開始畫面','to-welcome')}</div><p class="fine">製作中｜可遊玩 · ${RELEASE}<br>本機紀錄不會同步到其他裝置；請定期匯出備份。</p>`);dialog.querySelectorAll('input').forEach(el=>el.onchange=()=>guarded(()=>store.change(s=>{s.settings[el.dataset.setting]=el.checked})));}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function exportSave(){download(new Blob([store.pack(store.get())],{type:'application/json'}),`CxQ-幸運小鎮-${new Date().toISOString().replace(/[:.]/g,'-')}.json`);toast('備份已匯出，請保留下載的檔案。')}
function saves(){const s=store.get(),bs=store.backups();modal('存檔與備份',`${recovery?'<p>尚未恢復紀錄。請匯入你已下載的有效備份。</p>':`<p>最後儲存：${new Date(s.savedAt).toLocaleString('zh-TW')}<br>${number(s.coins)} 金幣 · ${ROLE_MAP[s.role].name} · 收藏 ${Object.keys(s.owned).length} 種</p>`}<div class="actions">${button('下載完整備份','export',recovery?'disabled':'','primary')}${button('匯入備份','import')}</div><input id="import-file" type="file" accept=".json,application/json" hidden><h3>最近五份有效紀錄</h3>${bs.length?bs.map((b,i)=>`<div class="backup-row"><div>${new Date(b.state.savedAt).toLocaleString('zh-TW')}<small>${b.state.coins} 金幣 · ${ROLE_MAP[b.state.role].name}${b.state.pending?' · 有待結算旋轉':''}</small></div>${button('還原','restore',`data-index="${i}"`)}</div>`).join(''):'<p>操作後會自動產生輪替備份。</p>'}<p class="fine">瀏覽器與 IndexedDB 各保留一份存檔；清除網站資料可能一起刪除。下載到裝置的備份才能獨立保留。</p>${store.damagedCopies().length?button('下載受損紀錄','export-damaged'):''}`);$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2e6){toast('備份檔案過大，請使用本遊戲匯出的 JSON。');return}try{const raw=await file.text(),next=store.unpack(raw);confirmRestore(raw,next)}catch(err){toast('無法匯入：'+err.message)}};}
function confirmRestore(raw,s){const furn=Object.keys(s.owned).filter(id=>BY_ID[id].kind==='furniture').length,clothes=Object.keys(s.owned).filter(id=>BY_ID[id].kind!=='furniture').length;confirmAction('確認還原備份',`備份時間：${new Date(s.savedAt).toLocaleString('zh-TW')}<br>金幣：${number(s.coins)} · 家具 ${furn} 種 · 服裝配件 ${clothes} 種<br>目前紀錄會先加入輪替備份，再套用這份紀錄。`,'備份目前紀錄並還原',async()=>{await store.restore(raw);recovery=false;draft=null;selected=null;lastResult=null;lastGrid=null;page=store.get().started?'town':'welcome';if(store.get().pending)await animatePending();else render();toast('已還原備份。')})}
function collection(){const s=store.get();modal('收藏與生活相簿',`<p>家具 ${FURNITURE.filter(i=>s.owned[i.id]).length}／${FURNITURE.length} · 新衣 ${CLOTHES.filter(i=>s.owned[i.id]).length}／10 · 配件 ${ACCESSORIES.filter(i=>s.owned[i.id]).length}／3</p><h3>機台紀念</h3><div class="collection-machines">${MACHINES.map(m=>`<div>${picture(`art/machine-${m.id}.webp`,m.name)}<b>${m.name}</b><small>${s.stats.visited.includes(m.id)?'已體驗':'還沒體驗'}</small></div>`).join('')}</div><h3>${ROLE_MAP[s.role].name}的拍照紀念</h3><p class="fine">圖片會下載到裝置；這裡保存最近 20 次拍照日期與名稱。</p>${s.albums[s.role].map(a=>`<p>${esc(a.name)} · ${new Date(a.at).toLocaleString('zh-TW')}</p>`).join('')||'<p>去小屋拍一張生活照吧。</p>'}`)}
async function photo(){photoMode=true;render();await drawRoom();modal('留下一張小日子',`<p>下載目前角色與房間的完整照片。</p><div class="actions">${button('下載小屋照片','download-photo','','primary')}${button('完成拍照','finish-photo')}</div>`)}
async function capture(){const canvas=$('#room-canvas');await drawRoom(canvas);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error('照片無法產生');const s=store.get(),name=`${ROLE_MAP[s.role].name}-${s.rooms[s.role].name}`;download(blob,`${name}-${Date.now()}.png`);await store.change(s=>{s.albums[s.role].unshift({name,at:Date.now()});s.albums[s.role]=s.albums[s.role].slice(0,20)});toast('照片已下載，拍照紀念也已儲存。')}
function roomSettings(){const s=store.get(),room=s.rooms[s.role];modal('我的房間',`<label class="field">房間名稱<input id="room-name" maxlength="40" value="${esc(room.name)}"></label>${button('儲存名稱','rename-room')}<h3>牆面與地板主題</h3><div class="theme-grid">${THEMES.map(t=>`<button data-action="room-theme" data-theme="${t.id}">${picture(t.art,t.name)}<b>${t.name}</b><small>${room.theme===t.id?'使用中':s.themes.includes(t.id)?'已解鎖，免費切換':t.price+' 金幣解鎖'}</small></button>`).join('')}</div><h3>擴建空間</h3><p>目前 ${room.size}×${room.size} 格。${room.size===6?'800 金幣擴建到 8×8 格，保留已有布置。':'已擴建完成。'}</p>${room.size===6?button('擴建這個角色的小屋','expand-room',s.coins<800?'disabled':''):''}`)}
root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)handle(b).catch(err=>toast(err.message))});dialog.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled&&b.dataset.action!=='confirm')handle(b).catch(err=>toast(err.message))});dialog.addEventListener('close',()=>{clearInterval(aidTimer);if(photoMode){photoMode=false;render()}});
async function handle(b){const a=b.dataset.action;if(a==='close-dialog'){dialog.close();return}if(a==='select-role'){selectedRole=b.dataset.role;render();return}if(a==='navigate'){await navigate(b.dataset.page);return}if(a==='characters'){if(draft){await navigate('characters');return}if(busy||store.get().pending)throw Error('請先完成旋轉。');selectedRole=store.get().role;page='characters';render();return}if(a==='continue'){page='town';render();return}if(a==='open-machine'){machine=b.dataset.machine;lastGrid=null;lastResult=null;page='machine';render();return}if(a==='product'){product(b.dataset.item);return}if(a==='shop-filter'){shopFilter=b.dataset.filter;shopTheme='all';render();return}if(a==='rules'){const m=MACHINES.find(m=>m.id===machine);modal(m.name+'玩法',`<p>${m.desc}</p><p>${m.rules}</p><p>每次扣 ${m.cost} 金幣。六種圖案等機率出現，所有角色使用相同機率。金幣只用於本遊戲，沒有現金兌換。</p><div class="symbol-guide">${SYMBOLS.map(x=>`<div>${picture(x.art,x.name)}<small>${x.name}</small></div>`).join('')}</div>`);return}if(a==='settings'){settings();return}if(a==='saves'){saves();return}if(a==='export'){exportSave();return}if(a==='import'){$('#import-file').click();return}if(a==='export-damaged'){download(new Blob([JSON.stringify(store.damagedCopies())],{type:'application/json'}),'CxQ-受損存檔原始資料.json');return}if(a==='restore'){const entry=store.backups()[+bIndex(b)];confirmRestore(entry.raw,entry.state);return}if(a==='aid'){aid();return}if(a==='aid-start'){startAid(b.dataset.job);return}if(a==='aid-click'){b.disabled=true;b.classList.add('done');aidClicks++;sound();return}if(a==='tasks'){tasks();return}if(a==='collection'){collection();return}if(a==='room-settings'){roomSettings();return}if(a==='photo'){await photo();return}if(a==='finish-photo'){dialog.close();return}if(a==='to-welcome'){dialog.close();await navigate('welcome');return}
 await guarded(async()=>{
 if(a==='enter'){await store.change(s=>{s.role=b.dataset.role;s.started=true});page='town';pose='stand';render();}
 else if(a==='resume-spin'){await animatePending();}
 else if(a==='spin'){if(busy||store.get().pending)return;await beginSpin(store,machine);await animatePending();}
 else if(a==='toy-keep'){await store.change(s=>{s.pending=toyReroll(s.pending,+b.dataset.keep)},{allowPending:true});await animatePending();}
 else if(a==='toy-collect'){await store.change(s=>{s.pending.phase='ready';s.pending.note='收下這次玩具組合的獎金。'},{allowPending:true});await animatePending();}
 else if(a==='toggle-setting'){await store.change(s=>{s.settings[b.dataset.setting]=!s.settings[b.dataset.setting]});render();}
 else if(a==='buy'){const id=b.dataset.item,i=BY_ID[id];await store.change(s=>{if(s.coins<i.price)throw Error('金幣不足');if(i.kind!=='furniture'&&s.owned[id])throw Error('已擁有這件物品');if((s.owned[id]||0)>=50)throw Error('收藏數量已達上限');s.coins-=i.price;s.owned[id]=(s.owned[id]||0)+1;s.wishes=s.wishes.filter(x=>x!==id)});sound(true);product(id);render();toast(i.name+'已加入收藏。');}
 else if(a==='wish'){const id=b.dataset.item;await store.change(s=>{s.wishes=s.wishes.includes(id)?s.wishes.filter(x=>x!==id):[id,...s.wishes].slice(0,30)});product(id);render();}
 else if(a==='wear'){const id=b.dataset.item;await store.change(s=>{const o=s.outfits[s.role];if(id==='original')o.suit='original';else if(id==='none')o.accessory=null;else{const i=BY_ID[id];if(!s.owned[id]||(i.role&&i.role!==s.role))throw Error('這件衣服不適用或尚未購買');if(i.kind==='outfit')o.suit=id;else o.accessory=id}});render();sound();}
 else if(a==='save-preset'){await store.change(s=>{const o=s.outfits[s.role];o.presets.push({suit:o.suit,accessory:o.accessory});o.presets=o.presets.slice(-4)});render();toast('穿搭已保存。');}
 else if(a==='load-preset'){await store.change(s=>{const o=s.outfits[s.role],p=o.presets[+b.dataset.index];o.suit=p.suit;o.accessory=p.accessory});render();}
 else if(a==='edit-room'){draftRole=store.get().role;draftBaseline=JSON.stringify(store.get().rooms[draftRole]);draft=structuredClone(store.get().rooms[draftRole]);selected=null;undo=[];redo=[];render();}
 else if(a==='cancel-room'){confirmAction('取消這次布置？','尚未套用的變更會取消。','取消變更',async()=>{draft=null;selected=null;render()});}
 else if(a==='save-room'){const room=structuredClone(draft);await store.change(s=>{if(s.role!==draftRole||JSON.stringify(s.rooms[draftRole])!==draftBaseline)throw Error('角色或小屋已在其他分頁更新，請取消並重新編輯。');s.rooms[draftRole]=room});draft=null;selected=null;render();toast('小屋布置已儲存。');}
 else if(a==='place-item'){const base=draft.items.find(x=>x.uid===selected);let p=base&&!base.onTop&&supports(base.item,b.dataset.item)?{uid:crypto.randomUUID(),item:b.dataset.item,x:base.x,y:base.y,flip:false,onTop:base.uid}:emptySpot(draft,b.dataset.item);if(p&&!canPlace(draft,p))p=emptySpot(draft,b.dataset.item);if(!p)throw Error('房間沒有足夠空位，可以先收回家具。');remember();draft.items.push(p);selected=p.uid;render();}
 else if(a==='rotate-item'){const p=draft.items.find(x=>x.uid===selected),next={...p,flip:!p.flip};if(!canPlace(draft,next))throw Error('旋轉後空間不足');remember();move(draft,p,next);render();}
 else if(a==='remove-item'){remember();draft.items=draft.items.filter(x=>x.uid!==selected&&x.onTop!==selected);selected=null;render();}
 else if(a==='undo'){redo.push(structuredClone(draft));draft=undo.pop();if(!draft.items.some(x=>x.uid===selected))selected=null;render();}
 else if(a==='redo'){undo.push(structuredClone(draft));draft=redo.pop();if(!draft.items.some(x=>x.uid===selected))selected=null;render();}
 else if(a==='preview-room'){const room=store.get().rooms[store.get().role],p=emptySpot(room,b.dataset.item);if(!p)throw Error('小屋沒有足夠空位可以預覽。');modal('放進小屋看看',`<canvas id="preview-canvas" width="1200" height="800" class="preview-canvas"></canvas><p>預覽不會購買或修改小屋。</p>${button('回商品','product',`data-item="${b.dataset.item}"`)}`);await drawRoom($('#preview-canvas'),room,p);}
 else if(a==='pose'){pose=b.dataset.pose;activity=pose==='dance'?'夥伴跟著音樂輕輕搖擺。':pose==='rest'?'今天也辛苦了，歇一下吧。':'';render();}
 else if(a==='download-photo'){await capture();}
 else if(a==='rename-room'){const name=$('#room-name').value.trim();if(!name)throw Error('請輸入房間名稱');await store.change(s=>{s.rooms[s.role].name=name});roomSettings();render();}
 else if(a==='room-theme'){const t=THEMES.find(t=>t.id===b.dataset.theme);if(!store.get().themes.includes(t.id)){confirmAction('解鎖房間主題',`花 ${t.price} 金幣解鎖「${t.name}」，10 位角色都可免費切換使用。`,'購買並套用',async()=>{await store.change(s=>{if(s.coins<t.price)throw Error('金幣不足');s.coins-=t.price;s.themes.push(t.id);s.rooms[s.role].theme=t.id});render();toast('房間主題已套用。')})}else{await store.change(s=>{s.rooms[s.role].theme=t.id});render();roomSettings();}}
 else if(a==='expand-room'){confirmAction('擴建小屋', '花 800 金幣，將目前角色的小屋擴建為 8×8 格。','確認擴建',async()=>{await store.change(s=>{if(s.coins<800)throw Error('金幣不足');if(s.rooms[s.role].size!==6)throw Error('已擴建');s.coins-=800;s.rooms[s.role].size=8});render();toast('小屋擴建完成！')})}
 else if(a==='claim-task'){await store.change(s=>{resetDay(s);const id=b.dataset.task;if(s.tasks.claimed.includes(id))throw Error('今天已領取');if(id==='spin'&&s.stats.spins<5||id==='visit'&&s.stats.visited.length<3||id==='life'&&s.tasks.interactions<3)throw Error('委託尚未完成');s.coins+=id==='spin'?40:id==='visit'?50:30;s.tasks.claimed.push(id)});tasks();render();}
 else if(a==='aid-claim'){if(aidClicks<3||Date.now()-aidStart<20000)throw Error('小幫忙還沒完成');await store.change(s=>{if(s.coins>=100)throw Error('目前金幣已足夠');if(Date.now()-s.aidAt<180000)throw Error('補助尚在冷卻');s.coins=300;s.aidAt=Date.now()});dialog.close();render();toast('生活補助已入帳，現在有 300 金幣。');}
 });}
function bIndex(b){return b.dataset.index}
store.subscribe(()=>{if(!busy&&!operation)render()});
try{const result=await store.init();selectedRole=store.get().role;recovery=!!result.needsRecovery;render();if(result.recovered)toast('主紀錄異常，已從有效備份恢復；原始受損資料可在備份頁下載。');if(store.get().pending)await animatePending();}catch(e){root.innerHTML=`<main class="paper"><h1>存檔暫時無法載入</h1><p>${esc(e.message)}</p><p>請保留網站資料，稍後重新整理。</p></main>`}
addEventListener('beforeunload',e=>{if(draft){e.preventDefault();e.returnValue=''}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)audio?.suspend();else store.sync()});
