const SFX={click:'click',select:'select',coin:'coin',roll:'roll',stop:'stop',scratch:'scratch',reveal:'reveal',dress:'dress',place:'place',step:'step',pet:'pet',win:'win',bigwin:'bigwin'};
const MUSIC={welcome:'intro',characters:'intro',town:'town',shop:'town',wardrobe:'home',pets:'home',home:'home',arcade:'arcade',machine:'arcade',scratch:'arcade'};
let ctx,settings={sound:true,music:true,musicVolume:.35,soundVolume:.65},unlocked=false,current=null,currentName=null,targetName=null,sequence=0;
const buffers=new Map(),last=new Map(),tracks=new Set();
async function buffer(name){if(!buffers.has(name))buffers.set(name,fetch('audio/sfx-'+name+'.mp3').then(r=>{if(!r.ok)throw Error('音效無法載入');return r.arrayBuffer()}).then(b=>ctx.decodeAudioData(b)));return buffers.get(name)}
export function configure(s,page){settings=s;targetName=MUSIC[page]||'town';if(current)current.volume=settings.music?settings.musicVolume*.6:0;if(unlocked&&!document.hidden)switchMusic(targetName);}
export async function unlock(){if(unlocked){ctx?.resume();return;}try{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();unlocked=true;switchMusic(targetName||'intro');}catch{}}
export async function play(name='click',{rate=1,gain=1}={}){if(!unlocked||!settings.sound||document.hidden)return;const now=performance.now(),gap=name==='step'?220:name==='scratch'?85:35;if(now-(last.get(name)||0)<gap)return;last.set(name,now);try{const b=await buffer(SFX[name]||'click');const src=ctx.createBufferSource(),g=ctx.createGain();src.buffer=b;src.playbackRate.value=rate;g.gain.value=settings.soundVolume*.5*gain;src.connect(g);g.connect(ctx.destination);src.start();}catch{}}
function switchMusic(name){if(!settings.music){sequence++;for(const a of tracks)a.pause();return;}if(currentName===name&&current){current.volume=settings.musicVolume*.6;current.play().catch(()=>{});return;}const old=current,a=new Audio('audio/music-'+name+'.mp3'),id=++sequence;tracks.add(a);current=a;currentName=name;a.loop=true;a.volume=0;a.play().catch(()=>{});const start=performance.now(),oldVolume=old?.volume||0;const retire=()=>{if(old){old.pause();tracks.delete(old)}};const fade=()=>{if(id!==sequence){retire();return;}const p=Math.min(1,(performance.now()-start)/700);a.volume=(document.hidden||!settings.music?0:settings.musicVolume*.6)*p;if(old)old.volume=oldVolume*(1-p);if(p<1)requestAnimationFrame(fade);else retire();};requestAnimationFrame(fade);}
globalThis.document?.addEventListener('visibilitychange',()=>{if(document.hidden){sequence++;for(const a of tracks)a.pause();ctx?.suspend();}else if(unlocked){ctx?.resume();switchMusic(targetName||currentName);}});
export function status(){return{unlocked,music:currentName,playing:!!current&&!current.paused,volume:current?.volume||0};}
