import {winningIndices} from './paytable.mjs?v=20261008-complete2';
import {SYMBOLS} from './data.mjs?v=20261008-complete2';
import {play} from './audio.mjs?v=20261008-complete2';
let animations=[],skipped=false;
export function beginPresentation(){skipped=false;}
export function skipPresentation(){skipped=true;for(const a of animations)try{a.finish()}catch{}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
export async function spinReels(el,grid,{fast=false,reduced=false,keep=-1,locked=false,previous=null}={}){if(!el)return;animations=[];const rows=grid.length,cols=grid[0].length;el.innerHTML=`<div class="moving-reels" style="--columns:${cols};--rows:${rows}">${Array.from({length:cols},(_,x)=>{const values=Array.from({length:24},(_,i)=>(i*5+x)%6).concat(grid.map(row=>row[x]));return `<div class="moving-column ${x===keep?'kept-axis':''}"><div class="reel-strip">${values.map((v,i)=>`<div class="strip-symbol" ${i>=24?'data-final="true"':''}><img src="${SYMBOLS[v].art}" alt="${SYMBOLS[v].name}"></div>`).join('')}</div></div>`;}).join('')}</div>`;if(locked&&previous){const overlay=document.createElement('div');overlay.className='star-lock-layer';overlay.style.setProperty('--columns',cols);overlay.style.setProperty('--rows',rows);overlay.innerHTML=previous.flat().map(v=>v===1?`<div class="star-held"><img src="${SYMBOLS[1].art}" alt="已鎖定星星"></div>`:'<div></div>').join('');el.append(overlay);}
 const height=el.clientHeight/rows;el.querySelectorAll('.strip-symbol').forEach(s=>s.style.height=height+'px');play('roll');const timer=setInterval(()=>play('roll',{rate:1.2,gain:.35}),380);
 try{await Promise.all([...el.querySelectorAll('.reel-strip')].map(async(strip,x)=>{if(x===keep){strip.style.transform=`translateY(${-24*height}px)`;return;}const duration=skipped?1:reduced?100:fast?650+x*100:1500+x*240;const a=strip.animate([{transform:'translateY(0)',filter:'blur(0)',offset:0},{transform:`translateY(${-4*height}px)`,filter:'blur(2px)',offset:.14},{transform:`translateY(${-21*height}px)`,filter:'blur(1.5px)',offset:.73},{transform:`translateY(${-24*height}px)`,filter:'blur(0)',offset:1}],{duration,easing:'cubic-bezier(.2,.3,.15,1)',fill:'forwards'});animations.push(a);await a.finished.catch(()=>{});strip.style.transform=`translateY(${-24*height}px)`;a.cancel();play('stop',{rate:.9+x*.08});strip.parentElement.animate([{transform:'translateY(-3px)'},{transform:'translateY(2px)'},{transform:'translateY(0)'}],{duration:reduced?1:180});}));}finally{clearInterval(timer);animations=[];}
 if(locked)el.classList.add('locked-stars');
}
export function winningCells(g,m){return winningIndices(g,m);}
export async function payout(win,cost,{reduced=false,fast=false}={}){if(win<=0)return;const layer=document.createElement('div');const tier=win>=cost*20?'grand':win>=cost*5?'big':'small';layer.className='award-overlay '+tier+'-award';layer.dataset.tier=tier;layer.innerHTML=`<div class="award-plaque"><span>${win>=cost*20?'大獎時刻':win>=cost*2?'幸運降臨':'收下小幸運'}</span><strong>0</strong><small>金幣</small><button data-action="skip-animation">點擊略過</button></div>`;document.body.append(layer);if(tier!=='small'&&!reduced){const rays=document.createElement('div');rays.className='award-rays';layer.prepend(rays);for(let i=0;i<(tier==='grand'?36:18);i++){const coin=document.createElement('img');coin.src='art/coin.webp';coin.className='award-particle';coin.style.setProperty('--x',(i*37%100)+'%');coin.style.setProperty('--delay',(i%8*.12)+'s');coin.style.setProperty('--fall',(1.2+i%5*.2)+'s');layer.append(coin);}}let restoreCharacter=null,restorePet=null;const companion=document.querySelector('.companion-panel .avatar,.plaza-companion .avatar,.scratch-companion .avatar');if(companion&&!reduced&&companion.dataset.suit==='original'&&win>=cost*2){const image=companion.querySelector('img'),old=image.src,source='art/cheer-'+companion.dataset.role+'.webp';const preload=new Image();preload.src=source;await Promise.race([preload.decode().catch(()=>{}),wait(1600)]);if(preload.naturalWidth){image.src=source;restoreCharacter=()=>{if(image.isConnected)image.src=old;};}}if(companion&&!reduced)companion.animate([{transform:'translateY(0)'},{transform:'translateY(-14px) rotate(-3deg)'},{transform:'translateY(0) rotate(3deg)'},{transform:'translateY(-8px)'},{transform:'translateY(0)'}],{duration:800,iterations:tier==='grand'?3:2});const pet=document.querySelector('.scratch-pet,.plaza-pet');if(pet&&!reduced){const old=pet.src,id=old.match(/pet-([a-z]+)\.webp/)?.[1];if(id){const preload=new Image();preload.src='art/pet-'+id+'-cheer.webp';await Promise.race([preload.decode().catch(()=>{}),wait(1600)]);if(preload.naturalWidth){pet.src=preload.src;restorePet=()=>{if(pet.isConnected)pet.src=old;};}}}if(pet&&!reduced)pet.animate([{transform:'translateY(0)'},{transform:'translateY(-12px) rotate(-5deg)'},{transform:'translateY(0)'},{transform:'translateY(-8px) rotate(5deg)'},{transform:'translateY(0)'}],{duration:700,iterations:3});const duration=reduced?100:tier==='small'?(fast?350:600):fast?650:win>=cost*20?1800:950,start=performance.now();play(win>=cost*20?'bigwin':'win');const output=layer.querySelector('strong');await new Promise(resolve=>{function tick(now){const p=skipped?1:Math.min(1,(now-start)/duration);output.textContent=Math.round(win*(1-(1-p)**3)).toLocaleString('zh-TW');if(p<1)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});
 if(!reduced&&!skipped){const wallet=document.querySelector('.wallet'),target=wallet?.getBoundingClientRect();for(let i=0;i<Math.min(14,win>=cost*20?14:7);i++){const coin=document.createElement('img');coin.src='art/coin.webp';coin.className='flying-coin';coin.style.left=`${innerWidth/2+(i%5-2)*22}px`;coin.style.top=`${innerHeight*.48+Math.floor(i/5)*20}px`;document.body.append(coin);const a=coin.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${(target?.x||innerWidth-40)-innerWidth/2}px,${(target?.y||20)-innerHeight*.48}px) scale(.5)`,opacity:0}],{duration:650,delay:i*35,easing:'cubic-bezier(.3,0,.6,1)',fill:'forwards'});a.finished.then(()=>coin.remove());}play('coin');await wait(tier==='small'?(fast?120:220):(fast?250:550));}restoreCharacter?.();restorePet?.();layer.remove();}

export async function cascade(el,previous,next,{reduced=false,fast=false}={}){if(!el)return;const rows=next.length,cols=next[0].length,cleared=new Set();previous.forEach((row,y)=>{for(let x=0;x<cols;){let end=x+1;while(end<cols&&row[end]===row[x])end++;if(end-x>=3)for(let a=x;a<end;a++)cleared.add(y*cols+a);x=end;}});const html=g=>'<div class="reels" style="--columns:'+cols+';--rows:'+rows+'">'+g.flat().map((v,i)=>'<div class="reel-cell" data-cell="'+i+'"><img src="'+SYMBOLS[v].art+'" alt="'+SYMBOLS[v].name+'"></div>').join('')+'</div>';el.innerHTML=html(previous);if(!skipped&&!reduced){play('reveal');animations=[...el.querySelectorAll('[data-cell]')].filter(c=>cleared.has(+c.dataset.cell)).map(c=>c.animate([{transform:'scale(1)',filter:'brightness(1.5)',opacity:1},{transform:'scale(.2)',opacity:0}],{duration:fast?180:350,fill:'forwards'}));await Promise.all(animations.map(a=>a.finished.catch(()=>{})));}el.innerHTML=html(next);if(!skipped&&!reduced){animations=[...el.querySelectorAll('[data-cell]')].filter(c=>{const x=+c.dataset.cell%cols;return [...cleared].some(k=>k%cols===x);}).map(c=>c.animate([{transform:'translateY(-75px)',opacity:0},{transform:'translateY(0)',opacity:1}],{duration:fast?230:450,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'}));await Promise.all(animations.map(a=>a.finished.catch(()=>{})));}animations=[];}
export async function specialEvent(p,{reduced=false,fast=false}={}){if(skipped||reduced)return;let art,label;if(p.machine==='garden'&&p.note.includes('開花')){art='art/furniture-flower.webp';label='花園開花！';}else if(p.machine==='photo'&&p.note.includes('完成')){art='art/symbol-camera.webp';label='相簿完成一頁！';}if(!art)return;const badge=document.createElement('div');badge.className='special-event';badge.innerHTML='<img src="'+art+'" alt="'+label+'"><b>'+label+'</b>';document.querySelector('.machine-stage')?.append(badge);play('reveal');await wait(fast?400:850);badge.remove();}
