import {BY_ID} from './data.mjs?v=20261008-complete1';
import {canPlace,move,supports,size} from './room.mjs?v=20261008-complete1';
import {openCells,furnitureRect} from './room-life.mjs?v=20261008-complete1';
import {canvasPoint,floorCell} from './room-space.mjs?v=20261008-complete1';
export function placement(room,p){const b=size(p);if(p.x<0||p.y<0||p.x+b.w>room.size||p.y+b.h>room.size)return{valid:false,reason:'超出房間邊界'};if(!canPlace(room,p))return{valid:false,reason:p.onTop?'這個桌面／座位已有擺飾':'這裡已有家具，請選空位'};const next=structuredClone(room),old=next.items.find(q=>q.uid===p.uid);if(old)move(next,old,p);else next.items.push(p);if(!openCells(next).length)return{valid:false,reason:'至少保留一格讓夥伴走動'};return{valid:true,reason:p.onTop?'可放在家具上':'可以放置'};}
export function bindEditor(canvas,api){let down=null,dragging=false;const room=()=>api.room(),hit=q=>[...room().items].sort((a,b)=>b.y-a.y||Number(!!b.onTop)-Number(!!a.onTop)).find(p=>{const b=furnitureRect(p,room());return q.x>b.x-b.w/2&&q.x<b.x+b.w/2&&q.y>b.y-b.h&&q.y<b.y;});
 function candidate(q,p){const target=hit(q),next={...p,...floorCell(q,room())};delete next.onTop;if(target&&target.uid!==p.uid&&!target.onTop&&supports(target.item,p.item)){next.x=target.x;next.y=target.y;next.onTop=target.uid;}return next;}
 function preview(q){const p=api.ghost()||room().items.find(p=>p.uid===api.selected());if(!p)return;const next=candidate(q,p);api.setGhost(next);const status=placement(room(),next);canvas.dataset.placement=status.valid?'valid':'invalid';api.message(BY_ID[p.item].name+' · '+status.reason);api.draw();}
 canvas.onpointerdown=e=>{if(!e.isPrimary)return;e.preventDefault();down=canvasPoint(canvas,e);dragging=false;const p=hit(down);if(!api.ghost()&&p){api.select(p.uid);api.draw();}canvas.setPointerCapture(e.pointerId);if(api.ghost())preview(down);};
 canvas.onpointermove=e=>{if(!down&&(!api.ghost()||e.pointerType!=='mouse'))return;const q=canvasPoint(canvas,e);if(down&&Math.hypot(q.x-down.x,q.y-down.y)>5)dragging=true;if(dragging||api.ghost())preview(q);};
 canvas.onpointerup=e=>{if(!down)return;const q=canvasPoint(canvas,e),p=room().items.find(p=>p.uid===api.selected());if(api.ghost()||p&&(dragging||!hit(q))){if(!api.ghost())api.setGhost(candidate(q,p));else preview(q);const next=api.ghost(),status=placement(room(),next);if(status.valid){api.remember();const old=room().items.find(p=>p.uid===next.uid);if(old)move(room(),old,next);else room().items.push(next);api.select(next.uid);api.setGhost(null);api.message('已放置，按「套用布置」保存。');api.render();}else api.message(status.reason+'；位置尚未套用。');}else api.draw();down=null;dragging=false;};
 canvas.onpointercancel=()=>{down=null;dragging=false;api.setGhost(null);api.draw();};canvas.onkeydown=e=>{if(e.key==='Escape'){api.setGhost(null);api.draw();return;}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const p=room().items.find(p=>p.uid===api.selected());if(!p)return;e.preventDefault();const next={...p,x:p.x+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),y:p.y+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)};delete next.onTop;const status=placement(room(),next);if(status.valid){api.remember();move(room(),p,next);api.render();requestAnimationFrame(()=>document.querySelector('#room-canvas')?.focus());}else{api.setGhost(next);api.message(status.reason);api.draw();}};
}
