import {FLOOR as floor,background} from './room-space.mjs?v=20261007-names1';
import {windowImage,drawWindow} from './window-scene.mjs?v=20261007-names1';
import {BY_ID,ROLE_MAP,PET_MAP,THEMES} from './data.mjs?v=20261007-names1';
import {size} from './room.mjs?v=20261007-names1';
import {play} from './audio.mjs?v=20261007-names1';
const actors=new Map(),petActors=new Map(),cache=new Map();
function load(src){if(!cache.has(src))cache.set(src,new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('生活素材載入失敗：'+src));i.src=src;}));return cache.get(src)}
export function openCells(room){const blocked=new Set();for(const p of room.items){if(p.onTop)continue;const b=size(p);for(let y=p.y;y<p.y+b.h;y++)for(let x=p.x;x<p.x+b.w;x++)blocked.add(x+','+y);}const cells=[];for(let y=0;y<room.size;y++)for(let x=0;x<room.size;x++)if(!blocked.has(x+','+y))cells.push({x,y});return cells;}
export function pathTo(room,start,target){const free=new Set(openCells(room).map(p=>p.x+','+p.y)),key=p=>Math.round(p.x)+','+Math.round(p.y),from=key(start),to=key(target);if(!free.has(from)||!free.has(to))return null;const queue=[{x:Math.round(start.x),y:Math.round(start.y)}],previous=new Map([[from,null]]);for(let i=0;i<queue.length;i++){const p=queue[i];if(key(p)===to){const path=[];let k=to;while(previous.get(k)!==null){const [x,y]=k.split(',').map(Number);path.unshift({x,y});k=previous.get(k);}return path;}for(const [dx,dy] of [[0,1],[1,0],[0,-1],[-1,0]]){const q={x:p.x+dx,y:p.y+dy},k=key(q);if(free.has(k)&&!previous.has(k)){previous.set(k,key(p));queue.push(q);}}}return null;}
function point(p,room){return{x:floor.x+(p.x+.5)/room.size*floor.w,y:floor.y+(p.y+.8)/room.size*floor.h};}
export function furnitureRect(p,room){if(p.onTop){const q=room.items.find(x=>x.uid===p.onTop),b=furnitureRect(q,room);return{x:b.x,y:b.y-b.h*.52,w:65,h:65};}const b=size(p),small=['tea','flower','cushion','pillow','clock','basket','toy-bear','plant'].includes(p.item)||['small','cushion'].includes(BY_ID[p.item]?.category),scale=small?.7:1;return{x:floor.x+(p.x+.5*b.w)/room.size*floor.w,y:floor.y+(p.y+.8*b.h)/room.size*floor.h,w:Math.max(100,b.w/room.size*floor.w*.9)*scale,h:Math.max(95,b.h/room.size*floor.h*3.15)*scale};}
export async function startLife(canvas,s,{onActivity=()=>{},onInteraction=()=>{},onError=()=>{}}={}){const room=s.rooms[s.role],o=s.outfits[s.role],key=o.suit==='original'?s.role:o.suit,petId=s.pets.active[s.role],ctx=canvas.getContext('2d');let stopped=false,raf=0,interaction=null,last=0,lastDraw=0,petHappyUntil=0,interactionFxUntil=0,visual=null,seatBlend=0,petPos=null,petSleepAt=performance.now()+10000,petMoving=false,petPath=[],petWait=performance.now()+1500,petRest=performance.now(),petDir=1,petRoamed=false;const petKey=s.role+'|'+petId;const cachedPet=petActors.get(petKey);const petMode=s.pets.modes[s.role];
 let sceneImage=null;windowImage(room).then(im=>sceneImage=im);const free=openCells(room);if(!free.length){onError('小屋需要至少一格空位讓夥伴走動');return{stop(){},pose(){},snapshot(){return null}};}let actor=actors.get(s.role)||{...free.at(-1),dir:1,path:[],wait:0,pose:'stand',anchor:null};if(!free.some(p=>p.x===Math.round(actor.x)&&p.y===Math.round(actor.y))){Object.assign(actor,free.at(-1),{path:[],anchor:null,pose:'stand'});}if(actor.anchor&&!room.items.some(p=>p.uid===actor.anchor.uid)){actor.anchor=null;actor.pose='stand';}actors.set(s.role,actor);petPos=cachedPet&&free.some(q=>q.x===Math.round(cachedPet.pos.x)&&q.y===Math.round(cachedPet.pos.y))?{...cachedPet.pos}:{x:Math.round(actor.x),y:Math.round(actor.y)};if(cachedPet){petDir=cachedPet.dir;petRest=cachedPet.rest;petRoamed=cachedPet.roamed;if(cachedPet.mode===petMode&&cachedPet.path.every(p=>free.some(q=>q.x===p.x&&q.y===p.y))){petPath=cachedPet.path.map(p=>({...p}));petWait=cachedPet.wait;}}
 const files=[THEMES.find(t=>t.id===room.theme).art,o.suit==='original'?ROLE_MAP[s.role].original:BY_ID[o.suit].art,'art/walk-'+key+'-a.webp','art/walk-'+key+'-b.webp','art/sit-'+key+'.webp','art/walk-'+key+'-c.webp','art/walk-'+key+'-d.webp','art/lie-'+key+'.webp',...room.items.map(p=>BY_ID[p.item].art),...(petId?[PET_MAP[petId].art,'art/pet-'+petId+'-sleep.webp','art/pet-'+petId+'-walk-a.webp','art/pet-'+petId+'-walk-b.webp','art/pet-'+petId+'-cheer.webp']:[])];let images;try{images=await Promise.all(files.map(load));}catch(e){onError(e.message);return{stop(){},pose(){},snapshot(){return null}};}if(!canvas.isConnected)return{stop(){},pose(){},snapshot(){return null}};canvas.dataset.petMode=petMode;canvas.setAttribute('aria-busy','false');const[bg,stand,walkA,walkB,sit,walkC,walkD,lie]=images,arts=images.slice(8,8+room.items.length),petImages=petId?images.slice(8+room.items.length):[],[petArt,petSleep,petWalkA,petWalkB,petCheer]=petImages;
 const route=(target,p=null)=>{if(actor.anchor){const nearest=free.filter(q=>pathTo(room,q,target)!==null).sort((a,b)=>Math.hypot(a.x-actor.x,a.y-actor.y)-Math.hypot(b.x-actor.x,b.y-actor.y))[0];if(nearest)Object.assign(actor,{x:nearest.x,y:nearest.y});}const path=pathTo(room,actor,target);if(!path)return false;actor.path=path;actor.anchor=null;actor.pose='stand';interaction=p;actor.wait=0;if(p&&!path.length){actor.anchor=p;actor.pose=interactionKind(p.item);actor.wait=performance.now()+14000;interactionFxUntil=performance.now()+1600;interaction=null;play('reveal',{gain:.35});onActivity(ROLE_MAP[s.role].name+'：'+BY_ID[p.item].action+'。');onInteraction();}return true;};
 const interact=p=>{const candidates=free.map(q=>({q,path:pathTo(room,actor,q)})).filter(x=>x.path).sort((a,b)=>{const near=q=>Math.max(p.x-q.x,0,q.x-(p.x+size(p).w-1))+Math.max(p.y-q.y,0,q.y-(p.y+size(p).h-1));return near(a.q)-near(b.q)||a.path.length-b.path.length});if(!candidates.length){onActivity('這件家具附近暫時走不過去。');return;}const q=candidates[0].q,b=size(p),distance=Math.max(p.x-q.x,0,q.x-(p.x+b.w-1))+Math.max(p.y-q.y,0,q.y-(p.y+b.h-1));if(distance>1){onActivity('家具旁沒有可走到的空位，請調整布置。');return;}route(candidates[0].q,p);if(actor.path.length)onActivity(ROLE_MAP[s.role].name+'正在走向'+BY_ID[p.item].name+'。');};
 canvas.onpointerup=e=>{const b=canvas.getBoundingClientRect(),q={x:(e.clientX-b.left)/b.width*1400,y:(e.clientY-b.top)/b.height*560};const pp=point(petPos,room);if(petId&&Math.abs(q.x-pp.x)<55&&Math.abs(q.y-(pp.y-45))<55){actor.wait=performance.now()+4000;petWait=performance.now()+4000;petPath=[];petSleepAt=performance.now()+12000;petHappyUntil=performance.now()+1800;play('pet');onActivity('摸摸'+s.pets.names[petId]+'，小夥伴開心地靠近你。');return;}const item=[...room.items].sort((a,b)=>b.y-a.y||Number(!!b.onTop)-Number(!!a.onTop)).find(p=>{const b=furnitureRect(p,room);return q.x>b.x-b.w/2&&q.x<b.x+b.w/2&&q.y>b.y-b.h&&q.y<b.y});if(item){interact(item);return;}const target={x:Math.floor((q.x-floor.x)/floor.w*room.size),y:Math.floor((q.y-floor.y)/floor.h*room.size)};if(route(target))onActivity('一起走到那邊看看。');else onActivity('這裡沒有可通行的路線，換個空位吧。');};
 function figure(image,p,height,flip,bob=0,sway=0){const q=point(p,room),h=height+(s.settings.reduced?0:Math.sin(performance.now()/650)*1.5),w=h*image.width/image.height;ctx.save();ctx.translate(q.x,q.y-bob);ctx.scale(flip?-1:1,1);ctx.rotate(s.settings.reduced?0:sway);ctx.drawImage(image,-w/2,-h,w,h);ctx.restore();}
 function drawActor(now,walking,frame){const anchor=actor.anchor,art=anchor?arts[room.items.findIndex(p=>p.uid===anchor.uid)]:null,a=anchor?interactionAnchor(anchor,room,art):null,seated=['sit','floor-sit','lie','rest'].includes(actor.pose);let target=point(actor,room);if(a?.kind==='sit')target={x:a.x,y:a.seatY+135*.29};if(a?.kind==='lie')target={x:a.x,y:a.lieY};if(a?.kind==='stand')target={x:a.x+(anchor.flip?-1:1)*a.w*.48,y:a.y-8};if(!visual)visual={...target};const easing=s.settings.reduced?1:.2;visual.x+=(target.x-visual.x)*easing;visual.y+=(target.y-visual.y)*easing;seatBlend+=(Number(seated)-seatBlend)*easing;const pos={x:(visual.x-floor.x)/floor.w*room.size-.5,y:(visual.y-floor.y)/floor.h*room.size-.8},bob=s.settings.reduced?0:walking?Math.abs(Math.sin(now/130))*3:actor.pose==='dance'?Math.abs(Math.sin(now/140))*10:Math.sin(now/1000)*.7;if(seatBlend<.99){ctx.save();ctx.globalAlpha=1-seatBlend;figure(walking?frame:stand,pos,175,actor.dir<0,bob,actor.pose==='dance'?Math.sin(now/220)*.05:0);ctx.restore();}if(seatBlend>.01){ctx.save();ctx.globalAlpha=seatBlend;if(a?.kind==='lie'){const w=Math.min(260,a.w*.86),h=w*lie.height/lie.width;ctx.translate(visual.x,visual.y);if(!anchor.flip)ctx.scale(-1,1);ctx.drawImage(lie,-w/2,-h/2,w,h);}else figure(sit,pos,135,!!anchor?.flip);ctx.restore();}if(a&&['sit','lie'].includes(a.kind)){ctx.save();ctx.beginPath();ctx.rect(a.x-a.w/2,a.frontY,a.w,a.y-a.frontY+2);ctx.clip();ctx.translate(a.x,a.y);if(anchor.flip)ctx.scale(-1,1);ctx.drawImage(art,-a.w/2,-a.h,a.w,a.h);ctx.restore();}if(a&&a.kind==='stand'&&(['table','desk','cabinet','shelf','vanity'].includes(anchor.item)||BY_ID[anchor.item]?.category==='surface')){ctx.save();ctx.beginPath();ctx.rect(a.x-a.w/2,a.y-a.h*.34,a.w,a.h*.34+2);ctx.clip();ctx.translate(a.x,a.y);if(anchor.flip)ctx.scale(-1,1);ctx.drawImage(art,-a.w/2,-a.h,a.w,a.h);ctx.restore();}if(!s.settings.reduced&&now<interactionFxUntil){ctx.save();ctx.fillStyle='#ffe29a';for(let i=0;i<5;i++){const phase=(now/700+i*.21)%1;ctx.globalAlpha=1-phase;ctx.beginPath();ctx.arc(visual.x+(i-2)*11,visual.y-155-phase*30,2,0,7);ctx.fill();}ctx.restore();}canvas.dataset.seatBlend=seatBlend.toFixed(2);canvas.dataset.anchor=anchor?.uid||'';}
 function draw(now){background(ctx,bg,drawWindow,room,sceneImage,now,s.settings.reduced);const walking=actor.path.length>0,phase=Math.floor(now/130)%4,walkFrame=[walkA,walkC,walkB,walkD][phase];canvas.dataset.walkFrame=phase;let actorDepth=actor.anchor?actor.anchor.y+size(actor.anchor).h+.05:actor.y+.8;const entries=room.items.map((p,i)=>({depth:(p.onTop?room.items.find(q=>q.uid===p.onTop):p).y+size(p.onTop?room.items.find(q=>q.uid===p.onTop):p).h+(p.onTop?.02:0),draw:()=>{const b=furnitureRect(p,room),art=arts[i],scale=Math.min(b.w/art.width,b.h/art.height);ctx.save();ctx.translate(b.x,b.y);if(p.flip)ctx.scale(-1,1);ctx.drawImage(art,-art.width*scale/2,-art.height*scale,art.width*scale,art.height*scale);ctx.restore();}}));
 entries.push({depth:actorDepth,draw:()=>drawActor(now,walking,walkFrame)});
 if(petArt)entries.push({depth:petPos.y+.8,draw:()=>{const sleeping=!petMoving&&now-petRest>3500;canvas.dataset.petPose=now<petHappyUntil?'cheer':sleeping?'sleep':petMoving?'walk':'stand';figure(now<petHappyUntil?petCheer:sleeping?petSleep:petMoving?(phase%2?petWalkA:petWalkB):petArt,petPos,sleeping?48:67,petDir<0,s.settings.reduced?0:now<petHappyUntil?Math.abs(Math.sin(now/95))*15:petMoving?Math.abs(Math.sin(now/130))*4:Math.sin(now/1100)*2,Math.sin(now/1700)*.02);}});entries.sort((a,b)=>a.depth-b.depth).forEach(e=>e.draw());canvas.dataset.actorX=actor.x.toFixed(2);canvas.dataset.actorY=actor.y.toFixed(2);canvas.dataset.actorPose=walking?'walk':actor.pose;
 }
 function tick(now){if(stopped||!canvas.isConnected)return;raf=requestAnimationFrame(tick);const dt=Math.min(.08,(now-last)/1000||0);last=now;if(document.hidden||document.body.classList.contains('portrait-lock'))return;if(actor.path.length){const next=actor.path[0],dx=next.x-actor.x,dy=next.y-actor.y,d=Math.hypot(dx,dy),step=dt*1.1;if(Math.abs(dx)>.02)actor.dir=dx<0?-1:1;if(d<=step){actor.x=next.x;actor.y=next.y;actor.path.shift();}else{actor.x+=dx/d*step;actor.y+=dy/d*step;}play('step',{gain:.18});if(!actor.path.length){actor.wait=now+14000;if(interaction){const p=interaction;actor.anchor=p;const action=BY_ID[p.item].action;actor.pose=interactionKind(p.item);interactionFxUntil=now+1600;play('reveal',{gain:.35});onActivity(ROLE_MAP[s.role].name+'：'+action+'。');onInteraction();interaction=null;}}}else if(!s.settings.reduced&&now>actor.wait&&!actor.anchor){actor.wait=now+6000;const reachable=free.filter(q=>pathTo(room,actor,q)?.length);if(reachable.length){if(room.items.length&&Math.random()<.3)interact(room.items[Math.floor(Math.random()*room.items.length)]);else route(reachable[Math.floor(Math.random()*reachable.length)]);}}else if(actor.anchor&&now>actor.wait){actor.anchor=null;actor.pose='stand';actor.wait=now+2500;}
 if(petArt){if(petPath.length){const q=petPath[0],dx=q.x-petPos.x,dy=q.y-petPos.y,d=Math.hypot(dx,dy),step=dt*(petId==='moon'||petId==='hedgehog'?.85:1.55);if(Math.abs(dx)>.01)petDir=dx<0?-1:1;if(d<=step){petPos.x=q.x;petPos.y=q.y;petPath.shift();}else{petPos.x+=dx/d*step;petPos.y+=dy/d*step;}petRest=now;}if(!petPath.length&&now>petWait&&now>petHappyUntil){const targets=free.filter(q=>pathTo(room,petPos,q)?.length);if(petMode==='follow'){if(Math.hypot(actor.x-petPos.x,actor.y-petPos.y)>1.2){targets.sort((a,b)=>Math.hypot(a.x-actor.x,a.y-actor.y)-Math.hypot(b.x-actor.x,b.y-actor.y));if(targets.length)petPath=pathTo(room,petPos,targets[0])||[];}petWait=now+1200;}else if(!s.settings.reduced&&targets.length){if(petRoamed&&Math.random()<.25){petWait=now+10000;}else{petPath=pathTo(room,petPos,targets[Math.floor(Math.random()*targets.length)])||[];petRoamed=true;petWait=now+3500;}}else petWait=now+1500;}petMoving=petPath.length>0;canvas.dataset.petMode=petMode;canvas.dataset.petX=petPos.x.toFixed(2);canvas.dataset.petY=petPos.y.toFixed(2);}
 if(now-lastDraw>32){draw(now);lastDraw=now;}}
 raf=requestAnimationFrame(tick);return{stop(){if(petId&&petPos)petActors.set(petKey,{pos:{...petPos},path:petPath.map(p=>({...p})),wait:petWait,rest:petRest,dir:petDir,roamed:petRoamed,mode:petMode});stopped=true;cancelAnimationFrame(raf);canvas.onpointerup=null;},pose(p){actor.path=[];actor.anchor=null;actor.pose=p==='rest'?'floor-sit':p;actor.wait=performance.now()+14000;},snapshot(){return{actor:{x:actor.x,y:actor.y,pose:actor.pose},pet:petPos?{...petPos}:null}},interact};
}

export function interactionKind(id){const f=BY_ID[id];return id==='bed'||f?.category==='bed'?'lie':['chair','sofa','stool','ottoman'].includes(id)||f?.category==='seat'?'sit':['cushion','pillow','rug'].includes(id)||f?.category==='cushion'?'floor-sit':id==='record'?'dance':'stand';}
export function interactionAnchor(p,room,art){const b=furnitureRect(p,room),scale=Math.min(b.w/art.width,b.h/art.height),w=art.width*scale,h=art.height*scale,kind=interactionKind(p.item);return{x:b.x,y:b.y,w,h,kind,seatY:b.y-h*.34,lieY:b.y-h*.43,frontY:b.y-h*(kind==='lie'?.22:.24)};}
