import {BY_ID,ROLE_MAP,PET_MAP,THEMES} from './data.mjs?v=20261006-town3';
import {size} from './room.mjs?v=20261006-town3';
import {play} from './audio.mjs?v=20261006-town3';
const floor={x:130,y:390,w:940,h:325},actors=new Map(),cache=new Map();
function load(src){if(!cache.has(src))cache.set(src,new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('生活素材載入失敗：'+src));i.src=src;}));return cache.get(src)}
export function openCells(room){const blocked=new Set();for(const p of room.items){if(p.onTop)continue;const b=size(p);for(let y=p.y;y<p.y+b.h;y++)for(let x=p.x;x<p.x+b.w;x++)blocked.add(x+','+y);}const cells=[];for(let y=0;y<room.size;y++)for(let x=0;x<room.size;x++)if(!blocked.has(x+','+y))cells.push({x,y});return cells;}
export function pathTo(room,start,target){const free=new Set(openCells(room).map(p=>p.x+','+p.y)),key=p=>Math.round(p.x)+','+Math.round(p.y),from=key(start),to=key(target);if(!free.has(from)||!free.has(to))return null;const queue=[{x:Math.round(start.x),y:Math.round(start.y)}],previous=new Map([[from,null]]);for(let i=0;i<queue.length;i++){const p=queue[i];if(key(p)===to){const path=[];let k=to;while(previous.get(k)!==null){const [x,y]=k.split(',').map(Number);path.unshift({x,y});k=previous.get(k);}return path;}for(const [dx,dy] of [[0,1],[1,0],[0,-1],[-1,0]]){const q={x:p.x+dx,y:p.y+dy},k=key(q);if(free.has(k)&&!previous.has(k)){previous.set(k,key(p));queue.push(q);}}}return null;}
function point(p,room){return{x:floor.x+(p.x+.5)/room.size*floor.w,y:floor.y+(p.y+.8)/room.size*floor.h};}
export function furnitureRect(p,room){if(p.onTop){const q=room.items.find(x=>x.uid===p.onTop),b=furnitureRect(q,room);return{x:b.x,y:b.y-b.h*.52,w:75,h:85};}const b=size(p),small=['tea','flower','cushion','pillow','clock','basket','toy-bear','plant'].includes(p.item),scale=small?.7:1;return{x:floor.x+(p.x+.5*b.w)/room.size*floor.w,y:floor.y+(p.y+.8*b.h)/room.size*floor.h,w:Math.max(100,b.w/room.size*floor.w*.9)*scale,h:Math.max(135,b.h/room.size*floor.h*3.15)*scale};}
export async function startLife(canvas,s,{onActivity=()=>{},onInteraction=()=>{},onError=()=>{}}={}){const room=s.rooms[s.role],o=s.outfits[s.role],key=o.suit==='original'?s.role:o.suit,petId=s.pets.active[s.role],ctx=canvas.getContext('2d');let stopped=false,raf=0,interaction=null,last=0,lastDraw=0,petPos=null,petSleepAt=performance.now()+10000,petMoving=false;
 const free=openCells(room);if(!free.length){onError('小屋需要至少一格空位讓夥伴走動');return{stop(){},pose(){},snapshot(){return null}};}let actor=actors.get(s.role)||{...free.at(-1),dir:1,path:[],wait:0,pose:'stand',anchor:null};if(!free.some(p=>p.x===Math.round(actor.x)&&p.y===Math.round(actor.y))){Object.assign(actor,free.at(-1),{path:[],anchor:null,pose:'stand'});}if(actor.anchor&&!room.items.some(p=>p.uid===actor.anchor.uid)){actor.anchor=null;actor.pose='stand';}actors.set(s.role,actor);petPos={x:actor.x-.2,y:actor.y+.2};
 const files=[THEMES.find(t=>t.id===room.theme).art,o.suit==='original'?ROLE_MAP[s.role].original:BY_ID[o.suit].art,'art/walk-'+key+'-a.webp','art/walk-'+key+'-b.webp','art/sit-'+key+'.webp',...room.items.map(p=>BY_ID[p.item].art),...(petId?[PET_MAP[petId].art,'art/pet-'+petId+'-sleep.webp','art/pet-'+petId+'-walk-a.webp','art/pet-'+petId+'-walk-b.webp']:[])];let images;try{images=await Promise.all(files.map(load));}catch(e){onError(e.message);return{stop(){},pose(){},snapshot(){return null}};}if(!canvas.isConnected)return{stop(){},pose(){},snapshot(){return null}};canvas.setAttribute('aria-busy','false');const[bg,stand,walkA,walkB,sit]=images,arts=images.slice(5,5+room.items.length),petImages=petId?images.slice(5+room.items.length):[],[petArt,petSleep,petWalkA,petWalkB]=petImages;
 const route=(target,p=null)=>{if(actor.anchor){const nearest=free.filter(q=>pathTo(room,q,target)!==null).sort((a,b)=>Math.hypot(a.x-actor.x,a.y-actor.y)-Math.hypot(b.x-actor.x,b.y-actor.y))[0];if(nearest)Object.assign(actor,{x:nearest.x,y:nearest.y});}const path=pathTo(room,actor,target);if(!path)return false;actor.path=path;actor.anchor=null;actor.pose='stand';interaction=p;actor.wait=0;return true;};
 const interact=p=>{const candidates=free.map(q=>({q,path:pathTo(room,actor,q)})).filter(x=>x.path).sort((a,b)=>{const near=q=>Math.max(p.x-q.x,0,q.x-(p.x+size(p).w-1))+Math.max(p.y-q.y,0,q.y-(p.y+size(p).h-1));return near(a.q)-near(b.q)||a.path.length-b.path.length});if(!candidates.length){onActivity('這件家具附近暫時走不過去。');return;}route(candidates[0].q,p);onActivity(ROLE_MAP[s.role].name+'正在走向'+BY_ID[p.item].name+'。');};
 canvas.onpointerup=e=>{const b=canvas.getBoundingClientRect(),q={x:(e.clientX-b.left)/b.width*1200,y:(e.clientY-b.top)/b.height*800};const pp=point(petPos,room);if(petId&&Math.abs(q.x-pp.x)<55&&Math.abs(q.y-(pp.y-45))<55){actor.wait=performance.now()+4000;petSleepAt=performance.now()+12000;play('pet');onActivity('摸摸'+s.pets.names[petId]+'，小夥伴開心地靠近你。');return;}const item=[...room.items].sort((a,b)=>b.y-a.y||Number(!!b.onTop)-Number(!!a.onTop)).find(p=>{const b=furnitureRect(p,room);return q.x>b.x-b.w/2&&q.x<b.x+b.w/2&&q.y>b.y-b.h&&q.y<b.y});if(item){interact(item);return;}const target={x:Math.floor((q.x-floor.x)/floor.w*room.size),y:Math.floor((q.y-floor.y)/floor.h*room.size)};if(route(target))onActivity('一起走到那邊看看。');else onActivity('這裡沒有可通行的路線，換個空位吧。');};
 function figure(image,p,height,flip,bob=0,sway=0){const q=point(p,room),h=height+Math.sin(performance.now()/650)*1.5,w=h*image.width/image.height;ctx.save();ctx.translate(q.x,q.y-bob);ctx.scale(flip?-1:1,1);ctx.rotate(sway);ctx.drawImage(image,-w/2,-h,w,h);ctx.restore();}
 function draw(now){ctx.clearRect(0,0,1200,800);ctx.drawImage(bg,0,0,1200,800);const walking=actor.path.length>0,phase=Math.floor(now/210)%2;let actorDepth=actor.anchor?actor.anchor.y+size(actor.anchor).h+.05:actor.y+.8;const entries=room.items.map((p,i)=>({depth:(p.onTop?room.items.find(q=>q.uid===p.onTop):p).y+size(p.onTop?room.items.find(q=>q.uid===p.onTop):p).h+(p.onTop?.02:0),draw:()=>{const b=furnitureRect(p,room),art=arts[i],scale=Math.min(b.w/art.width,b.h/art.height);ctx.save();ctx.translate(b.x,b.y);if(p.flip)ctx.scale(-1,1);ctx.drawImage(art,-art.width*scale/2,-art.height*scale,art.width*scale,art.height*scale);ctx.restore();}}));
 entries.push({depth:actorDepth,draw:()=>{const seated=['rest','tea','read','draw','eat'].includes(actor.pose);if(actor.anchor&&seated){const b=furnitureRect(actor.anchor,room),p={x:(b.x-floor.x)/floor.w*room.size-.5,y:(b.y-floor.y)/floor.h*room.size-.8};figure(sit,p,220,false,0,actor.pose==='tea'?Math.sin(now/850)*.018:0);}else figure(walking?(phase?walkA:walkB):seated?sit:stand,actor,seated?220:250,actor.dir<0,s.settings.reduced?0:walking?Math.abs(Math.sin(now/140))*5:actor.pose==='dance'?Math.abs(Math.sin(now/150))*12:Math.sin(now/900)*2,actor.pose==='dance'?Math.sin(now/230)*.05:0);}});
 if(petArt)entries.push({depth:petPos.y+.8,draw:()=>{const sleeping=!walking&&now>petSleepAt&&now<petSleepAt+6000;canvas.dataset.petPose=sleeping?'sleep':petMoving?'walk':'stand';figure(sleeping?petSleep:petMoving?(phase?petWalkA:petWalkB):petArt,petPos,sleeping?65:95,actor.dir<0,s.settings.reduced?0:petMoving?Math.abs(Math.sin(now/130))*4:Math.sin(now/1100)*2,Math.sin(now/1700)*.02);}});entries.sort((a,b)=>a.depth-b.depth).forEach(e=>e.draw());canvas.dataset.actorX=actor.x.toFixed(2);canvas.dataset.actorY=actor.y.toFixed(2);canvas.dataset.actorPose=walking?'walk':actor.pose;
 }
 function tick(now){if(stopped||!canvas.isConnected)return;raf=requestAnimationFrame(tick);const dt=Math.min(.08,(now-last)/1000||0);last=now;if(document.hidden)return;if(actor.path.length){const next=actor.path[0],dx=next.x-actor.x,dy=next.y-actor.y,d=Math.hypot(dx,dy),step=dt*1.1;if(Math.abs(dx)>.02)actor.dir=dx<0?-1:1;if(d<=step){actor.x=next.x;actor.y=next.y;actor.path.shift();}else{actor.x+=dx/d*step;actor.y+=dy/d*step;}play('step',{gain:.18});if(!actor.path.length){actor.wait=now+14000;if(interaction){const p=interaction;actor.anchor=p;const action=BY_ID[p.item].action;actor.pose=/休息|小憩|放鬆/.test(action)?'rest':/茶/.test(action)?'tea':/閱讀/.test(action)?'read':/畫/.test(action)?'draw':/點心/.test(action)?'eat':p.item==='record'?'dance':'stand';onActivity(ROLE_MAP[s.role].name+'：'+action+'。');onInteraction();interaction=null;}}}else if(!s.settings.reduced&&now>actor.wait&&!actor.anchor){actor.wait=now+6000;const reachable=free.filter(q=>pathTo(room,actor,q)?.length);if(reachable.length){if(room.items.length&&Math.random()<.3)interact(room.items[Math.floor(Math.random()*room.items.length)]);else route(reachable[Math.floor(Math.random()*reachable.length)]);}}else if(actor.anchor&&now>actor.wait){actor.anchor=null;actor.pose='stand';actor.wait=now+2500;}
 if(petArt){if(now>petSleepAt+6000)petSleepAt=now+10000;if(actor.path.length)petSleepAt=now+10000;const target={x:Math.max(0,Math.min(room.size-1,actor.x-.45*actor.dir)),y:Math.max(0,Math.min(room.size-1,actor.y+.25))};petMoving=Math.hypot(target.x-petPos.x,target.y-petPos.y)>.12;petPos.x+=(target.x-petPos.x)*Math.min(1,dt*2);petPos.y+=(target.y-petPos.y)*Math.min(1,dt*2);const cell=free.reduce((a,b)=>Math.hypot(b.x-petPos.x,b.y-petPos.y)<Math.hypot(a.x-petPos.x,a.y-petPos.y)?b:a);if(!free.some(p=>p.x===Math.round(petPos.x)&&p.y===Math.round(petPos.y)))petPos={...cell};}
 if(now-lastDraw>32){draw(now);lastDraw=now;}}
 raf=requestAnimationFrame(tick);return{stop(){stopped=true;cancelAnimationFrame(raf);canvas.onpointerup=null;},pose(p){actor.path=[];actor.anchor=null;actor.pose=p;actor.wait=performance.now()+14000;},snapshot(){return{actor:{x:actor.x,y:actor.y,pose:actor.pose},pet:petPos?{...petPos}:null}},interact};
}
