import {saveScratch,ticketLayout} from './scratch.mjs?v=20261006-town4';
import {play} from './audio.mjs?v=20261006-town4';
export function sweptDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,q=dx*dx+dy*dy,f=q?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/q)):0;return Math.hypot(p.x-a.x-dx*f,p.y-a.y-dy*f);}
export function bindScratch(store,onSaved,onError){const t=store.get().scratch,canvas=document.querySelector('#ticket-foil');if(!t||!canvas)return null;const regions=ticketLayout(t),marks=t.marks.map(a=>new Set(a)),surface=new Set(t.surfaceMarks||[]),ctx=canvas.getContext('2d'),W=1200,H=675;let pointer=null,last=null,timer=null,dirty=false,closed=false,chain=Promise.resolve(),soundAt=0,fxRaf=0,particles=[];const dust=document.createElement('canvas');dust.width=W;dust.height=H;dust.className='ticket-dust';canvas.after(dust);const dc=dust.getContext('2d');function flakes(now){dc.clearRect(0,0,W,H);particles=particles.filter(p=>now-p.at<550);for(const p of particles){const t=(now-p.at)/550;dc.globalAlpha=(1-t)*.8;dc.fillStyle=p.color;dc.fillRect(p.x+p.dx*t,p.y-25*t+60*t*t,p.size,p.size*.4);}if(particles.length&&!closed)fxRaf=requestAnimationFrame(flakes);else fxRaf=0;}
function paint(){ctx.globalCompositeOperation='source-over';ctx.clearRect(0,0,W,H);if(t.revealed.every(Boolean))return;const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#99b3b2');g.addColorStop(.25,'#e2e8d9');g.addColorStop(.5,'#b5c8c3');g.addColorStop(.8,'#eef0dc');g.addColorStop(1,'#849d98');ctx.fillStyle=g;ctx.fillRect(W*.06,H*.2,W*.88,H*.7);ctx.fillStyle='#5b7976';ctx.font='bold 26px sans-serif';ctx.textAlign='center';for(const r of regions)ctx.fillText('刮開驚喜',(r.x+r.w/2)*W,(r.y+r.h/2)*H);ctx.globalCompositeOperation='destination-out';for(const cell of surface)ctx.clearRect(cell%96/96*W,Math.floor(cell/96)/54*H,W/96+1,H/54+1);regions.forEach((r,i)=>{if(t.revealed[i])ctx.clearRect(r.x*W,r.y*H,r.w*W,r.h*H);else for(const cell of marks[i])ctx.clearRect((r.x+cell%24/24*r.w)*W,(r.y+Math.floor(cell/24)/16*r.h)*H,r.w*W/24+1,r.h*H/16+1);});}
function refresh(){const current=store.get().scratch;if(current?.id!==t.id)return;t.revealed=current.revealed;current.marks.forEach((a,i)=>a.forEach(v=>marks[i].add(v)));for(const v of current.surfaceMarks||[])surface.add(v);const done=current.revealed.filter(Boolean).length,coverage=current.revealed.every(Boolean)?1:marks.reduce((n,a)=>n+a.size,0)/(marks.length*384),label=document.querySelector('#scratch-progress');if(label)label.textContent=`已揭曉 ${done}／${marks.length} 區 · 刮除 ${Math.round(coverage*100)}%`;const collect=document.querySelector('[data-action="scratch-collect"]');if(collect)collect.disabled=!current.revealed.every(Boolean);const help=document.querySelector('#scratch-help');if(help)help.hidden=coverage<.8||current.revealed.every(Boolean);document.querySelectorAll('[data-ticket-region]').forEach(el=>el.classList.toggle('revealed',current.revealed[+el.dataset.ticketRegion]));if(pointer===null)paint();}
function flush(){clearTimeout(timer);timer=null;if(!dirty)return chain;dirty=false;const snapshot=marks.map(a=>[...a]),surfaceSnapshot=[...surface];chain=chain.then(()=>saveScratch(store,t.id,snapshot,false,surfaceSnapshot)).then(()=>{if(!closed){refresh();onSaved?.();}}).catch(e=>{if(!closed)onError(e.message);});return chain;}
function erase(e){const rect=canvas.getBoundingClientRect(),p={x:(e.clientX-rect.left)/rect.width*W,y:(e.clientY-rect.top)/rect.height*H},a=last||p,radius=Math.min(65,Math.max(24,(e.pointerType==='touch'?23:15)*W/rect.width));ctx.globalCompositeOperation='destination-out';ctx.lineWidth=radius*2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fill();regions.forEach((r,i)=>{for(let y=0;y<16;y++)for(let x=0;x<24;x++){const q={x:(r.x+(x+.5)*r.w/24)*W,y:(r.y+(y+.5)*r.h/16)*H};if(sweptDistance(q,a,p)<=radius)marks[i].add(y*24+x);}});const before=surface.size;for(let yy=0;yy<54;yy++)for(let xx=0;xx<96;xx++)if(sweptDistance({x:(xx+.5)/96*W,y:(yy+.5)/54*H},a,p)<=radius)surface.add(yy*96+xx);if(surface.size>before&&!store.get().settings.reduced){for(let i=0;i<3;i++)particles.push({x:p.x+(Math.random()-.5)*radius,y:p.y+(Math.random()-.5)*radius,dx:(Math.random()-.5)*60,size:3+Math.random()*5,color:i%2?'#e6ead7':'#a4bbb3',at:performance.now()});particles=particles.slice(-60);if(!fxRaf)fxRaf=requestAnimationFrame(flakes);}last=p;dirty=true;if(!timer)timer=setTimeout(()=>{timer=null;flush();},160);if(performance.now()-soundAt>95){play('scratch',{gain:.4});soundAt=performance.now();}canvas.dataset.touchedRegions=marks.filter(a=>a.size).length;}
canvas.onpointerdown=e=>{e.preventDefault();if(pointer!==null||!e.isPrimary||t.revealed.every(Boolean))return;pointer=e.pointerId;last=null;canvas.setPointerCapture(pointer);erase(e);};canvas.onpointermove=e=>{if(e.pointerId!==pointer)return;e.preventDefault();const events=e.getCoalescedEvents?.();for(const point of events?.length?events:[e])erase(point);};const finish=e=>{if(e?.pointerId!==undefined&&pointer!==e.pointerId)return;if(pointer!==null&&canvas.hasPointerCapture(pointer))try{canvas.releasePointerCapture(pointer);}catch{}pointer=null;last=null;flush().then(()=>{if(!closed)refresh();});};canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;
const visibility=()=>{if(document.hidden)finish();};const hide=()=>finish();addEventListener('resize',hide);document.addEventListener('visibilitychange',visibility);addEventListener('pagehide',hide);paint();refresh();return{id:t.id,refresh,flush,get active(){return pointer!==null;},dispose(){closed=true;cancelAnimationFrame(fxRaf);finish();document.removeEventListener('visibilitychange',visibility);removeEventListener('pagehide',hide);removeEventListener('resize',hide);canvas.onpointerdown=canvas.onpointermove=canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=null;}};
}
