import {MACHINES,BETS} from './data.mjs?v=20261006-town7';
export function random(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}
const pick=(rng,n)=>Math.min(n-1,Math.floor(rng()*n));
const grid=(m,rng)=>Array.from({length:m.rows},()=>Array.from({length:m.cols},()=>pick(rng,6)));
const count=(g,v)=>g.flat().filter(x=>x===v).length;
function lines(g,base){let win=0,cells=[];g.forEach((row,y)=>{for(let x=0;x<row.length;){let end=x+1;while(end<row.length&&row[end]===row[x])end++;if(end-x>=3){win+=base+(end-x-3)*8;for(let i=x;i<end;i++)cells.push([y,i])}x=end}});return {win,cells}}
function classic(g,base,two){const a=g[0];if(a.every(x=>x===a[0]))return base+(a[0]===0?base:0);return new Set(a).size===2?two:0}
function friendlyRow(rng,base){const n=rng(),v=pick(rng,6);if(n<.28)return [[v,(v+1+pick(rng,4))%6,(v+5)%6]];if(n<.97){const row=[v,v,(v+1+pick(rng,5))%6],i=pick(rng,3);[row[i],row[2]]=[row[2],row[i]];return [row]}const symbol=n<.995?1+pick(rng,5):0;return [[symbol,symbol,symbol]]}
function scatter(m,symbol,n,rng){const others=Array.from({length:6},(_,i)=>i).filter(v=>v!==symbol),g=Array.from({length:m.rows},(_,y)=>Array.from({length:m.cols},(_,x)=>others[(x+y+pick(rng,2))%others.length]));for(const row of g)for(let x=2;x<row.length;x++)if(row[x]===row[x-1]&&row[x]===row[x-2])row[x]=others[(others.indexOf(row[x])+1)%others.length];const positions=Array.from({length:m.rows*m.cols},(_,i)=>i);for(let i=0;i<n;i++){const p=positions.splice(pick(rng,positions.length),1)[0];g[Math.floor(p/m.cols)][p%m.cols]=symbol}return g}
export function roll(machine,progress,rng=random){const m=MACHINES.find(x=>x.id===machine);if(!m)throw Error('找不到機台');let g=grid(m,rng),frames=[],win=0,note='',garden=progress.garden,photo=progress.photo,phase='ready';
 if(machine==='classic'||machine==='toy'){g=friendlyRow(rng);win=classic(g,machine==='toy'?110:100,machine==='toy'?20:22);note=win?'幸運圖案連線！':'這次沒有連線，下一次會有新驚喜。';if(machine==='toy'){phase='choice';note='可收獎或保留一軸免費重轉；重轉會取代目前獎金。'}frames=[structuredClone(g)]}
 if(machine==='sweet'){if(rng()<.63){const y=pick(rng,3),x=pick(rng,3),v=pick(rng,6);for(let k=0;k<3;k++)g[y][x+k]=v}frames=[structuredClone(g)];for(let i=0;i<3;i++){const l=lines(g,23);if(!l.win)break;win+=l.win*(i+1);note=`完成 ${i+1} 次甜點連鎖`;if(i<2){for(let x=0;x<m.cols;x++){const remaining=g.map((row,y)=>({v:row[x],y})).filter(({y})=>!l.cells.some(([yy,xx])=>yy===y&&xx===x)).map(o=>o.v),column=Array.from({length:m.rows-remaining.length},()=>pick(rng,6)).concat(remaining);g.forEach((row,y)=>row[x]=column[y]);}frames.push(structuredClone(g))}}if(!note)note='這次甜點沒有連成一排。'}
 if(machine==='moon'){const n=rng(),stars=n<.05?0:n<.37?2:n<.90?3:n<.98?5:n<.996?8:15;g=scatter(m,1,stars,rng);frames=[structuredClone(g)];if(stars>=3){for(let i=0;i<2;i++){g=g.map(row=>row.map(v=>v===1?1:pick(rng,6)));frames.push(structuredClone(g))}note=`鎖星成功！免費重轉後收集 ${count(g,1)} 顆星。`}else note=`收集 ${stars} 顆星，三顆可啟動鎖星重轉。`;win=count(g,1)===15?300:count(g,1)*5}
 if(machine==='garden'){const n=rng(),leaves=n<.28?0:n<.48?2:n<.83?3:n<.98?5:n<.998?8:12;g=scatter(m,3,leaves,rng);frames=[structuredClone(g)];garden+=leaves;const flowers=Math.floor(garden/18);garden%=18;win=leaves*4+lines(g,12).win+flowers*55;note=flowers?'花園開花！額外得到 55 金幣。':`收集 ${leaves} 片葉子，花園進度 ${garden}/18。`}
 if(machine==='photo'){const n=rng(),photos=n<.28?0:n<.48?1:n<.83?2:n<.98?3:5;g=scatter(m,4,photos,rng);frames=[structuredClone(g)];photo+=photos;const pages=Math.floor(photo/12);photo%=12;win=photos*6+pages*50;if(g[0].some(v=>count(g,v)>=3))win+=18;note=pages?'相簿完成一頁！額外得到 50 金幣。':`收集 ${photos} 個相機，相簿進度 ${photo}/12。`}
 return {id:crypto.randomUUID(),machine,phase,grid:g,frames,win,note,garden,photo};}
export function toyReroll(p,keep,rng=random){if(p.machine!=='toy'||p.phase!=='choice'||!Number.isInteger(keep)||keep<0||keep>2)throw Error('無法重轉');const next=structuredClone(p),n=rng(),v=p.grid[0][keep],other=[0,1,2].filter(i=>i!==keep);next.grid=[p.grid[0].slice()];if(n<.70){next.grid[0][other[0]]=v;next.grid[0][other[1]]=(v+1+pick(rng,5))%6}else if(n<.725){next.grid[0][other[0]]=v;next.grid[0][other[1]]=v}else{next.grid[0][other[0]]=(v+1)%6;next.grid[0][other[1]]=(v+2+pick(rng,4))%6}next.frames=[structuredClone(next.grid)];next.win=classic(next.grid,110,20)*(p.bet||1);next.phase='ready';next.note=`保留第 ${keep+1} 軸，免費重轉已完成。`;return next}
export async function beginSpin(store,machine){const m=MACHINES.find(x=>x.id===machine);return store.change(s=>{if(s.scratch)throw Error('請先完成目前刮刮樂');const bet=s.bets?.[machine]||1;if(!BETS.includes(bet))throw Error('下注倍率不正確');if(s.coins<m.cost*bet)throw Error('金幣不足，可以到櫃台申請生活補助。');s.coins-=m.cost*bet;s.pending=roll(machine,s.progressByBet?.[bet]||s.progress);s.pending.bet=bet;s.pending.win*=bet;s.stats.spins++;if(!s.stats.visited.includes(machine))s.stats.visited.push(machine)})}
export function settle(store){return store.change(s=>{const p=s.pending;if(!p||p.phase!=='ready')throw Error('尚未完成旋轉選擇');s.coins+=p.win;s.stats.won+=p.win;s.stats.biggest=Math.max(s.stats.biggest,p.win);s.progress={garden:p.garden,photo:p.photo};s.progressByBet[p.bet||1]={...s.progress};s.pending=null},{allowPending:true})}
