import {TICKET_CATALOG,TICKET_COSTS,ticketProduct,productLayout} from './ticket-catalog.mjs?v=20261008-complete2';
import {SYMBOLS,ROLE_MAP,BY_ID} from './data.mjs?v=20261008-complete2';
const n=v=>v.toLocaleString('zh-TW'),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,attrs='',cls='')=>`<button type="button" class="wood-button ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
export function productRulesHTML(p){return `<div class="product-rule"><img src="${p.art}" alt="${p.name} ${p.cost} 金幣票面示意"><p><b>面額 ${n(p.cost)} 金幣 · 最高 ${n(p.max)} 金幣</b></p><p>${p.rules}</p>${p.mode==='trio'?`<div class="symbol-guide">${SYMBOLS.map((s,i)=>`<div><img src="${s.art}" alt="${s.name}"><small>${s.name}三同<br>${[200,100,60,40,30,20][i]} 金幣</small></div>`).join('')}</div>`:''}<p>票面符號、號碼與獎金先保存；結算依上述規則逐項計算。刮除方式與揭曉順序不影響結果。</p></div>`;}
export function productLobby(s,cost){const cards=TICKET_CATALOG.filter(p=>p.cost===cost);return `<main class="scratch-page scratch-lobby product-lobby"><div class="section-heading"><span class="eyebrow">SCRATCH COLLECTION</span><h1>挑一張今天的小幸運</h1><p>五種面額 · 十款獨立票券，每張都有自己的玩法。</p></div><div class="ticket-costs"><span>面額</span>${TICKET_COSTS.map(v=>btn(n(v)+' 金幣','scratch-cost',`data-cost="${v}" aria-pressed="${v===cost}"`,v===cost?'active':'')).join('')}</div><div class="ticket-grid">${cards.map(p=>`<article class="ticket-card product-card product-${p.theme}"><div class="ticket-card-preview"><img src="${p.art}" alt="${p.name}獨立票面"></div><div class="product-copy"><h2>${p.name}</h2><p>${p.desc}</p><small>${n(p.cost)} 金幣／張 · 最高 ${n(p.max)}</small><div class="actions">${btn('玩法與獎表','ticket-rules',`data-kind="${p.id}" data-cost="${p.cost}"`)}${btn('買一張 · '+n(p.cost),'buy-ticket',`data-kind="${p.id}" data-cost="${p.cost}" ${s.coins<p.cost?'disabled':''}`,'primary')}</div></div></article>`).join('')}</div><div class="catalog-pages"><span>每個面額有兩款不同玩法，點選面額換票。</span>${btn('生活補助','aid')}${btn('回拉霸館','navigate','data-page="arcade"')}</div></main>`;}
function cell(t,p,i){const v=t.values[i],prize=t.prizes[i];
 if(['trio','stars'].includes(p.mode))return `<img src="${SYMBOLS[v].art}" alt="${SYMBOLS[v].name}">`;
 if(p.mode==='coins')return v===1?`<img class="ticket-small-icon" src="art/coin.webp" alt="金幣"><b>${n(prize)}</b>`:'<img src="art/scratch-pocket-v2.webp" alt="空口袋"><small>空口袋</small>';
 if(p.mode==='numbers')return `<b>${v}</b><small>${n(prize)} 金幣</small><span>${t.lucky.includes(v)?'命中':'未命中'}</span>`;
 if(p.mode==='keys')return i%4===3?`<img src="art/scratch-chest-v2.webp" alt="寶箱"><small>${n(prize)} 金幣</small>`:v===1?'<img src="art/scratch-key-v2.webp" alt="鑰匙"><small>鑰匙</small>':'<img src="art/scratch-stone-v2.webp" alt="石頭"><small>未找到鑰匙</small>';
 if(p.mode==='garden')return v===1?'<img src="art/furniture-flower.webp" alt="花朵">':'<img src="art/scratch-sprout-v2.webp" alt="嫩芽">';
 if(p.mode==='bags')return i===5?`<small>本張倍率</small><b>×${v}</b>`:`<img class="ticket-small-icon" src="art/scratch-letter-v2.webp" alt="獎金信"><b>${n(prize)}</b><small>金幣</small>`;
 if(p.mode==='bingo')return `<b>${v}</b><small>${t.lucky.includes(v)?'命中':'未命中'}</small>`;
 if(p.mode==='trail')return v===1?'<img src="art/scratch-trail-v2.webp" alt="足跡"><small>足跡</small>':'<img src="art/scratch-stone-v2.webp" alt="石頭"><small>停止</small>';
 if(p.mode==='vault')return i%3===2?`<small>金庫獎金</small><b>${n(prize)}</b>`:`<small>${i%3===0?'你的點數':'守衛點數'}</small><b>${v}</b>`;
 return '';
}
export function productScreen(s){const t=s.scratch,p=ticketProduct(t.kind),key=s.outfits[s.role].suit,avatar=key==='original'?ROLE_MAP[s.role].original:BY_ID[key].art;return `<main class="scratch-page product-scratch"><div class="section-heading"><span class="eyebrow">${p.cost} 金幣／張</span><h1>${p.name}</h1><p>${p.desc}</p></div><section class="scratch-table"><div class="ticket-work product-ticket product-${p.theme}" style="--ticket-art:url('${p.art}')"><div class="ticket-heading"><b>${p.name} · ${p.cost} 金幣</b><small>${p.mode==='numbers'?'對號領取該格獎金':p.mode==='bingo'?'每條完整連線 400 金幣':p.mode==='vault'?'你的點數 ＞ 守衛點數才領獎':p.desc}</small></div>${t.lucky.length?`<div class="ticket-lucky">${p.mode==='numbers'?'幸運號碼':'開獎號碼'}：${t.lucky.join(' · ')}</div>`:''}<div class="whole-ticket-values">${productLayout(t).map((r,i)=>`<div class="ticket-region" data-ticket-region="${i}" aria-hidden="${!t.revealed[i]}" style="left:${r.x*100}%;top:${r.y*100}%;width:${r.w*100}%;height:${r.h*100}%"><div class="scratch-value">${cell(t,p,i)}</div></div>`).join('')}</div><canvas id="ticket-foil" width="1200" height="675" aria-label="${p.name}刮除區，按住連續滑動"></canvas><div class="ticket-prize">本張獲得 ${n(t.win)} 金幣</div></div></section><aside class="scratch-actions paper"><div class="scratch-companion"><div class="avatar"><img class="body-art" src="${avatar}" alt="${ROLE_MAP[s.role].name}"></div></div>${t.lucky.length?`<p class="ticket-open-numbers">${p.mode==='numbers'?'幸運號碼':'開獎號碼'}：${t.lucky.join(' · ')}</p>`:''}<p id="scratch-progress">已揭曉 ${t.revealed.filter(Boolean).length}／${t.values.length} 區</p>${btn('玩法與獎表','ticket-rules',`data-kind="${p.id}" data-cost="${p.cost}"`)}<button id="scratch-help" hidden class="wood-button" data-action="scratch-finish">補刮剩餘小角落</button><div class="actions">${btn('收下獎金','scratch-collect',t.revealed.every(Boolean)?'':'disabled','primary')}${btn('全部揭曉','scratch-all')}${btn('先回遊戲館','navigate','data-page="arcade"')}</div></aside></main>`;}
