'use strict';
const KEY='dream_clicker_v1';
const HEROES=[
 {n:'芽芽',job:'幸運採集者',base:15,prod:1,unlock:0,skill:'主角暴擊率 +8%，暴擊獲得 5 倍星願。'},
 {n:'暖暖',job:'療癒守護者',base:100,prod:5,unlock:50,skill:'離線收益 +50%，穩定照顧旅團。'},
 {n:'森森',job:'森林引導者',base:750,prod:22,unlock:500,skill:'所有角色與建築的升級費用 -10%。'},
 {n:'小憶',job:'回憶收藏家',base:5000,prod:95,unlock:3500,skill:'故事碎片取得速度提高 100%。'},
 {n:'樂樂',job:'慶典主持人',base:28000,prod:420,unlock:20000,skill:'連擊維持時間加倍，最高倍率提高。'},
 {n:'星眠',job:'月夜守望者',base:150000,prod:1800,unlock:100000,skill:'離線收益再提高，並預覽遠征結果範圍。'},
 {n:'鎖鎖',job:'寶箱管理員',base:850000,prod:7800,unlock:600000,skill:'每 60 秒送來寶箱，遠征骰子可重投。'},
 {n:'紫願',job:'星願信使',base:4500000,prod:34000,unlock:3000000,skill:'所有遠征時間縮短 30%。'},
 {n:'雨音',job:'雨露培育者',base:24000000,prod:150000,unlock:16000000,skill:'每次點擊可能獲得夢露永久素材。'},
 {n:'雲絲',job:'心光裁縫師',base:130000000,prod:680000,unlock:90000000,skill:'所有角色產量乘算提高 25%。'}
];
const BUILDINGS=[
 {n:'星願樹小屋',file:'star-cottage',base:800,mul:1.20,desc:'點擊收益 +20%'},{n:'安心毛毯屋',file:'blanket-house',base:3500,mul:1.18,desc:'全體每秒產量 +18%'},{n:'森林採集所',file:'forest-hut',base:15000,mul:1.12,desc:'角色升級費用額外 -2%'},{n:'回憶相館',file:'memory-studio',base:65000,mul:1.15,desc:'故事碎片取得 +15%'},{n:'慶典廣場',file:'festival-kiosk',base:280000,mul:1.12,desc:'暴擊率 +2%'},{n:'月光觀星台',file:'moon-observatory',base:1200000,mul:1.25,desc:'離線收益 +25%'},{n:'黃金鑰匙舖',file:'key-shop',base:5500000,mul:1.20,desc:'寶箱獎勵 +20%'},{n:'星願郵塔',file:'mail-tower',base:25000000,mul:1.15,desc:'遠征獎勵 +15%'},{n:'雨露溫室',file:'rain-greenhouse',base:110000000,mul:1.18,desc:'夢露效果 +18%'},{n:'雲端織夢塔',file:'cloud-atelier',base:500000000,mul:1.30,desc:'全體產量 +30%'}];
const ROUTES=[{n:'星光森林採集',time:60,min:600,max:1000,map:1,need:2},{n:'雨夜小鎮信件',time:180,min:3500,max:6000,map:2,need:8},{n:'月光郵路護送',time:600,min:18000,max:32000,map:3,need:5},{n:'雲端夢境急件',time:1800,min:90000,max:160000,map:4,need:7},{n:'永恆星願樹',time:7200,min:500000,max:900000,map:5,need:9}];
const STORY=[['沒有收件人的信','金色種子','芽芽的回信'],['柔軟的惡夢','雨夜熱茶','安心的歸處'],['森林鈴聲','綠色郵票','地圖上的名字'],['明日照片','日常相簿','記憶的證明'],['小小慶典','廣場彩燈','最長的煙火'],['月光路標','紫色星屑','改寫預言'],['拒絕開啟的寶箱','承諾之鑰','大家的歸處'],['天空急件','星雨方向','世界兩端'],['雨後之花','溫室歉意','溫柔細雨'],['五色夢線','天空裂痕','新的夢境郵路']];
const STICKERS=['01-happy','02-laugh','03-sad','04-cry','05-angry','06-surprised','07-shy','08-confused','09-proud','10-sleepy','11-cheer','12-love','13-nervous','14-celebrate','15-hurt','16-victory'];
const fresh=()=>({stars:0,total:0,taps:0,hero:0,heroLv:Array(10).fill(0),buildLv:Array(10).fill(0),clickLv:0,critLv:0,comboLv:0,buy:1,dust:0,dew:0,stories:Array(10).fill(0),expedition:null,lastChest:Date.now(),last:Date.now(),notice:'點擊主角，獲得第一顆星願。'});
let s=fresh(),tab='main',combo=1,lastTap=0,toastTimer=0;try{s={...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
const $=q=>document.querySelector(q),fmt=n=>n<1000?Math.floor(n).toLocaleString():n<1e6?(n/1e3).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'K':n<1e9?(n/1e6).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'M':n<1e12?(n/1e9).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'B':(n/1e12).toFixed(2)+'T';
const heroImg=i=>`assets/characters/character-${String(i+1).padStart(2,'0')}.png`,cardImg=i=>`assets/cards/character-card-${String(i+1).padStart(2,'0')}.png`,houseImg=i=>`assets/houses/${BUILDINGS[i].file}.png`,sticker=i=>`assets/stickers/${STICKERS[i]}.png`;
const discount=()=>Math.max(.65,1-(s.heroLv[2]>0?.10:0)-s.buildLv[2]*.02),dustMul=()=>1+s.dust*.1,cloudMul=()=>s.heroLv[9]>0?1.25:1;const clickPower=()=>Math.max(1,(1+s.clickLv)*Math.pow(1.18,s.buildLv[0])*dustMul()*(1+s.dew*.01));const critChance=()=>Math.min(.5,.05+s.critLv*.01+(s.hero===0?.08:0)+s.buildLv[4]*.02);const heroDps=i=>s.heroLv[i]*HEROES[i].prod*Math.pow(1.16,Math.floor(s.heroLv[i]/10));const dps=()=>HEROES.reduce((v,_,i)=>v+heroDps(i),0)*Math.pow(1.18,s.buildLv[1])*Math.pow(1.3,s.buildLv[9])*dustMul()*cloudMul();const levelCost=(i,lv=s.heroLv[i])=>HEROES[i].base*Math.pow(1.15,lv)*discount();const buildingCost=(i,lv=s.buildLv[i])=>BUILDINGS[i].base*Math.pow(2.35,lv)*discount();
function bundleCost(fn,start,count){let sum=0;for(let i=0;i<count;i++)sum+=fn(start+i);return sum}function affordable(fn,start,max=1000){let sum=0,n=0;while(n<max){const c=fn(start+n);if(sum+c>s.stars)break;sum+=c;n++}return {n,cost:sum}}function buyInfo(fn,start){if(s.buy==='max')return affordable(fn,start);return {n:s.buy,cost:bundleCost(fn,start,s.buy)}}function save(){s.last=Date.now();localStorage.setItem(KEY,JSON.stringify(s))}function notify(t){s.notice=t;const n=$('#notice');if(n)n.textContent=t;const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove('on'),1200)}function react(i){const el=$('#reaction');if(!el)return;el.src=sticker(i);el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function header(){return `<header><div><small>STARWISH CLICKER</small><h1>星願旅團</h1><span>${HEROES[s.hero].n}｜${HEROES[s.hero].job}</span></div><div class="counter"><small>目前星願</small><b id="starCount">${fmt(s.stars)}</b><span id="dpsCount">每秒 ${fmt(dps())}</span></div></header><div id="notice" class="notice">${s.notice}</div>`}
function main(){return `<section class="stage"><img class="side-npc left" src="assets/npcs/merchant.png"><img class="side-npc right" src="assets/npcs/cartographer.png"><img id="reaction" class="reaction" src="${sticker(0)}"><button id="tapHero" aria-label="點擊${HEROES[s.hero].n}"><img src="${heroImg(s.hero)}"><span>${HEROES[s.hero].n}</span></button><div id="floatLayer"></div><div class="combo">連擊 <b id="combo">×${combo.toFixed(1)}</b></div></section><section class="quick"><div class="power"><span>每次點擊</span><b>+${fmt(clickPower())}</b><small>暴擊率 ${(critChance()*100).toFixed(0)}%</small></div>${upgradeRow('click','星願手套',s.clickLv,25*Math.pow(1.8,s.clickLv),`點擊 +1 → +${s.clickLv+2}`,'assets/items/currency-star.png')}${upgradeRow('crit','幸運鈴鐺',s.critLv,120*Math.pow(2,s.critLv),`暴擊率 +1%`,'assets/items/badge.png')}${upgradeRow('combo','慶典節拍',s.comboLv,400*Math.pow(2.1,s.comboLv),`連擊收益 +5%`,'assets/items/petal.png')}</section>`}
function upgradeRow(id,n,lv,cost,desc,img){return `<button class="upgrade" data-upgrade="${id}" ${s.stars<cost?'disabled':''}><img src="${img}"><span><b>${n} Lv.${lv}</b><small>${desc}</small></span><strong>升級<small>${fmt(cost)}</small></strong></button>`}
function heroes(){return `<section class="panel"><div class="title"><div><small>每秒自動產生星願</small><h2>旅團夥伴</h2></div>${buyModes()}</div><div class="list">${HEROES.map((h,i)=>{const unlocked=s.total>=h.unlock||s.heroLv[i]>0||i===0,info=buyInfo(lv=>levelCost(i,lv),s.heroLv[i]);return `<article class="unit ${s.hero===i?'selected':''} ${unlocked?'':'locked'}"><button class="portrait" data-lead="${i}" ${unlocked?'':'disabled'}><img src="${cardImg(i)}"><small>${s.hero===i?'主角':'設為主角'}</small></button><div><h3>${h.n} <small>Lv.${s.heroLv[i]}</small></h3><p>${h.skill}</p><span>每秒 ${fmt(heroDps(i))}</span></div><button class="buy" data-buyhero="${i}" ${!unlocked||!info.n||s.stars<info.cost?'disabled':''}><b>${unlocked?`升 ${info.n} 級`:`累積 ${fmt(h.unlock)}`}</b><small>${unlocked?fmt(info.cost):'尚未遇見'}</small></button></article>`}).join('')}</div></section>`}
function buyModes(){return `<div class="buy-modes">${[1,10,100,'max'].map(x=>`<button data-mode="${x}" class="${String(s.buy)===String(x)?'on':''}">${x==='max'?'最大':'×'+x}</button>`).join('')}</div>`}
function village(){const built=s.buildLv.filter(Boolean).length;return `<section class="panel"><div class="title"><div><small>建築提供永久本輪加成</small><h2>夢境村莊</h2></div><b>${built}/10</b></div><div class="village-map">${BUILDINGS.map((b,i)=>s.buildLv[i]?`<figure class="house h${i}"><img src="${houseImg(i)}"><figcaption>${b.n} Lv.${s.buildLv[i]}</figcaption></figure>`:'').join('')}${built?'':'<div class="empty">建造第一棟房屋，點亮村莊</div>'}</div><div class="list buildings">${BUILDINGS.map((b,i)=>{const info=buyInfo(lv=>buildingCost(i,lv),s.buildLv[i]);return `<article class="building"><img src="${houseImg(i)}"><div><h3>${b.n} <small>Lv.${s.buildLv[i]}</small></h3><p>${b.desc}</p></div><button data-buybuild="${i}" ${!info.n||s.stars<info.cost?'disabled':''}><b>${s.buildLv[i]?'升級':'建造'} ${info.n}</b><small>${fmt(info.cost)}</small></button></article>`}).join('')}</div></section>`}
function expedition(){if(s.expedition){const r=ROUTES[s.expedition.id],left=Math.max(0,s.expedition.ends-Date.now());return `<section class="panel"><div class="title"><div><small>計時派遣</small><h2>${r.n}</h2></div><b id="routeTime">${time(left)}</b></div><div class="active-route"><img src="assets/map/expedition-${r.map}.jpg"><div class="party">${s.expedition.team.map(i=>`<img src="${heroImg(i)}">`).join('')}</div><p>預計獎勵 ${fmt(r.min)}～${fmt(r.max)} 星願</p><button id="claimRoute" ${left>0?'disabled':''}>${left>0?'遠征進行中':'擲骰並領取獎勵'}</button></div></section>`}return `<section class="panel"><div class="title"><div><small>離開前安排額外收益</small><h2>計時遠征</h2></div><img class="die" src="assets/items/dream-die.png"></div><div class="routes">${ROUTES.map((r,i)=>{const unlocked=s.total>=r.min/2,sec=Math.floor(r.time*(s.heroLv[7]>0?.7:1));return `<article class="route ${unlocked?'':'locked'}"><img src="assets/map/expedition-${r.map}.jpg"><div><h3>${r.n}</h3><p>時間 ${time(sec*1000)}｜獎勵 ${fmt(r.min)}～${fmt(r.max)}</p><small>${HEROES[r.need].n}同行：獎勵 +30%</small></div><button data-route="${i}" ${unlocked?'':'disabled'}>${unlocked?'出發':'未解鎖'}</button></article>`}).join('')}</div></section>`}
function time(ms){const sec=Math.ceil(ms/1000),m=Math.floor(sec/60),h=Math.floor(m/60);return h?`${String(h).padStart(2,'0')}:${String(m%60).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}