(()=>{
const modeInfo={
 daily:{name:'今日運勢',kicker:'一天一次的溫柔提醒',intro:'看看今天的整體能量、幸運提示，以及最值得完成的一件小事。',guide:'希望',image:'assets/characters/hope.png',accent:'#9eacc3'},
 love:{name:'感情占卜',kicker:'關係裡沒有標準答案',intro:'看見你的狀態、關係中的氣流，以及此刻最適合的下一步。',guide:'快樂',image:'assets/characters/joy.png',accent:'#d89b9e'},
 career:{name:'工作財運',kicker:'把混亂變成可行的一步',intro:'整理目前的機會、風險與行動時機，不替你做決定。',guide:'信任',image:'assets/characters/trust.png',accent:'#9d8a6e'},
 decision:{name:'是非・二選一',kicker:'不是替你選，而是看清差異',intro:'輸入猶豫的事情，比較兩條路各自帶來的能量與代價。',guide:'夢想',image:'assets/characters/dream.png',accent:'#aa97c1'},
 mood:{name:'心情測驗',kicker:'你現在真正需要的是什麼？',intro:'憑第一直覺選一扇門，聽聽內心正在發出的訊號。',guide:'療癒',image:'assets/characters/healing.png',accent:'#a9b5bd'}
};
const readings={
 daily:[
 {title:'雨後初晴',score:78,summary:'早上的情緒可能有些雜亂，但真正的局勢比你想像中穩定。午後開始，一件遲遲沒有回應的事情會出現小小轉機。',good:'整理、回覆訊息、完成舊任務',avoid:'在疲憊時做重大決定',action:'刪除或收起一件不再需要的東西。',sticker:'13-cheer'},
 {title:'風正在轉向',score:84,summary:'今天適合主動一點。你不需要準備到完美，只要先把真正的需要說清楚，停滯的關係或工作就可能開始移動。',good:'提出需求、短程出門、開始新計畫',avoid:'反覆猜測別人的想法',action:'在中午前完成一件拖延三天以上的小事。',sticker:'01-joyful'},
 {title:'安靜累積',score:69,summary:'今天不是衝刺的日子。看似沒有進展的地方，其實正在累積必要的條件。減少外界雜訊，你會更清楚自己真正想留下什麼。',good:'閱讀、存錢、獨處、整理順序',avoid:'因焦慮而臨時加碼',action:'留二十分鐘不看訊息，只專注做一件事。',sticker:'10-thinking'}],
 love:[
 {title:'靠近，但不要催促',score:76,summary:'關係裡存在真實的好感，只是雙方的速度不完全相同。現在最有力量的做法不是試探，而是讓互動保持自然與穩定。',good:'真誠回應、輕鬆邀約、說清界線',avoid:'用冷淡測試對方是否在意',action:'傳遞一個不帶壓力、可以被輕鬆回覆的訊息。',sticker:'03-shy'},
 {title:'先回到自己的位置',score:61,summary:'你可能把太多注意力放在對方的反應上，因而忽略了自己的感受。這段關係真正需要的是平衡，而不是更多用力。',good:'照顧生活節奏、觀察行動、保留空間',avoid:'替對方找理由或過度解讀',action:'寫下你希望一段關係帶給你的三種感受。',sticker:'09-confused'},
 {title:'一次溫柔的確認',score:82,summary:'模糊已經累積到需要被說清楚的程度。這次溝通不必沉重，只要誠實表達你的感受與期待，就能知道彼此是否走在同一方向。',good:'坦白、確認、面對真正問題',avoid:'假裝不在意',action:'用「我目前的感受是……」開啟一次對話。',sticker:'04-moved'}],
 career:[
 {title:'穩中有進',score:81,summary:'累積的工作開始有被看見的機會。今天適合處理最重要但不一定最緊急的任務，先完成核心，再回頭修飾細節。',good:'提案、整理成果、確認時程',avoid:'一次接下太多新任務',action:'把今天最重要的工作寫成一句明確的完成條件。',sticker:'15-proud'},
 {title:'先守住資源',score:65,summary:'目前資訊還不夠完整，衝動投入可能讓成本變高。財運不是不好，而是需要更清楚的預算與停損線。',good:'比價、查資料、保留現金',avoid:'情緒性消費與口頭承諾',action:'延後一筆非必要支出二十四小時。',sticker:'10-thinking'},
 {title:'主動才會打開',score:87,summary:'機會不會自己走到面前。你的條件已經比想像中完整，現在需要的是清楚提出需求，讓別人知道你準備好了。',good:'爭取、寄出作品、主動聯絡',avoid:'因害怕拒絕而保持沉默',action:'今天主動完成一次詢問、申請或邀約。',sticker:'13-cheer'}],
 decision:[
 {title:'答案偏向你真正想要的那一邊',score:74,summary:'兩個選項都能前進，但其中一個讓你感到踏實，另一個只是暫時減輕焦慮。請優先選擇能長期維持的方向。',good:'比較長期成本、確認底線',avoid:'只看眼前最輕鬆的選項',action:'想像半年後的自己，寫下他會感謝你做了哪個選擇。',sticker:'10-thinking'},
 {title:'不是現在',score:58,summary:'問題目前缺少一項關鍵資訊。與其在不完整的條件下勉強二選一，不如先設定一個確認期限，讓新的事實加入判斷。',good:'等待證據、詢問細節、設定期限',avoid:'因別人催促而倉促答應',action:'列出做決定前還必須確認的唯一一件事。',sticker:'11-nervous'},
 {title:'可以前進，但先小規模測試',score:79,summary:'方向偏正面，但不需要一次押上全部。先用可以承受的成本試走一步，真實回饋會比想像更可靠。',good:'試用、短期計畫、小額投入',avoid:'把選擇想成不可逆',action:'把下一步縮小成一個能在三天內完成的測試。',sticker:'01-joyful'}],
 mood:[
 {title:'你需要被理解',summary:'你並不是太敏感，只是有些感受被放得太久。現在不需要急著振作，先找一個安全的地方，把真正介意的事情說完整。',good:'傾聽、書寫、找可信任的人',avoid:'用忙碌壓下所有感受',action:'用五分鐘寫下：「其實我最在意的是……」',sticker:'04-moved'},
 {title:'你需要休息',summary:'疲憊讓每一件事看起來都比原本更困難。今天最重要的不是多完成一件事，而是停止繼續透支。',good:'提早睡、散步、降低訊息量',avoid:'在精疲力竭時責怪自己',action:'今晚比平常提早三十分鐘停止工作。',sticker:'16-goodnight'},
 {title:'你需要重新掌握節奏',summary:'真正讓你不安的可能不是事情太多，而是不知道該從哪裡開始。只要重新排出順序，失控感就會慢慢降低。',good:'列清單、拒絕干擾、完成小事',avoid:'同時處理所有問題',action:'選出一件十分鐘內能完成的事情，現在就做。',sticker:'13-cheer'}]
};
const state={view:'home',mode:'daily',question:'',optionA:'',optionB:'',selected:null,reading:null,journal:[]};
try{state.journal=JSON.parse(localStorage.getItem('quiet-oracle-journal')||'[]')}catch{state.journal=[]}
const root=document.getElementById('app');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function dateLabel(){return new Date().toLocaleDateString('zh-TW',{month:'long',day:'numeric',weekday:'long'})}
function seedIndex(length,extra=0){const d=new Date();return(d.getFullYear()*13+(d.getMonth()+1)*31+d.getDate()*17+extra)%length}
function info(){return modeInfo[state.mode]}
function saveJournal(){localStorage.setItem('quiet-oracle-journal',JSON.stringify(state.journal))}
function begin(m){state.mode=m;state.question='';state.optionA='';state.optionB='';state.selected=null;state.reading=null;state.view='prepare';render()}
function reveal(choice=0){const src=readings[state.mode];const base=src[seedIndex(src.length,choice+state.question.length+state.optionA.length*2+state.optionB.length*3)];const result={...base,id:(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)),date:new Date().toLocaleString('zh-TW',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}),mode:info().name};state.reading=result;state.journal=[result,...state.journal].slice(0,30);saveJournal();state.view='result';render()}
function header(){return `<header class="quiet-header"><button class="wordmark" data-act="home"><span>命</span><b>今日占卜</b></button><button class="journal-link" data-act="journal">占卜手帳 <i>${state.journal.length}</i></button></header>`}
function home(){return `<div class="home-view"><section class="hero-reading"><div class="date-line"><span>${dateLabel()}</span><i></i></div><div class="hero-copy"><p class="overline">今天的心，需要哪一種提醒？</p><h1>讓答案<br>慢慢浮現。</h1><p>不用急著相信命運。只要花一分鐘，聽聽此刻的自己。</p><button class="primary-action" data-mode="daily"><span>開始今日占卜</span><small>約 30 秒</small></button></div><div class="hero-character"><div class="soft-sun"></div><img src="assets/characters/memory.png" alt="今日陪伴者：回憶"><div class="character-note"><small>今日陪伴者</small><b>回憶</b><p>「你不需要一次想清楚所有事。」</p></div></div></section><section class="mode-section"><div class="section-title"><div><p class="overline">其他占卜</p><h2>你現在想問什麼？</h2></div><p>選一個最接近你心裡的問題。</p></div><div class="mode-list">${['love','career','decision','mood'].map((m,i)=>`<button data-mode="${m}"><span class="mode-number">0${i+1}</span><span class="mode-text"><b>${modeInfo[m].name}</b><small>${modeInfo[m].kicker}</small></span><img src="${modeInfo[m].image}" alt=""><i>開始</i></button>`).join('')}</div></section><footer class="home-footer"><span>占卜是整理想法的方式，不替你做重要決定。</span><button data-act="journal">查看過去的訊息</button></footer></div>`}
function prepare(){const x=info();let input='';if(state.mode==='decision')input=`<div class="choice-inputs"><label><span>選項 A</span><input id="optionA" value="${esc(state.optionA)}" placeholder="例如：主動聯絡"></label><label><span>選項 B</span><input id="optionB" value="${esc(state.optionB)}" placeholder="例如：再等一下"></label></div>`;else if(!['daily','mood'].includes(state.mode))input=`<label class="question-input"><span>想問的事情</span><textarea id="question" placeholder="簡單寫下目前的狀況，也可以留白……">${esc(state.question)}</textarea></label>`;return `<section class="session-view"><button class="back-link" data-act="home">返回首頁</button><div class="session-character"><div class="soft-sun"></div><img src="${x.image}" alt="${x.guide}陪伴者"><div><small>本次陪伴者</small><b>${x.guide}</b></div></div><article class="session-card"><p class="overline">${x.kicker}</p><h1>${x.name}</h1><p class="session-intro">${x.intro}</p>${input}<div class="privacy-note"><span>只保存在這台裝置</span><p>你的問題不會被上傳，占卜結果也可以隨時從手帳刪除。</p></div><button class="primary-action wide" data-act="ritual">${state.mode==='mood'?'開始直覺測驗':'準備好了'}</button></article></section>`}
function ritual(){const x=info();let choices='';if(state.mode==='mood')choices=`<div class="door-choices">${['晨霧','微光','深林'].map((l,i)=>`<button data-reveal="${i}"><i></i><span>${l}</span></button>`).join('')}</div>`;else if(state.mode==='decision')choices=`<div class="stone-choices">${[0,1,2].map(i=>`<button data-reveal="${i}" aria-label="選擇第 ${i+1} 顆石頭"><i></i></button>`).join('')}</div>`;else choices=`<div class="oracle-cards">${[0,1,2,3,4].map(i=>`<button data-card="${i}" class="${state.selected===i?'selected':''}" aria-label="選擇第 ${i+1} 張牌"><span><i></i></span></button>`).join('')}</div><button class="hold-button" data-act="reveal-selected" ${state.selected===null?'disabled':''}><i></i>${state.selected===null?'先選一張牌':'按住或點擊揭開訊息'}</button>`;return `<section class="ritual-view"><button class="back-link" data-act="prepare">重新輸入</button><div class="ritual-heading"><p class="overline">${x.name}</p><h1>${state.mode==='mood'?'憑第一直覺，選一扇門。':state.mode==='decision'?'選一顆最吸引你的石頭。':'安靜想著你的問題，選一張牌。'}</h1><p>${state.mode==='mood'?'不用分析畫面，只要留意第一個想靠近的選擇。':'沒有選錯的可能。你選擇的瞬間，就是這次占卜的一部分。'}</p></div>${choices}</section>`}
function result(){const x=info(),r=state.reading;return `<section class="result-view"><div class="result-top"><button class="back-link" data-act="home">回到首頁</button><span>結果已保存至手帳</span></div><div class="result-layout"><div class="result-visual"><div class="result-orbit"></div><img src="assets/stickers/${r.sticker}.png" alt="${x.guide}的反應"><div class="guide-quote"><small>${x.guide}想告訴你</small><p>「先照顧今天的自己，答案就會慢慢變清楚。」</p></div></div><article class="reading-paper"><p class="overline">${r.mode}結果</p><div class="result-title"><h1>${r.title}</h1>${r.score?`<span><b>${r.score}</b><small>綜合能量</small></span>`:''}</div><p class="summary">${r.summary}</p><div class="reading-grid"><div><small>今天適合</small><p>${r.good}</p></div><div><small>最好避免</small><p>${r.avoid}</p></div></div><div class="today-action"><small>今天可以完成的一件小事</small><p>${r.action}</p></div><div class="result-buttons"><button class="primary-action" data-mode="${state.mode}">再占一次</button><button data-act="journal">打開手帳</button></div><p class="disclaimer">這是一個當下的提醒，不是預言，也不取代你的判斷。</p></article></div></section>`}
function journal(){return `<section class="journal-view"><button class="back-link" data-act="home">返回首頁</button><div class="journal-heading"><p class="overline">只屬於你的記錄</p><h1>占卜手帳</h1><p>回頭閱讀時，不必檢查結果是否「應驗」，只要看看當時的自己在意什麼。</p></div>${state.journal.length?`<div class="journal-entries">${state.journal.map(i=>`<article><div><small>${esc(i.date)} · ${esc(i.mode)}</small><h2>${esc(i.title)}</h2><p>${esc(i.summary)}</p></div><span>${i.score||'—'}</span></article>`).join('')}</div>`:`<div class="journal-empty"><img src="assets/characters/memory.png" alt=""><h2>手帳還是空白的</h2><p>完成第一次占卜後，回憶會替你把訊息收好。</p><button class="primary-action" data-mode="daily">開始今日占卜</button></div>`}</section>`}
function render(){const x=info();document.documentElement.style.setProperty('--accent',x.accent);let body=state.view==='home'?home():state.view==='prepare'?prepare():state.view==='ritual'?ritual():state.view==='result'?result():journal();root.innerHTML=`<main class="quiet-app">${header()}${body}</main>`;bind()}
function bind(){root.querySelectorAll('[data-mode]').forEach(el=>el.addEventListener('click',()=>begin(el.dataset.mode)));root.querySelectorAll('[data-act]').forEach(el=>el.addEventListener('click',()=>{const a=el.dataset.act;if(a==='home'){state.view='home';render();scrollTo(0,0)}else if(a==='journal'){state.view='journal';render();scrollTo(0,0)}else if(a==='prepare'){state.view='prepare';render()}else if(a==='ritual'){const q=document.getElementById('question'),aEl=document.getElementById('optionA'),bEl=document.getElementById('optionB');if(q)state.question=q.value;if(aEl)state.optionA=aEl.value;if(bEl)state.optionB=bEl.value;state.view='ritual';render()}else if(a==='reveal-selected'&&state.selected!==null)reveal(state.selected)}));root.querySelectorAll('[data-card]').forEach(el=>el.addEventListener('click',()=>{state.selected=Number(el.dataset.card);render()}));root.querySelectorAll('[data-reveal]').forEach(el=>el.addEventListener('click',()=>reveal(Number(el.dataset.reveal))))}
render();
})();
