import {runBackgroundBattle} from './background-battle.mjs';
import {blessingFit,nextThreat} from './battle-guidance.mjs?v=20261007-names1';
import {sharedAssets,assetUrl,registerAssetCache} from './asset-loader.mjs?v=20261007-names1';
import {sessionAssets,chapterAssets,followingChapter,heroAssets,upcomingUnitAssets} from './asset-plan.mjs?v=20261007-names1';
import {installTouchGuard} from './touch-guard.mjs?v=20261007-names1';
import {installPractice} from './practice-ui.mjs?v=20261007-names1';
import {upgradeDetails} from './upgrade-details.mjs?v=20261007-names1';
import {ENEMY_CATALOG,ENEMY_IDS,isBoss,enemyArtAssets} from './enemy-catalog.mjs?v=20261007-names1';
import {selectAutoBlessing} from './assists.mjs?v=20261007-names1';
import {WEAPONS,weaponSummary,WEAPON_DROP_CHANCE} from './hero-weapons.mjs?v=20261007-names1';
import {spritePlacement} from './sprite-placement.mjs?v=20261007-names1';
import {advancedMotionArt,advancedMotionAssets,hasAdvancedMotion} from './advanced-motion.mjs?v=20261007-names1';
import {installCampaignSelection} from './campaign-ui.mjs?v=20261007-names1';
import {installVictoryGallery} from './victory-gallery.mjs?v=20261007-names1';
import {installDungeons} from './dungeon-ui.mjs?v=20261007-names1';
import {DUNGEONS,dungeonReward,dungeonWave} from './dungeons.mjs?v=20261007-names1';
import {installCommanderTabs} from './commander-ui.mjs?v=20261007-names1';
import {rememberCommander} from './commander-config.mjs?v=20261007-names1';
import {drawAttackFootprint,drawArmyMechanics} from './army3-effects.mjs?v=20261007-names1';
import {shapeDescription} from './attack-shapes.mjs?v=20261007-names1';
import {installMenuMotion} from './menu-motion.mjs?v=20261007-names1';
import {EFFECT_ART,troopPose,enemyPose,heroPose} from './animation-state.mjs?v=20261007-names1';
import {drawCombatEffects} from './combat-effects.mjs?v=20261007-names1';
import {installInterface} from './interface-ui.mjs?v=20261007-names1';
import {installExpedition} from './expedition-ui.mjs?v=20261007-names1';
import {MAPS,storyFor,storyMap} from './expedition.mjs?v=20261007-names1';
import {renderHeroGuide} from './hero-guide.mjs?v=20261007-names1';
import {createBattleClock} from './battle-clock.mjs?v=20261007-names1';
import {installTactics} from './tactical-ui.mjs?v=20261007-names1';
import {ROLES,UNITS,UNIT_BRANCHES,PADS,pointAt,createBattle,deploy,upgrade,sell,setPriority,upgradeCost,towerStats,startWave,advance,chooseBlessing,BLESSINGS,kindsFor} from './core.mjs?v=20261007-names1';
import {HERO_SPECIALIZATIONS,HERO_TALENTS,supportFor} from './hero-rules.mjs?v=20261007-names1';
import {masteryLevel} from './mastery.mjs?v=20261007-names1';
import {newArmySave,decodeArmySave,prepareArmyExpedition,settleArmySave} from './army-save.mjs?v=20261007-names1';
import {restoreCheckpoint} from './checkpoint.mjs?v=20261007-names1';
import {CAMPAIGN} from './encounters.mjs?v=20261007-names1';
import {SPELL_ART,projectilePose} from './motion.mjs?v=20261007-names1';
import {unitArt,branchGuide} from './unit-presentation.mjs?v=20261007-names1';
import {routePads,regionFor,alignCommander} from './routes.mjs?v=20261007-names1';
import {createAudio} from './audio.mjs?v=20261007-names1';
import {installJourney} from './journey-ui.mjs?v=20261007-names1';
installTouchGuard();
const audio=createAudio(),systemMotion=matchMedia('(prefers-reduced-motion: reduce)'),reducedMotion={get matches(){return systemMotion.matches||audio.preferences.reducedMotion;}};
audio.hold(true);
let interfaceUI=null;
let dungeon=null,dungeonUI=null;
let backgroundAt=0,backgroundDebt=0,backgroundWait=0,backgroundWorking=false,backgroundTerminal=false,backgroundAllowed=false;
let lastSettlement={coins:0,xp:0};let practice=false,autoNextAt=0;let expedition=null,mode='campaign',map=null,chosenUnit=null;let journey=null,tactics=null,storedRaw=null;const battleClock=createBattleClock();
function motionPreference(){document.body.dataset.motion=reducedMotion.matches?'reduced':'full';}
systemMotion.addEventListener('change',motionPreference);motionPreference();
const $=id=>document.getElementById(id),ctx=$('canvas').getContext('2d'),images={},key='cxq.defense.army.v3';
let profile=newArmySave(),battle=createBattle({hero:'growth'}),hero='growth',specialization=null,talents={},last=0,ready=false,failed=false,selectedPad=null,stage=1,unitPreview=null;
let transitioning=false;const loadingStatus=document.createElement('dialog');loadingStatus.id='loading-status';loadingStatus.setAttribute('aria-label','準備冒險');loadingStatus.addEventListener('cancel',e=>e.preventDefault());document.body.append(loadingStatus);
async function loadArt(id){const im=await sharedAssets.get(id);images[id]=im;}
const heroArt=heroAssets;
function prepared(ids){return sharedAssets.hasAll(ids);}
async function ensureBattleArt(s){const ids=sessionAssets(s);if(transitioning&&!prepared(ids)&&!loadingStatus.open){loadingStatus.textContent='準備新動作…';loadingStatus.showModal();}await sharedAssets.prepare(ids,{onProgress:({completed,total})=>{if(transitioning)globalThis.CxQLoading?.render(loadingStatus,{completed,total,failed:0,percent:total?Math.floor(completed/total*100):100,ready:completed===total},s.dungeon?'準備副本':s.mode==='endless'?'準備99層守城':'準備本關戰場');}});for(const id of ids)images[id]=sharedAssets.peek(id);}
function preloadFollowing(s){const ids=upcomingUnitAssets(s);const run=()=>sharedAssets.prepare(ids,{background:true}).catch(()=>{});if('requestIdleCallback' in window)requestIdleCallback(run,{timeout:3000});else setTimeout(run,1500);}
async function transition(fn,{silent=false}={}){if(transitioning||failed)return;transitioning=true;if(!silent){loadingStatus.replaceChildren();loadingStatus.textContent='準備冒險…';loadingStatus.showModal();}syncPause();try{await fn();}catch(e){if(!loadingStatus.open)loadingStatus.showModal();loadingStatus.replaceChildren();const message=document.createElement('p');message.textContent='準備暫時未完成。已載入的內容與進度保留，請重試。';const retry=document.createElement('button');retry.textContent='重試';retry.onclick=()=>{loadingStatus.close();transition(fn);};const cancel=document.createElement('button');cancel.textContent='返回';cancel.onclick=()=>loadingStatus.close();loadingStatus.append(message,retry,cancel);return;}finally{transitioning=false;if(!loadingStatus.querySelector('button')&&loadingStatus.open)loadingStatus.close();syncPause();}}
function error(e){failed=true;$('error').hidden=false;$('error').textContent=`已暫停：${e.message}。未覆蓋原始存檔。請先保留備份再重新載入。`;syncPause();}
try{const raw=localStorage.getItem(key);storedRaw=raw;if(raw)profile=decodeArmySave(raw);const savedHero=localStorage.getItem('cxq.defense.camp-hero')||profile.checkpoint?.hero.role;if(savedHero&&Object.hasOwn(ROLES,savedHero))hero=savedHero;}catch(e){error(e);}
function persist(next){if(localStorage.getItem(key)!==storedRaw)throw Error('另一個分頁更新了進度，請重新載入後再操作');const canonical=decodeArmySave(next),raw=JSON.stringify(canonical);if(storedRaw&&JSON.parse(storedRaw).collection?.version===1&&!localStorage.getItem(key+'.before-collection2'))localStorage.setItem(key+'.before-collection2',storedRaw);localStorage.setItem(key,raw);storedRaw=raw;profile=canonical;journey?.updateWallet();interfaceUI?.refresh();}
function restoreCommander(){const config=profile.commanders?.[hero];specialization=config?.specialization??null;talents={...(config?.talents??{})};}
restoreCommander();
function saveBoundary(){if(practice)return;const coins=profile.collection.coins,xp=profile.mastery.xp[battle.hero.role];persist(settleArmySave(profile,battle,profile.mastery.activeRun.id));lastSettlement={coins:profile.collection.coins-coins,xp:profile.mastery.xp[battle.hero.role]-xp};}
function syncPause(){const rotate=$('rotate'),landscape=innerWidth>innerHeight;rotate.hidden=!landscape;if(landscape){if(rotate.open&&document.activeElement.closest('dialog')!==rotate)rotate.close();if(!rotate.open)rotate.showModal();}else if(rotate.open)rotate.close();battle.paused=failed||((document.hidden||backgroundWorking)&&!backgroundAllowed)||(!document.hidden&&landscape)||transitioning||!!document.querySelector('dialog[open]:not(#troops)');}
function show(id){if(id==='options'){$('home').hidden=$('cover').open||$('camp').open;$('options').querySelector('[data-close]').textContent=$('home').hidden?'返回':'繼續戰鬥';}if(id==='troops'){if(!$(id).open)$(id).show();}else $(id).showModal();if(id==='cover'){$(id).tabIndex=-1;$(id).focus({preventScroll:true});}syncPause();}
function closeAll(){document.querySelectorAll('dialog[open]:not(#rotate)').forEach(d=>d.close());syncPause();}
function resize(){const app=$('app'),style=getComputedStyle(app),available=app.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom)-document.querySelector('header').getBoundingClientRect().height-document.querySelector('footer').getBoundingClientRect().height;const scale=Math.min(app.clientWidth/390,Math.max(0,available)/585);$('field').style.width=390*scale+'px';$('field').style.height=585*scale+'px';syncPause();}
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden){backgroundAllowed=backgroundEnabled.checked&&autoWaves.checked&&!failed&&!transitioning&&!battle.paused&&!practice&&['battle','intermission'].includes(battle.phase);backgroundAt=Date.now();backgroundDebt=0;backgroundWait=autoNextAt?Math.max(0,4-(autoNextAt-performance.now())/1000):0;autoNextAt=0;}else{void pumpBackground();}syncPause();});
// HUD text and the tactical toolbar can change height after the first layout.
// Refit the board whenever chrome changes, not only when the viewport rotates.
const chromeObserver=new ResizeObserver(resize);for(const el of [document.querySelector('header'),document.querySelector('footer')])chromeObserver.observe(el);
window.visualViewport?.addEventListener('resize',resize);
$('rotate').addEventListener('cancel',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&['rotate','cover','camp','blessing','result','loading-status'].includes(document.activeElement.closest('dialog')?.id)){e.preventDefault();e.stopImmediatePropagation();}},true);
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',syncPause);d.addEventListener('cancel',e=>{if(['cover','camp','blessing','result'].includes(d.id))e.preventDefault();});});
const commanderTabs=installCommanderTabs($('cultivation'),$('build'));
function optionGroup(label,choices,value,locked,onchange){const wrapper=document.createElement('label');wrapper.textContent=label;const select=document.createElement('select');select.disabled=locked;select.add(new Option(locked?'熟練度不足':'不裝備',''));for(const c of choices)select.add(new Option(c.name,c.id));select.value=value||'';const detail=document.createElement('p');const update=()=>{detail.textContent=choices.find(c=>c.id===select.value)?.description||'可在出戰前自由選擇，戰鬥中不能更換。';};select.onchange=()=>{const scroll=$('build').scrollTop;try{onchange(select.value||null);persist(rememberCommander(profile,hero,specialization,talents));renderHero();$('build').scrollTop=scroll;}catch(e){restoreCommander();error(e);}};wrapper.append(select);$('build').append(wrapper,detail);update();}
function renderHero(){for(const b of $('heroes').children)b.setAttribute('aria-pressed',String(b.dataset.hero===hero));const xp=profile.mastery.xp[hero],level=masteryLevel(xp);$('hero-portrait').src=`../../../assets/characters/cxq-role-${hero}.webp`;$('hero-portrait').alt=ROLES[hero].name;$('hero-info').textContent=`${ROLES[hero].name} · 熟練 Lv.${level}`;$('cultivation-info').textContent=`${ROLES[hero].name} · ${xp} XP`;$('hero-summary').textContent=({growth:'培育精銳 · 全場部隊強化',dream:'夢印連動 · 星光清場',luck:'幸運補給 · 次數暴擊',joy:'連擊加速 · 全隊鼓舞',night:'遠距追擊 · 集中重擊',sadness:'細雨緩速 · 防線控場',trust:'職業協同 · 連結支援',memory:'記錄傷害 · 回響爆發',healing:'波次修復 · 生命庇護',hope:'穿甲之光 · 強敵對策'})[hero];$('build').replaceChildren();renderHeroGuide($('build'),hero,xp,level,{specialization,talents});optionGroup('三級英雄專精',HERO_SPECIALIZATIONS[hero],specialization,level<3,v=>specialization=v);for(const [slot,tier] of Object.entries(HERO_TALENTS))optionGroup(`${tier.level} 級戰術`,tier.choices,talents[slot],level<tier.level,v=>talents[slot]=v);const w=profile.weapons?.[hero];if(w){const summary=weaponSummary(hero,w),card=document.createElement('section');card.className='ability-card';card.dataset.commanderTab='weapon';const im=document.createElement('img');im.src='art/weapon-'+hero+'.webp';im.alt=WEAPONS[hero].name;im.width=112;im.height=112;im.loading='lazy';const heading=document.createElement('h3');heading.textContent=WEAPONS[hero].name+' · '+(w.unlocked?'專武 Lv.'+summary.level:'尚未開啟');const text=document.createElement('p');text.textContent='僅英雄熟練副本困難模式通關掉落，機率 '+(WEAPON_DROP_CHANCE*100)+'%。首次開啟，重複掉落 +100 專武經驗。'+(w.unlocked?summary.effect+'；熟練 '+w.xp+'，'+(summary.level===10?'已滿等。':'下一級：'+summary.nextEffect+'，尚需 '+summary.remaining+' 經驗。'):'開啟效果：'+summary.nextEffect+'；滿等效果：'+weaponSummary(hero,{unlocked:true,xp:4500}).effect+'。待轉入經驗 '+w.pending+'，首次掉落才轉入。')+'只有此困難副本的英雄滿等溢出經驗可轉入，其他玩法、訓練書與金幣均不能提升。';const effect=document.createElement('p');effect.textContent=w.unlocked?'目前效果：'+summary.effect+'；'+(summary.level===10?'已滿等。':'下一級：'+summary.nextEffect+'，還需 '+summary.remaining+' 經驗。'):'開啟效果：'+summary.nextEffect+'。滿等效果：'+weaponSummary(hero,{unlocked:true,xp:4500}).effect+'。';const progress=document.createElement('p');progress.textContent='專武熟練 '+w.xp+' / 4500 · '+(w.unlocked?'已取得':'待轉入 '+w.pending+' XP，首次取得才轉入');text.textContent='取得：英雄熟練副本「困難」通關，當前英雄專武掉落率 10%。首次取得開啟；重複掉落 +100 XP。只有此困難副本的英雄滿等溢出經驗能轉入；訓練書、金幣與其他玩法不能提升。';card.append(im,heading,effect,progress,text);$('build').append(card);}commanderTabs.refresh();$('resume').hidden=!profile.checkpoint;$('cover-resume').hidden=!profile.checkpoint;}
$('cultivate').onclick=()=>show('cultivation');$('squad-info').onclick=()=>show('squad');
for(const [id,r] of Object.entries(ROLES)){const b=document.createElement('button');b.dataset.hero=id;b.innerHTML=`<img loading="lazy" decoding="async" src="../../../assets/characters/cxq-role-${id}.webp" alt=""><span>${r.name}</span>`;b.onclick=()=>{hero=id;try{localStorage.setItem('cxq.defense.camp-hero',id);}catch{}restoreCommander();renderHero();Promise.all(heroArt(id).map(loadArt)).catch(()=>{});};$('heroes').append(b);}
function perform(fn){return transition(async()=>{const draft=structuredClone(battle);draft.paused=false;if(!fn(draft))return;await ensureBattleArt(draft);if(!practice&&['planning','intermission'].includes(draft.phase))persist(settleArmySave(profile,draft,profile.mastery.activeRun.id));battle=draft;preloadFollowing(battle);closeAll();},{silent:prepared(sessionAssets(battle))});}
function openPad(i){
 if(!ready||failed||['victory','defeat'].includes(battle.phase))return;
 selectedPad=i;unitPreview=null;const t=battle.towers.find(t=>t.pad===i),content=$('troop-content');content.replaceChildren();$('troops').querySelector('.troop-confirm-actions')?.remove();$('troop-title').textContent=t?`${UNITS[t.role].name} · Lv.${t.level}`:`部署位置 ${i+1}`;
 if(!t&&chosenUnit){show('troops');previewDeployment(i,chosenUnit);return;}
 if(!t){const grid=document.createElement('div');grid.className='deploy-grid';for(const id of battle.loadout){const r=UNITS[id],b=document.createElement('button');b.innerHTML=`<img src="art/unit-${id}.webp" alt=""><span>${r.name}</span><small>${r.cost} 金幣</small>`;b.disabled=battle.gold<r.cost;b.onclick=()=>previewDeployment(i,id);grid.append(b);}content.append(grid);}
 else {
 const stats=towerStats(t,battle),head=document.createElement('div');head.className='unit-panel-head';head.innerHTML=`<img src="art/${unitArt(t)}.webp" alt="${UNITS[t.role].name}"><p>${stats.income?'每波補給 '+stats.income+' 金幣（全隊上限 36）':'傷害 '+stats.damage.toFixed(1)+' · 射程 '+stats.range+'<br>每 '+stats.interval.toFixed(2)+' 秒攻擊'}<br>${shapeDescription(stats)}</p>`;content.append(head);
 const grid=document.createElement('div');grid.className='unit-upgrades';content.append(grid);
 const offer=(branch=null)=>{const next={...t,level:t.level+1,branch:branch?.id??t.branch},after=towerStats(next,battle),button=document.createElement('button');button.innerHTML=`<img src="art/${unitArt(next)}.webp" alt=""><span>${branch?.name||'升至 Lv.'+next.level}</span><small>${stats.income?'補給 '+stats.income+'→'+after.income:stats.damage.toFixed(0)+'→'+after.damage.toFixed(0)} · ${upgradeCost(t)} 金幣</small>`;button.dataset.cost=upgradeCost(t);button.disabled=battle.gold<upgradeCost(t);button.onclick=()=>previewUpgrade(i,next);grid.append(button);};
 if(t.level===2)UNIT_BRANCHES[t.role].forEach(offer);else if(t.level<10)offer();else{const p=document.createElement('p');p.textContent='已達最高等級';grid.append(p);}
 const tools=document.createElement('div');tools.className='unit-panel-tools';const priority=document.createElement('select');priority.setAttribute('aria-label','攻擊優先順序');for(const [v,label] of [['first','接近終點'],['strong','最高生命'],['armor','重甲優先']])priority.add(new Option(label,v));priority.value=t.priority||'first';priority.onchange=()=>perform(s=>setPriority(s,i,priority.value));const detail=document.createElement('button');detail.textContent='介紹';detail.onclick=()=>journey.openUnit(t.role);const sellButton=document.createElement('button');sellButton.textContent=`撤回 +${Math.floor(t.spent*.7)}`;sellButton.onclick=()=>{content.replaceChildren();const p=document.createElement('p');p.textContent=`撤回 ${UNITS[t.role].name}？退還 ${Math.floor(t.spent*.7)} 金幣（投入的 70%）。`;content.append(p);const yes=document.createElement('button');yes.id='confirm-sell';yes.textContent='確認撤回';yes.onclick=()=>perform(s=>sell(s,i));const no=document.createElement('button');no.textContent='保留部隊';no.onclick=()=>openPad(i);troopConfirm(yes,no);};tools.append(priority,detail,sellButton);content.append(tools);
 }
 show('troops');content.scrollTop=0;
}
function troopConfirm(yes,back){$('troops').querySelector('.troop-confirm-actions')?.remove();const actions=document.createElement('div');actions.className='troop-confirm-actions';actions.append(yes,back);$('troop-content').after(actions);$('troop-content').scrollTop=0;}
function previewDeployment(pad,role){
 const stats=towerStats({role,level:1,branch:null},battle);unitPreview={pad,stats};const content=$('troop-content');content.innerHTML=`<div class="unit-panel-head"><img src="art/unit-${role}.webp" alt=""><p>${UNITS[role].name}<br>${stats.income?'每波補給 '+stats.income+' 金幣（全隊上限 36）':'傷害 '+stats.damage.toFixed(1)+' · 射程 '+stats.range+'<br>每 '+stats.interval.toFixed(2)+' 秒攻擊'}<br>${shapeDescription(stats)}</p></div>`;
 const yes=document.createElement('button');yes.id='confirm-deploy';yes.textContent=`部署 · ${UNITS[role].cost} 金幣`;yes.dataset.cost=UNITS[role].cost;yes.disabled=battle.gold<UNITS[role].cost;yes.onclick=()=>perform(s=>deploy(s,pad,role));const back=document.createElement('button');back.textContent='更換兵種';back.onclick=()=>{chosenUnit=null;openPad(pad);};troopConfirm(yes,back);
}
function previewUpgrade(pad,next){
 const old=battle.towers.find(t=>t.pad===pad),before=towerStats(old,battle),after=towerStats(next,battle);unitPreview={pad,stats:after,oldStats:before};const content=$('troop-content');content.innerHTML=`<div class="unit-panel-head"><img src="art/${unitArt(next)}.webp" alt="${UNITS[next.role].name} 升級造型"><p>Lv.${old.level} → Lv.${next.level}<br>${before.income?'每波補給 '+before.income+' → '+after.income+' 金幣<br>恢復 '+before.heal+' → '+after.heal+' 點生命':'傷害 '+before.damage.toFixed(1)+' → '+after.damage.toFixed(1)}<br>射程 ${before.range} → ${after.range}<br>攻擊間隔 ${before.interval.toFixed(2)} → ${after.interval.toFixed(2)} 秒<br>${shapeDescription(before)} → ${shapeDescription(after)}${upgradeDetails(before,after).map(line=>'<br>'+line).join('')}</p></div><p class="branch-effect">${branchGuide(next.role,next.branch)}${next.level===3?'分支確定後，此次部署不能更換。':''}</p>`;
 const yes=document.createElement('button');yes.id='confirm-upgrade';yes.textContent=`升級 · ${upgradeCost(old)} 金幣`;yes.dataset.cost=upgradeCost(old);yes.disabled=battle.gold<upgradeCost(old);yes.onclick=()=>perform(s=>upgrade(s,pad,next.branch));const back=document.createElement('button');back.textContent='返回比較';back.onclick=()=>openPad(pad);troopConfirm(yes,back);
}
PADS.forEach((p,i)=>{const b=document.createElement('button');b.className='pad-hit';b.style.left=p.x/390*100+'%';b.style.top=p.y/585*100+'%';b.setAttribute('aria-label',`部署位置 ${i+1}`);b.onclick=()=>openPad(i);$('pads').append(b);});
function start(){practice=false;return transition(async()=>{const next=prepareArmyExpedition(profile,{hero,dungeon,specialization,talents,stage,mode,map:dungeon?DUNGEONS[dungeon.type].map:mode==='campaign'?storyMap(stage):map,loadout:profile.loadout},crypto.randomUUID());await ensureBattleArt(next.battle);persist(next.save);battle=next.battle;chosenUnit=null;renderDock();tactics?.reset();closeAll();preloadFollowing(battle);},{silent:prepared(sessionAssets(createBattle({hero,stage,mode,map:dungeon?DUNGEONS[dungeon.type].map:mode==='campaign'?storyMap(stage):map,dungeon,loadout:profile.loadout})))});}
function briefing(){const c=CAMPAIGN[stage-1];$('briefing-title').textContent=mode==='endless'?`無盡守城 · ${MAPS[map].name}`:`${storyFor(stage).label} · ${c.name}`;$('briefing-tip').textContent=mode==='endless'?MAPS[map].intro+' 無盡模式：每兩波選擇祝福、每五波可撤離。':storyFor(stage).text+' 戰術：'+c.tip;$('briefing-team').textContent=`指揮英雄：${ROLES[hero].name} · ${profile.loadout.map(id=>UNITS[id].name).join('／')}`;$('briefing-enemies').replaceChildren();for(const kind of new Set(dungeon?[1,2,3].flatMap(w=>dungeonWave(dungeon,w)):c.waves.flat())){const f=document.createElement('figure'),im=document.createElement('img'),label=document.createElement('figcaption');im.src=`art/${kind}.webp`;label.textContent=ENEMY_CATALOG[kind].name;f.append(im,label);$('briefing-enemies').append(f);}if(dungeon){const reward=dungeonReward(dungeon);$('briefing-title').textContent=DUNGEONS[dungeon.type].name+' · '+['一般','進階','困難'][dungeon.difficulty-1];$('briefing-tip').textContent=DUNGEONS[dungeon.type].description+' 通關額外 '+reward.coins+' 星露、'+reward.xp+' 熟練度、'+reward.books+' 本訓練書。三波挑戰，不推進主線。';}campaignDialog.close();show('briefing');}
$('briefing-start').onclick=()=>profile.checkpoint?show('replace'):start();
$('briefing').querySelector('[data-close]').onclick=()=>{$('briefing').close();if(dungeon)dungeonUI.open();else if(mode==='endless')$('start-endless').click();else selectStage();};
const battlefieldHero=document.createElement('button');battlefieldHero.id='battle-hero';battlefieldHero.className='battle-hero-hit';battlefieldHero.setAttribute('aria-label','英雄技能與全場支援說明');battlefieldHero.onclick=()=>commandHit.click();$('pads').append(battlefieldHero);
const commandHit=document.createElement('button');commandHit.className='commander-hit';commandHit.setAttribute('aria-label','英雄指揮區');commandHit.innerHTML='<img alt="指揮英雄"><span>指揮官</span>';document.querySelector('header').prepend(commandHit);
const campaignDialog=document.createElement('dialog');campaignDialog.id='campaign';campaignDialog.innerHTML='<h2>選擇守護地點</h2><div class="scroll-body" id="stages"></div><button id="campaign-back">返回營地</button>';document.body.append(campaignDialog);campaignDialog.addEventListener('close',syncPause);$('campaign-back').onclick=()=>campaignDialog.close();
const campaignSelection=installCampaignSelection({dialog:campaignDialog,catalog:CAMPAIGN,getProgress:()=>profile.campaign,onChoose:c=>{stage=c.stage;briefing();}});
function selectStage(){dungeon=null;mode='campaign';map=null;campaignSelection.render();show('campaign');campaignSelection.restoreScroll();}
$('start').setAttribute('aria-label','選擇關卡');$('start').onclick=selectStage;$('confirm-start').onclick=start;
$('squad').querySelector('p').textContent='同種可重複部署，占用空地台並消耗金幣。現有四種出戰部隊；主線關卡依序開放。';
const squadDescriptions=['橡果弩手｜連弩／重弩','蘑菇炮手｜擴散／穿甲','霜露精靈｜長效緩速／定身','螢光射手｜遠射／連射'];
$('squad').querySelectorAll('figcaption').forEach((e,i)=>e.textContent=squadDescriptions[i]);
const resultPortrait=document.createElement('img');resultPortrait.className='result-portrait';resultPortrait.alt='';$('result-title').after(resultPortrait);
for(const id of ['squad','briefing','result']){const d=$(id),body=document.createElement('div');body.className='dialog-content';for(const e of [...d.children])if(e.tagName!=='H2'&&e.tagName!=='BUTTON')body.append(e);d.querySelector('h2').after(body);}
installVictoryGallery($('result'),()=>battle,()=>reducedMotion.matches);
const retry=document.createElement('button');retry.id='retry-expedition';retry.textContent='再挑戰同一關';$('result').insertBefore(retry,$('result-home'));retry.onclick=()=>{if(practice)return startTrial(battle.loadout[0]);mode=battle.mode;stage=battle.stage;map=battle.map;dungeon=battle.dungeon?{...battle.dungeon}:null;hero=battle.hero.role;specialization=battle.hero.specialization;talents={...battle.hero.talents};return start();};
const nextStage=document.createElement('button');nextStage.id='next-stage';nextStage.textContent='前往下一關';$('result').insertBefore(nextStage,$('result-home'));nextStage.onclick=()=>{if(battle.dungeon||battle.mode!=='campaign'||battle.phase!=='victory'||battle.stage>=CAMPAIGN.length)return;mode='campaign';stage=battle.stage+1;hero=battle.hero.role;specialization=battle.hero.specialization;talents={...battle.hero.talents};start();};
$('enter-camp').onclick=()=>{closeAll();renderHero();show('camp');};$('camp-cover').onclick=()=>{closeAll();show('cover');};$('cover-settings').onclick=()=>show('cover-help');
$('cover-resume').onclick=()=> $('resume').click();
$('resume').onclick=()=>transition(async()=>{const restored=restoreCheckpoint(profile.checkpoint);alignCommander(restored);await ensureBattleArt(restored);battle=restored;practice=false;chosenUnit=null;renderDock();tactics?.reset();closeAll();preloadFollowing(battle);});
$('wave').onclick=()=>{try{saveBoundary();startWave(battle);}catch(e){error(e);}};
$('skill').onclick=()=>castHero(battle);$('settings').onclick=()=>show('options');
function home(){practice=false;dungeon=null;restoreCommander();closeAll();battle=createBattle({hero});alignCommander(battle);renderHero();show('camp');}
$('home').onclick=()=>battle.phase==='battle'?show('leave'):home();$('confirm-home').onclick=home;$('result-home').onclick=home;
$('export').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([failed&&storedRaw?storedRaw:JSON.stringify(profile,null,2)],{type:'application/json'}));a.href=url;a.download='cxq-defense-army.json';a.hidden=true;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);};
let pendingImport=null;
const backupInput=document.createElement('input');backupInput.type='file';backupInput.accept='.json,application/json';backupInput.id='backup-file';backupInput.hidden=true;document.body.append(backupInput);
const importButton=document.createElement('button');importButton.id='import';importButton.textContent='匯入備份';$('export').after(importButton);
const importDialog=document.createElement('dialog');importDialog.id='import-confirm';importDialog.innerHTML='<h2>還原遊戲備份</h2><p id="import-summary"></p><button id="apply-import">確認取代本機進度</button><button id="cancel-import">取消</button>';document.body.append(importDialog);importDialog.addEventListener('close',syncPause);
importButton.onclick=()=>backupInput.click();
backupInput.onchange=async()=>{const file=backupInput.files[0];backupInput.value='';if(!file)return;pendingImport=null;try{if(file.size>1024*1024)throw Error('備份檔案過大');pendingImport=decodeArmySave(await file.text());$('import-summary').textContent=`此備份已開放第 ${pendingImport.campaign.unlocked} 關。還原會取代目前進度與戰場；建議先匯出目前備份。`;$('apply-import').hidden=false;}catch(e){$('import-summary').textContent=`無法還原：${e.message}。目前進度沒有變更。`;$('apply-import').hidden=true;}show('import-confirm');};
$('cancel-import').onclick=()=>{pendingImport=null;importDialog.close();};
$('apply-import').onclick=()=>{if(!pendingImport)return;try{persist(pendingImport);failed=false;$('error').hidden=true;$('start').disabled=false;$('enter-camp').disabled=false;pendingImport=null;hero=profile.checkpoint?.hero.role||'growth';restoreCommander();home();}catch(e){$('import-summary').textContent=`無法儲存：${e.message}。請保留備份。`;}};
function image(id,x,y,w,h,alpha=1){if(!images[id])return;ctx.globalAlpha=alpha;ctx.drawImage(images[id],x,y,w,h);ctx.globalAlpha=1;}
function centeredImage(id,size,alpha=1){const im=images[id];if(!im)return;const scale=size/Math.max(im.width,im.height),w=im.width*scale,h=im.height*scale;image(id,-w/2,-h/2,w,h,alpha);}
function sprite(id,x,y,h,alpha=1){if(alpha>0)renderedActors.push(id);const im=images[id];if(im){const p=spritePlacement(id,im,h);image(id,x+p.x,y+p.y,p.width,p.height,alpha);}}
let renderedActors=[];
const facingByActor=new Map();let facingBattle=null;
function actor(id,x,y,h,identity){
 if(facingBattle!==battle){facingByActor.clear();facingBattle=battle;}
 const t=battle.towers.find(t=>t.pad===identity.pad),event=battle.events.findLast(e=>['anticipate','release'].includes(e.type)&&!e.hero&&e.pad===identity.pad),target=battle.enemies.find(e=>e.id===event?.targetId);
 if(target)facingByActor.set(identity.pad,pointAt(target.distance,battle,target.route).x<x?-1:1);
 const direction=facingByActor.get(identity.pad)||1,m=troopPose(battle,t,reducedMotion.matches);if(hasAdvancedMotion(id)){m.x=0;m.y=0;m.angle=0;m.sx=1;m.sy=1;}let art=id;const supply=battle.events.findLast(e=>e.type==='supply');if(t.role==='artisan'&&supply&&battle.time-supply.time<.34)m.phase='release';
 // Never swap a developed branch back to the base character during an attack.
 if(!reducedMotion.matches){const pose=advancedMotionArt(id,m.phase);if(images[pose])art=pose;else if(id==='unit-'+t.role){if(m.phase==='windup'&&images[id+'-ready'])art=id+'-ready';else if(['release','recover'].includes(m.phase)&&images[id+'-release'])art=id+'-release';}}
 const upgradeEvent=battle.events.findLast(e=>e.type==='upgrade'&&e.pad===t.pad&&battle.time-e.time<.28);
 ctx.save();ctx.translate(x+m.x*direction,y+m.y);ctx.scale(direction*m.sx,m.sy);ctx.rotate(m.angle);
 if(upgradeEvent?.before&&!reducedMotion.matches){const k=(battle.time-upgradeEvent.time)/.28;sprite(unitArt(upgradeEvent.before),0,0,h,1-k);sprite(art,0,0,h,k);}else if(m.phase==='recover'&&art!==id&&!reducedMotion.matches){const k=Math.max(0,Math.min(1,(m.progress-.48)/.52));sprite(art,0,0,h,1-k);sprite(id,0,0,h,k);}else if(m.phase==='windup'&&art!==id&&!reducedMotion.matches){const k=Math.min(1,m.progress*3);sprite(id,0,0,h,1-k);sprite(art,0,0,h,k);}else sprite(art,0,0,h);
 ctx.restore();
}
function rangeArt(id,p,r,alpha=.7){const support=id==='aura-range',ratio=support?.4228515625:.423242,size=r/ratio,cx=support?.4990234375:.5,cy=support?.494140625:.5;image(support?'support-range':id,p.x-size*cx,p.y-size*cy,size,size,alpha);}
function health(e,p,height){
 const y=p.y-height-4,track={x:.015625,y:.357143,w:.96875,h:.274725},fill={x:.048828,y:.333333,w:.902344,h:.333333};
 image('health-track',p.x-20-track.x*40/track.w,y-track.y*6/track.h,40/track.w,6/track.h);
 ctx.save();ctx.beginPath();ctx.rect(p.x-18,y+1,36*Math.max(0,e.hp/e.maxHp),4);ctx.clip();image('health-fill',p.x-18-fill.x*36/fill.w,y+1-fill.y*4/fill.h,36/fill.w,4/fill.h);ctx.restore();
}
let lastLayout='';
const heroMotionResources=new Map(),heroMotionPending=new Set();
function draw(){
 if(battle&&globalThis.CxQCharacterMotion&&!heroMotionResources.has(battle.hero.role)&&!heroMotionPending.has(battle.hero.role)){const role=battle.hero.role;heroMotionPending.add(role);CxQCharacterMotion.prepare(role).then(r=>heroMotionResources.set(role,r)).catch(()=>{setTimeout(()=>heroMotionPending.delete(role),30000)});}

 renderedActors=[];
 const region=regionFor(battle),pads=routePads(battle);audio.region(region);const layout=[region,battle.hero.x,battle.hero.y].join(':');if(layout!==lastLayout){lastLayout=layout;for(const [i,b] of [...$('pads').querySelectorAll('.pad-hit')].entries()){b.style.left=pads[i].x/390*100+'%';b.style.top=pads[i].y/585*100+'%';}commandHit.querySelector('img').src=`art/hero-portrait-${battle.hero.role}.webp`;}if(document.body.dataset.region!==region)document.body.dataset.region=region;
 ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,390,585);image(region==='forest'?'road':'road-'+region,0,0,390,585);
 for(const p of pads)image('pad',p.x-40,p.y-24,80,50);
 for(const o of tactics?.overlays()||[]){rangeArt(o.id,o.p,o.r,tactics.coverage?.45:.9);image('button',Math.max(2,Math.min(278,o.p.x-55)),Math.max(2,o.p.y-o.r),110,24);ctx.font='bold 12px system-ui';ctx.fillStyle='#fff8dc';ctx.textAlign='center';ctx.fillText(o.label,Math.max(57,Math.min(333,o.p.x)),Math.max(2,o.p.y-o.r)+17);}
 if($('troops').open&&selectedPad!==null){const t=battle.towers.find(t=>t.pad===selectedPad),r=unitPreview?.stats|| (t?towerStats(t,battle):null);if(r){if(unitPreview?.oldStats&&unitPreview.oldStats.range!==r.range)rangeArt('range',pads[selectedPad],unitPreview.oldStats.range,.8);if(!r.income)rangeArt(unitPreview?.oldStats?'aura-range':'range',pads[selectedPad],r.range,.5);drawAttackFootprint({s:battle,p:pads[selectedPad],r,image,rangeArt,ctx,selectedPad});if(r.minRange)rangeArt('aura-range',pads[selectedPad],r.minRange,.5);}}
 for(const e of battle.enemies){const p=pointAt(e.distance,battle,e.route);if(e.castUntil>battle.time)rangeArt('aura-range',p,100,.5);else if(e.wardUntil>battle.time)rangeArt('aura-range',p,36,.4);}
 if($('troops').open&&selectedPad!==null){const p=pads[selectedPad];image('target',p.x-12,p.y-42,24,24);}
 drawArmyMechanics({s:battle,image,rangeArt,ctx,reduced:reducedMotion.matches,simple:document.body.dataset.effects==='simple'});
 if(battle.hero.weaponLevel)image('weapon-'+battle.hero.role,battle.hero.x+18,battle.hero.y-10,30,30);const hp=heroPose(battle,reducedMotion.matches);image('hero-dais',battle.hero.x-32,battle.hero.y-12,64,30);const heroHot=$('battle-hero');heroHot.style.left=battle.hero.x/390*100+'%';heroHot.style.top=battle.hero.y/585*100+'%';
 const objects=battle.towers.map(t=>({y:pads[t.pad].y,draw:()=>actor(unitArt(t),pads[t.pad].x,pads[t.pad].y,72,{pad:t.pad})}));
 objects.push({y:battle.hero.y,draw:()=>{ctx.save();ctx.translate(battle.hero.x,battle.hero.y);const motion=heroMotionResources.get(battle.hero.role);if(motion&&!reducedMotion.matches&&battle.phase!=='victory'&&hp.phase!=='idle'){const frame=hp.phase==='windup'?Math.floor(hp.progress*2):hp.phase==='release'?2+Math.min(1,Math.floor(hp.progress/.48*2)):4+Math.min(1,Math.floor((hp.progress-.48)/.52*2));CxQCharacterMotion.draw(ctx,motion,'finisher',(frame+.01)/10,-35,-78,70,78);}else{ctx.scale(hp.scale,hp.scale);sprite(hp.art,0,0,78);}ctx.restore();}});

 const coreHit=battle.events.findLast(e=>e.type==='leak'),coreAge=coreHit?battle.time-coreHit.time:99;
 const coreShake=!reducedMotion.matches&&coreAge<.4?Math.sin(coreAge*45)*3:0;
 const corePoint=pointAt(1e9,battle);image('dream-core',corePoint.x-39+coreShake,503,78,78,battle.hp>0?1:.4);
 if(coreAge<.5)image('impact',corePoint.x-25,521,50,50,1-coreAge/.5);
 ctx.font='bold 15px system-ui';ctx.textAlign='center';ctx.fillStyle='#fff8dc';ctx.strokeStyle='#153d32';ctx.lineWidth=3;
 const coreLabel=`核心 ${battle.hp}/${battle.maxHp}${battle.shield?' · 護盾 '+battle.shield:''}`;ctx.strokeText(coreLabel,corePoint.x,580);ctx.fillText(coreLabel,corePoint.x,580);


 for(const e of battle.enemies){const p=pointAt(e.distance,battle,e.route),height=isBoss(e.kind)?80:52;objects.push({y:p.y,draw:()=>{ctx.save();ctx.translate(p.x,p.y);if(pointAt(Math.max(0,e.distance-2),battle,e.route).x>p.x)ctx.scale(-1,1);const motion=enemyPose(battle,e,reducedMotion.matches);ctx.translate(motion.x,motion.y);ctx.rotate(motion.angle);const stepping=motion.step,art=isBoss(e.kind)&&e.castUntil>battle.time?e.kind+'-ready':isBoss(e.kind)&&battle.events.some(v=>v.type==='boss-ward'&&v.enemyId===e.id&&battle.time-v.time<.5)?e.kind+'-cast':stepping&&images[e.kind+'-step']?e.kind+'-step':e.kind;sprite(art,0,0,height);if(e.slowUntil>battle.time)image('projectile-frost',-16,-12,32,32,.5);ctx.restore();health(e,p,height);const status=[];if(e.blockedUntil>battle.time)status.push('anim-shatter');if(e.air)status.push('moth');for(const kind of new Set((e.damageStacks||[]).filter(v=>v.until>battle.time).map(v=>v.kind)))status.push(kind==='spark'||kind==='flame'?'fx-spark':'projectile-spore');if(e.shredUntil>battle.time)status.push('target');if(e.markUntil>battle.time)status.push('fx-light');for(const [i,icon] of status.slice(0,3).entries())image(icon,p.x+18+i*18,p.y-height,20,20);const stacks=(e.damageStacks||[]).filter(v=>v.until>battle.time).length;if(stacks){ctx.font='bold 14px system-ui';ctx.textAlign='center';ctx.fillStyle='#fff8dc';ctx.strokeStyle='#153d32';ctx.lineWidth=3;ctx.strokeText('持續 ×'+stacks,p.x,p.y-height-12);ctx.fillText('持續 ×'+stacks,p.x,p.y-height-12);}}});}
 objects.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());for(const t of battle.towers){const p=pads[t.pad],remaining=Math.ceil(Math.max(t.heroPowerUntil||0,t.trustUntil||0,battle.hero.hasteUntil||0)-battle.time),charges=t.luckyCharges||0;if(remaining>0||charges>0){image('button',p.x-30,p.y-76,60,22);ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#fff8dc';ctx.fillText(remaining>0?`增益 ${remaining}秒`:`暴擊 ${charges}次`,p.x,p.y-60);}}
 for(const t of battle.towers){const p=pads[t.pad];image('button',p.x-24,p.y+3,48,22);ctx.font='bold 14px system-ui';ctx.fillStyle='#fff8dc';ctx.textAlign='center';ctx.fillText(`Lv.${t.level}`,p.x,p.y+19);}
 for(const shot of battle.shots){
  const e=battle.enemies.find(e=>e.id===shot.targetId);if(!e)continue;
  const visual=shot,p=projectilePose(visual,pointAt(e.distance,battle,e.route),battle.time,reducedMotion.matches),size=shot.hero?34:shot.kind==='spore'?26:32,id=images[`projectile-${shot.kind}`]?`projectile-${shot.kind}`:({crystal:'fx-light',wind:'fx-rune',bloom:'fx-petal',gear:'projectile-spore'})[shot.kind]||SPELL_ART[shot.kind]||'seed';
  if(!reducedMotion.matches&&document.body.dataset.effects!=='simple'){const tail=projectilePose(visual,pointAt(e.distance,battle,e.route),battle.time-.035,false);ctx.save();ctx.translate(tail.x,tail.y);ctx.rotate(tail.angle);centeredImage(id,size*.8,.25);ctx.restore();}
  ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);centeredImage(id,size);ctx.restore();
 }
 drawCombatEffects({s:battle,pads,corePoint:{x:corePoint.x,y:550},image,sprite,ctx,roles:ROLES,reduced:reducedMotion.matches,simple:document.body.dataset.effects==='simple'});
}
function frame(now){const dt=last?(now-last)/1000:0;last=now;syncPause();if(backgroundWorking||backgroundAllowed){requestAnimationFrame(frame);return;}const before=backgroundTerminal?'battle':battle.phase,settledInBackground=backgroundTerminal;backgroundTerminal=false;battleClock.tick(dt,battle.paused||backgroundWorking||backgroundAllowed,step=>{advance(battle,step);return battle.phase===before;});if(!settledInBackground&&before!==battle.phase&&['intermission','victory','defeat'].includes(battle.phase)){try{saveBoundary();}catch(e){error(e);}}
 audio.consume(battle);const portrait=commandHit.querySelector('img'),src='art/hero-portrait-'+battle.hero.role+'.webp';if(portrait.getAttribute('src')!==src)portrait.src=src;portrait.style.transform='none';commandHit.dataset.phase='portrait';draw();const status=`<span class="hud-name">${practice?'試用 · ':''}${ROLES[battle.hero.role].name} · ${battle.dungeon?DUNGEONS[battle.dungeon.type].name:battle.mode==='endless'?'無盡':`第 ${battle.stage} 關`} · ${battle.wave} 波</span><span>生命 ${battle.hp}</span><span>金幣 ${battle.gold}</span>`;if($('status').innerHTML!==status)$('status').innerHTML=status;
 $('wave').disabled=!ready||battle.paused||!['planning','intermission'].includes(battle.phase)||!battle.towers.some(t=>towerStats(t,battle).damage>0)||!!battle.blessingChoices.length;setText('wave',battle.phase==='battle'?'守護中':'開始下一波');const remaining=Math.max(0,Math.ceil(battle.hero.skillReady-battle.time));$('skill').disabled=!ready||battle.paused||battle.phase!=='battle'||remaining>0;setText('hint',battle.phase!=='battle'&&battle.towers.length&&!battle.towers.some(t=>towerStats(t,battle).damage>0)?'補給兵不攻擊，請再部署一名輸出部隊':chosenUnit&&battle.phase!=='battle'?`已選 ${UNITS[chosenUnit].name}，點空地台部署`:battle.phase==='battle'?'守住道路，把握英雄技能時機':battle.towers.length?(battle.towers.some(t=>towerStats(t,battle).damage>0)?'準備完成後，開始下一波':'補給兵不攻擊，請再部署一名輸出部隊'):'點選石台，部署你的部隊');
 const autoBlessing=selectAutoBlessing(battle,profile.assists);if(autoBlessing&&!document.querySelector('dialog[open]')){if(chooseBlessing(battle,autoBlessing)){try{saveBoundary();setText('hint','自動選擇：'+BLESSINGS[autoBlessing].name);}catch(e){error(e);}}}
 if(battle.blessingChoices.length&&!document.querySelector('dialog[open]')){$('blessings').replaceChildren();for(const id of battle.blessingChoices){const b=document.createElement('button');b.className='blessing-card';b.innerHTML='<strong>'+BLESSINGS[id].name+'</strong><small>'+BLESSINGS[id].description+'</small><small>'+blessingFit(battle,id)+'</small>';b.onclick=()=>perform(s=>chooseBlessing(s,id));$('blessings').append(b);}show('blessing');}
 if(!failed&&before!==battle.phase&&['victory','defeat'].includes(battle.phase)){
  const won=battle.phase==='victory',c=CAMPAIGN[battle.stage-1];resultPortrait.src=won?`art/${battle.hero.role}-victory.webp`:`../../../assets/characters/cxq-role-${battle.hero.role}.webp`;
  $('result-title').textContent=won?(battle.stage===CAMPAIGN.length?'主線守護完成':'守護成功'):'整隊，再出發';
  $('next-stage').hidden=!!battle.dungeon||!won||battle.stage>=CAMPAIGN.length||battle.mode==='endless';
  $('result-text').textContent=`第 ${battle.stage} 關 · ${c.name}｜擊退 ${battle.kills} 名敵人｜核心 ${battle.hp}/${battle.maxHp}。${ROLES[battle.hero.role].name} 累積熟練度 ${profile.mastery.xp[battle.hero.role]} XP。${won?'前往下一關，迎接新的敵群。':`戰術提醒：${c.tip} 可調整編隊，或在後段補上緩速與火力。未完成的波次不發獎。`}`;
  if(battle.mode==='endless')$('result-text').textContent=`${MAPS[battle.map||'forest'].name} · 完成 ${battle.phase==='victory'?battle.wave:Math.max(0,battle.wave-1)} / 99 層 · 擊退 ${battle.kills} 名敵人。已取得獎勵保留；本地紀錄 ${profile.endless[battle.map||'forest']} 波。`;
  else if(won&&!battle.dungeon)$('result-text').textContent+=' '+(battle.stage===CAMPAIGN.length||storyFor(battle.stage+1).id!==storyFor(battle.stage).id?storyFor(battle.stage).end:'伙伴們整理防線，帶著新的線索繼續前進。');
  if(!won&&battle.leaks){const most=Object.entries(battle.leaks).sort((a,b)=>b[1]-a[1])[0];if(most)$('result-text').textContent+=' 本局漏怪最多：'+(ENEMY_CATALOG[most[0]].name+'，'+ENEMY_CATALOG[most[0]].tip);}
  $('result').querySelector('.reward-receipt')?.remove();if(!practice){const receipt=document.createElement('p');receipt.className='reward-receipt';receipt.textContent=`本波已入帳：星露 +${lastSettlement.coins} · 熟練度 +${lastSettlement.xp} XP`; $('result-text').after(receipt);}
  show('result');
 }if(['victory','defeat'].includes(battle.phase)&&$('result').open){let report=$('result').querySelector('.battle-report');if(!report){report=document.createElement('section');report.className='battle-report ability-card';$('result-text').after(report);}const rows=Object.entries(battle.contributions??{}).sort((a,b)=>b[1]-a[1]).map(([id,n])=>(id==='hero'?ROLES[battle.hero.role].name:id==='retired'?'已撤回部隊':UNITS[id].name)+'：'+Math.round(n));const leaks=Object.entries(battle.leaks??{}).map(([id,n])=>ENEMY_CATALOG[id].name+' ×'+n);report.textContent='有效傷害（含持續與區域傷害）貢獻：'+(rows.join('／')||'無')+'。漏怪：'+(leaks.join('／')||'無')+'。'+(battle.leaks?.moth?'建議帶入對空部隊。':battle.leaks?.runner?'建議將控制與輸出搭配在轉彎處。':battle.leaks?.armored||battle.leaks?.boss?'建議搭配破甲或穿甲輸出。':'可調整升級順序與部隊覆蓋，集中火力處理敵群。');}
 if(battle.dungeon&&['victory','defeat'].includes(battle.phase)){const reward=dungeonReward(battle.dungeon);$('result-title').textContent=battle.phase==='victory'?'副本完成':'副本挑戰結束';$('result-text').textContent=DUNGEONS[battle.dungeon.type].name+' · 完成 '+(battle.phase==='defeat'?Math.max(0,battle.wave-1):battle.wave)+' 波。'+(battle.phase==='victory'?'通關加碼 '+reward.coins+' 星露、'+reward.xp+' 熟練度、'+reward.books+' 張一般訓練書，已自動保存。':'已完成波次收益保留，未取得通關加碼。');$('next-stage').hidden=true;if(battle.dungeon.type==='mastery'&&battle.dungeon.difficulty===3&&battle.phase==='victory'&&profile.weaponReceipt){const r=profile.weaponReceipt;$('result-text').textContent+=' 專武：'+(r.opened?'首次取得，已開啟。':r.drop?'重複掉落。':'本次未掉落。')+'專武熟練 +'+r.xp+'，待轉入 '+r.pending+'。';}}if(practice&&['victory','defeat'].includes(battle.phase)){$('result-title').textContent='試用結束';$('result-text').textContent='本次試用不消耗資源、不取得獎勵；正式戰場存檔保留。';$('next-stage').hidden=true;}
 if(!backgroundWorking&&!backgroundAllowed&&autoWaves.checked&&!practice&&!battle.paused&&battle.phase==='intermission'&&!battle.blessingChoices.length){autoNextAt||=now+4000;setText('hint',`自動接波 · ${Math.max(0,Math.ceil((autoNextAt-now)/1000))} 秒`);if(now>=autoNextAt){try{saveBoundary();startWave(battle);}catch(e){error(e);}autoNextAt=0;}}else autoNextAt=0;
 retreat.hidden=!(!practice&&battle.mode==='endless'&&battle.phase==='intermission'&&battle.wave>0&&battle.wave%5===0);tactics?.update();interfaceUI?.update(battle,selectedPad);requestAnimationFrame(frame);}
function setText(id,value){if($(id).textContent!==value)$(id).textContent=value;}

const autoLabel=document.createElement('label');autoLabel.innerHTML='<input type="checkbox" id="auto-waves"> 波次間自動接波（四秒準備）';$('options').append(autoLabel);const autoWaves=autoLabel.querySelector('input');autoWaves.checked=true;
const backgroundLabel=document.createElement('label');backgroundLabel.innerHTML='<input type="checkbox" id="background-battle" checked> 背景繼續推塔（自動接波與選祝福）';$('options').append(backgroundLabel);const backgroundEnabled=backgroundLabel.querySelector('input');try{const saved=JSON.parse(localStorage.getItem(key+'.background-options')||'{}');if(typeof saved.waves==='boolean')autoWaves.checked=saved.waves;if(typeof saved.background==='boolean')backgroundEnabled.checked=saved.background;}catch{}const backgroundHelp=document.createElement('p');backgroundHelp.className='note';backgroundHelp.textContent='切換分頁或暫時鎖屏後，依經過時間補算實際戰鬥；每波保存。勝敗時停止，不會自動開新局。關閉或重新載入後，仍從已保存的波次準備階段接續。';$('options').append(backgroundHelp);
for(const control of [autoWaves,backgroundEnabled])control.addEventListener('change',()=>{if(control===backgroundEnabled&&backgroundEnabled.checked)autoWaves.checked=true;if(control===autoWaves&&!autoWaves.checked)backgroundEnabled.checked=false;backgroundAllowed=false;backgroundAt=0;backgroundDebt=0;try{localStorage.setItem(key+'.background-options',JSON.stringify({waves:autoWaves.checked,background:backgroundEnabled.checked}))}catch{}syncPause()});
const dock=document.createElement('div');dock.id='troop-dock';$('hint').before(dock);
function renderDock(){dock.replaceChildren();for(const id of battle.loadout){const b=document.createElement('button');b.dataset.troop=id;b.setAttribute('aria-pressed',String(chosenUnit===id));b.innerHTML=`<img src="art/unit-${id}.webp" alt="${UNITS[id].name}"><span>${UNITS[id].cost}</span>`;b.onclick=()=>{chosenUnit=chosenUnit===id?null:id;renderDock();};dock.append(b);}interfaceUI?.dockTools();}
const retreat=document.createElement('button');retreat.id='retreat';retreat.textContent='安全撤離 · 結算';retreat.hidden=true;$('wave').after(retreat);
retreat.onclick=()=>{try{saveBoundary();persist({...profile,checkpoint:null});$('result-title').textContent='無盡守護 · 安全撤離';$('result-text').textContent=`完成 ${battle.wave} 波，已取得的星露與熟練度保留。最高紀錄 ${profile.endless[battle.map||'forest']} 波。`;$('next-stage').hidden=true;show('result');}catch(e){error(e);}};

// Read-only diagnostics for release acceptance; callers receive a detached snapshot.
export function diagnostics(){return {loading:sharedAssets.debug(),battle:structuredClone(battle),art:Object.keys(images),audio:audio.debug(),animation:{actors:[...renderedActors],heroPhase:commandHit.dataset.phase,effects:document.body.dataset.effects},failed,transitioning};}
const practiceRoom=installPractice({getProfile:()=>profile,show,syncPause,audio,reducedMotion});
journey=installJourney({getProfile:()=>profile,commit:persist,show,syncPause,audio,onMotion:motionPreference,onTrial:config=>practiceRoom.open(config)});
expedition=installExpedition({getProfile:()=>profile,commit:persist,show,syncPause,openUnit:id=>journey.openUnit(id),startEndless:id=>{dungeon=null;mode='endless';map=id;stage=1;briefing();}});
tactics=installTactics({getBattle:()=>battle,clock:battleClock,show,syncPause,audio,perform,getProfile:()=>profile,commit:persist});

for(const [i,position] of [[0,[12,58]],[1,[83,39]],[2,[62,70]]]){const w=document.createElement('img');w.src='art/fx-light.webp';w.alt='';w.className='cover-wisp';w.style.left=position[0]+'%';w.style.top=position[1]+'%';w.style.animationDelay=(-i*1.2)+'s';$('cover').append(w);}
dungeonUI=installDungeons({show,syncPause,onChoose:value=>{dungeon=value;mode='campaign';stage=1;map=DUNGEONS[value.type].map;briefing();}});
interfaceUI=installInterface({getProfile:()=>profile,getHero:()=>hero,getBattle:()=>battle,show,syncPause,refreshHero:renderHero,audio,reducedMotion,openUnit:id=>journey.openUnit(id)});
installMenuMotion({reducedMotion});
registerAssetCache();audio.hold(false);alignCommander(battle);renderHero();show('cover');resize();
// The cover and camp do not wait for late-game sprites. Battle transitions decode
// exactly the selected hero, region and saved unit levels before showing the field.
ready=true;$('start').disabled=failed;$('enter-camp').disabled=failed;document.body.dataset.ready='true';requestAnimationFrame(frame);

async function pumpBackground(){if(backgroundWorking||!backgroundAllowed)return;backgroundWorking=true;try{const now=Date.now();backgroundDebt+=Math.max(0,(now-backgroundAt)/1000);backgroundAt=now;let work=true;while(work&&backgroundAllowed&&!failed){const before=battle.phase;const out=runBackgroundBattle(battle,backgroundDebt,{speed:battleClock.speed,assists:profile.assists,wait:backgroundWait,onBoundary:()=>saveBoundary()});backgroundDebt=out.left;backgroundWait=out.wait;if(before!==battle.phase&&['victory','defeat'].includes(battle.phase))backgroundTerminal=true;if(out.done){backgroundAllowed=false;backgroundDebt=0;break;}work=out.steps===6000&&backgroundDebt>=1/(60*battleClock.speed);if(work)await new Promise(r=>setTimeout(r,0));}if(!document.hidden){backgroundAllowed=false;backgroundAt=0;backgroundDebt=0;last=0;await ensureBattleArt(battle);}}catch(e){backgroundAllowed=false;error(e)}finally{backgroundWorking=false;syncPause();}}
setInterval(()=>{if(document.hidden)void pumpBackground()},500);
document.addEventListener('resume',()=>void pumpBackground());
