import {ASSET_REVISIONS} from './asset-revisions.mjs?v=20261007-names1';
const base=new URL('./',import.meta.url);
export function artPath(id){if(ASSET_REVISIONS.files['art/play-'+id+'.webp'])return 'art/play-'+id+'.webp';return id in ASSET_REVISIONS.characters?'../../../assets/characters/cxq-role-'+id+'.webp':'art/'+id+'.webp';}
export function fileUrl(p){return new URL(p+'?r='+(ASSET_REVISIONS.files[p]||'1'),base).href;}
export function assetUrl(id,{thumbnail=false}={}){const p=thumbnail&&ASSET_REVISIONS.files['art/thumb-'+id+'.webp']?'art/thumb-'+id+'.webp':artPath(id);return new URL(p+'?r='+(ASSET_REVISIONS.files[p]||ASSET_REVISIONS.characters[id]||'1'),base).href;}
export function createAssetLoader({imageFactory=()=>new Image(),concurrency=4,timeout=45000}={}){const images=new Map(),pending=new Map(),queue=[];let active=0,started=0,foregroundStarted=0,backgroundStarted=0;function pump(){while(active<concurrency&&queue.length){const job=queue.shift();active++;job().finally(()=>{active--;pump();});}}
 function get(id,{background=false}={}){if(images.has(id))return Promise.resolve(images.get(id));if(pending.has(id))return pending.get(id);const promise=new Promise((resolve,reject)=>{const job=async()=>{started++;background?backgroundStarted++:foregroundStarted++;try{for(let attempt=0;attempt<2;attempt++){const im=imageFactory();im.decoding='async';im.fetchPriority=background?'low':'auto';im.src=assetUrl(id);let timer;try{await Promise.race([im.decode(),new Promise((_,fail)=>timer=setTimeout(()=>fail(Error('圖片載入逾時')),timeout))]);images.set(id,im);resolve(im);return;}catch(e){im.src='';if(attempt===1)throw e;}finally{clearTimeout(timer);}}}catch(e){reject(e);}finally{pending.delete(id);}};background?queue.push(job):queue.unshift(job);pump();});pending.set(id,promise);return promise;}
 async function prepare(ids,{background=false,onProgress=()=>{}}={}){const unique=[...new Map(ids.filter(Boolean).map(id=>[assetUrl(id),id])).values()];let completed=0;onProgress({completed,total:unique.length});await Promise.all(unique.map(async id=>{await get(id,{background});onProgress({completed:++completed,total:unique.length});}));return ids.filter(Boolean).map(id=>{const image=images.get(id)||images.get(unique.find(other=>assetUrl(other)===assetUrl(id)));images.set(id,image);return image;});}
 return {get,prepare,peek:id=>images.get(id),hasAll:ids=>ids.every(id=>images.has(id)),debug:()=>({loaded:images.size,pending:pending.size,active,queued:queue.length,started,foregroundStarted,backgroundStarted})};}
export const sharedAssets=createAssetLoader();
export function registerAssetCache(){if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register(new URL('asset-cache.js',base),{scope:new URL('./',base).pathname}).catch(()=>{});}
