import {fileUrl} from './asset-loader.mjs';
const key='cxq.defense.preferences.v1';
const defaults={music:true,sound:true,volume:.3,track:'auto',reducedMotion:false};
export function readPreferences(){try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(!raw)return {...defaults};return {music:typeof raw.music==='boolean'?raw.music:true,sound:typeof raw.sound==='boolean'?raw.sound:true,volume:Number.isFinite(raw.volume)?Math.max(0,Math.min(1,raw.volume)):.3,track:['auto','forest','moon','dawn'].includes(raw.track)?raw.track:'auto',reducedMotion:raw.reducedMotion===true};}catch{return {...defaults};}}
export function createAudio(){let prefs=readPreferences(),unlocked=false,region='forest',lastId=0,lastTime=0,current='',lastHit=0,held=false;const music=new Audio();music.loop=true;music.preload='none';const pool=new Map(),combatTimes=new Map();
 const store=()=>{try{localStorage.setItem(key,JSON.stringify(prefs));}catch{/* Gameplay persistence is separate; audio preferences are optional. */}};
 function sync(){if(!unlocked||!prefs.music||document.hidden||held){music.pause();return;}const track=prefs.track==='auto'?region:prefs.track;if(track!==current){current=track;music.src=fileUrl(`audio/${track}.mp3`);music.preload='auto';}music.volume=prefs.volume;if(music.paused)music.play().catch(()=>{});}
 function sound(id){if(['shot','block','shield','boss-warning'].includes(id)){const now=performance.now();if(now-(combatTimes.get(id)??-Infinity)<180)return;combatTimes.set(id,now);}if(!unlocked||!prefs.sound||document.hidden)return;if(id==='hit'||id==='frost'){if(performance.now()-lastHit<100)return;lastHit=performance.now();}let list=pool.get(id);if(!list){list=Array.from({length:3},()=>{const a=new Audio(fileUrl(`audio/${id}.ogg`));a.preload='none';return a;});pool.set(id,list);}const a=list.find(a=>a.paused||a.ended);if(!a)return;a.volume=Math.min(.65,prefs.volume+.15);a.currentTime=0;a.play().catch(()=>{});}
 document.addEventListener('pointerdown',()=>{unlocked=true;sync();},{once:true});document.addEventListener('keydown',()=>{unlocked=true;sync();},{once:true});document.addEventListener('visibilitychange',()=>{sync();if(document.hidden)for(const list of pool.values())for(const a of list)a.pause();});document.addEventListener('click',e=>{if(e.target.closest('button:not(:disabled)'))sound('click');});
 return {get preferences(){return {...prefs};},set(next){prefs={...prefs,...next};store();sync();},hold(value){if(held===value)return;held=value;sync();},sound,region(id){if(id==='ruins')id='dawn';if(region!==id){region=id;sync();}},consume(s){if(s.time<lastTime||s.eventId<lastId)lastId=0;lastTime=s.time;for(const e of s.events){if(e.id<=lastId)continue;lastId=e.id;const id=({upgrade:'upgrade',deploy:'click',sell:'sell',release:e.hero?'cast':'shot',wave:'wave',intermission:'coin',block:'block','boss-warning':'boss-warning','boss-ward':'shield','shield-break':'shield','enemy-heal':'cast','enemy-rage':'boss-warning','hero-skill':'cast',hit:e.kind==='frost'?'frost':'hit',leak:'core',victory:'victory',defeat:'defeat'})[e.type];if(id&&!s.paused)sound(id);}},debug(){return {unlocked,current,paused:music.paused,readyState:music.readyState,volume:music.volume};}};
}
