import {DUNGEONS,dungeonReward} from './dungeons.mjs?v=20261007-names1';
export function installDungeons({show,syncPause,onChoose}){
 const dialog=document.createElement('dialog');dialog.id='dungeons';dialog.className='journey-dialog';dialog.innerHTML='<h2>資源副本</h2><div class="journey-body dungeon-body"></div><button class="journey-close">返回營地</button>';dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('close',syncPause);document.body.append(dialog);
 const entry=document.createElement('button');entry.id='start-dungeons';entry.textContent='金錢／熟練度／訓練副本';document.getElementById('start-endless').after(entry);
 const body=dialog.querySelector('.journey-body'),tabs=document.createElement('nav');tabs.className='dungeon-tabs';tabs.setAttribute('aria-label','副本種類');body.before(tabs);const sections=[];
 for(const [type,config] of Object.entries(DUNGEONS)){const tab=document.createElement('button');tab.textContent=config.name;tab.dataset.type=type;tab.setAttribute('aria-pressed',String(type==='training'));tabs.append(tab);
  const section=document.createElement('section');section.className='dungeon-card';section.hidden=type!=='training';sections.push([type,section]);tab.onclick=()=>{for(const [id,card] of sections)card.hidden=id!==type;for(const b of tabs.children)b.setAttribute('aria-pressed',String(b===tab));body.scrollTop=0;};const img=document.createElement('img');img.src=`art/dungeon-${type}.webp`;img.alt=config.name;img.loading='lazy';
  const content=document.createElement('div');content.className='dungeon-card-content';const title=document.createElement('h3'),description=document.createElement('p');title.textContent=config.name;description.textContent=config.description+' 下列為通關加碼，波次收益另計。';content.append(title,description);
  for(let difficulty=1;difficulty<=3;difficulty++){const reward=dungeonReward({type,difficulty}),button=document.createElement('button');button.dataset.dungeon=type;button.dataset.difficulty=difficulty;button.textContent=`${['一般','進階','困難'][difficulty-1]} · ${reward.coins} 星露${reward.xp?'＋'+reward.xp+' 熟練度':''}${reward.books?'＋'+reward.books+' 張一般訓練書':''}`;if(type==='mastery'&&difficulty===3)button.textContent+='＋10% 專武掉落';button.onclick=()=>{dialog.close();onChoose({type,difficulty});};const row=document.createElement('section'),label=document.createElement('p');row.className='dungeon-difficulty';label.textContent=button.textContent;button.textContent=['一般出戰','進階出戰','困難出戰'][difficulty-1];row.append(label,button);content.append(row);}
  section.append(img,content);body.append(section);
 }
 const note=document.createElement('p');note.textContent='沒有體力限制，可重複挑戰。每局通關獎勵只結算一次；失敗保留已完成波次的基本收益。出戰會取代上次戰場，永久進度保留。';body.append(note);entry.onclick=()=>show('dungeons');return {open:()=>show('dungeons')};
}
