import {floorReward,towerDaily,validateRewardLedger} from './endless-rewards.mjs?v=20261007-names1';
import {installFormation} from './formation-ui.mjs?v=20261007-names1';
import {UNITS,UNIT_GUIDES,UNIT_RARITY} from './army.mjs?v=20261007-names1';
import {GRADES,unitLevel} from './recruitment.mjs?v=20261007-names1';
import {MAPS} from './expedition.mjs?v=20261007-names1';
export function installExpedition({getProfile,commit,show,syncPause,openUnit,startEndless}){
 const $=id=>document.getElementById(id),body=$('squad').querySelector('.dialog-content');
 const formation=installFormation({dialog:$('squad'),body,getProfile,commit,openUnit});const render=()=>formation.render();
 $('squad-info').onclick=()=>{render();show('squad');};
 const endless=document.createElement('button');endless.id='start-endless';endless.textContent='99層守塔';$('start').after(endless);
 const mapDialog=document.createElement('dialog');mapDialog.id='endless-maps';mapDialog.className='journey-dialog';mapDialog.innerHTML='<h2>99層守塔 · 選擇守護塔</h2><div class="journey-body"></div><button class="journey-close">返回營地</button>';mapDialog.querySelector('button').onclick=()=>mapDialog.close();mapDialog.addEventListener('close',syncPause);document.body.append(mapDialog);
 const rewards=document.createElement('dialog');rewards.id='endless-rewards';rewards.className='journey-dialog';rewards.innerHTML='<h2>守城獎勵 · 1～99 層</h2><div class="journey-body"></div><button>返回</button>';rewards.querySelector('button').onclick=()=>rewards.close();rewards.addEventListener('close',syncPause);document.body.append(rewards);
 function showRewards(tower='forest'){const body=rewards.querySelector('.journey-body');body.replaceChildren();const maps=document.createElement('select');maps.setAttribute('aria-label','查看塔別獎勵');for(const [id,m] of Object.entries(MAPS)){const o=new Option(m.name,id);maps.append(o);}maps.value=tower;const note=document.createElement('p');note.textContent='每座塔各自一份每日加碼，台灣時間 00:00 更新。不限挑戰次數，重複通過仍有每局收益；失敗保留已完成層數。訓練書皆為一般書。首次通過任一塔 99 層另給 1000 星露＋1000 張書：'+(validateRewardLedger(getProfile().rewardLedger).first99?'已領取':'尚未領取');const selector=document.createElement('select');selector.setAttribute('aria-label','查看獎勵層數區間');for(let start=1;start<=99;start+=10)selector.append(new Option('第 '+start+'～'+Math.min(99,start+9)+' 層',String(start)));const rules=document.createElement('details');rules.className='reward-rules';const summary=document.createElement('summary');summary.textContent='獎勵規則 · 每塔每日獨立';rules.append(summary,note);const rows=document.createElement('div');body.append(maps,rules,selector,rows);const renderRows=()=>{rows.replaceChildren();const daily=towerDaily(getProfile().rewardLedger,maps.value),start=Number(selector.value);rewards.querySelector('h2').textContent=MAPS[maps.value].name+' · 層數獎勵';for(let n=start;n<=Math.min(99,start+9);n++){const r=floorReward(n),p=document.createElement('section');p.className='ability-card';const h=document.createElement('h3'),t=document.createElement('p');h.textContent='第 '+n+' 層 · 今日'+(daily.claimed.includes(n)?'已領':'未領');t.textContent='每局：'+r.coins+' 星露＋'+r.books+' 張書；每日首次額外：'+r.dailyCoins+' 星露＋'+r.dailyBooks+' 張書';p.append(h,t);rows.append(p);}};maps.onchange=selector.onchange=renderRows;renderRows();show('endless-rewards');}
 endless.onclick=()=>{const contents=mapDialog.querySelector('.journey-body');contents.replaceChildren();for(const [id,m] of Object.entries(MAPS)){const card=document.createElement('section');card.className='tower-choice';const b=document.createElement('button'),daily=towerDaily(getProfile().rewardLedger,id);b.dataset.map=id;b.innerHTML='<img loading="lazy" src="art/'+(id==='forest'?'road':'road-'+id)+'.webp" alt=""><strong>'+m.name+'</strong><small>'+m.tag+' · 最高 '+Math.min(99,getProfile().endless[id])+' / 99 層</small><small>今日已領 '+daily.claimed.length+' / 99 層 · '+(daily.next?'下一份：第 '+daily.next+' 層':'今日加碼全數領取')+'</small>';b.onclick=()=>{mapDialog.close();startEndless(id);};const rewardButton=document.createElement('button');rewardButton.className='tower-reward-link';rewardButton.textContent='查看本塔獎勵';rewardButton.onclick=()=>showRewards(id);card.append(b,rewardButton);contents.append(card);}const p=document.createElement('p');p.textContent='最高99層；每兩層選擇強化，每五層可安全撤離並獲得訓練書。每次過層都有基本收益，各塔每層當日首次另給加碼，台灣時間00:00重置。失敗保留已完成層數收益。';contents.append(p);const rewardsButton=document.createElement('button');rewardsButton.textContent='查看全部層數與每日獎勵';rewardsButton.onclick=()=>showRewards('forest');contents.append(rewardsButton);show('endless-maps');};
 return {render};
}
