import {floorReward,taiwanDay,validateRewardLedger} from './endless-rewards.mjs';
import {installFormation} from './formation-ui.mjs?v=20261005-complete1';
import {UNITS,UNIT_GUIDES,UNIT_RARITY} from './army.mjs?v=20261005-complete1';
import {GRADES,unitLevel} from './recruitment.mjs?v=20261005-complete1';
import {MAPS} from './expedition.mjs?v=20261005-complete1';
export function installExpedition({getProfile,commit,show,syncPause,openUnit,startEndless}){
 const $=id=>document.getElementById(id),body=$('squad').querySelector('.dialog-content');
 const formation=installFormation({dialog:$('squad'),body,getProfile,commit,openUnit});const render=()=>formation.render();
 $('squad-info').onclick=()=>{render();show('squad');};
 const endless=document.createElement('button');endless.id='start-endless';endless.textContent='無盡守城';$('start').after(endless);
 const mapDialog=document.createElement('dialog');mapDialog.id='endless-maps';mapDialog.className='journey-dialog';mapDialog.innerHTML='<h2>無盡守城 · 選擇戰場</h2><div class="journey-body"></div><button class="journey-close">返回營地</button>';mapDialog.querySelector('button').onclick=()=>mapDialog.close();mapDialog.addEventListener('close',syncPause);document.body.append(mapDialog);
 const rewards=document.createElement('dialog');rewards.id='endless-rewards';rewards.className='journey-dialog';rewards.innerHTML='<h2>守城獎勵 · 1～99 層</h2><div class="journey-body"></div><button>返回</button>';rewards.querySelector('button').onclick=()=>rewards.close();rewards.addEventListener('close',syncPause);document.body.append(rewards);
 function showRewards(){const ledger=validateRewardLedger(getProfile().rewardLedger),today=taiwanDay(),body=rewards.querySelector('.journey-body');body.replaceChildren();const note=document.createElement('p');note.textContent='每日加碼以台灣時間 00:00 更新，跨地圖共用。每次新局通過層數仍有基本收益；失敗保留已完成層數。所有訓練書為一般書。首次 99 層另給 1000 星露＋1000 張書：'+(ledger.first99?'已領取':'尚未領取');body.append(note);const selector=document.createElement('select');selector.setAttribute('aria-label','查看獎勵層數區間');for(let start=1;start<=99;start+=10){const option=document.createElement('option');option.value=String(start);option.textContent=`第 ${start}～${Math.min(99,start+9)} 層`;selector.append(option);}const rows=document.createElement('div');body.append(selector,rows);const renderRows=()=>{rows.replaceChildren();const start=Number(selector.value);for(let n=start;n<=Math.min(99,start+9);n++){const r=floorReward(n),p=document.createElement('section');p.className='ability-card';const h=document.createElement('h3'),t=document.createElement('p');h.textContent='第 '+n+' 層 · 每日'+(ledger.day===today&&ledger.daily.includes(n)?'已領':'未領');t.textContent='每局：'+r.coins+' 星露'+(r.books?'＋'+r.books+' 張書':'')+'；每日首次額外：'+r.dailyCoins+' 星露'+(r.dailyBooks?'＋'+r.dailyBooks+' 張書':'');p.append(h,t);rows.append(p);}};selector.onchange=renderRows;renderRows();show('endless-rewards');}
 endless.onclick=()=>{const contents=mapDialog.querySelector('.journey-body');contents.replaceChildren();for(const [id,m] of Object.entries(MAPS)){const b=document.createElement('button');b.dataset.map=id;b.innerHTML=`<img loading="lazy" src="art/${id==='forest'?'road':'road-'+id}.webp" alt="${m.name}道路預覽"><strong>${m.name}</strong><small>${m.tag} · 最高 ${Math.min(99,getProfile().endless[id])} / 99 層</small>`;b.onclick=()=>{mapDialog.close();startEndless(id);};contents.append(b);}const p=document.createElement('p');p.textContent='最高99層；每兩層選擇強化，每五層可安全撤離並獲得訓練書。每次過層都有基本收益，每層當日首次另給加碼，台灣時間00:00重置。失敗保留已完成層數收益。';contents.append(p);const rewardsButton=document.createElement('button');rewardsButton.textContent='查看全部層數與每日獎勵';rewardsButton.onclick=showRewards;contents.append(rewardsButton);show('endless-maps');};
 return {render};
}
