import {assetUrl} from './asset-loader.mjs?v=20261007-names1';
import {UNITS,UNIT_GUIDES,UNIT_RARITY} from './army.mjs?v=20261007-names1';
import {GRADES,unitLevel} from './recruitment.mjs?v=20261007-names1';
import {attackType,troopGroup} from './attack-shapes.mjs?v=20261007-names1';
export function installFormation({dialog,body,getProfile,commit,openUnit}){
 const dock=document.createElement('section');dock.className='formation-dock';dock.innerHTML='<p id="loadout-summary"></p><div class="formation-slots"></div><div class="formation-filters"><label>定位<select id="squad-role"><option value="all">全部定位</option><option value="damage">輸出</option><option value="control">控制</option><option value="support">支援</option></select></label><label>稀有度<select id="squad-rarity"><option value="all">全部階級</option>'+GRADES.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')+'</select></label><label><input id="squad-owned" type="checkbox">只看已取得</label></div><p class="formation-message" role="status"></p>';body.before(dock);
 let drag=null,moved=false;body.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};moved=false;},{passive:true});body.addEventListener('pointermove',e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>10)moved=true;},{passive:true});body.addEventListener('click',e=>{if(moved&&e.detail!==0){e.preventDefault();e.stopImmediatePropagation();}},true);body.addEventListener('pointercancel',()=>moved=true);
 function render(reset=false){const p=getProfile(),scroll=reset?0:body.scrollTop;dock.querySelector('#loadout-summary').textContent=`出戰 ${p.loadout.length} / 5 · 英雄另有固定指揮席`;const slots=dock.querySelector('.formation-slots');slots.replaceChildren();for(let i=0;i<5;i++){const id=p.loadout[i],b=document.createElement('button');b.className='formation-slot';b.disabled=!id;b.setAttribute('aria-label',id?'查看 '+UNITS[id].name:'空出戰欄位');b.innerHTML=id?`<img src="${assetUrl('unit-'+id,{thumbnail:true})}" alt=""><span>${UNITS[id].name}</span>`:'<span>空位</span>';if(id)b.onclick=()=>openUnit(id);slots.append(b);}body.replaceChildren();const group=dock.querySelector('#squad-role').value,rarity=dock.querySelector('#squad-rarity').value,ownedOnly=dock.querySelector('#squad-owned').checked;
 const grid=document.createElement('div');grid.className='loadout-grid';const entries=Object.entries(UNITS).filter(([id])=>(group==='all'||troopGroup(id)===group)&&(rarity==='all'||UNIT_RARITY[id]===rarity)&&(!ownedOnly||p.collection.owned.includes(id)));for(const [id,r] of entries){const owned=p.collection.owned.includes(id),active=p.loadout.includes(id),card=document.createElement('section');card.dataset.troop=id;card.innerHTML=`<img loading="lazy" src="${assetUrl('unit-'+id,{thumbnail:true})}" alt="${r.name}"><h3>${r.name}</h3><p>${GRADES.find(g=>g.id===UNIT_RARITY[id]).name} · ${attackType(r)}</p><p>${owned?'培養 Lv.'+unitLevel(p.collection.training[id]):'尚未取得 · 可試用'} · 部署 ${r.cost} 金幣</p>`;const detail=document.createElement('button');detail.textContent='介紹與試用';detail.onclick=()=>openUnit(id);const toggle=document.createElement('button');toggle.dataset.unit=id;toggle.setAttribute('aria-pressed',String(active));toggle.textContent=active?'移出隊伍':owned?'加入隊伍':'需先招募';toggle.disabled=!owned||(active&&p.loadout.length===1)||(!active&&p.loadout.length===5);toggle.onclick=()=>{const current=getProfile(),has=current.loadout.includes(id),loadout=has?current.loadout.filter(u=>u!==id):[...current.loadout,id];commit({...current,loadout});dock.querySelector('.formation-message').textContent=r.name+(has?'已移出':'已加入');render();};card.append(detail,toggle);grid.append(card);}if(!entries.length){const p=document.createElement('p');p.textContent='沒有符合篩選條件的兵種。';grid.append(p);}body.append(grid);
 const presets=document.createElement('details');presets.className='formation-presets';presets.innerHTML='<summary>常用隊伍 · 三組</summary>';for(let i=0;i<3;i++){const row=document.createElement('div');for(const action of ['套用','保存']){const b=document.createElement('button');b.textContent=action+'隊伍 '+(i+1);b.disabled=action==='套用'&&!p.formations[i];b.onclick=()=>{const current=getProfile();if(action==='套用')commit({...current,loadout:[...current.formations[i]]});else{const formations=[...current.formations];formations[i]=[...current.loadout];for(let j=0;j<i;j++)formations[j]??=[...current.loadout];commit({...current,formations});}render();};row.append(b);}presets.append(row);}body.append(presets);body.scrollTop=scroll;
 }dock.querySelectorAll('select,input').forEach(el=>el.onchange=()=>render(true));return {render};
}
