import {sharedAssets,assetUrl} from './asset-loader.mjs';
import {ROLES,UNITS} from './core.mjs?v=20261005-complete1';
import {unitArt} from './unit-presentation.mjs?v=20261005-complete1';

// Presentation only. Player saves and combat rules remain owned by army-ui.
export function installInterface({getProfile,getHero,getBattle,show,syncPause,refreshHero,audio,reducedMotion,openUnit}){
 const $=id=>document.getElementById(id),camp=$('camp');let lastEvent=0,lastBattle=null,nextUIUpdate=0;
 const gallery=document.createElement('dialog');gallery.id='hero-gallery';gallery.innerHTML='<h2>英雄指揮所</h2><div class="gallery-body"><div class="gallery-stage"><img id="gallery-portrait" alt=""><p id="gallery-name"></p></div><p id="gallery-description"></p></div><button data-gallery-close>返回營地</button>';document.body.append(gallery);gallery.addEventListener('close',syncPause);gallery.querySelector('[data-gallery-close]').onclick=()=>gallery.close();gallery.querySelector('.gallery-body').append($('heroes'));gallery.querySelector('[data-gallery-close]').before($('cultivate'));$('cultivate').textContent='能力、技能與熟練度';
 const coverHero=document.createElement('img');coverHero.id='cover-selected-hero';coverHero.alt='';$('cover').querySelector('.cover-tagline').after(coverHero);
 const nav=camp.querySelector('.camp-links'),heroButton=document.createElement('button');heroButton.id='hero-gallery-open';heroButton.innerHTML='<img src="art/nav-heroes.webp" alt=""><span>英雄</span>';heroButton.onclick=()=>{refreshHero();refresh();show('hero-gallery');};nav.prepend(heroButton);
 for(const [id,art,label] of [['squad-info','nav-squad','編隊'],['open-collection','nav-recruit','招募']])$(id).innerHTML=`<img src="art/${art}.webp" alt=""><span>${label}</span>`;
 const heading=document.createElement('div');heading.className='camp-heading';heading.append($('camp-cover'),camp.querySelector('h1'),$('camp-settings'));camp.prepend(heading);$('camp-settings').textContent='設定';camp.querySelector('.preview-label').remove();camp.querySelector('.selector-caption').remove();
 const main=camp.querySelector('.fixed-actions'),modes=document.createElement('div');modes.className='entry-modes';for(const [id,art,title,copy] of [['start','entry-story-v2','章節冒險',''],['start-endless','entry-tower-v2','99層守塔',''],['start-dungeons','entry-resources-v2','資源副本','']]){const b=$(id);b.classList.remove('lettered');b.innerHTML=`<img src="${assetUrl(art)}" alt="${title}">`;b.setAttribute('aria-label',title);modes.append(b);}const primary=document.createElement('button');primary.id='camp-primary';primary.textContent='故事冒險';primary.onclick=()=>$('start').click();main.replaceChildren($('resume'),primary,modes);camp.append(main,nav);$('resume').textContent='繼續冒險';
 const patrol=document.createElement('div');patrol.className='camp-patrol';patrol.setAttribute('aria-hidden','true');for(const id of ['archer','frost']){const im=document.createElement('img');im.src=`art/unit-${id}.webp`;im.alt='';patrol.append(im);}camp.querySelector('.hero-showcase').prepend(patrol);
 // Compact tools are opened only when needed instead of occupying a permanent row.
 const toolsDialog=document.createElement('dialog');toolsDialog.id='field-tools';toolsDialog.innerHTML='<h2>戰場情報</h2><p>查看射程、敵人情報與本局已選祝福；關閉後繼續戰鬥。</p><button id="field-tools-close">返回戰場</button>';toolsDialog.querySelector('p').after(document.querySelector('.tactical-toolbar'));document.body.append(toolsDialog);toolsDialog.addEventListener('close',syncPause);$('field-tools-close').onclick=()=>toolsDialog.close();$('coverage-toggle').addEventListener('click',()=>toolsDialog.close());
 function dockTools(){if($('battle-tools'))return;const b=document.createElement('button');b.id='battle-tools';b.textContent='情報';b.onclick=()=>show('field-tools');$('troop-dock').append(b);}
 $('troops').classList.add('inline-troops');document.querySelector('#app footer').append($('troops'));$('troops').querySelector('[data-close]').textContent='收起';$('troops').addEventListener('close',()=>document.body.classList.remove('unit-selected'));
 $('canvas').addEventListener('click',()=>{if($('troops').open)$('troops').close();});
 const typeLabel=document.createElement('label');typeLabel.className='readability-control';typeLabel.innerHTML='<input id="large-text" type="checkbox"> 大字閱讀（說明與選單）';$('options').querySelector('.options-body').prepend(typeLabel);try{$('large-text').checked=localStorage.getItem('cxq.defense.large-text')==='true';}catch{}const applyText=()=>{document.body.dataset.text=$('large-text').checked?'large':'normal';};applyText();$('large-text').onchange=()=>{applyText();try{localStorage.setItem('cxq.defense.large-text',String($('large-text').checked));}catch{}};
 const toast=document.createElement('div');toast.id='battle-notice';toast.setAttribute('role','status');toast.hidden=true;$('app').append(toast);let toastUntil=0;
 function refresh(){const id=getHero();coverHero.src=`../../../assets/characters/cxq-role-${id}.webp`;coverHero.alt=ROLES[id].name;$('gallery-portrait').src=`../../../assets/characters/cxq-role-${id}.webp`;$('gallery-portrait').alt=ROLES[id].name;$('gallery-name').textContent=$('hero-info').textContent;$('gallery-description').textContent=$('hero-summary').textContent;primary.hidden=!!getProfile().checkpoint;$('resume').hidden=!getProfile().checkpoint;}
 new MutationObserver(refresh).observe($('hero-info'),{childList:true,characterData:true,subtree:true});
 let demoToken=0;gallery.addEventListener('close',()=>{demoToken++;refresh();});
 const demo=document.createElement('button');demo.id='hero-demo';demo.textContent='試放技能';demo.onclick=async()=>{const im=$('gallery-portrait'),id=getHero(),token=++demoToken;if(reducedMotion.matches)return;demo.disabled=true;try{await Promise.all(['ready','cast'].map(async pose=>{await sharedAssets.get(id+'-'+pose);}));for(const [pose,duration] of [['ready',250],['cast',500]]){if(token!==demoToken||getHero()!==id||!gallery.open)return;im.src=assetUrl(id+'-'+pose);await im.animate([{opacity:.85},{opacity:1}],{duration}).finished;}audio.sound('upgrade');}catch{}finally{demo.disabled=false;if(token===demoToken)refresh();}};gallery.querySelector('.gallery-stage').append(demo);
 function update(s,pad){const now=performance.now();if(now<nextUIUpdate)return;nextUIUpdate=now+100;document.body.classList.toggle('unit-selected',$('troops').open);if(lastBattle!==s){lastBattle=s;lastEvent=s.events.at(-1)?.id||0;}const ev=s.events.findLast(e=>e.id>lastEvent&&['upgrade','wave','boss-warning','hero-skill'].includes(e.type));if(ev){lastEvent=ev.id;if(['wave','boss-warning'].includes(ev.type)){toast.textContent=ev.type==='wave'?`第 ${s.wave} 波開始`:'頭目蓄力：'+({chill:'冰霜壓制',summon:'援軍召喚',haste:'發條加速',ward:'群體護甲'}[ev.ability]||'特殊技能');toast.hidden=false;toastUntil=performance.now()+1800;if(!reducedMotion.matches)toast.animate([{opacity:0,transform:'translateY(-6px)'},{opacity:1,transform:'translateY(0)'}],{duration:180});}}if(performance.now()>toastUntil)toast.hidden=true;for(const b of $('troops').querySelectorAll('[data-cost]'))b.disabled=s.gold<Number(b.dataset.cost)||['victory','defeat'].includes(s.phase);for(const b of $('troop-dock').querySelectorAll('[data-troop]')){b.disabled=s.gold<UNITS[b.dataset.troop].cost;b.setAttribute('aria-label',`${UNITS[b.dataset.troop].name}，${UNITS[b.dataset.troop].cost} 金幣${b.disabled?'，金幣不足':''}`);}}
 let previousMotion=null;setInterval(()=>{const reduce=reducedMotion.matches;if(previousMotion===reduce)return;previousMotion=reduce;patrol.getAnimations({subtree:true}).forEach(a=>a.cancel());if(!reduce){[...patrol.children].forEach((im,i)=>im.animate([{transform:'translateX(-12px) rotate(-2deg)'},{transform:'translateX(12px) rotate(2deg)'},{transform:'translateX(-12px) rotate(-2deg)'}],{duration:5000+i*1400,iterations:Infinity,easing:'ease-in-out'}));}},600);
 refresh();dockTools();return {refresh,update,dockTools};
}
