import {inventoryItems,bookSource,weaponSource} from './inventory.mjs?v=20261007-names1';
import {BOOK_GRADES,BOOK_NAMES,bookInventory,synthesizeBooks} from './training-books.mjs?v=20261007-names1';
import {UNITS,UNIT_RARITY} from './army.mjs?v=20261007-names1';
import {assetUrl} from './asset-loader.mjs?v=20261007-names1';
export function installInventory({getProfile,commit,show,syncPause,audio,openUnit,updateWallet}){
 const $=id=>document.getElementById(id),seenKey='cxq.defense.bag-seen.v1';let filter='all',selected=null,seen={};
 try{const v=JSON.parse(localStorage.getItem(seenKey)||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))seen=v;}catch{}
 function dialog(id,title){const d=document.createElement('dialog');d.id=id;d.className='journey-dialog inventory-dialog';d.innerHTML='<header class="bag-header"><h2>'+title+'</h2></header><div class="journey-body"></div><footer class="bag-footer"><button class="journey-close">收起背包</button></footer>';d.querySelector('.journey-close').onclick=()=>d.close();d.addEventListener('close',syncPause);document.body.append(d);return d;}
 const bag=dialog('training-bag','冒險背包'),detail=dialog('bag-item','物品詳情'),craft=dialog('bag-craft','訓練書合成');detail.querySelector('.journey-close').textContent=craft.querySelector('.journey-close').textContent='返回背包';
 const currency=document.createElement('p');currency.className='bag-currency';bag.querySelector('header').append(currency);
 const tabs=document.createElement('nav');tabs.className='bag-tabs';tabs.setAttribute('aria-label','背包分類');for(const [id,name] of [['all','全部'],['books','訓練書'],['weapons','英雄專武']]){const b=document.createElement('button');b.textContent=name;b.dataset.bagTab=id;b.onclick=()=>{filter=id;render();bag.querySelector('.journey-body').scrollTop=0;};tabs.append(b);}bag.querySelector('.journey-body').before(tabs);
 const opener=document.createElement('button');opener.id='training-bag-open';opener.innerHTML='<img src="'+assetUrl('nav-bag-v2')+'" alt=""><span>背包</span>';$('camp').querySelector('.camp-links').append(opener);opener.onclick=()=>{render();show(bag.id);};
 function action(parent,label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=fn;parent.append(b);return b;}
 function mark(item){seen[item.key]=item.stamp;try{localStorage.setItem(seenKey,JSON.stringify(seen));}catch{}}
 function render(){const body=bag.querySelector('.journey-body'),scroll=body.scrollTop,items=inventoryItems(getProfile());currency.textContent='星露 '+getProfile().collection.coins+' · 訓練書 '+Object.values(bookInventory(getProfile())).reduce((a,b)=>a+b,0)+' 張';tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.bagTab===filter)));body.replaceChildren();const grid=document.createElement('div');grid.className='bag-grid';for(const item of items.filter(i=>filter==='all'||i.kind===filter)){const b=document.createElement('button');b.className='bag-slot';b.dataset.item=item.key;b.setAttribute('aria-label',item.name+'，'+(item.kind==='books'?item.count+' 張':'熟練 Lv.'+item.summary.level));b.setAttribute('aria-pressed',String(selected===item.key));const im=document.createElement('img');im.src=assetUrl(item.art);im.alt='';im.loading='lazy';const title=document.createElement('span'),count=document.createElement('strong');title.className='bag-slot-name';title.textContent=item.shortName;count.className='bag-count';count.textContent=item.kind==='books'?item.count.toLocaleString():'Lv.'+item.summary.level;b.append(im,title,count);if(item.stamp>Number(seen[item.key]||0)){const n=document.createElement('span');n.className='bag-new';n.textContent='新';b.append(n);}b.onclick=()=>{selected=item.key;mark(item);render();showItem(item.key);};grid.append(b);}body.append(grid);if(!grid.children.length){const p=document.createElement('p');p.className='bag-empty';p.textContent='尚未取得英雄專武。挑戰英雄熟練副本・困難，有機會獲得當前英雄的專武。';body.append(p);}body.scrollTop=scroll;}
 function showItem(key){const item=inventoryItems(getProfile()).find(i=>i.key===key);if(!item)return;selected=key;mark(item);render();detail.querySelector('h2').textContent=item.name;const body=detail.querySelector('.journey-body'),footer=detail.querySelector('footer');body.replaceChildren();footer.querySelectorAll('button:not(.journey-close)').forEach(b=>b.remove());const im=document.createElement('img');im.className='bag-item-art';im.src=assetUrl(item.art);im.alt=item.name;body.append(im);const info=document.createElement('section');info.className='bag-description';const add=(h,t)=>{const title=document.createElement('h3'),p=document.createElement('p');title.textContent=h;p.textContent=t;info.append(title,p);};
 if(item.kind==='books'){add('持有數量',item.count+' 張');add('用途','只能培養'+BOOK_NAMES[item.grade]+'兵種。永久提升培養等級，不會消耗其他稀有度的訓練書。');add('取得方式',bookSource);const ids=getProfile().collection.owned.filter(id=>UNIT_RARITY[id]===item.grade);if(ids.length){const select=document.createElement('select');select.setAttribute('aria-label','選擇培養兵種');for(const id of ids)select.append(new Option(UNITS[id].name,id));info.append(select);action(footer,'前往培養',()=>{detail.close();bag.close();openUnit(select.value,'training');});}else add('對應兵種','尚未取得此稀有度兵種，可至星露招募取得。');if(item.grade!=='legendary')action(footer,'合成下一級',()=>{detail.close();showCraft(item.grade);});}
 else{add('專武熟練','Lv.'+item.summary.level+' / 10');add('目前效果',item.summary.effect);add('下一級',item.summary.nextEffect?item.summary.nextEffect+' · 尚需 '+item.summary.remaining+' 熟練':'已達最高專武熟練');add('取得與培養',weaponSource);action(footer,'前往指揮所',()=>{detail.close();bag.close();$('hero-gallery-open')?.click();});}body.append(info);show(detail.id);}
 function showCraft(grade){const next=BOOK_GRADES[BOOK_GRADES.indexOf(grade)+1],body=craft.querySelector('.journey-body'),footer=craft.querySelector('footer');craft.querySelector('h2').textContent=BOOK_NAMES[grade]+' → '+BOOK_NAMES[next];body.replaceChildren();footer.querySelectorAll('button:not(.journey-close)').forEach(b=>b.remove());const icons=document.createElement('div');icons.className='bag-craft-icons';for(const [g,label] of [[grade,'10 張'],[next,'1 張']]){const f=document.createElement('figure');f.innerHTML='<img src="'+assetUrl('training-book-'+g)+'" alt="'+BOOK_NAMES[g]+'訓練書"><figcaption>'+label+'</figcaption>';icons.append(f);}const held=document.createElement('p'),tools=document.createElement('div'),input=document.createElement('input'),summary=document.createElement('p'),notice=document.createElement('p');tools.className='bag-stepper';input.type='number';input.inputMode='numeric';input.min='1';input.step='1';input.value='1';input.setAttribute('aria-label','合成後獲得的訓練書數量');const minus=action(tools,'−',()=>{input.value=String(Math.max(1,Number(input.value||1)-1));refresh();});tools.append(input);const plus=action(tools,'＋',()=>{input.value=String(Math.min(Math.floor(bookInventory(getProfile())[grade]/10),Number(input.value||0)+1));refresh();});const max=action(body,'最大可合成',()=>{input.value=String(Math.floor(bookInventory(getProfile())[grade]/10));refresh();});const confirm=action(footer,'確認合成',()=>{if(confirm.disabled)return;try{const result=synthesizeBooks(getProfile(),grade,Number(input.value));commit(result);audio.sound('synthesis');updateWallet();render();craft.close();selected='book-'+next;showItem(selected);}catch{notice.textContent='未能合成，請確認數量或重新開啟背包。';refresh();}});function refresh(){const n=Number(input.value),owned=bookInventory(getProfile())[grade],available=Math.floor(owned/10);held.textContent='持有 '+owned+' 張'+BOOK_NAMES[grade]+'訓練書';summary.textContent=Number.isSafeInteger(n)&&n>0?'消耗 '+n*10+' 張 → 獲得 '+n+' 張'+BOOK_NAMES[next]+'訓練書':'請輸入正整數';confirm.disabled=!Number.isSafeInteger(n)||n<1||n>available;minus.disabled=n<=1;plus.disabled=available<1||n>=available;max.disabled=available<1;input.max=String(available);notice.textContent=available<1?'還差 '+(10-owned)+' 張'+BOOK_NAMES[grade]+'訓練書即可合成下一級。':Number.isSafeInteger(n)&&n>available?'數量不足，最多可合成 '+available+' 張。':'';}input.oninput=refresh;body.prepend(icons,held,tools);body.append(summary,notice);refresh();show(craft.id);}
 return {render};
}
