import {RECRUIT_UNITS,unitLevel} from './recruitment.mjs?v=20261003-interface1';
import {UNITS,UNIT_BRANCHES,UNIT_GUIDES} from './army.mjs?v=20261003-interface1';
import {branchGuide,unitArt} from './unit-presentation.mjs?v=20261003-interface1';
import {installRecruitment} from './recruitment-ui.mjs?v=20261003-interface1';
const guides={archer:['穩定單體火力','便宜、出手快，適合補足前中後段火力。連弩處理快腳；重弩提高單次傷害。'],cannon:['群怪與範圍清場','攻速較慢，敵群聚集時最有效；擴散增加覆蓋，穿甲針對重甲。'],frost:['緩速與節奏控制','傷害較低，需與輸出伙伴搭配。長效緩速延長控制，凝霜每第三擊短暫定身。'],firefly:['遠距離持續輸出','適合補防線死角。遠射增加覆蓋範圍，連射提升攻擊頻率。']};
export function installJourney({getProfile,commit,show,syncPause,audio,onMotion,onTrial}){
 const $=id=>document.getElementById(id);
 function dialog(id,title){const d=document.createElement('dialog');d.id=id;d.className='journey-dialog';d.innerHTML=`<h2>${title}</h2><div class="journey-body"></div><button class="journey-close">返回營地</button>`;d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',syncPause);document.body.append(d);return d;}
 const collection=dialog('collection','星露招募'),unitDialog=dialog('unit-guide','部隊介紹');
 const wallet=document.createElement('p');wallet.id='camp-wallet';wallet.className='camp-wallet';$('camp').querySelector('.camp-links').before(wallet);
 const summon=document.createElement('button');summon.id='open-collection';summon.textContent='星露招募';$('camp').querySelector('.camp-links').append(summon);
 const settings=document.createElement('button');settings.id='camp-settings';settings.textContent='設定與備份';$('camp').querySelector('.camp-links').append(settings);settings.onclick=()=>show('options');
 const coverSettings=document.createElement('button');coverSettings.id='cover-options';coverSettings.textContent='設定';$('cover').append(coverSettings);coverSettings.onclick=()=>show('options');
 function updateWallet(){const p=getProfile();wallet.textContent=`星露 ${p.collection.coins} · 主線 ${p.campaign.cleared.length} / 15`;}

 function openUnit(id){
 const d=unitDialog.querySelector('.journey-body'),r=UNITS[id],profile=getProfile(),owned=profile.collection.owned.includes(id);$('unit-guide').querySelector('h2').textContent=r.name;
 d.innerHTML=`<div class="unit-showcase"><img src="art/range.webp" class="guide-range" alt="射程示意"><img src="art/unit-${id}.webp" class="guide-unit" alt="${r.name}"></div><p class="ownership-label">${owned?'已取得 · 養成 Lv.'+unitLevel(profile.collection.training[id]):'尚未取得 · 可免費試用'}</p><h3>${UNIT_GUIDES[id][0]}</h3><p>${UNIT_GUIDES[id][1]}</p><div class="unit-facts"><span>部署<br><strong>${r.cost} 金幣</strong></span><span>傷害<br><strong>${r.damage}</strong></span><span>射程<br><strong>${r.range}</strong></span><span>攻擊間隔<br><strong>${r.interval} 秒</strong></span></div><p class="guide-footnote">以上為 Lv.1 基礎數值，未計入永久養成與戰場增益。</p>`;
 const variants=document.createElement('div');variants.className='unit-variants';for(const [label,art] of [['基礎造型','unit-'+id],...UNIT_BRANCHES[id].map(b=>[b.name,unitArt({role:id,level:5,branch:b.id})])]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-pressed',String(label==='基礎造型'));b.onclick=()=>{d.querySelector('.guide-unit').src='art/'+art+'.webp';variants.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));};variants.append(b);}d.querySelector('.unit-showcase').after(variants);
 const demo=document.createElement('button');demo.id='unit-demo';demo.textContent='播放出手動作（示意）';demo.onclick=()=>{if(document.body.dataset.motion==='reduced')return;d.querySelector('.guide-unit').animate([{transform:'translateX(-50%) rotate(0)'},{transform:'translateX(-54%) rotate(-6deg)',offset:.35},{transform:'translateX(-44%) rotate(5deg)',offset:.55},{transform:'translateX(-50%) rotate(0)'}],{duration:650,easing:'ease-out'});audio.sound('upgrade');};variants.after(demo);
 const match={archer:'搭配晶角破甲，應對重甲；搭配緩速延長輸出。',cannon:'搭配藤蔓或霜露，把敵群留在爆炸範圍。',frost:'搭配炮手或重型狙擊，讓緩速換成更多命中。',firefly:'補足其他部隊的遠端火力空隙。',crystal:'搭配高攻速兵種，放大破甲的整隊效益。',chime:'適合雙路匯合或敵人密集的區域。',blossom:'放在多個輸出兵種附近，支援收益較高。',clockwork:'搭配前方緩速部隊，避免敵人快速進入近距死角。',alchemist:'適合前段掛上持續傷害，再由後方火力收尾。',vine:'搭配範圍炮擊，集中處理被定身的敵群。',oracle:'標記強敵，搭配其他輸出集中攻擊。',dragon:'搭配緩速與聚集路段，發揮範圍吐息。'};
 const pairing=document.createElement('section');pairing.className='ability-card';pairing.innerHTML=`<h3>搭配方向</h3><p>${match[id]}</p>`;d.append(pairing);
 const grid=document.createElement('div');grid.className='branch-guides';for(const b of UNIT_BRANCHES[id]){const f=document.createElement('figure');f.innerHTML=`<img src="art/${unitArt({role:id,level:5,branch:b.id})}.webp" alt="${b.name} 五級造型"><figcaption>${b.name}</figcaption><p>${branchGuide(id,b.id)}</p>`;grid.append(f);}d.append(grid);
 const note=document.createElement('p');note.textContent='三級選定分支後，本次部署不能更換；撤回退還累計投入的 70%。';d.append(note);
 const trial=document.createElement('button');trial.id='unit-trial';trial.textContent='免費試用 · 不影響進度';trial.onclick=()=>onTrial(id);d.append(trial);unitDialog.querySelector('.journey-close').textContent='返回';show('unit-guide');
 }
 const recruitment=installRecruitment({dialog:collection,getProfile,commit,audio,updateWallet,openUnit});summon.onclick=()=>{recruitment.render();show('collection');};$('camp').addEventListener('focusin',updateWallet);
 $('squad').querySelectorAll('figure').forEach((f,i)=>{const b=document.createElement('button');b.className='unit-detail';b.textContent='能力與升級';b.onclick=()=>openUnit(RECRUIT_UNITS[i]);f.append(b);});
 const controls=document.createElement('div');controls.className='audio-controls';controls.innerHTML='<label><input type="checkbox" id="music-enabled"> 背景音樂</label><label><input type="checkbox" id="sound-enabled"> 操作與戰鬥音效</label><label>音樂曲目<select id="music-track"><option value="auto">隨區域切換</option><option value="forest">翠林 · Back to Nature</option><option value="moon">月露 · Fairy Lights</option><option value="dawn">晨曦 · Jaunt</option></select></label><label>音量<input id="audio-volume" type="range" min="0" max="1" step="0.05"></label><label><input type="checkbox" id="motion-reduced"> 減少動態效果</label><details><summary>音樂與音效來源</summary><p>音樂：troubadour；音效：Kenney。皆採 CC0 授權。</p><a href="audio/CREDITS.md" target="_blank" rel="noopener">完整授權紀錄</a></details>';$('options').querySelector('p').after(controls);
 const prefs=audio.preferences;$('music-enabled').checked=prefs.music;$('sound-enabled').checked=prefs.sound;$('music-track').value=prefs.track;$('audio-volume').value=prefs.volume;$('motion-reduced').checked=prefs.reducedMotion;
 controls.onchange=()=>{audio.set({music:$('music-enabled').checked,sound:$('sound-enabled').checked,track:$('music-track').value,volume:Number($('audio-volume').value),reducedMotion:$('motion-reduced').checked});onMotion();};
 const optionsBody=document.createElement('div');optionsBody.className='options-body';const close=$('options').querySelector('[data-close]');for(const child of [...$('options').children])if(child.tagName!=='H2'&&child!==close&&child.id!=='home')optionsBody.append(child);close.before(optionsBody,$('home'));
 updateWallet();return {updateWallet,openUnit};
}
