import {GRADES,DRAW_COST,RECRUIT_UNITS,drawOdds,recruit,trainingRanks} from './recruitment.mjs?v=20261001-complete4';
import {UNITS,UNIT_BRANCHES} from './army.mjs?v=20261001-complete4';
import {branchGuide,unitArt} from './unit-presentation.mjs?v=20261001-complete4';
const guides={archer:['穩定單體火力','便宜、出手快，適合補足前中後段火力。連弩處理快腳；重弩提高單次傷害。'],cannon:['群怪與範圍清場','攻速較慢，敵群聚集時最有效；擴散增加覆蓋，穿甲針對重甲。'],frost:['緩速與節奏控制','傷害較低，需與輸出伙伴搭配。長效緩速延長控制，凝霜每第三擊短暫定身。'],firefly:['遠距離持續輸出','適合補防線死角。遠射增加覆蓋範圍，連射提升攻擊頻率。']};
export function installJourney({getProfile,commit,show,syncPause,audio,onMotion}){
 const $=id=>document.getElementById(id);
 function dialog(id,title){const d=document.createElement('dialog');d.id=id;d.className='journey-dialog';d.innerHTML=`<h2>${title}</h2><div class="journey-body"></div><button class="journey-close">返回營地</button>`;d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',syncPause);document.body.append(d);return d;}
 const collection=dialog('collection','星露招募'),unitDialog=dialog('unit-guide','部隊介紹');
 const wallet=document.createElement('p');wallet.id='camp-wallet';wallet.className='camp-wallet';$('camp').querySelector('.camp-links').before(wallet);
 const summon=document.createElement('button');summon.id='open-collection';summon.textContent='星露招募';$('camp').querySelector('.camp-links').append(summon);
 const settings=document.createElement('button');settings.id='camp-settings';settings.textContent='設定與備份';$('camp').querySelector('.camp-links').append(settings);settings.onclick=()=>show('options');
 const coverSettings=document.createElement('button');coverSettings.id='cover-options';coverSettings.textContent='設定';$('cover').append(coverSettings);coverSettings.onclick=()=>show('options');
 let revealing=false;
 function updateWallet(){const p=getProfile();wallet.textContent=`星露 ${p.collection.coins} · 主線 ${p.campaign.cleared.length} / 15`;}
 function renderCollection(message=null){const c=getProfile().collection,body=collection.querySelector('.journey-body'),odds=drawOdds(c),ranks=trainingRanks(c);body.replaceChildren();
  const intro=document.createElement('p');intro.textContent=`星露 ${c.coins}｜每次 ${DRAW_COST}。四種部隊全開，招募取得部隊收藏與訓練；沒有付費。`;body.append(intro);
  const result=document.createElement('section');result.id='recruit-result';result.setAttribute('aria-live','polite');
  if(message){const grade=GRADES.find(g=>g.id===message.grade);result.innerHTML=`<img class="recruit-portrait" src="art/unit-${message.unit}.webp" alt="${UNITS[message.unit].name}"><h3>${grade.name} · ${UNITS[message.unit].name}</h3><p>訓練 +${message.training}${message.duplicate?` · 重複收藏返還 ${message.refund} 星露`:' · 新收藏'}</p>`;if(!audio.preferences.reducedMotion&&!matchMedia('(prefers-reduced-motion:reduce)').matches)result.animate([{opacity:0,transform:'translateY(12px) scale(.9)'},{opacity:1,transform:'none'}],{duration:550,easing:'ease-out'});}
  body.append(result);const draw=document.createElement('button');draw.id='recruit-once';draw.textContent=c.coins>=100?'招募一次 · 100 星露':`星露不足 · 還差 ${100-c.coins}`;draw.disabled=c.coins<100||revealing;
  draw.onclick=()=>{if(revealing)return;revealing=true;draw.disabled=true;try{const next=recruit(getProfile().collection);commit({...getProfile(),collection:next.collection});audio.sound('upgrade');renderCollection(next.result);updateWallet();setTimeout(()=>{revealing=false;if(collection.open)collection.querySelector('#recruit-once').disabled=getProfile().collection.coins<100;},650);}catch(e){revealing=false;result.textContent=`未完成招募：${e.message}`;draw.disabled=false;}};body.append(draw);
  const details=document.createElement('details');details.innerHTML=`<summary>機率、保底與星露來源</summary><p>一般機率：銀葉 70%、金枝 25%、虹晶 5%。本次實際機率：${odds.map((n,i)=>GRADES[i].name+' '+n+'%').join('、')}。每個品級內四種部隊各 25%。</p><p>連續 9 次沒有金枝以上，第 10 次至少金枝；連續 29 次沒有虹晶，第 30 次必得虹晶。距金枝保底最多 ${10-c.sinceGold} 次，虹晶最多 ${30-c.sincePrism} 次。</p><p>銀葉／金枝／虹晶給予 1／3／8 訓練；同款重複返還 20／35／60 星露。每 10 訓練提升 1 階，傷害 +1%，最多 8%。新戰役才套用訓練加成。</p><p>每完成一波獲得 5 星露；首次通關另得 80＋關卡×10 星露。重玩可取得波次獎勵，但不能重複取得首通獎勵。</p>`;body.append(details);
  const grid=document.createElement('div');grid.className='collection-grid';for(const id of RECRUIT_UNITS){const b=document.createElement('button');b.innerHTML=`<img src="art/unit-${id}.webp" alt=""><span>${UNITS[id].name}</span><small>訓練 ${c.training[id]} · ${ranks[id]} 階</small><small>${GRADES.map(g=>c.owned.includes(id+':'+g.id)?g.name:'—').join(' / ')}</small>`;b.onclick=()=>openUnit(id);grid.append(b);}body.append(grid);
  const history=document.createElement('details');history.innerHTML='<summary>最近招募紀錄</summary>';const list=document.createElement('ol');for(const h of c.history){const li=document.createElement('li');li.textContent=`第 ${h.number} 次：${GRADES.find(g=>g.id===h.grade).name} ${UNITS[h.unit].name}${h.duplicate?'（重複）':''}`;list.append(li);}history.append(list);body.append(history);
 }
 function openUnit(id){const d=unitDialog.querySelector('.journey-body'),r=UNITS[id];$('unit-guide').querySelector('h2').textContent=r.name;d.innerHTML=`<div class="unit-showcase"><img src="art/range.webp" class="guide-range" alt="射程示意"><img src="art/unit-${id}.webp" class="guide-unit" alt="${r.name}"></div><h3>${guides[id][0]}</h3><p>${guides[id][1]}</p><p>部署 ${r.cost} 金幣｜傷害 ${r.damage}｜射程 ${r.range}｜每 ${r.interval} 秒攻擊</p><p>三級選定分支後，本次部署不能更換；撤回退還累計投入的 70%。</p>`;const grid=document.createElement('div');grid.className='branch-guides';for(const b of UNIT_BRANCHES[id]){const f=document.createElement('figure');f.innerHTML=`<img src="art/${unitArt({role:id,level:5,branch:b.id})}.webp" alt="${b.name} 五級造型"><figcaption>${b.name}</figcaption><p>${branchGuide(id,b.id)}</p>`;grid.append(f);}d.append(grid);unitDialog.querySelector('.journey-close').textContent='返回';show('unit-guide');}
 summon.onclick=()=>{renderCollection();show('collection');};$('camp').addEventListener('focusin',updateWallet);
 $('squad').querySelectorAll('figure').forEach((f,i)=>{const b=document.createElement('button');b.className='unit-detail';b.textContent='能力與升級';b.onclick=()=>openUnit(RECRUIT_UNITS[i]);f.append(b);});
 const controls=document.createElement('div');controls.className='audio-controls';controls.innerHTML='<label><input type="checkbox" id="music-enabled"> 背景音樂</label><label><input type="checkbox" id="sound-enabled"> 操作與戰鬥音效</label><label>音樂曲目<select id="music-track"><option value="auto">隨區域切換</option><option value="forest">翠林 · Back to Nature</option><option value="moon">月露 · Fairy Lights</option><option value="dawn">晨曦 · Jaunt</option></select></label><label>音量<input id="audio-volume" type="range" min="0" max="1" step="0.05"></label><label><input type="checkbox" id="motion-reduced"> 減少動態效果</label><details><summary>音樂與音效來源</summary><p>音樂：troubadour；音效：Kenney。皆採 CC0 授權。</p><a href="audio/CREDITS.md" target="_blank" rel="noopener">完整授權紀錄</a></details>';$('options').querySelector('p').after(controls);
 const prefs=audio.preferences;$('music-enabled').checked=prefs.music;$('sound-enabled').checked=prefs.sound;$('music-track').value=prefs.track;$('audio-volume').value=prefs.volume;$('motion-reduced').checked=prefs.reducedMotion;
 controls.onchange=()=>{audio.set({music:$('music-enabled').checked,sound:$('sound-enabled').checked,track:$('music-track').value,volume:Number($('audio-volume').value),reducedMotion:$('motion-reduced').checked});onMotion();};
 const optionsBody=document.createElement('div');optionsBody.className='options-body';const close=$('options').querySelector('[data-close]');for(const child of [...$('options').children])if(child.tagName!=='H2'&&child!==close)optionsBody.append(child);close.before(optionsBody);
 updateWallet();return {updateWallet};
}
