import {createPractice,beginPractice,tickPractice} from './practice-model.mjs';
import {UNITS,UNIT_BRANCHES} from './army.mjs';
import {towerStats,pointAt,ROLES} from './core.mjs';
import {PADS} from './core.mjs';
import {unitArt} from './unit-presentation.mjs';
import {advancedMotionArt,advancedMotionAssets} from './advanced-motion.mjs';
import {spritePlacement} from './sprite-placement.mjs';
import {troopPose,EFFECT_ART} from './animation-state.mjs';
import {drawCombatEffects} from './combat-effects.mjs';
import {drawArmyMechanics,drawAttackFootprint} from './army3-effects.mjs';
import {SPELL_ART,projectilePose} from './motion.mjs';
import {trainingInfo} from './training-books.mjs';
import {shapeDescription} from './attack-shapes.mjs';
export function installPractice({getProfile,show,syncPause,audio,reducedMotion}){
 const d=document.createElement('dialog');d.id='practice-room';d.innerHTML=`<div class="practice-header"><div><small>兵種演練</small><h2></h2></div><button id="practice-exit">離開</button></div><div class="practice-field"><canvas width="390" height="585" aria-label="兵種演練場"></canvas><p class="practice-status" role="status"></p></div><div class="practice-controls"><div class="practice-choices"><label>等級<select id="practice-level">${Array.from({length:10},(_,i)=>'<option value="'+(i+1)+'">Lv.'+(i+1)+'</option>').join('')}</select></label><label>分支<select id="practice-branch"></select></label><label>目標<select id="practice-target"><option value="single">訓練靶</option><option value="group">群體</option><option value="armor">重甲</option><option value="air">飛行</option></select></label></div><div class="practice-tools"><button id="practice-range" aria-pressed="false">顯示射程</button><button id="practice-speed">速度 1×</button><button id="practice-switch">換兵種</button></div><details><summary>能力與演練結果</summary><p id="practice-stats"></p><p id="practice-score"></p></details><div class="practice-actions"><button id="practice-play">開始演練</button><button id="practice-reset">重置</button></div></div>`;document.body.append(d);
 const picker=document.createElement('dialog');picker.id='practice-picker';picker.className='journey-dialog';picker.innerHTML='<h2>選擇演練兵種</h2><div class="journey-body"></div><button>返回演練</button>';document.body.append(picker);picker.querySelector('button').onclick=()=>picker.close();picker.addEventListener('close',syncPause);
 const $=id=>d.querySelector('#'+id),canvas=d.querySelector('canvas'),ctx=canvas.getContext('2d'),cache=new Map();let s=null,id='archer',running=false,range=false,speed=1,token=0,last=0,raf=0,loading=false,soundId=0;
 const image=(name,x,y,w,h,alpha=1)=>{const im=cache.get(name);if(!im)return;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x,y,w,h);ctx.restore();};
 const sprite=(name,x,y,h,alpha=1)=>{const im=cache.get(name);if(!im)return;const p=spritePlacement(name,im,h);image(name,x+p.x,y+p.y,p.width,p.height,alpha);};
 async function load(names){await Promise.all([...new Set(names.filter(Boolean))].map(async name=>{if(cache.has(name))return;const im=new Image();im.src='art/'+name+'.webp?v=20261005-studio1';await im.decode();cache.set(name,im);}));}
 async function reset(){const epoch=++token;running=false;s=null;loading=true;$('practice-play').disabled=true;$('practice-reset').disabled=true;d.querySelector('h2').textContent=UNITS[id].name;d.querySelector('.practice-status').textContent='準備演練場…';
 try{const draft=createPractice({id,level:Number($('practice-level').value),branch:$('practice-branch').value,target:$('practice-target').value,training:trainingInfo(getProfile(),id).damage});
 await load(['meadow','road','pad','practice-target','walker','armored','moth','range','aura-range','target','thorn-zone','flame-cone','projectile-bolt','projectile-spore','projectile-frost','projectile-glow','fx-light','fx-rune','fx-petal','fx-spark','fx-clover',...EFFECT_ART,...draft.towers.flatMap(t=>[unitArt(t),...advancedMotionAssets(unitArt(t)),SPELL_ART[UNITS[t.role].kind]])]);if(epoch!==token||!d.open)return;s=draft;last=0;soundId=0;const stats=towerStats(s.towers[0],s);$('practice-stats').textContent=(stats.income?'每波補給 '+Math.min(36,stats.income)+' 金幣':'傷害 '+stats.damage.toFixed(1)+' · 射程 '+stats.range+' · '+stats.interval.toFixed(2)+' 秒／次')+' · '+shapeDescription(stats);$('practice-play').textContent='開始演練';$('practice-score').textContent='尚未開始';d.querySelector('.practice-status').textContent=['artisan','blossom'].includes(id)?'已安排弩手協助，觀察補給與支援效果':s.practice.target==='air'&&!UNITS[id].air?'此兵種無法攻擊飛行目標':'準備完成';draw();}catch{if(epoch===token)d.querySelector('.practice-status').textContent='圖片暫時無法載入，請按重置再試一次';}finally{if(epoch===token){loading=false;$('practice-reset').disabled=false;$('practice-play').disabled=!s;}}
 }
 function branches(){const current=$('practice-branch').value;$('practice-branch').replaceChildren();for(const b of UNIT_BRANCHES[id])$('practice-branch').add(new Option(b.name,b.id));if(UNIT_BRANCHES[id].some(b=>b.id===current))$('practice-branch').value=current;$('practice-branch').disabled=Number($('practice-level').value)<3;}
 function rangeArt(name,p,r,alpha=1){image(name,p.x-r,p.y-r,r*2,r*2,alpha);}
 function draw(){if(!s)return;ctx.clearRect(0,0,390,585);image('meadow',0,0,390,585);image('road',0,0,390,585);for(const t of s.towers){const p=PADS[t.pad];image('pad',p.x-23,p.y-11,46,24);if(range&&t.pad===4){const r=towerStats(t,s);rangeArt('range',p,r.range,.6);drawAttackFootprint({s,p,r,image,rangeArt,ctx,selectedPad:4});}}
 drawArmyMechanics({s,image,ctx,reduced:reducedMotion.matches,simple:false});
 for(const e of s.enemies){const p=pointAt(e.distance,s);sprite(s.practice.target==='single'?'practice-target':e.kind,p.x,p.y,45);if(e.slowUntil>s.time)image('projectile-frost',p.x-14,p.y-24,28,28,.6);if(e.rootUntil>s.time)image('fx-rune',p.x-18,p.y-16,36,36,.8);}
 for(const t of s.towers){const p=PADS[t.pad],pose=troopPose(s,t,reducedMotion.matches),base=unitArt(t),art=advancedMotionArt(base,pose.phase);sprite(art,p.x,p.y,72);}
 for(const shot of s.shots){const e=s.enemies.find(e=>e.id===shot.targetId);if(!e)continue;const p=projectilePose(shot,pointAt(e.distance,s),s.time,reducedMotion.matches);const name=SPELL_ART[shot.kind]||'projectile-bolt';image(name,p.x-9,p.y-9,18,18);}
 drawCombatEffects({s,pads:PADS,corePoint:{x:200,y:550},image,sprite:(name,x,y,h,alpha)=>sprite(s.practice.target==='single'&&name==='walker'?'practice-target':name,x,y,h,alpha),ctx,roles:ROLES,reduced:reducedMotion.matches});}
 function frame(now){raf=0;if(!d.open)return;const dt=last?Math.min(.1,(now-last)/1000):0;last=now;const blocked=picker.open||[...document.querySelectorAll('dialog[open]')].some(x=>!['practice-room','practice-picker','unit-guide','formation','squad','camp'].includes(x.id));if(s&&running&&!loading&&!blocked&&!document.hidden&&innerHeight>=innerWidth){s.paused=false;tickPractice(s,dt*speed);for(const e of s.events){if(e.id<=soundId)continue;soundId=e.id;const effect={release:'shot',hit:'hit',supply:'coin',block:'block'}[e.type];if(effect)audio.sound(effect);}if(s.practice.ended){running=false;$('practice-play').textContent='再次演練';d.querySelector('.practice-status').textContent='演練完成';}const main=s.towers[0];$('practice-score').textContent='出手 '+main.attacks+' 次 · 傷害 '+Math.round(s.contributions[id]||0)+(UNITS[id].income?' · 補給 '+(s.events.findLast(e=>e.type==='supply')?.amount||0)+' 金幣':'');}draw();raf=requestAnimationFrame(frame);}
 function play(){if(loading||!s)return;if(s.practice.ended){reset().then(()=>play());return;}if(!s.practice.started)beginPractice(s);running=!running;s.paused=!running;$('practice-play').textContent=running?'暫停演練':'繼續演練';d.querySelector('.practice-status').textContent=running?'演練中':'已暫停';}
 $('practice-play').onclick=play;$('practice-reset').onclick=reset;$('practice-level').onchange=()=>{branches();reset();};$('practice-branch').onchange=reset;$('practice-target').onchange=reset;
 $('practice-range').onclick=()=>{range=!range;$('practice-range').setAttribute('aria-pressed',String(range));$('practice-range').textContent=range?'隱藏射程':'顯示射程';draw();};$('practice-speed').onclick=()=>{speed=speed===1?.5:1;$('practice-speed').textContent='速度 '+speed+'×';};$('practice-switch').onclick=()=>{const body=picker.querySelector('.journey-body');body.replaceChildren();for(const [key,r] of Object.entries(UNITS)){const b=document.createElement('button');b.innerHTML='<img loading="lazy" src="art/unit-'+key+'.webp" alt=""><span>'+r.name+'</span>';b.onclick=()=>{id=key;branches();picker.close();reset();};body.append(b);}show('practice-picker');};
 $('practice-exit').onclick=()=>d.close();d.addEventListener('close',()=>{token++;running=false;cancelAnimationFrame(raf);syncPause();});document.addEventListener('visibilitychange',()=>last=0);
 return{open(config){id=typeof config==='string'?config:config.id;const value=typeof config==='string'?{}:config;$('practice-level').value=String(value.level||1);branches();if(value.branch)$('practice-branch').value=value.branch;$('practice-target').value='single';show('practice-room');reset();cancelAnimationFrame(raf);last=0;raf=requestAnimationFrame(frame);}};
}
