import {GRADES,DRAW_COST,RECRUIT_UNITS,drawOdds,recruitBatch,trainingRanks,unitLevel,xpForLevel,MAX_LEVEL,exchangeCost,exchangeUnit} from './recruitment.mjs?v=20261003-interface1';
import {UNITS,UNIT_RARITY} from './army.mjs?v=20261003-interface1';
export function installRecruitment({dialog,getProfile,commit,audio,updateWallet,openUnit}){
 const body=dialog.querySelector('.journey-body');let busy=false,generation=0,animations=[],pending=null;
 const reduced=()=>audio.preferences.reducedMotion||matchMedia('(prefers-reduced-motion:reduce)').matches;
 const stop=()=>{generation++;for(const a of animations)a.cancel();animations=[];busy=false;pending=null;};
 dialog.addEventListener('close',stop);dialog.addEventListener('cancel',stop);
 const animate=(el,frames,options)=>{if(reduced())return Promise.resolve();const a=el.animate(frames,options);animations.push(a);return a.finished.catch(()=>{});};
 function results(){const c=getProfile().collection,first=c.lastBatch?.first??c.total;return c.history.filter(h=>h.number>=first).reverse().map(h=>{const g=GRADES.find(g=>g.id===h.grade);return {...h,training:h.training||0,refund:0};});}
 function card(r){const g=GRADES.find(g=>g.id===r.grade),el=document.createElement('article');el.className='recruit-card';el.dataset.grade=r.grade;el.innerHTML=`<h3>${g.name}</h3><img src="art/unit-${r.unit}.webp" alt="${UNITS[r.unit].name}"><strong>${UNITS[r.unit].name}</strong><p>${r.legacy?'舊版收藏已保留':!r.duplicate?'新兵種已解鎖':r.points?'滿級 · 招募點數 +'+r.points:r.levelAfter>r.levelBefore?'升級！Lv.'+r.levelBefore+' → '+r.levelAfter:'重複 · 兵種經驗 +1'}</p>`;return el;}
 function finish(){stop();render();body.scrollTop=0;}
 async function reveal(items){const token=++generation;busy=true;body.replaceChildren();const scene=document.createElement('section');scene.className='summon-scene';scene.innerHTML='<img class="summon-seal" src="art/summon-seal.webp" alt="星露召喚印記"><p role="status">結果已保存，正在召喚伙伴…</p>';const skip=document.createElement('button');skip.id='recruit-skip';skip.textContent='全部揭曉';skip.onclick=finish;body.append(scene,skip);audio.sound('cast');
  await animate(scene.querySelector('img'),[{transform:'scale(.7) rotate(-25deg)',opacity:.3},{transform:'scale(1) rotate(0)',opacity:1}],{duration:650,easing:'ease-out'});
  if(token!==generation||!dialog.open)return;const grid=document.createElement('div');grid.className='recruit-results';scene.replaceChildren(grid);
  for(let i=0;i<items.length;i++){if(token!==generation||!dialog.open)return;const el=card(items[i]);grid.append(el);el.scrollIntoView({block:'nearest'});audio.sound(items[i].grade==='legendary'?'victory':'upgrade');await animate(el,[{transform:'perspective(600px) rotateY(85deg) scale(.9)',opacity:0},{transform:'perspective(600px) rotateY(0) scale(1)',opacity:1}],{duration:items.length===1?550:220,easing:'ease-out'});}
  if(token===generation)finish();
 }
 function ask(count){if(busy)return;pending=count;const cost=count*DRAW_COST,confirm=body.querySelector('#recruit-confirm');confirm.hidden=false;confirm.replaceChildren();const p=document.createElement('p');p.textContent=`確認消耗 ${cost} 星露，招募 ${count} 次？保底逐次累計；重複兵種自動累積經驗；整批結果先保存再演出。`;const yes=document.createElement('button');yes.id='recruit-confirm-yes';yes.textContent=`確認招募 · ${cost} 星露`;const no=document.createElement('button');no.textContent='取消';no.onclick=()=>{pending=null;confirm.hidden=true;};yes.onclick=()=>{if(busy||pending!==count)return;busy=true;yes.disabled=true;try{const next=recruitBatch(getProfile().collection,count);commit({...getProfile(),collection:next.collection});updateWallet();pending=null;void reveal(next.results);}catch(e){busy=false;pending=null;confirm.textContent=`未完成招募：${e.message}。未扣除本次費用。`;}};confirm.append(p,yes,no);confirm.scrollIntoView({block:'start',behavior:'instant'});yes.focus({preventScroll:true});}
 function render(){stop();const c=getProfile().collection,ranks=trainingRanks(c),odds=drawOdds(c);body.replaceChildren();const intro=document.createElement('p');intro.textContent=`星露 ${c.coins}｜已取得 ${c.owned.length} / ${RECRUIT_UNITS.length} 種｜招募點數 ${c.points}。首次解鎖、重複自動培養。`;body.append(intro);
  const actions=document.createElement('div');actions.className='recruit-actions';for(const count of [1,10]){const b=document.createElement('button');b.id=count===1?'recruit-once':'recruit-ten';b.textContent=`${count===1?'單次招募':'十連招募'} · ${count*DRAW_COST}`;b.disabled=c.coins<count*DRAW_COST;b.onclick=()=>ask(count);actions.append(b);}body.append(actions);const confirm=document.createElement('section');confirm.id='recruit-confirm';confirm.hidden=true;body.append(confirm);
  const last=results();if(last.length){const section=document.createElement('section');section.id='recruit-result';const title=document.createElement('h3');title.textContent=`最近 ${last.length} 次結果 · 已保存`;const total=document.createElement('p');total.textContent=`兵種經驗 +${last.reduce((n,r)=>n+r.training,0)}｜結果與升級已存檔`;const grid=document.createElement('div');grid.className='recruit-results';last.forEach(r=>grid.append(card(r)));section.append(title,total,grid);body.append(section);}
  const details=document.createElement('details');details.innerHTML=`<summary>機率、保底與獎勵用途</summary><p>基礎機率：一般 70%、稀有 23%、史詩 6%、傳說 1%。下一抽：${odds.map((n,i)=>GRADES[i].name+' '+n+'%').join('、')}。同階兵種均分該階機率；十連逐次計算。</p><p>每 10 抽至少稀有、30 抽至少史詩、80 抽必得傳說，取得該階以上即重置對應計數。距離保底最多 ${10-c.sinceRare}／${30-c.sinceEpic}／${80-c.sinceLegendary} 抽。</p><p>首次解鎖兵種 Lv.1；重複 +1 專屬經驗，自動升級，最高 Lv.20。每級永久傷害 +3%，新戰役套用；滿級重複 +10 招募點數。與局內升級分開。</p><p>每完成一波 +10 星露；首通另得 150＋關卡×10。沒有付費抽獎。清除網站資料會失去本機存檔，請匯出備份。</p>`;body.append(details);
  const grid=document.createElement('div');grid.className='collection-grid';for(const id of RECRUIT_UNITS){const b=document.createElement('button');b.innerHTML=`<img src="art/unit-${id}.webp" alt=""><span>${UNITS[id].name}</span><small>${GRADES.find(g=>g.id===UNIT_RARITY[id]).name} · ${c.owned.includes(id)?'Lv.'+unitLevel(c.training[id]):'尚未取得'}</small><small>${unitLevel(c.training[id])===MAX_LEVEL?'已滿級':'經驗 '+c.training[id]+' / '+xpForLevel(unitLevel(c.training[id])+1)} · 傷害 +${ranks[id]}%</small>`;b.onclick=()=>openUnit(id);const wrap=document.createElement('section');wrap.append(b);const exchange=document.createElement('button');exchange.textContent='兌換 · '+exchangeCost(id)+' 點';exchange.disabled=c.points<exchangeCost(id)||(c.owned.includes(id)&&unitLevel(c.training[id])===MAX_LEVEL);exchange.onclick=()=>{try{const next=exchangeUnit(getProfile().collection,id);commit({...getProfile(),collection:next.collection});updateWallet();render();}catch(e){exchange.textContent=e.message;}};wrap.append(exchange);grid.append(wrap);}body.append(grid);
  const history=document.createElement('details');history.innerHTML='<summary>最近招募紀錄</summary>';const list=document.createElement('ol');c.history.forEach(h=>{const li=document.createElement('li');li.textContent=`第 ${h.number} 次：${GRADES.find(g=>g.id===h.grade).name} ${UNITS[h.unit].name}${h.duplicate?'（重複）':''}`;list.append(li);});history.append(list);body.append(history);body.scrollTop=0;
 }
 return {render,stop};
}
