import {GRADES,DRAW_COST,RECRUIT_UNITS,drawOdds,recruitBatch,trainingRanks} from './recruitment.mjs?v=20261002-layout2';
import {UNITS} from './army.mjs?v=20261002-layout2';
export function installRecruitment({dialog,getProfile,commit,audio,updateWallet,openUnit}){
 const body=dialog.querySelector('.journey-body');let busy=false,generation=0,animations=[],pending=null;
 const reduced=()=>audio.preferences.reducedMotion||matchMedia('(prefers-reduced-motion:reduce)').matches;
 const stop=()=>{generation++;for(const a of animations)a.cancel();animations=[];busy=false;pending=null;};
 dialog.addEventListener('close',stop);dialog.addEventListener('cancel',stop);
 const animate=(el,frames,options)=>{if(reduced())return Promise.resolve();const a=el.animate(frames,options);animations.push(a);return a.finished.catch(()=>{});};
 function results(){const c=getProfile().collection,first=c.lastBatch?.first??c.total;return c.history.filter(h=>h.number>=first).reverse().map(h=>{const g=GRADES.find(g=>g.id===h.grade);return {...h,training:g.training,refund:h.duplicate?g.refund:0};});}
 function card(r){const g=GRADES.find(g=>g.id===r.grade),el=document.createElement('article');el.className='recruit-card';el.dataset.grade=r.grade;el.innerHTML=`<h3>${g.name}</h3><img src="art/unit-${r.unit}.webp" alt="${UNITS[r.unit].name}"><strong>${UNITS[r.unit].name}</strong><p>訓練 +${r.training}<br>${r.duplicate?`重複 · 星露 +${r.refund}`:'新收藏'}</p>`;return el;}
 function finish(){stop();render();body.scrollTop=0;}
 async function reveal(items){const token=++generation;busy=true;body.replaceChildren();const scene=document.createElement('section');scene.className='summon-scene';scene.innerHTML='<img class="summon-seal" src="art/summon-seal.webp" alt="星露召喚印記"><p role="status">結果已保存，正在召喚伙伴…</p>';const skip=document.createElement('button');skip.id='recruit-skip';skip.textContent='全部揭曉';skip.onclick=finish;body.append(scene,skip);audio.sound('cast');
  await animate(scene.querySelector('img'),[{transform:'scale(.7) rotate(-25deg)',opacity:.3},{transform:'scale(1) rotate(0)',opacity:1}],{duration:650,easing:'ease-out'});
  if(token!==generation||!dialog.open)return;const grid=document.createElement('div');grid.className='recruit-results';scene.replaceChildren(grid);
  for(let i=0;i<items.length;i++){if(token!==generation||!dialog.open)return;const el=card(items[i]);grid.append(el);el.scrollIntoView({block:'nearest'});audio.sound(items[i].grade==='prism'?'victory':'upgrade');await animate(el,[{transform:'perspective(600px) rotateY(85deg) scale(.9)',opacity:0},{transform:'perspective(600px) rotateY(0) scale(1)',opacity:1}],{duration:items.length===1?550:220,easing:'ease-out'});}
  if(token===generation)finish();
 }
 function ask(count){if(busy)return;pending=count;const cost=count*DRAW_COST,confirm=body.querySelector('#recruit-confirm');confirm.hidden=false;confirm.replaceChildren();const p=document.createElement('p');p.textContent=`確認消耗 ${cost} 星露，招募 ${count} 次？保底逐次累計；重複返還於整批結算後加入。`;const yes=document.createElement('button');yes.id='recruit-confirm-yes';yes.textContent=`確認招募 · ${cost} 星露`;const no=document.createElement('button');no.textContent='取消';no.onclick=()=>{pending=null;confirm.hidden=true;};yes.onclick=()=>{if(busy||pending!==count)return;busy=true;yes.disabled=true;try{const next=recruitBatch(getProfile().collection,count);commit({...getProfile(),collection:next.collection});updateWallet();pending=null;void reveal(next.results);}catch(e){busy=false;pending=null;confirm.textContent=`未完成招募：${e.message}。未扣除本次費用。`;}};confirm.append(p,yes,no);body.scrollTop=0;yes.focus({preventScroll:true});}
 function render(){stop();const c=getProfile().collection,ranks=trainingRanks(c),odds=drawOdds(c);body.replaceChildren();const intro=document.createElement('p');intro.textContent=`星露 ${c.coins}｜四種部隊全開。招募取得收藏與訓練，不需付費。`;body.append(intro);
  const actions=document.createElement('div');actions.className='recruit-actions';for(const count of [1,10]){const b=document.createElement('button');b.id=count===1?'recruit-once':'recruit-ten';b.textContent=`${count===1?'單次招募':'十連招募'} · ${count*DRAW_COST}`;b.disabled=c.coins<count*DRAW_COST;b.onclick=()=>ask(count);actions.append(b);}body.append(actions);const confirm=document.createElement('section');confirm.id='recruit-confirm';confirm.hidden=true;body.append(confirm);
  const last=results();if(last.length){const section=document.createElement('section');section.id='recruit-result';const title=document.createElement('h3');title.textContent=`最近 ${last.length} 次結果 · 已保存`;const total=document.createElement('p');total.textContent=`訓練共 +${last.reduce((n,r)=>n+r.training,0)}｜重複返還 ${last.reduce((n,r)=>n+r.refund,0)} 星露`;const grid=document.createElement('div');grid.className='recruit-results';last.forEach(r=>grid.append(card(r)));section.append(title,total,grid);body.append(section);}
  const details=document.createElement('details');details.innerHTML=`<summary>機率、保底與獎勵用途</summary><p>一般：銀葉 70%、金枝 25%、虹晶 5%。下一抽：${odds.map((n,i)=>GRADES[i].name+' '+n+'%').join('、')}。每個品級內四種部隊各 25%。十連按順序計算十次，沒有額外隱藏機率。</p><p>連續 9 次未得金枝以上，第 10 次至少金枝；連續 29 次未得虹晶，第 30 次必得虹晶。距保底最多 ${10-c.sinceGold}／${30-c.sincePrism} 次。</p><p>銀葉／金枝／虹晶給 1／3／8 訓練；同款重複返還 20／35／60 星露。每 10 訓練提升 1 階，傷害 +1%，最多 8%。新戰役才套用。</p><p>每完成一波得 5 星露，首通另得 80＋關卡×10。重玩不重複發首通獎。清除網站資料會刪除本機進度，請先匯出備份。</p>`;body.append(details);
  const grid=document.createElement('div');grid.className='collection-grid';for(const id of RECRUIT_UNITS){const b=document.createElement('button');b.innerHTML=`<img src="art/unit-${id}.webp" alt=""><span>${UNITS[id].name}</span><small>訓練 ${c.training[id]} · ${ranks[id]} 階</small><small>${GRADES.map(g=>c.owned.includes(id+':'+g.id)?g.name:'—').join(' / ')}</small>`;b.onclick=()=>openUnit(id);grid.append(b);}body.append(grid);
  const history=document.createElement('details');history.innerHTML='<summary>最近招募紀錄</summary>';const list=document.createElement('ol');c.history.forEach(h=>{const li=document.createElement('li');li.textContent=`第 ${h.number} 次：${GRADES.find(g=>g.id===h.grade).name} ${UNITS[h.unit].name}${h.duplicate?'（重複）':''}`;list.append(li);});history.append(list);body.append(history);body.scrollTop=0;
 }
 return {render,stop};
}
