import {activeModifiers,supportRadius} from './hero-rules.mjs?v=20261005-story1';
const names={growth:'森林祝福',dream:'星雨',luck:'幸運祝福',joy:'歡樂鼓舞',night:'月夜重擊',sadness:'雨幕',trust:'守護連結',memory:'回憶重現',healing:'生命庇護',hope:'曙光'};
const uses={growth:'敵群進入集中火力區時強化全場部隊。',dream:'敵人聚集時清理群體。',luck:'搭配高傷害部隊，在強敵到來前準備暴擊。',joy:'多處防線同時接敵時提高全隊火力。',night:'集中處理最接近終點的強敵。',sadness:'敵群快要突破防線時爭取輸出時間。',trust:'強化全場部隊並以核心護盾增加容錯。',memory:'先累積回響，再釋放較強的穿甲攻擊。',healing:'核心受損時修復；生命已滿仍可獲得護盾。',hope:'針對密集重甲與頭目使用穿甲光芒。'};
export function skillSpec(h,r){
 const m=activeModifiers(h),role=h.role;
 const spec={name:names[role],use:uses[role],cooldown:m.cooldown,radius:supportRadius(h)+(role==='growth'&&h.specialization==='grove'?55:0),scope:['growth','luck','trust'].includes(role)?'nearby':role==='joy'?'army':role==='healing'?'core':'enemy',duration:(role==='growth'&&h.specialization==='grove'?8:role==='joy'&&h.specialization==='festival'?9:6)+m.duration,charges:h.specialization==='critical'?4:3,heal:3,shield:role==='healing'?(h.specialization==='protect'?5:3):(h.specialization==='shelter'?4:2),damage:(role==='sadness'?20:role==='memory'?r.damage*2+(h.echo||0):r.damage*(h.specialization==='hunt'?5:4))*m.damage,splash:role==='dream'?(h.specialization==='wide'?115:85):role==='sadness'?85:role==='hope'?(h.specialization==='dawn'?65:40):role==='memory'&&h.specialization==='spread'?45:0,pierce:['memory','hope'].includes(role),slow:role==='sadness'?.4:0,slowDuration:(h.specialization==='rain'?6:4)+m.duration,root:h.specialization==='still'?.6:0};
 const d=Number(spec.damage.toFixed(1));
 const description=role==='growth'?`全場部隊傷害 ×1.3，持續 ${spec.duration} 秒。`:role==='luck'?`全場每支部隊獲得 ${spec.charges} 次雙倍攻擊；攻擊時消耗，重複施放重設次數。`:role==='joy'?`全場部隊攻擊間隔 ×0.7，持續 ${spec.duration} 秒；不影響英雄普攻。`:role==='trust'?`全場部隊攻擊間隔 ×0.8，持續 ${spec.duration} 秒；核心護盾 +${spec.shield}。`:role==='healing'?`核心恢復最多 ${spec.heal} 點生命，不超過上限；護盾 +${spec.shield}，優先抵銷漏怪傷害。`:`對全場最接近終點的敵人發射追蹤技能：基礎傷害 ${d}${spec.pierce?'，無視護甲':'，受護甲影響'}${spec.splash?`；命中位置半徑 ${spec.splash} 內敵人同受效果`:'；只影響單一目標'}。${spec.slow?`敵人速度 ×${spec.slow}，持續 ${spec.slowDuration} 秒。`:''}${spec.root?`另外定身 ${spec.root} 秒，頭目效果縮短。`:''}${h.talents?.ultimate==='resolve'?'對頭目直接傷害另加 25%。':''}`;
 return {...spec,description:description+' 新波次技能冷卻重置；限時增益、剩餘暴擊及技能護盾不跨波保留。',geometry:spec.scope==='enemy'?'全場選取目標；命中時依敵人中心計算波及，非英雄普攻射程。':spec.scope==='nearby'?'全場已部署部隊均受益，不受距離限制。':spec.scope==='army'?'影響全場已部署部隊，不受英雄站位限制。':'直接作用於核心，不受站位限制。'};
}
