import {ROLES,UNITS,towerStats,pointAt,castHero,enemyStats,moveHero} from './core.mjs?v=20261002-layout2';
import {encounterWave} from './encounters.mjs?v=20261002-layout2';
import {heroRange,supportRadius} from './hero-rules.mjs?v=20261002-layout2';
import {skillSpec} from './skill-spec.mjs?v=20261002-layout2';
import {routePads,commandPoints,regionFor} from './routes.mjs?v=20261002-layout2';
export function installTactics({getBattle,clock,show,syncPause,audio,perform}){
 const $=id=>document.getElementById(id);let coverage=false,preview=null,notice='',noticeUntil=0,commandPreview=null;
 $('command').addEventListener('close',()=>commandPreview=null);
 document.querySelector('.commander-hit').onclick=()=>{const s=getBattle(),h=s.hero,pads=routePads(s),r=supportRadius(h),body=$('command-zones');body.replaceChildren();$('confirm-command')?.remove();commandPreview=null;const summary=document.createElement('p'),confirm=document.createElement('button');confirm.id='confirm-command';confirm.textContent='請先選擇位置';confirm.disabled=true;const wait=Math.max(0,Math.ceil((h.moveReady||0)-s.time));for(const [i,p]of commandPoints(s).entries()){const name=(regionFor(s)==='moon'?['左翼','右翼','後防']:['前線','中場','後防'])[i],b=document.createElement('button');b.textContent=`預覽 ${name}${wait?` · ${wait} 秒後可移動`:''}`;b.onclick=()=>{commandPreview=p;const before=s.towers.filter(t=>Math.hypot(pads[t.pad].x-h.x,pads[t.pad].y-h.y)<=r),after=s.towers.filter(t=>Math.hypot(pads[t.pad].x-p.x,pads[t.pad].y-p.y)<=r),gain=after.filter(t=>!before.includes(t)).length,loss=before.filter(t=>!after.includes(t)).length;summary.textContent=`${name}：普攻射程 ${heroRange(h,ROLES[h.role].range)}。${['growth','joy','trust'].includes(h.role)?`被動支援半徑 ${r}；受益部隊 ${before.length} → ${after.length}，新增 ${gain}、失去 ${loss}。`:'此英雄沒有附近部隊的常駐支援被動。'}首次換位不需等待，之後換位冷卻 20 秒。`;body.prepend(summary);body.scrollTop=0;confirm.textContent=`確認移往${name}`;confirm.disabled=wait>0||(p.x===h.x&&p.y===h.y);};body.append(b);}confirm.onclick=()=>{if(commandPreview)perform(s=>moveHero(s,commandPreview.x,commandPreview.y));};body.append(summary);body.after(confirm);body.scrollTop=0;show('command');};
 const speed=document.createElement('button');speed.id='battle-speed';speed.textContent='1×';speed.setAttribute('aria-label','戰鬥速度 1 倍');$('settings').before(speed);speed.onclick=()=>{clock.setSpeed(clock.speed===3?1:clock.speed+1);speed.textContent=clock.speed+'×';speed.setAttribute('aria-label',`戰鬥速度 ${clock.speed} 倍`);};
 const ranges=document.createElement('button');ranges.id='coverage-toggle';ranges.textContent='查看射程';ranges.setAttribute('aria-pressed','false');$('hint').before(ranges);ranges.onclick=()=>{coverage=!coverage;ranges.setAttribute('aria-pressed',String(coverage));ranges.textContent=coverage?'收起射程':'查看射程';};
 const toolbar=document.createElement('div');toolbar.className='tactical-toolbar';ranges.before(toolbar);toolbar.append(ranges);const intel=document.createElement('button');intel.id='wave-intel';intel.textContent='波次情報';toolbar.append(intel);const info=document.createElement('dialog');info.id='enemy-info';info.className='journey-dialog';info.innerHTML='<h2>波次情報</h2><div class="journey-body"></div><button class="journey-close">返回戰場</button>';info.querySelector('button').onclick=()=>info.close();info.addEventListener('close',syncPause);document.body.append(info);
 intel.onclick=()=>{const s=getBattle(),wave=Math.min(6,s.phase==='battle'?s.wave:s.wave+1),kinds=encounterWave(s.stage,wave),body=info.querySelector('.journey-body');info.querySelector('h2').textContent=`第 ${wave} 波 · ${kinds.length} 名敵人`;body.replaceChildren();for(const kind of new Set(kinds)){const stats=enemyStats(kind,s,wave),names={walker:'步兵',runner:'快腳',armored:'重甲',boss:'頭目'},tips={walker:'普通地面敵人；用穩定火力守住道路。',runner:'移動速度快；在轉彎處搭配緩速，避免火力只集中前段。',armored:'護甲降低一般傷害；破甲砲或穿甲英雄更適合。',boss:'首次出現 5 秒後預警 1.2 秒，再為自身與半徑 100 內敵人護甲增加 25 個百分點、持續 3 秒；之後每次施放完等待 8 秒。定身時長僅一般敵人的 35%。可用穿甲攻擊反制。'};const section=document.createElement('section');section.className='enemy-guide';section.innerHTML=`<img src="art/${kind}.webp" alt="${names[kind]}"><h3>${names[kind]} ×${kinds.filter(k=>k===kind).length}</h3><p>本波生命 ${stats.hp.toFixed(1)}｜移速 ${stats.speed.toFixed(1)}｜護甲 ${(stats.armor*100).toFixed(0)}%｜漏過核心損失 ${stats.leak} 生命。</p><p>${tips[kind]}</p>`;body.append(section);}show('enemy-info');};
 const d=document.createElement('dialog');d.id='skill-preview';d.className='tactical-dialog';d.innerHTML='<h2></h2><div class="scroll-body"></div><div class="tactical-actions"><button id="confirm-skill">確認施放</button><button id="cancel-skill">取消</button></div>';document.body.append(d);d.addEventListener('close',()=>{preview=null;syncPause();});$('cancel-skill').onclick=()=>d.close();
 const options=document.createElement('label');options.className='quick-skill-option';options.innerHTML='<input type="checkbox" id="quick-skill"> 技能快速施放（不顯示確認預覽）';$('options').querySelector('.options-body').append(options);try{$('quick-skill').checked=localStorage.getItem('cxq.defense.quick-skill')==='true';}catch{}$('quick-skill').onchange=()=>{try{localStorage.setItem('cxq.defense.quick-skill',String($('quick-skill').checked));}catch{}};
 function plan(){const s=getBattle(),h=s.hero,spec=skillSpec(h,ROLES[h.role]),pads=routePads(s),target=s.enemies.filter(e=>e.hp>0).sort((a,b)=>b.distance-a.distance||a.id-b.id)[0],near=s.towers.filter(t=>Math.hypot(pads[t.pad].x-h.x,pads[t.pad].y-h.y)<=spec.radius);let reason=s.phase!=='battle'?'戰鬥開始後才能施放。':h.skillReady>s.time?`冷卻剩餘 ${Math.ceil(h.skillReady-s.time)} 秒。`:spec.scope==='enemy'&&!target?'沒有可攻擊的敵人。':['growth','luck'].includes(h.role)&&!near.length?'支援範圍內沒有部隊，請先部署或移動英雄。':h.role==='joy'&&!s.towers.length?'尚未部署部隊。':'';return {spec,target,near,reason};}
 function cast(){const s=getBattle(),p=plan();if(p.reason){notice=p.reason;noticeUntil=performance.now()+4000;return;}d.close();syncPause();if(s.paused)return;const oldHp=s.hp,oldShield=s.shield;if(castHero(s,p.target?.id)){notice=`${p.spec.name}：${p.spec.scope==='enemy'?'已發射，命中時結算':p.spec.scope==='core'?`恢復 ${s.hp-oldHp} 生命、護盾 +${s.shield-oldShield}`:p.spec.scope==='army'?`${s.towers.length} 支部隊獲得加速`:`影響 ${p.near.length} 支部隊${s.shield>oldShield?`、護盾 +${s.shield-oldShield}`:''}`}`;noticeUntil=performance.now()+4000;}}
 function openSkill(){const p=plan();if($('quick-skill').checked){cast();return;}preview=p;d.querySelector('h2').textContent=p.spec.name;const body=d.querySelector('.scroll-body');body.replaceChildren();for(const line of [p.spec.description,p.spec.geometry,`冷卻 ${p.spec.cooldown} 秒。${p.spec.use}`,p.reason||`確認後施放；取消不消耗冷卻。${getBattle().hero.role==='healing'&&getBattle().hp===getBattle().maxHp?'目前生命已滿，僅增加護盾。':''}`]){const text=document.createElement('p');text.textContent=line;body.append(text);}$('confirm-skill').disabled=!!p.reason;show('skill-preview');}
 $('skill').onclick=openSkill;$('confirm-skill').onclick=cast;
 function overlays(){const s=getBattle(),h=s.hero,pads=routePads(s),list=[];if(coverage){for(const t of s.towers)list.push({id:'range',p:pads[t.pad],r:towerStats(t,s).range,label:UNITS[t.role].name+' 普攻'});list.push({id:'range',p:h,r:heroRange(h,ROLES[h.role].range),label:'英雄普攻'});}if($('command').open){list.push({id:'range',p:h,r:heroRange(h,ROLES[h.role].range),label:'普攻'});if(['growth','joy','trust'].includes(h.role))list.push({id:'aura-range',p:h,r:supportRadius(h),label:'被動支援'});}if(commandPreview&&$('command').open){list.push({id:'range',p:commandPreview,r:heroRange(h,ROLES[h.role].range),label:'移動後普攻'});if(['growth','joy','trust'].includes(h.role))list.push({id:'aura-range',p:commandPreview,r:supportRadius(h),label:'移動後支援'});}if(preview&&d.open){const q=preview;if(q.spec.scope==='nearby'){list.push({id:'aura-range',p:h,r:q.spec.radius,label:'技能支援'});for(const t of q.near)list.push({id:'aura-range',p:pads[t.pad],r:20,label:'受益'});}if(q.target&&q.spec.scope==='enemy'){const p=pointAt(q.target.distance,s,q.target.route);list.push({id:'range',p,r:q.spec.splash||18,label:q.spec.splash?'技能波及':'單體目標'});}if(q.spec.scope==='army')for(const t of s.towers)list.push({id:'aura-range',p:pads[t.pad],r:20,label:'全隊加速'});if(q.spec.scope==='core')list.push({id:'aura-range',p:{x:200,y:550},r:28,label:'核心庇護'});}return list;}
 function update(){if(speed.textContent!==clock.speed+'×'){speed.textContent=clock.speed+'×';speed.setAttribute('aria-label',`戰鬥速度 ${clock.speed} 倍`);}const s=getBattle(),spec=skillSpec(s.hero,ROLES[s.hero.role]),remaining=Math.max(0,Math.ceil(s.hero.skillReady-s.time));const label=remaining?`${spec.name} · ${remaining} 秒`:spec.name;if($('skill').textContent!==label)$('skill').textContent=label;if(performance.now()<noticeUntil)$('hint').textContent=notice;}
 return {overlays,update,reset(){clock.reset();coverage=false;preview=null;notice='';ranges.textContent='查看射程';ranges.setAttribute('aria-pressed','false');},get coverage(){return coverage;}};
}
