import {nextThreat} from './battle-guidance.mjs';
import {ENEMY_CATALOG} from './enemy-catalog.mjs';
import {shouldAutoSkill} from './assists.mjs';
import {ROLES,UNITS,towerStats,pointAt,castHero,enemyStats,kindsFor,BLESSINGS} from './core.mjs?v=20261005-complete1';
import {encounterWave} from './encounters.mjs?v=20261005-complete1';
import {heroRange,supportRadius} from './hero-rules.mjs?v=20261005-complete1';
import {skillSpec} from './skill-spec.mjs?v=20261005-complete1';
import {routePads,commandPoints,regionFor} from './routes.mjs?v=20261005-complete1';
export function installTactics({getBattle,clock,show,syncPause,audio,perform,getProfile,commit}){
 const $=id=>document.getElementById(id);let coverage=false,preview=null,notice='',noticeUntil=0,commandPreview=null;
 $('command').addEventListener('close',()=>commandPreview=null);
 document.querySelector('.commander-hit').onclick=()=>{const s=getBattle(),spec=skillSpec(s.hero,ROLES[s.hero.role]),body=$('command-zones');body.replaceChildren();for(const line of ['英雄在指揮席支援全場。',spec.description,spec.geometry]){const p=document.createElement('p');p.textContent=line;body.append(p);}show('command');};

 const speed=document.createElement('button');speed.id='battle-speed';speed.textContent='1×';speed.setAttribute('aria-label','戰鬥速度 1 倍');$('settings').before(speed);speed.onclick=()=>{clock.setSpeed(clock.speed===3?1:clock.speed+1);speed.textContent=clock.speed+'×';speed.setAttribute('aria-label',`戰鬥速度 ${clock.speed} 倍`);};
 const ranges=document.createElement('button');ranges.id='coverage-toggle';ranges.textContent='查看射程';ranges.setAttribute('aria-pressed','false');$('hint').before(ranges);ranges.onclick=()=>{coverage=!coverage;ranges.setAttribute('aria-pressed',String(coverage));ranges.textContent=coverage?'收起射程':'查看射程';};
 const toolbar=document.createElement('div');toolbar.className='tactical-toolbar';ranges.before(toolbar);toolbar.append(ranges);const intel=document.createElement('button');intel.id='wave-intel';intel.textContent='波次情報';toolbar.append(intel);const info=document.createElement('dialog');info.id='enemy-info';info.className='journey-dialog';info.innerHTML='<h2>波次情報</h2><div class="journey-body"></div><button class="journey-close">返回戰場</button>';info.querySelector('button').onclick=()=>info.close();info.addEventListener('close',syncPause);document.body.append(info);
 intel.onclick=()=>{const s=getBattle(),wave=s.phase==='battle'?s.wave:s.wave+1,kinds=kindsFor(s,wave),body=info.querySelector('.journey-body');info.querySelector('h2').textContent=`第 ${wave} 波 · ${kinds.length} 名敵人`;body.replaceChildren();const forecast=document.createElement('p');forecast.className='session-forecast';forecast.textContent=nextThreat(s).text;body.append(forecast);for(const kind of new Set(kinds)){const stats=enemyStats(kind,s,wave),names=Object.fromEntries(Object.entries(ENEMY_CATALOG).map(([id,v])=>[id,v.name])),tips=Object.fromEntries(Object.entries(ENEMY_CATALOG).map(([id,v])=>[id,v.tip]));const section=document.createElement('section');section.className='enemy-guide';section.innerHTML=`<img src="art/${kind}.webp" alt="${names[kind]}"><h3>${names[kind]} ×${kinds.filter(k=>k===kind).length}</h3><p>本波生命 ${stats.hp.toFixed(1)}｜移速 ${stats.speed.toFixed(1)}｜護甲 ${(stats.armor*100).toFixed(0)}%｜漏過核心損失 ${stats.leak} 生命。</p><p>${tips[kind]}</p>`;body.append(section);}show('enemy-info');};
 const blessingView=document.createElement('dialog');blessingView.id='active-blessings';blessingView.className='journey-dialog';blessingView.innerHTML='<h2>本局祝福</h2><div class="journey-body"></div><button>返回戰場</button>';blessingView.querySelector('button').onclick=()=>blessingView.close();blessingView.addEventListener('close',syncPause);document.body.append(blessingView);const blessingsButton=document.createElement('button');blessingsButton.textContent='本局祝福';toolbar.append(blessingsButton);blessingsButton.onclick=()=>{const s=getBattle(),body=blessingView.querySelector('.journey-body');body.replaceChildren();const counts=(s.blessingHistory??[]).reduce((v,id)=>(v[id]=(v[id]??0)+1,v),{});if(!Object.keys(counts).length){const p=document.createElement('p');p.textContent='本局尚未選擇祝福。';body.append(p);}for(const [id,n] of Object.entries(counts)){const p=document.createElement('p');p.textContent=BLESSINGS[id].name+' ×'+n+'：'+BLESSINGS[id].description+(id==='power'?' 累計基礎傷害 +'+(n*8)+'%。':id==='reach'?' 累計射程 +'+(n*8)+'，上限 260。':id==='command'?' 累計間隔縮短 '+(100*(1-Math.pow(.94,Math.min(n,8)))).toFixed(1)+'%。':id==='shatter'?' 累計對緩速敵人直接傷害 +'+n*12+'%。':id==='supplies'?' 已取得 '+n*100+' 本局金幣。':' 已施放 '+n+' 次修復，實際恢復不超過生命上限。');body.append(p);}show('active-blessings');};
 const assistOptions=document.createElement('section');assistOptions.className='ability-card';assistOptions.innerHTML='<h3>戰鬥輔助</h3><label><input id="auto-hero-skill" type="checkbox"> 自動施放英雄技能</label><label><input id="auto-blessing-choice" type="checkbox"> 自動選擇祝福</label><label>祝福優先<select id="auto-blessing-strategy"><option value="balanced">均衡</option><option value="damage">傷害</option><option value="control">控制</option><option value="survival">生存</option></select></label><p>開啟後自動施放技能與選擇祝福。</p>';$('options').querySelector('.options-body').append(assistOptions);const prefs=getProfile().assists;$('auto-hero-skill').checked=prefs.autoSkill;$('auto-blessing-choice').checked=prefs.autoBlessing;$('auto-blessing-strategy').value=prefs.strategy;assistOptions.onchange=()=>commit({...getProfile(),assists:{autoSkill:$('auto-hero-skill').checked,autoBlessing:$('auto-blessing-choice').checked,strategy:$('auto-blessing-strategy').value}});
 const d=document.createElement('dialog');d.id='skill-preview';d.className='tactical-dialog';d.innerHTML='<h2></h2><div class="scroll-body"></div><div class="tactical-actions"><button id="confirm-skill">確認施放</button><button id="cancel-skill">取消</button></div>';document.body.append(d);d.addEventListener('close',()=>{preview=null;syncPause();});$('cancel-skill').onclick=()=>d.close();
 const options=document.createElement('label');options.className='quick-skill-option';options.innerHTML='<input type="checkbox" id="quick-skill"> 一鍵施放英雄技能';$('options').querySelector('.options-body').append(options);try{$('quick-skill').checked=localStorage.getItem('cxq.defense.quick-skill')!=='false';}catch{}$('quick-skill').onchange=()=>{try{localStorage.setItem('cxq.defense.quick-skill',String($('quick-skill').checked));}catch{}};
 function plan(){const s=getBattle(),h=s.hero,spec=skillSpec(h,ROLES[h.role]),pads=routePads(s),target=s.enemies.filter(e=>e.hp>0).sort((a,b)=>b.distance-a.distance||a.id-b.id)[0],near=s.towers;let reason=s.phase!=='battle'?'戰鬥開始後才能施放。':h.skillReady>s.time?`冷卻剩餘 ${Math.ceil(h.skillReady-s.time)} 秒。`:spec.scope==='enemy'&&!target?'沒有可攻擊的敵人。':['growth','luck'].includes(h.role)&&!near.length?'尚未部署部隊。':h.role==='joy'&&!s.towers.length?'尚未部署部隊。':'';return {spec,target,near,reason};}
 function cast(){const s=getBattle(),p=plan();if(p.reason){notice=p.reason;noticeUntil=performance.now()+4000;return;}d.close();syncPause();if(s.paused)return;const oldHp=s.hp,oldShield=s.shield;if(castHero(s,p.target?.id)){notice=`${p.spec.name}：${p.spec.scope==='enemy'?'已施放':p.spec.scope==='core'?`恢復 ${s.hp-oldHp} 生命、護盾 +${s.shield-oldShield}`:p.spec.scope==='army'?`${s.towers.length} 支部隊獲得加速`:`影響 ${p.near.length} 支部隊${s.shield>oldShield?`、護盾 +${s.shield-oldShield}`:''}`}`;noticeUntil=performance.now()+4000;}}
 function openSkill(){const p=plan();if($('quick-skill').checked){cast();return;}preview=p;d.querySelector('h2').textContent=p.spec.name;const body=d.querySelector('.scroll-body');body.replaceChildren();for(const line of [p.spec.description,p.spec.geometry,`冷卻 ${p.spec.cooldown} 秒。${p.spec.use}`,p.reason||`確認後施放；取消不消耗冷卻。${getBattle().hero.role==='healing'&&getBattle().hp===getBattle().maxHp?'目前生命已滿，僅增加護盾。':''}`]){const text=document.createElement('p');text.textContent=line;body.append(text);}$('confirm-skill').disabled=!!p.reason;show('skill-preview');}
 $('skill').onclick=openSkill;$('confirm-skill').onclick=cast;
 function overlays(){const s=getBattle(),h=s.hero,pads=routePads(s),list=[];if(coverage){for(const t of s.towers)if(!towerStats(t,s).income)list.push({id:'range',p:pads[t.pad],r:towerStats(t,s).range,label:UNITS[t.role].name+' 普攻'});}if(preview&&d.open){const q=preview;if(q.spec.scope==='nearby'){for(const t of q.near)list.push({id:'aura-range',p:pads[t.pad],r:20,label:'受益'});}if(q.target&&q.spec.scope==='enemy'){const p=pointAt(q.target.distance,s,q.target.route);list.push({id:'range',p,r:q.spec.splash||18,label:q.spec.splash?'技能波及':'單體目標'});}if(q.spec.scope==='army')for(const t of s.towers)list.push({id:'aura-range',p:pads[t.pad],r:20,label:'全隊加速'});if(q.spec.scope==='core')list.push({id:'aura-range',p:{x:pointAt(1e9,s).x,y:550},r:28,label:'核心庇護'});}return list;}
 function update(){if(shouldAutoSkill(getBattle(),getProfile().assists))cast();if(speed.textContent!==clock.speed+'×'){speed.textContent=clock.speed+'×';speed.setAttribute('aria-label',`戰鬥速度 ${clock.speed} 倍`);}const s=getBattle(),spec=skillSpec(s.hero,ROLES[s.hero.role]),remaining=Math.max(0,Math.ceil(s.hero.skillReady-s.time));const label=remaining?`${spec.name} · ${remaining} 秒`:spec.name;if($('skill').textContent!==label)$('skill').textContent=label;if(performance.now()<noticeUntil)$('hint').textContent=notice;}
 return {overlays,update,reset(){clock.reset();coverage=false;preview=null;notice='';ranges.textContent='查看射程';ranges.setAttribute('aria-pressed','false');},get coverage(){return coverage;}};
}
