import {sharedAssets,assetUrl} from './asset-loader.mjs';
import {UNITS,UNIT_BRANCHES,UNIT_GUIDES,UNIT_RARITY} from './army.mjs';
import {GRADES} from './recruitment.mjs';
import {trainingInfo,trainingPreview,useTrainingBooks,BOOK_NAMES} from './training-books.mjs';
import {unitArt,branchGuide} from './unit-presentation.mjs';
import {advancedMotionAssets} from './advanced-motion.mjs';
import {spritePlacement} from './sprite-placement.mjs';
import {attackType,shapeDescription} from './attack-shapes.mjs';
export function installUnitGallery({dialog,getProfile,commit,show,onTrial,audio}){
 let id='archer',level=1,branch=null,tab='intro',token=0,raf=0,started=0,poses=[],loaded=[],idle=null,stageImage=null;
 dialog.classList.add('unit-gallery');dialog.innerHTML='<div class="unit-gallery-header"><div><p class="unit-rarity"></p><h2></h2></div><button class="gallery-back">返回</button></div><div class="unit-gallery-stage"><canvas width="390" height="270" aria-label="兵種展示"></canvas><p class="unit-stage-caption"></p></div><nav aria-label="兵種資料分頁"><button data-unit-tab="intro">介紹</button><button data-unit-tab="training">培養</button><button data-unit-tab="evolution">進階</button></nav><div class="unit-gallery-body"></div><div class="unit-gallery-actions"><button id="unit-trial">開始演練</button></div>';
 const body=dialog.querySelector('.unit-gallery-body'),canvas=dialog.querySelector('canvas'),ctx=canvas.getContext('2d');
 dialog.querySelector('.gallery-back').onclick=()=>dialog.close();dialog.querySelector('#unit-trial').onclick=()=>onTrial({id,level,branch});
 dialog.querySelectorAll('[data-unit-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.unitTab;render();});
 dialog.addEventListener('close',()=>{token++;cancelAnimationFrame(raf);});
 function animate(now){raf=0;if(!dialog.open||!idle)return;let index=0;const age=(now-started)%4500;if(document.body.dataset.motion!=='reduced'&&!document.hidden&&!document.querySelector('#practice-room[open]')&&age<900){index=age<220?1:age<560?2:0;}const im=loaded[index]||idle,p=spritePlacement((index?poses[index-1]:unitArt({role:id,level,branch})),im,Math.min(160,canvas.height*.65));ctx.clearRect(0,0,390,270);if(stageImage)ctx.drawImage(stageImage,0,-190,390,585);ctx.drawImage(im,195+p.x,236+p.y,p.width,p.height);raf=requestAnimationFrame(animate);}
 async function appearance(){const epoch=++token;cancelAnimationFrame(raf);const art=unitArt({role:id,level,branch});poses=advancedMotionAssets(art);idle=null;ctx.clearRect(0,0,390,270);dialog.querySelector('.unit-stage-caption').textContent='Lv.'+level+' · '+(level>=3?UNIT_BRANCHES[id].find(b=>b.id===branch)?.name:'基礎兵種');
 try{const ims=await Promise.all([art,...poses].map(async key=>{return sharedAssets.get(key);}));if(epoch!==token||!dialog.open)return;loaded=ims;idle=ims[0];if(!stageImage){stageImage=await sharedAssets.get('unit-gallery-stage');}if(epoch!==token||!dialog.open)return;started=performance.now();raf=requestAnimationFrame(animate);}catch{if(epoch===token)dialog.querySelector('.unit-stage-caption').textContent='圖片載入中，請重新選擇';}}
 function render(){const profile=getProfile(),r=UNITS[id],info=trainingInfo(profile,id);dialog.querySelector('h2').textContent=r.name;dialog.querySelector('.unit-rarity').textContent=GRADES.find(g=>g.id===UNIT_RARITY[id]).name+' · '+attackType(r);dialog.querySelectorAll('[data-unit-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.unitTab===tab)));body.replaceChildren();body.scrollTop=0;
 if(tab==='intro'){const text=document.createElement('section');text.innerHTML='<h3>'+UNIT_GUIDES[id][0]+'</h3><p>'+UNIT_GUIDES[id][1]+'</p><div class="gallery-facts"><span>部署<strong>'+r.cost+' 金幣</strong></span><span>'+(r.income?'補給':'傷害')+'<strong>'+(r.income||r.damage)+'</strong></span><span>射程<strong>'+r.range+'</strong></span><span>間隔<strong>'+r.interval+' 秒</strong></span></div><p>'+shapeDescription(r)+' · '+(r.income?'完成波次提供補給':r.air?'可攻擊地面與飛行敵人':'攻擊地面敵人')+'</p>';body.append(text);}
 if(tab==='training'){const text=document.createElement('section');text.innerHTML='<h3>培養 Lv.'+info.level+'</h3><p>'+info.effectLabel+' +'+info.damage+'%'+(info.max?' · 已滿等':' → 下一級 +'+info.nextDamage+'%')+'</p><p>本級進度 '+info.progress+' / '+info.required+'</p><p>持有 '+BOOK_NAMES[info.grade]+'訓練書 '+info.available+' 張</p>';if(id==='artisan'){const p=document.createElement('p');p.textContent='提升補給收益。全隊每波最多獲得 36 金幣。';text.append(p);}body.append(text);
 const count=document.createElement('input');count.type='number';count.min='1';count.step='1';count.value='1';count.setAttribute('aria-label','使用訓練書數量');const summary=document.createElement('p'),next=document.createElement('button'),max=document.createElement('button'),confirm=document.createElement('button'),controls=document.createElement('div');controls.className='gallery-training-tools';let preview=null;const refresh=()=>{try{preview=trainingPreview(getProfile(),id,Number(count.value));summary.textContent='使用 '+preview.consumed+' 張 · Lv.'+preview.before+' → Lv.'+preview.after+' · '+info.effectLabel+' +'+preview.damageBefore+'% → +'+preview.damageAfter+'%';confirm.disabled=false;}catch{preview=null;summary.textContent=!info.owned?'先招募此兵種，即可培養':info.max?'已達最高培養等級':info.available===0?'前往兵種演練副本取得訓練書':'請輸入持有範圍內的整數';confirm.disabled=true;}};count.oninput=refresh;next.textContent='下一級';next.disabled=!info.owned||info.max||info.available<info.remaining;next.onclick=()=>{count.value=String(info.remaining);refresh();};max.textContent='最大培養';max.disabled=!info.owned||info.max||info.available===0;max.onclick=()=>{count.value=String(info.available);refresh();};confirm.textContent='確認培養';confirm.onclick=()=>{if(!preview)return;commit(useTrainingBooks(getProfile(),id,Number(count.value)).profile);audio.sound('training');render();};controls.append(count,next,max);body.append(controls,summary,confirm);refresh();}
 if(tab==='evolution'){const choices=document.createElement('div');choices.className='gallery-tier';for(const n of [1,3,5,7,10]){const b=document.createElement('button');b.textContent='Lv.'+n;b.setAttribute('aria-pressed',String(level===n));b.onclick=()=>{level=n;branch??=UNIT_BRANCHES[id][0].id;render();appearance();};choices.append(b);}body.append(choices);const cards=document.createElement('div');cards.className='gallery-branches';for(const b of UNIT_BRANCHES[id]){const card=document.createElement('button');card.setAttribute('aria-pressed',String(branch===b.id));card.innerHTML='<img loading="lazy" src="'+assetUrl(unitArt({role:id,level:Math.max(3,level),branch:b.id}))+'" alt=""><strong>'+b.name+'</strong><span>'+branchGuide(id,b.id)+'</span>';card.onclick=()=>{branch=b.id;if(level<3)level=3;render();appearance();};cards.append(card);}body.append(cards);}
 }
 return{openUnit(key){id=key;level=1;branch=null;tab='intro';render();show(dialog.id);appearance();}};
}
