import * as audioV2 from './audio-v2.mjs';
import {CAST,BY_ID,STAGES,MODES,LINES,ENDINGS,CONTROLS,ACTION_NAMES,ART,makeJourney,journeyOptions,advanceJourney,VERSION} from './cast.mjs?v=20261008-complete2';
import {createMatch,step,DT,nextRound,resetTraining,demonstration,restore} from './core.mjs?v=20261008-complete2';
import {storage} from './save.mjs?v=20261008-complete2';
import {Painter,SELECT_ASSETS} from './render.mjs?v=20261008-complete2';
import {Input} from './input.mjs?v=20261008-complete2';
const $=s=>document.querySelector(s),screen=$('#screen'),modal=$('#modal'),cabinet=$('#cabinet'),db=storage();
let page='home',match=null,run=null,paused=false,loaded=false,selection={mode:'story',p1:'growth',p2:'luck',stage:'festival',difficulty:'normal',cursor:0},result=null,roundHandled=false,storyRecorded=false,eventCursor=0,message='',messageUntil=0,frameTime=performance.now(),accumulator=0,hudAt=0,saveAt=0,fpsFrames=0,fpsAt=performance.now(),fps=0,lowSamples=0,music=null,musicId='',audioUnlocked=false,soundContext=null,soundAt=0,menuIndex=0,remapping=false;
const prefs=()=>db.get().settings,esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const asset=src=>paint.url(src);
const button=(label,action,data='',cls='')=>'<button type="button" class="art-button '+cls+'" data-action="'+action+'" '+data+'><img src="'+asset(action==='exit'?ART.return:ART.button)+'" alt=""><span'+(action==='exit'?' class="return-caption"':'')+'>'+label+'</span></button>';
const portrait=(id,extras='')=>'<img class="face" src="'+asset(BY_ID[id].portrait)+'" alt="'+BY_ID[id].name+'"><img class="frame" src="'+asset(ART.card)+'" alt="">'+extras;
const paint=new Painter($('#scene'),prefs),input=new Input(cabinet,()=>match,()=>loaded&&page==='battle'&&!paused&&!orientationBlocked()&&modal.hidden&&!document.hidden,prefs,menuKey);
function orientationBlocked(){return innerHeight>innerWidth;}
function rotationReturn(){const gate=$('#rotate');if(gate.querySelector('a'))return;const a=document.createElement('a');a.className='rotation-return';a.href='../../../?view=game-hub&v='+VERSION;a.setAttribute('aria-label','返回遊戲中心');const img=document.createElement('img');img.src=asset(ART.return);img.alt='返回遊戲中心';a.append(img);gate.append(a);}
function resize(){const style=getComputedStyle(document.documentElement),safe=side=>parseFloat(style.getPropertyValue('--safe-'+side))||0,left=safe('left'),right=safe('right'),top=safe('top'),bottom=safe('bottom'),width=innerWidth-left-right,height=innerHeight-top-bottom,scale=Math.min(width/1280,height/720);cabinet.style.transform='scale('+scale+')';cabinet.style.left=left+(width-1280*scale)/2+'px';cabinet.style.top=top+(height-720*scale)/2+'px';const blocked=orientationBlocked(),was=!$('#rotate').hidden;$('#rotate').hidden=!blocked;if(blocked){rotationReturn();input.reset();if(page==='battle'){paused=true;capture();}}else if(was&&page==='battle'){paused=true;showPause();}paint.resize();}
function preferences(){cabinet.style.setProperty('--controls-size',prefs().buttonSize);cabinet.style.setProperty('--controls-opacity',prefs().opacity);cabinet.style.setProperty('--control-x',prefs().offsetX+'px');cabinet.style.setProperty('--control-y',prefs().offsetY+'px');paint.resize();syncAudio();}
function barGeometry(type,i){const life=type==='life',a=paint.meta[life?'life-frame':'energy-frame'],b=a?.bounds,s=a?.slot,W=life?420:265,H=life?63:47,X=life?(i?0:70):0,Y=life?26:0;if(!b||!s)return{x:life?(i?25:92):27,y:life?41:15,w:life?368:210,h:life?22:15};const x=(s.x-b.x)/b.w*W,w=s.w/b.w*W;return{x:X+(i?W-x-w:x),y:Y+(s.y-b.y)/b.h*H,w,h:s.h/b.h*H};}
function fitBars(){for(let i=0;i<2;i++)for(const type of ['life','energy']){const g=barGeometry(type,i),window=$('#'+type+'-'+i),img=window.querySelector('img');window.style.left=g.x+'px';window.style.top=g.y+'px';window.style.width=g.w+'px';window.style.height=g.h+'px';img.style.width=g.w+'px';img.style.height=g.h+'px';}}
function capture(){if(loaded&&match)db.capture(match,run);}
function fitUi(root){for(const img of root.querySelectorAll('img')){const src=paint.source(img.getAttribute('src'));if(!src?.startsWith('art/')||img.dataset.fitted===src)continue;const b=paint.meta[src.split('/').pop().replace('.webp','')]?.bounds;if(!b)continue;const style=getComputedStyle(img),box=img.dataset.baseBox?JSON.parse(img.dataset.baseBox):[parseFloat(style.width),parseFloat(style.height),parseFloat(style.left)||0,parseFloat(style.top)||0], [w,h,x,y]=box;img.dataset.baseBox=JSON.stringify(box);if(!(w>0&&h>0))continue;img.dataset.fitted=src;img.style.objectFit='fill';img.style.width=w/b.w+'px';img.style.height=h/b.h+'px';img.style.left=x-w*b.x/b.w+'px';img.style.top=y-h*b.y/b.h+'px';}if(root===screen){const el=root.querySelector('#battle-hint'),b=paint.meta['menu-button']?.bounds;if(el&&b){el.style.backgroundImage='url("'+asset(ART.button)+'")';const h=el.offsetHeight;el.style.backgroundSize=670/b.w+'px '+h/b.h+'px';el.style.backgroundPosition=-670*b.x/b.w+'px '+(-h*b.y/b.h)+'px';}}if(root===modal){modal.style.backgroundImage='url("'+asset(ART.panel)+'")';const b=paint.meta['panel-frame']?.bounds;if(b){modal.style.backgroundSize=900/b.w+'px '+560/b.h+'px';modal.style.backgroundPosition=-900*b.x/b.w+'px '+(-560*b.y/b.h)+'px';}}}
function dialog(title,html){input.reset();if(page==='battle')paused=true;modal.innerHTML='<h2>'+title+'</h2>'+html;modal.hidden=false;fitUi(modal);syncAudio();}
function close(){modal.hidden=true;remapping=false;input.bind=null;}
function notify(text,duration=2){message=text;messageUntil=performance.now()+duration*1000;}
function top(){return '<div class="top-actions">'+button('遊戲說明','help')+button('設定','settings')+button('全螢幕','fullscreen')+'</div>';}
function render(){cabinet.dataset.screen=page;if(['select','setup'].includes(page)&&['story','survival'].includes(selection.mode)){selection.cursor=0;selection.p2=journeyOptions(makeJourney(selection.mode,selection.p1,selection.difficulty,selection.stage)).p2;}close();screen.innerHTML='';queueMicrotask(()=>fitUi(screen));if(page==='home'){screen.innerHTML=top()+'<img class="at logo" style="left:420px;top:30px" src="'+asset(ART.logo)+'" alt="CxQ 心光對決"><div class="at menu-stack" style="left:410px;top:195px">'+MODES.map(([id,name,sub])=>button(name+'<small>'+sub+'</small>','mode','data-mode="'+id+'"')).join('')+'</div><div class="at" style="left:25px;bottom:18px">'+button('返回遊戲中心','exit')+'</div><div class="at" style="right:25px;bottom:18px">'+(db.get().active?button('接續上次對戰','resume'):'')+'</div><div class="at small center" style="left:400px;bottom:12px;width:480px">十位心光角色 · 固定橫向 · 原創街機對決</div>';return;}
 if(page==='select'){screen.innerHTML=top()+'<h1 class="at heading" style="left:490px;top:25px">CHARACTER SELECT</h1><div class="at small center" style="left:440px;top:76px;width:400px">'+MODES.find(m=>m[0]===selection.mode)[1]+' · 選擇 '+(selection.cursor===0?'主角':'對手')+'</div>'+['p1','p2'].map((key,i)=>{const c=BY_ID[selection[key]];return '<div class="at fighter-copy '+(i?'right':'left')+'" style="left:'+(i?870:60)+'px;top:83px"><div class="heading">'+c.name+'</div><div class="gold label">'+c.title+' · '+c.style+'</div><div class="tip">'+c.tip+'</div></div>';}).join('')+'<div class="at heading" style="left:607px;top:308px;font-size:65px">VS</div><div class="roster">'+CAST.map(c=>'<button class="portrait '+([selection.p1,selection.p2].includes(c.id)?'chosen':'')+'" data-action="pick" data-id="'+c.id+'">'+portrait(c.id,(selection.p1===c.id?'<span class="marker">1P</span>':'')+(selection.p2===c.id?'<span class="marker second">'+(selection.mode==='local'?'2P':'COM')+'</span>':'')+'<span class="name">'+c.name+'</span>')+'</button>').join('')+'</div><div class="at" style="left:35px;bottom:20px">'+button('返回主選單','home')+'</div><div class="at" style="right:35px;bottom:20px">'+button(['story','survival'].includes(selection.mode)?'確認主角':selection.cursor===0?'確認 1P':'確認並設定舞台','confirm')+'</div><div class="at center small" style="left:370px;top:450px;width:540px">' + (['story','survival'].includes(selection.mode)?'方向鍵選角 · Enter 確認 · 對手依旅程安排':'方向鍵選角 · Enter 確認 · 點兩側名字切換角色') + '</div><button class="at heading" style="left:143px;top:83px;width:170px;height:100px" data-action="cursor" data-player="0" aria-label="選擇1P"></button><button class="at heading" style="right:143px;top:83px;width:170px;height:100px" data-action="cursor" data-player="1" aria-label="選擇2P"></button>';return;}
 if(page==='setup'){screen.innerHTML=top()+'<h1 class="at heading" style="left:320px;top:35px;width:640px;text-align:center">選擇舞台與難度</h1><div class="at" style="left:440px;top:145px;width:400px"><div class="heading center">'+BY_ID[selection.p1].name+' VS '+BY_ID[selection.p2].name+'</div><div class="menu-stack" style="margin:24px auto">'+STAGES.map(s=>button((s.id===selection.stage?'◆ ':'')+s.name,'stage','data-stage="'+s.id+'"')).join('')+'</div><div class="setup-row" style="justify-content:center">'+['easy','normal','hard'].map((d,i)=>button((d===selection.difficulty?'◆ ':'')+['入門','標準','挑戰'][i],'difficulty','data-difficulty="'+d+'"')).join('')+'</div></div><div class="at" style="left:35px;bottom:20px">'+button('返回選角','select')+'</div><div class="at" style="right:35px;bottom:20px">'+button('開始對決','start')+'</div>';return;}
 if(page==='battle'){screen.innerHTML=match.fighters.map((f,i)=>'<section class="hud p'+(i+1)+'"><div class="portrait">'+portrait(f.id)+'</div><span class="hero-name">'+(i+1)+'P '+BY_ID[f.id].name+'</span><span class="health" id="health-'+i+'"></span><img class="bar-frame" src="'+asset(ART.life)+'" alt=""><div class="fill-window" id="life-'+i+'"><img class="fill" src="'+asset(ART.lifeFill)+'" alt=""></div><span class="guard" id="guard-'+i+'"></span></section><section class="energy p'+(i+1)+'"><img src="'+asset(ART.energy)+'" alt=""><div class="fill-window" id="energy-'+i+'"><img class="fill" src="'+asset(ART.energyFill)+'" alt=""></div><span class="value" id="meter-'+i+'"></span></section>').join('')+'<div class="clock"><span id="clock"></span><small id="round-label"></small></div><div class="round-wins" style="left:35px" id="wins-0"></div><div class="round-wins" style="right:35px" id="wins-1"></div><div class="top-actions" style="top:178px;right:auto;left:570px">'+button('暫停','pause')+'</div>'+(match.mode==='training'?'<div class="training-tools">'+button('訓練工具','training')+'</div>':'')+'<div class="control-area"><button id="joystick" aria-label="方向桿：左右移動、下蹲、上跳"><img class="base" src="'+asset(ART.stick)+'" alt=""><img class="knob" src="'+asset(ART.knob)+'" alt=""></button><div class="control-pad">'+['light','heavy','skill','jump','guard','super'].map(k=>'<button class="control" data-control="'+k+'" aria-label="'+ACTION_NAMES[k]+'"><img src="'+asset(ART['control-'+k])+'" alt=""><span>'+({light:'輕攻',heavy:'重攻',skill:'技能',jump:'跳躍',guard:'格擋',super:'必殺'})[k]+'</span></button>').join('')+'</div></div><div class="battle-hint" id="battle-hint"></div><img class="announcement" id="announcement" hidden alt=""><div class="intro-line" id="intro-line"></div><div class="fps" id="fps"></div>';preferences();fitBars();hud();return;}
 if(page==='result'){const c=BY_ID[result.hero];screen.innerHTML=top()+'<img class="result-logo" src="'+asset(result.win?ART.win:ART.lose)+'" alt="'+(result.win?'勝利':'再接再厲')+'"><div class="result-copy"><h1 class="heading">'+c.name+' · '+(result.ending?'故事完成':result.win?'勝利':'挑戰結束')+'</h1><p>'+esc(result.ending?ENDINGS[c.id]:LINES[c.id][result.win?1:0])+'</p><p class="small">最大連段 '+result.combo+' · 總傷害 '+result.damage+'<br>'+result.subtitle+'</p></div><div class="result-actions">'+button(result.continue?'下一場對決':'再戰一次',result.continue?'continue':'retry')+button('返回主選單','home')+'</div>';return;}}
async function start(options,existing=null){if(!loaded)return;const prepareAt=performance.now();input.reset();const next=existing||createMatch(options);match=next;if(run?.mode==='survival'&&run.health!==null&&!existing)match.fighters[0].hp=Math.min(match.fighters[0].maxHp,Math.max(1,run.health));db.capture(next,run);loaded=false;paused=true;music?.pause();$('#loading').hidden=false;try{await paint.battle(next,(n,total,status)=>$('#load-status').textContent=status||'準備 '+BY_ID[next.fighters[0].id].name+' 與 '+BY_ID[next.fighters[1].id].name+' 的動作 '+n+' / '+total);loaded=true;cabinet.dataset.matchReadyMs=Math.round(performance.now()-prepareAt);$('#loading').hidden=true;selection={...selection,...options};match=next;page='battle';paused=false;roundHandled=false;storyRecorded=false;eventCursor=0;paint.seen=0;paint.effects=[];accumulator=0;fpsFrames=0;fpsAt=performance.now();lowSamples=0;render();resize();capture();syncAudio();sound('ready');}catch(e){loaded=true;$('#loading').hidden=true;paused=true;dialog('對戰素材載入失敗','<p class="notice error">'+esc(e.message)+'<br>可重新開始或接續對戰，已保存的進度仍保留。</p><div class="actions">'+button('返回主選單','home')+'</div>');}}
function begin(){run=['story','survival'].includes(selection.mode)?makeJourney(selection.mode,selection.p1,selection.difficulty,selection.stage):null;start(run?journeyOptions(run):selection);}
function finish(){const winner=match.result.winner,win=winner===0,hero=match.fighters[0].id,opponent=match.fighters[1].id;const display=winner===1&&match.mode==='local'?1:0;result={hero:match.fighters[display].id,win:match.mode==='local'?winner>=0:win,combo:match.bestCombo[display],damage:match.totalDamage[display],subtitle:match.mode==='local'?(winner+1)+'P 獲勝':'回合 '+match.wins.join(' : '),continue:false,ending:false};
 db.finish({hero,opponent,win,combo:match.bestCombo[0],wins:[...match.wins],mode:match.mode});
 if(run){const progress=advanceJourney(run,win,match.fighters[0].hp);Object.assign(result,{ending:progress.ending,continue:progress.continue});if(win){if(run.mode==='story'){db.get().story[hero]={cleared:Math.max(db.get().story[hero]?.cleared||0,progress.cleared),completed:!!db.get().story[hero]?.completed||progress.ending};result.subtitle='故事旅程 '+progress.cleared+' / 5';}else result.subtitle='生存連勝 '+run.wins+' · 下一場生命 '+Math.round(run.health);if(result.continue)db.get().run=structuredClone(run);db.save();}else result.subtitle=run.mode==='survival'?'本次生存連勝 '+run.wins:'故事旅程停在第 '+(run.index+1)+' 場';}
 page='result';paused=false;render();sound(win?'win':'lose');syncAudio();}
function showPause(){if(page!=='battle')return;paused=true;capture();dialog('對戰暫停','<p class="notice">目前回合、生命與能量已保留。</p><div class="actions">'+button('繼續對戰','unpause')+button('角色招式','moves')+button('操作設定','settings')+button('保存並返回選角','leave')+'</div>');}
function moves(){const c=BY_ID[match?.fighters[0].id||selection.p1];dialog(c.name+' · 招式表','<div class="moves"><p><strong>輕攻 → 重攻 → 技能</strong><br>命中後可接續，無須輸入複雜指令。<br>輕重同按：近距離投技<br>方向快速連按：衝刺</p><p><strong>'+c.skill+'</strong><br>'+c.tip+'<br><strong>'+c.superName+'</strong><br>必殺需 100 能量。</p><p>站立格擋：中段、跳攻<br>蹲下格擋：中段、下段<br>投技無法格擋；距離太遠會打空。</p><p>攻擊分為起手、有效、收招。<br>收招時可以被對手反擊。<br>連續五段後倒地，起身有短暫保護。</p></div><div class="actions">'+button(page==='battle'?'繼續對戰':'完成',page==='battle'?'unpause':'close')+'</div>');}
function help(){dialog('心光對決 · 遊戲說明','<div class="moves"><p>三回合兩勝制，每回合 60 秒。<br>十位角色各有專屬技能與必殺。<br>故事五場、自由、訓練、生存與雙人。</p><p>1P：A D 移動、S 蹲下、空白跳躍<br>J 輕攻、K 重攻、L 技能<br>I 格擋、U 必殺</p><p>2P：方向鍵移動與跳躍<br>數字鍵盤 1 輕攻、2 重攻、3 技能<br>0 格擋、5 必殺</p><p>手把：左搖桿移動、方向上跳躍<br>A / B / X / Y：輕攻 / 重攻 / 技能 / 跳<br>左肩格擋、右肩必殺、Start 暫停</p></div><p class="notice">手機可同時操作方向桿與攻擊鍵。所有畫面固定橫向。</p><div class="actions">'+button('角色招式','moves')+button('完成','close')+'</div>');}
function settings(){const p=prefs();dialog('操作與畫面設定','<div class="settings-grid"><label>畫質<select data-setting="quality">'+[['auto','自動'],['high','高畫質'],['low','效能模式']].map(([v,t])=>'<option value="'+v+'" '+(p.quality===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label>'+[['musicVolume','音樂音量',0,1,.05],['soundVolume','音效音量',0,1,.05],['buttonSize','按鈕大小',.8,1.15,.05],['opacity','按鈕透明度',.45,1,.05],['offsetX','向內位移',0,36,2],['offsetY','向上位移',0,24,2]].map(([key,title,min,max,inc])=>'<label>'+title+'<input type="range" data-setting="'+key+'" min="'+min+'" max="'+max+'" step="'+inc+'" value="'+p[key]+'"></label>').join('')+[['sound','音效'],['music','音樂'],['reducedMotion','減少震動'],['showFps','顯示 FPS'],['hitboxes','顯示判定框']].map(([key,title])=>'<label>'+title+'<input type="checkbox" data-setting="'+key+'" '+(p[key]?'checked':'')+'></label>').join('')+'</div><div class="actions">'+button('更換鍵盤按鍵','keys')+button('匯出備份','export')+button('匯入備份','import')+button(page==='battle'?'繼續對戰':'完成',page==='battle'?'unpause':'close')+'</div><input id="import-file" type="file" accept=".json,application/json" hidden>');}
function keySettings(){const p=prefs();dialog('鍵盤配置','<p class="notice" id="binding-note">點選要更換的鍵位，再按新按鍵。</p><div class="keys">'+['p1','p2'].flatMap((group,i)=>Object.keys(CONTROLS[group]).map(key=>button((i+1)+'P '+ACTION_NAMES[key]+' · '+esc(p.keys[group][key].replace('Key','')),'bind','data-group="'+group+'" data-key="'+key+'"'))).join('')+'</div><div class="actions">'+button('回到設定','settings')+button(page==='battle'?'繼續對戰':'完成',page==='battle'?'unpause':'close')+'</div>');}
function training(){dialog('訓練道場','<p class="notice">下＋技能上挑 · 下＋重攻低掃 · 空中攻擊 · 兩段後重攻終結。角色連段依所選角色示範。</p><div class="training-actions">'+[['light','輕攻示範'],['heavy','重攻示範'],['skill','技能示範'],['super','必殺示範'],['throw','投技示範'],['combo','角色連段'],['launcher','上挑示範'],['sweep','低掃示範'],['air','空中攻擊'],['finisher','終結技示範']].map(([k,t])=>button(t,'demo','data-move="'+k+'"')).join('')+button('近距離重置','reset-training','data-distance="close"')+button('遠距離重置','reset-training','data-distance="far"')+button(prefs().hitboxes?'關閉判定框':'顯示判定框','hitboxes')+'</div><div class="actions">'+[['stand','木樁'],['guard','格擋'],['counter','反擊練習']].map(([k,t])=>button((match.dummy===k?'◆ ':'')+t,'dummy','data-dummy="'+k+'"')).join('')+button('繼續練習','unpause')+'</div>');}
function hud(){if(page!=='battle'||!match)return;for(let i=0;i<2;i++){const f=match.fighters[i];const life=barGeometry('life',i),energy=barGeometry('energy',i),ratio=f.hp/f.maxHp;$('#life-'+i).style.width=(life.w*ratio)+'px';$('#energy-'+i).style.width=(energy.w*f.meter/100)+'px';if(i===1){$('#life-'+i).style.left=(life.x+life.w*(1-ratio))+'px';$('#energy-'+i).style.left=(energy.x+energy.w*(1-f.meter/100))+'px';}$('#health-'+i).textContent=Math.ceil(f.hp)+' / '+f.maxHp;$('#guard-'+i).textContent='格擋 '+Math.ceil(f.guard)+(f.shield>0?' · 護盾 '+Math.ceil(f.shield):'');$('#meter-'+i).textContent=f.meter>=100?'SUPER READY':Math.floor(f.meter)+' / 100';$('#wins-'+i).textContent='勝利 '+match.wins[i]+' / '+match.target;}
 $('#clock').textContent=match.mode==='training'?'∞':Math.ceil(match.time);$('#round-label').textContent='ROUND '+match.round;$('#fps').textContent=prefs().showFps?fps+' FPS'+(paint.low?' · 效能模式':''):'';const f=match.fighters[0];screen.querySelector('[data-control="skill"]').classList.toggle('cooldown',f.cooldown>0);screen.querySelector('[data-control="super"]').classList.toggle('cooldown',f.meter<100);const hint=performance.now()<messageUntil?message:match.mode==='training'?match.training.last+' · 傷害 '+match.training.damage+' · 最大 '+match.training.maxCombo+' 段':'輕攻 → 重攻 → 技能 · 輕重同按投技 · 快速連按方向衝刺';$('#battle-hint').textContent=hint;
 const announce=$('#announcement'),line=$('#intro-line');announce.hidden=true;line.textContent='';if(match.phase==='intro'){announce.src=asset(match.intro>.65?ART.ready:ART.fight);announce.hidden=false;line.textContent=LINES[f.id][0];}else if(match.phase==='round'){announce.src=asset(ART.ko);announce.hidden=false;line.textContent=match.result.winner<0?'平手 · 加賽回合':BY_ID[match.fighters[match.result.winner].id].name+' 拿下本回合';}fitUi(screen);}
function menuKey(code){if(remapping||!loaded)return;if(orientationBlocked())return;if(code==='Escape'){if(page==='battle')modal.hidden?showPause():unpause();else if(!modal.hidden)close();else if(page==='home')return;else{page='home';render();}return;}if(!modal.hidden){if(code==='Enter')modal.querySelector('[data-action="unpause"],[data-action="close"]')?.click();return;}if(page==='select'){const key=selection.cursor?'p2':'p1',index=CAST.findIndex(c=>c.id===selection[key]);const delta={ArrowLeft:-1,KeyA:-1,ArrowRight:1,KeyD:1,ArrowUp:-5,ArrowDown:5}[code];if(delta!==undefined){selection[key]=CAST[(index+delta+10)%10].id;render();}if(code==='Enter')confirmSelection();}else if(page==='home'){if(code==='ArrowDown')menuIndex=(menuIndex+1)%5;if(code==='ArrowUp')menuIndex=(menuIndex+4)%5;if(code==='Enter')mode(MODES[menuIndex][0]);screen.querySelectorAll('[data-action="mode"]')[menuIndex]?.focus();}else if(page==='setup'&&code==='Enter')begin();else if(page==='result'&&code==='Enter')action(result.continue?'continue':'retry');}
function warmAssets(files){void paint.group(files).catch(()=>{});}
async function mode(id){if(!loaded)return;const prepareAt=performance.now();loaded=false;$('#loading').hidden=false;try{await paint.group(SELECT_ASSETS,(n,total,status)=>$('#load-status').textContent=status||'準備選角 '+n+' / '+total);cabinet.dataset.selectionReadyMs=Math.round(performance.now()-prepareAt);selection.mode=id;selection.cursor=0;page='select';render();warmAssets(Object.values(ART));warmAssets([STAGES.find(s=>s.id===selection.stage).art]);}catch(e){dialog('選角素材載入失敗','<p class="notice error">'+esc(e.message)+'</p><div class="actions">'+button('完成','close')+'</div>');}finally{loaded=true;$('#loading').hidden=true;}}
function confirmSelection(){warmAssets(Object.values(BY_ID[selection.p1].poses));if(['story','survival'].includes(selection.mode)){selection.p2=journeyOptions(makeJourney(selection.mode,selection.p1,selection.difficulty,selection.stage)).p2;page='setup';render();warmAssets(Object.values(BY_ID[selection.p2].poses));}else if(selection.cursor===0){selection.cursor=1;render();}else{page='setup';render();warmAssets(Object.values(BY_ID[selection.p2].poses));}}
function unpause(){if(orientationBlocked())return;close();input.reset();paused=false;accumulator=0;syncAudio();}
async function action(a,el={dataset:{}}){const d=el.dataset;
 if(a==='mode')mode(d.mode);else if(a==='pick'){selection[selection.cursor?'p2':'p1']=d.id;render();}else if(a==='cursor'){selection.cursor=Number(d.player);render();}else if(a==='confirm')confirmSelection();
 else if(a==='home'){capture();input.reset();page='home';paused=false;match=null;run=null;render();syncAudio();}else if(a==='select'||a==='leave'){capture();input.reset();page='select';selection.cursor=0;paused=false;render();}
 else if(a==='stage'){selection.stage=d.stage;render();warmAssets([STAGES.find(s=>s.id===selection.stage).art]);}else if(a==='difficulty'){selection.difficulty=d.difficulty;render();}else if(a==='start')begin();
 else if(a==='resume'){try{const s=db.get();run=s.run?structuredClone(s.run):null;start({mode:s.active.mode,p1:s.active.fighters[0].id,p2:s.active.fighters[1].id,stage:s.active.stage,difficulty:s.active.difficulty},restore(s.active));}catch(e){dialog('接續失敗','<p class="notice error">'+esc(e.message)+'</p><div class="actions">'+button('完成','close')+'</div>');}}
 else if(a==='pause')showPause();else if(a==='unpause')unpause();else if(a==='close')close();else if(a==='settings')settings();else if(a==='keys')keySettings();else if(a==='moves')moves();else if(a==='help')help();
 else if(a==='training')training();else if(a==='demo'){demonstration(match,d.move);unpause();}else if(a==='reset-training'){resetTraining(match,d.distance);unpause();}else if(a==='dummy'){match.dummy=d.dummy;training();}else if(a==='hitboxes'){prefs().hitboxes=!prefs().hitboxes;db.save();training();}
 else if(a==='next-round'){close();nextRound(match);roundHandled=false;paused=false;input.reset();capture();}
 else if(a==='match-result'){close();finish();}
 else if(a==='continue'){if(run)start(journeyOptions(run));}else if(a==='retry')begin();
 else if(a==='fullscreen'){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape').catch(()=>{});}catch{notify('此瀏覽器不支援全螢幕，可直接橫向遊玩');}}
 else if(a==='exit'){capture();location.href='../../../?view=game-hub&v='+VERSION;}
 else if(a==='bind'){remapping=true;$('#binding-note').textContent='請按新的 '+ACTION_NAMES[d.key]+' 按鍵…';input.bind=code=>{remapping=false;if(['Escape','Tab','MetaLeft','MetaRight'].includes(code)||['p1','p2'].some(g=>Object.entries(prefs().keys[g]).some(([key,v])=>v===code&&(g!==d.group||key!==d.key)))){$('#binding-note').textContent='此按鍵已被使用或保留，請重新選擇。';return;}prefs().keys[d.group][d.key]=code;db.save();keySettings();};}
 else if(a==='export'){capture();dialog('匯出備份','<p class="notice">下載 JSON 檔案，或長按下方文字全選複製保存。</p><textarea class="backup-text" aria-label="備份內容" readonly>'+esc(db.damaged()||db.export())+'</textarea><div class="actions">'+button('下載 JSON','download-backup')+button('回到設定','settings')+'</div>');}
 else if(a==='download-backup'){const blob=new Blob([$('#modal textarea').value],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='CxQ-心光對決-備份.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 else if(a==='import'){dialog('匯入備份','<p class="notice">選取 JSON 檔案，或貼上完整備份內容。</p><textarea class="backup-text" aria-label="貼上備份內容" placeholder="貼上完整 JSON 備份"></textarea><div class="actions">'+button('選取檔案','choose-backup')+button('還原貼上的備份','restore-backup')+button('回到設定','settings')+'</div><input id="import-file" type="file" accept=".json,application/json" hidden>');}
 else if(a==='choose-backup')$('#import-file').click();else if(a==='restore-backup')importBackup($('#modal textarea').value);}
function importBackup(raw){try{db.replace(raw);match=null;run=null;page='home';paused=false;input.reset();preferences();render();dialog('備份匯入完成','<p class="notice">角色故事、設定與對戰進度已還原。</p><div class="actions">'+button('完成','close')+'</div>');}catch(error){dialog('備份無法匯入','<p class="notice error">'+esc(error.message)+'</p><div class="actions">'+button('回到匯入','import')+button('完成','close')+'</div>');}}
screen.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el.dataset.action,el);});modal.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el.dataset.action,el);});
modal.addEventListener('change',async e=>{const el=e.target;if(el.dataset.setting){const key=el.dataset.setting;prefs()[key]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;db.save();preferences();}if(el.id==='import-file'&&el.files[0])importBackup(await el.files[0].text());});
function syncAudio(){audioV2.configure({...prefs(),music:prefs().music&&!paused},page,match?.stage||selection.stage);}
function sound(type,event={}){audioV2.play(type,{character:match?.fighters[event.fighter]?.id,key:event.key,side:event.fighter||0});}
for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{audioUnlocked=true;audioV2.unlock();syncAudio();},{once:true});
function frame(t){const elapsed=Math.min(.1,(t-frameTime)/1000);frameTime=t;input.poll();if(loaded){if(page==='battle'&&match){if(!paused&&!orientationBlocked()&&!document.hidden){accumulator+=elapsed;let n=0;while(accumulator>=DT&&n++<8){step(match);accumulator-=DT;}if(n>=8)accumulator=0;}else accumulator=0;paint.draw(match);for(const e of match.events){if(e.id<=eventCursor)continue;eventCursor=e.id;if(['hit','block','super','counter','jump','dash','throw','shield','break','fight'].includes(e.type))sound(e.type,e);if(e.type==='attack'){sound('swing',e);if(e.key==='skill')sound('skill',e);}if(e.type==='reject')notify(e.why);if(e.type==='break')notify('格擋崩解！');}if(t-hudAt>66){hud();hudAt=t;}if(match.phase==='round'&&!roundHandled&&!orientationBlocked()){roundHandled=true;paused=true;capture();setTimeout(()=>{if(page!=='battle'||match.phase!=='round')return;dialog(match.result.winner<0?'本回合平手':BY_ID[match.fighters[match.result.winner].id].name+' 拿下本回合','<p class="notice">'+match.wins.join(' : ')+' · '+(match.result.reason==='TIME'?'時間到':'K.O.')+'</p><div class="actions">'+button(match.result.matchOver?'查看戰績':'下一回合',match.result.matchOver?'match-result':'next-round')+'</div>');},900);}if(t-saveAt>10000){capture();saveAt=t;}}
 else if(page==='home')paint.menu(t/1000);else if(page==='select'||page==='setup')paint.showcase(selection.p1,selection.p2,t/1000);else if(page==='result')paint.result(result.hero,result.win);
 fpsFrames++;if(t-fpsAt>=1000){fps=Math.round(fpsFrames*1000/(t-fpsAt));fpsFrames=0;fpsAt=t;if(page==='battle'&&!paused&&prefs().quality==='auto'&&fps<45)lowSamples++;else lowSamples=0;if(lowSamples>=3&&!paint.low){paint.low=true;paint.resize();notify('已切換效能模式，維持操作流暢');}}}requestAnimationFrame(frame);}
cabinet.addEventListener('scroll',()=>{if(cabinet.scrollTop||cabinet.scrollLeft){cabinet.scrollTop=0;cabinet.scrollLeft=0;}},{passive:true});
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden&&page==='battle')showPause();input.reset();syncAudio();});window.addEventListener('pagehide',()=>{capture();input.reset();audioV2.pause();});
try{resize();await paint.load((n,total,status)=>$('#load-status').textContent=status||'載入選單與選角 '+n+' / '+total);loaded=true;cabinet.dataset.menuReadyMs=Math.round(performance.now());$('#loading').hidden=true;preferences();render();if(db.damaged())dialog('存檔需要檢查','<p class="notice">原始存檔已保留，請先匯出备份再重新匯入。</p><div class="actions">'+button('操作設定','settings')+button('完成','close')+'</div>');}catch(e){$('#load-status').textContent='載入失敗：'+e.message+'。請重新整理再試。';}
requestAnimationFrame(frame);
