let context,compressor,music,musicName='',unlocked=false,settings={},page='home',stage='festival';
const buffers=new Map(),voices=new Set(),last=new Map();
const ctx=()=>{if(!context){context=new(window.AudioContext||window.webkitAudioContext)();compressor=context.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=5;compressor.connect(context.destination);}return context;};
export function configure(p,nextPage,nextStage){settings=p;page=nextPage;stage=nextStage||'festival';sync();}
export async function unlock(){try{await ctx().resume();unlocked=true;sync();}catch{}}
function sync(){if(!unlocked)return;const name=page==='battle'?stage:'menu';if(name!==musicName){music?.pause();musicName=name;music=new Audio('audio-v2/music-'+name+'.mp3');music.preload='none';music.loop=true;}music.volume=Math.min(1,(settings.musicVolume??settings.volume??.35)*.65);if(settings.music&&!document.hidden)music.play().catch(()=>{});else music.pause();}
async function buffer(name){if(!buffers.has(name))buffers.set(name,fetch('audio-v2/sfx-'+name+'.mp3').then(r=>{if(!r.ok)throw Error('Audio unavailable');return r.arrayBuffer();}).then(b=>ctx().decodeAudioData(b)).catch(e=>{buffers.delete(name);throw e;}));return buffers.get(name);}
export async function play(name,{character,key,side=0}={}){if(!unlocked||!settings.sound||document.hidden||voices.size>=12)return;const now=performance.now(),gap=name==='swing'?70:35;if(now-(last.get(name)||0)<gap)return;last.set(name,now);try{const source=ctx().createBufferSource(),gain=ctx().createGain(),pan=ctx().createStereoPanner();source.buffer=await buffer(name==='hit'?(key==='heavy'||key==='finisher'?'heavy':'light'):name);if(voices.size>=12||!settings.sound||document.hidden)return;gain.gain.value=Math.min(1,settings.soundVolume??settings.volume??.65)*.65;pan.pan.value=side? .2:-.2;source.connect(gain);gain.connect(pan);pan.connect(compressor);voices.add(source);source.onended=()=>voices.delete(source);source.start();if(character&&['skill','super'].includes(name))play(character,{side});}catch{}}
export function pause(){music?.pause();for(const source of voices)try{source.stop();}catch{}voices.clear();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();else{context?.resume();sync();}});
