import {CAST as ORIGINAL,STAGES as ARENAS,ENDINGS,CONTROLS,ACTION_NAMES} from '../cast.mjs?v=arcade1';
import {POSE_METRICS} from './pose-metrics.mjs?v=arcade1';
export {ENDINGS,CONTROLS,ACTION_NAMES};
export const VERSION='20261007-arcade1';
export const ACTIONS=['walk-a','walk-b','jump','crouch','guard','hurt','down','light','heavy','super'];
const speeds={joy:400,dream:355,night:365,sadness:350,trust:325,memory:375,growth:385,healing:345,luck:425,hope:365};
export const CAST=ORIGINAL.map(c=>({...c,speed:speeds[c.id],portrait:`../../../assets/characters/cxq-role-${c.id}.webp`,height:c.id==='joy'||c.id==='sadness'?305:280,poses:{idle:`../../fairytale-defense/rebuild/art/${c.id}-ready.webp`,skill:`../../fairytale-defense/rebuild/art/${c.id}-cast.webp`,victory:`../../fairytale-defense/rebuild/art/${c.id}-victory.webp`,...Object.fromEntries(ACTIONS.map(a=>[a,`art/${c.id}-${a}.webp`]))}}));
export const BY_ID=Object.fromEntries(CAST.map(c=>[c.id,c]));
for(const c of CAST)c.poseMetrics=POSE_METRICS[c.id]||{};
export const STAGES=ARENAS.map(s=>({...s,art:'../'+s.art}));
export const MODES=[['story','故事闖關','五場旅程・專屬結局'],['free','自由對戰','自由選角・三種難度'],['training','訓練道場','招式示範・命中練習'],['survival','生存挑戰','保留生命・連勝挑戰'],['local','雙人對戰','兩組鍵盤・兩支手把']];
export const LINES={joy:['今天也一起打出漂亮的節奏！','把這份笑容帶回小鎮吧。'],dream:['星願會替我找到前進的方向。','下一封星願信，寫給勇敢的你。'],night:['別怕，我會陪你到最後。','月燈會為每位旅人留著光。'],sadness:['下雨也沒關係，我準備好了。','謝謝你，陪我走過這場雨。'],trust:['這份約定，我會好好守住。','勝負過後，我們仍然是夥伴。'],memory:['今天的每個瞬間，都值得收藏。','這張合照，一定要留下來。'],growth:['每一次練習，都會讓我更靠近。','把今天的經驗，種成下一株新芽。'],healing:['認真比賽，也要好好照顧自己。','先坐下來，喝一杯暖暖的茶吧。'],luck:['四葉鈴響了，輪到我出招！','好運，也來自一路的練習。'],hope:['讓我們把心光織在一起。','十種心光，都能照亮明天。']};
export function makeJourney(mode,hero,difficulty='normal',stage='festival'){const ids=CAST.filter(c=>c.id!==hero).map(c=>c.id),offset=CAST.findIndex(c=>c.id===hero);return{mode,hero,difficulty,stage,index:0,wins:0,health:null,opponents:Array.from({length:5},(_,i)=>ids[(offset+i*2)%ids.length])};}
export function journeyOptions(run){return{mode:run.mode,p1:run.hero,p2:run.mode==='story'?run.opponents[run.index]:CAST.filter(c=>c.id!==run.hero)[run.index%9].id,stage:STAGES[(Math.max(0,STAGES.findIndex(s=>s.id===run.stage))+run.index)%4].id,difficulty:run.mode==='survival'&&run.index>=5?'hard':run.difficulty};}
export function advanceJourney(run,win,hp){if(!win)return{continue:false,ending:false,cleared:run.index};run.wins++;if(run.mode==='story'){const cleared=run.index+1,ending=cleared===5;if(!ending)run.index++;return{continue:!ending,ending,cleared};}run.health=Math.min(BY_ID[run.hero].hp,Math.max(1,hp)+120);run.index++;return{continue:true,ending:false,cleared:run.wins};}
export const ART={menu:'art/menu-backdrop.webp',select:'art/select-backdrop.webp',logo:'art/title-logo.webp',card:'art/portrait-frame.webp',button:'art/menu-button.webp',life:'art/life-frame.webp',lifeFill:'art/life-fill.webp',energy:'art/energy-frame.webp',energyFill:'art/energy-fill.webp',stick:'art/control-stick.webp',knob:'art/control-knob.webp',hit:'art/fx-hit.webp',block:'art/fx-block.webp',projectile:'art/fx-projectile.webp',ready:'art/text-ready.webp',fight:'art/text-fight.webp',ko:'art/text-ko.webp',win:'art/text-win.webp',lose:'art/text-lose.webp',panel:'art/panel-frame.webp',...Object.fromEntries(['light','heavy','skill','jump','guard','super'].map(k=>['control-'+k,`art/control-${k}.webp`]))};
