import {BY_ID,STAGES} from './cast.mjs?v=20261008-complete1';
export const WIDTH=1280,HEIGHT=720,FLOOR=546,DT=1/60;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const finite=(n,a=0,b=1e8)=>Number.isFinite(n)&&n>=a&&n<=b;
export function random(seed){let state=seed>>>0;const rng=()=>((state=(Math.imul(state,1664525)+1013904223)>>>0)/4294967296);rng.state=()=>state;return rng;}
function makeFighter(id,index){const c=BY_ID[id];if(!c)throw Error('角色不存在');return{id,index,x:index?800:480,y:FLOOR,vx:0,vy:0,facing:index?-1:1,hp:c.hp,maxHp:c.hp,meter:0,guard:100,shield:0,shieldTime:0,recoverable:0,healUses:0,action:null,buffer:null,stun:0,blockStun:0,knock:0,rising:0,invuln:0,cooldown:0,slow:0,combo:0,comboTime:0,held:{},dash:0,lastTap:{},hits:0,blocked:0,damage:0,lastMove:'',poseTime:0};}
export function createMatch(options={}){const mode=options.mode||'free';return{version:2,mode,stage:options.stage||'festival',difficulty:options.difficulty||'normal',options:{...options},fighters:[makeFighter(options.p1||'growth',0),makeFighter(options.p2||'luck',1)],time:60,clock:0,phase:'intro',intro:2.4,round:1,wins:[0,0],target:mode==='survival'?1:2,projectiles:[],zones:[],events:[],nextId:0,hitstop:0,flash:0,rng:random(options.seed??Date.now()),aiWait:1,aiAttackWait:1,aiIntent:'approach',roundEnded:false,result:null,dummy:options.dummy||'stand',bestCombo:[0,0],totalDamage:[0,0],training:{damage:0,maxCombo:0,hits:0,blocks:0,misses:0,last:'向前接近對手，再按輕攻擊',lastBox:null},demo:null};}
function emit(m,type,data={}){m.events.push({id:++m.nextId,at:m.clock,type,...data});if(m.events.length>100)m.events.splice(0,m.events.length-100);}
export function setHeld(m,i,key,value){if(m.fighters[i])m.fighters[i].held[key]=!!value;}
export function clearInputs(m){for(const f of m.fighters){f.held={};f.buffer=null;f.dash=0;if(!f.action&&!f.stun)f.vx=0;}}
export function hurtBox(f){if(f.knock>0)return{x:f.x-92,y:f.y-88,w:184,h:88};const low=(f.held.down||f.rising>0||f.action?.height==='low')&&f.y===FLOOR,h=low?126:214;return{x:f.x-56,y:f.y-h,w:112,h};}
export function pushBox(f){return{x:f.x-47,y:f.y-130,w:94,h:130};}
const overlaps=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
export function moveSpec(f,key){const air=f.y<FLOOR-12,low=!!f.held.down&&!air;let a={key,start:.10,active:.19,end:.17,damage:62,reach:156,top:174,boxHeight:128,stun:.36,knock:12,height:air?'overhead':low?'low':'mid',air,armor:false};
 if(key==='heavy')Object.assign(a,{start:.24,active:.23,end:.30,damage:116,reach:206,top:190,boxHeight:154,stun:.48,knock:35});
 if(key==='throw')Object.assign(a,{start:.10,active:.14,end:.35,damage:138,reach:105,top:190,boxHeight:185,stun:.68,knock:65,height:'throw'});
 if(key==='skill')Object.assign(a,{start:.21,active:.27,end:.30,damage:114,reach:196,top:218,boxHeight:186,stun:.45,knock:32});
 if(key==='super')Object.assign(a,{start:.32,active:.42,end:.54,damage:285,reach:268,top:240,boxHeight:226,stun:.8,knock:78});
 if(key==='launcher')Object.assign(a,{start:.16,active:.20,end:.24,damage:88,reach:158,top:282,boxHeight:255,stun:.58,knock:8,launch:true});
 if(key==='sweep')Object.assign(a,{start:.15,active:.22,end:.26,damage:82,reach:193,top:103,boxHeight:97,stun:.40,knock:22,height:'low'});
 if(key==='air')Object.assign(a,{start:.10,active:.24,end:.17,damage:92,reach:180,top:140,boxHeight:148,stun:.48,knock:12,height:'overhead',air:true});
 if(key==='finisher')Object.assign(a,{start:.20,active:.25,end:.38,damage:157,reach:215,top:205,boxHeight:180,stun:.68,knock:65});
 if(key==='launcher'&&['joy','luck'].includes(f.id))a.start*=.8;
 if(key==='sweep'&&['night','healing'].includes(f.id))a.reach+=25;
 if(key==='finisher'&&f.id==='trust'){a.armor=true;a.damage=184;a.start=.28;}
 if(key==='finisher'&&f.id==='memory'){a.echo=true;a.damage=120;}
 if(key==='air'&&['dream','hope'].includes(f.id)){a.reach+=35;a.damage=85;}
 if(low&&key==='light'){a.top=100;a.boxHeight=90;}if(low&&key==='heavy'){a.height='low';a.top=130;a.boxHeight=120;}
 if(air){a.top=125;a.boxHeight=130;a.reach+=22;}
 if(f.id==='trust'){a.damage*=1.08;a.start+=.035;a.reach+=16;}if(f.id==='joy')a.start*=.84;if(f.id==='luck')a.start*=.86;if(['growth','hope','sadness'].includes(f.id))a.reach+=20;
 if(key==='skill')switch(f.id){case'joy':a.rush=430;break;case'dream':Object.assign(a,{projectile:true,damage:96});break;case'night':Object.assign(a,{counter:true,start:0,active:.55,end:.22});break;case'sadness':Object.assign(a,{zone:'rain',damage:85});break;case'trust':Object.assign(a,{armor:true,start:.38,damage:164,reach:224});break;case'memory':Object.assign(a,{echo:true,damage:78});break;case'growth':Object.assign(a,{antiAir:true,top:320,boxHeight:300,damage:123});break;case'healing':Object.assign(a,{shield:true,damage:0});break;case'luck':Object.assign(a,{rush:610,height:'low',start:.12,top:126,boxHeight:115,damage:102});break;case'hope':Object.assign(a,{zone:'light',damage:98});}
 if(key==='super'){if(['dream','hope'].includes(f.id))a.projectile=true;if(f.id==='sadness')a.zone='rain';if(['joy','luck'].includes(f.id))a.rush=540;if(f.id==='night')a.reach=330;if(f.id==='trust')a.armor=true;if(f.id==='memory')a.echo=true;if(f.id==='growth')Object.assign(a,{antiAir:true,top:360,boxHeight:335});if(f.id==='healing')Object.assign(a,{height:'throw',reach:148});}
 if(key!=='throw'&&!a.projectile&&!a.zone&&!a.counter&&!a.shield){const metric=BY_ID[f.id].poseMetrics[key];if(metric){a.reach=Math.max(110,metric.forward*(low?.72:1)-22);if(key==='skill'&&a.antiAir)a.reach=Math.max(a.reach,130);}}
 return a;
}
export function attackBox(f){const a=f.action;if(!a||a.t<a.start||a.t>a.start+a.active||a.projectile||a.zone||a.counter||a.shield)return null;const p=clamp((a.t-a.start)/a.active,0,1),reach=a.reach*(.88+.12*Math.sin(p*Math.PI));return{x:f.facing===1?f.x+22:f.x-22-reach,y:f.y-a.top,w:reach,h:a.boxHeight};}
function rejection(m,f,key,why){if(f.index===0||m.mode==='local')emit(m,'reject',{fighter:f.index,key,why});return false;}
function begin(m,f,key){if(f.y<FLOOR-12&&['throw','skill','super'].includes(key))return rejection(m,f,key,'落地後才能施放');if(key==='skill'&&f.cooldown>0)return rejection(m,f,key,'技能準備中');if(key==='air'&&f.y>=FLOOR-12)return rejection(m,f,key,'跳躍後使用空中攻擊');if(key==='super'&&f.meter<100)return rejection(m,f,key,'必殺能量尚未滿');if(key==='super'){f.meter=0;m.flash=.18;emit(m,'super',{fighter:f.index,name:BY_ID[f.id].superName});}if(key==='skill')f.cooldown=f.id==='healing'?4:2.2;f.facing=m.fighters[1-f.index].x>=f.x?1:-1;f.action={...moveSpec(f,key),t:0,hit:false,fired:false};f.lastMove=key;f.dash=0;f.vx*=.25;emit(m,'attack',{fighter:f.index,key});return true;}
export function command(m,i,key){const f=m.fighters[i];if(!f||m.phase!=='fight')return false;if(['dashLeft','dashRight'].includes(key)){if(f.stun||f.blockStun||f.knock||f.action||f.y<FLOOR)return false;f.dash=.18;f.vx=(key==='dashLeft'?-1:1)*BY_ID[f.id].speed*2.25;emit(m,'dash',{fighter:i});return true;}if(key==='jump'){if(f.action?.key==='launcher'&&f.action.hit&&f.action.t>=f.action.start+.07){f.action=null;f.vy=-820;f.held.down=false;emit(m,'jump',{fighter:i});return true;}if(f.stun||f.blockStun||f.knock||f.action||f.y<FLOOR)return false;f.vy=-880;f.held.down=false;emit(m,'jump',{fighter:i});return true;}if(!['light','heavy','skill','super','throw','launcher','sweep','air','finisher'].includes(key))return false;
 if(key==='throw'&&f.action&&['light','heavy'].includes(f.action.key)&&f.action.t<.10&&!f.action.fired){f.action=null;return begin(m,f,key);}
 if(key==='super'&&f.meter<100)return rejection(m,f,key,'必殺能量尚未滿');if(key==='skill'&&f.cooldown>0)return rejection(m,f,key,'技能準備中');
 const cancel=f.action?.hit&&f.action.t>=f.action.start+.07&&((f.action.key==='light'&&['heavy','skill','super','launcher','sweep','finisher'].includes(key))||(['heavy','sweep','launcher','air'].includes(f.action.key)&&['skill','super','launcher','finisher'].includes(key)));
 if(cancel){f.action=null;return begin(m,f,key);}if(f.stun||f.blockStun||f.knock||f.action){f.buffer={key,until:m.clock+.32};return false;}return begin(m,f,key);
}
function addDamage(m,attacker,target,s){if(target.invuln>0||target.knock>0||target.rising>0||target.hp<=0)return false;const front=(attacker.x-target.x)*target.facing>=-2,ground=target.y>=FLOOR-1,counter=target.action?.counter&&target.action.t<=target.action.active;
 if(counter&&s.height!=='throw'){target.action=null;target.invuln=.25;const counterMove={key:'counter',damage:125,stun:.45,knock:36,height:'throw'};return addDamage(m,target,attacker,counterMove);}
 const blocked=front&&ground&&target.held.guard&&!target.stun&&!target.knock&&!target.action&&s.height!=='throw'&&(s.height==='mid'||s.height==='projectile'||s.height==='low'&&target.held.down||s.height==='overhead'&&!target.held.down);
 if(blocked){const cost=s.key==='super'?45:s.key==='heavy'?25:12;target.guard=Math.max(0,target.guard-cost);target.blockStun=.12;target.vx=attacker.facing*45;target.blocked++;target.meter=clamp(target.meter+7,0,100);attacker.meter=clamp(attacker.meter+4,0,100);if(s.key==='super')target.hp=Math.max(1,target.hp-15);if(attacker.index===0){m.training.blocks++;m.training.last='已被格擋：近距離輕重同按可使用投技';}emit(m,'block',{fighter:target.index,x:target.x,y:target.y-145});m.hitstop=.04;if(target.guard<=0){target.stun=.8;target.blockStun=0;target.guard=25;emit(m,'break',{fighter:target.index});}return true;}
 const scale=Math.max(.42,1-attacker.combo*.13),armor=!!target.action?.armor;let amount=Math.round(s.damage*scale*(armor?.65:1));const absorbed=Math.min(target.shield,amount);target.shield-=absorbed;amount-=absorbed;const actual=Math.min(target.hp,amount);target.hp-=actual;target.recoverable=clamp(target.recoverable+actual*.55,0,target.maxHp-target.hp);attacker.damage+=actual;m.totalDamage[attacker.index]+=actual;attacker.hits++;attacker.combo++;attacker.comboTime=s.stun+.045;const combo=attacker.combo;m.bestCombo[attacker.index]=Math.max(m.bestCombo[attacker.index],combo);attacker.meter=clamp(attacker.meter+10+actual*.035,0,100);target.meter=clamp(target.meter+actual*.045,0,100);
 if(!armor){target.action=null;target.buffer=null;target.stun=s.stun;target.blockStun=0;target.vx=attacker.facing*(s.knock||15)*4;if(s.stun>=.6)target.knock=.6;}
 if(s.launch&&!armor&&combo<5){target.vy=-620;target.knock=0;target.stun=Math.max(target.stun,.58);}
 if(combo>=5){target.stun=.5;target.knock=.5;target.invuln=.55;target.vx=attacker.facing*220;attacker.combo=0;attacker.comboTime=0;}
 if(s.slow)target.slow=1.2;if(attacker.index===0){m.training.damage+=actual;m.training.hits++;m.training.maxCombo=Math.max(m.training.maxCombo,combo);m.training.last=`命中 ${actual} · ${combo} 段${armor?' · 對手護甲':''}`;}
 m.hitstop=s.key==='super'?.11:s.key==='heavy'?.075:.05;emit(m,s.key==='counter'?'counter':actual?'hit':'shield',{fighter:attacker.index,target:target.index,damage:actual,combo,x:target.x,y:target.y-145,key:s.key});return true;
}
function fire(m,f,a){a.fired=true;const big=a.key==='super';if(a.shield){f.shield=Math.min(150,f.shield+90);f.shieldTime=3;if(f.healUses<2&&f.recoverable>0){const amount=Math.min(55,f.recoverable,f.maxHp-f.hp);f.hp+=amount;f.recoverable-=amount;f.healUses++;emit(m,'heal',{fighter:f.index,damage:amount,x:f.x,y:f.y-160});}if(f.index===0)m.training.last='暖心披肩：護盾 '+Math.round(f.shield)+' · 每回合最多兩次回復近期受傷';emit(m,'shield',{fighter:f.index,x:f.x,y:f.y-145});return;}
 if(a.projectile){m.projectiles.push({id:++m.nextId,owner:f.index,x:f.x+f.facing*80,y:f.y-122,vx:f.facing*(big?790:590),life:2.5,radius:big?42:25,spec:{...a,height:'projectile'}});return;}
 if(a.zone)m.zones.push({id:++m.nextId,owner:f.index,x:clamp(f.x+f.facing*(big?210:170),70,WIDTH-70),delay:big?.18:.28,life:.6,radius:big?210:125,hit:false,spec:{...a,height:'mid',slow:a.zone==='rain'}});
 if(a.echo)m.zones.push({id:++m.nextId,owner:f.index,x:clamp(f.x+f.facing*140,60,WIDTH-60),delay:.4,life:.4,radius:big?180:120,hit:false,spec:{...a,damage:big?85:58,height:'mid'}});
}
function tick(m,f,dt){const c=BY_ID[f.id],other=m.fighters[1-f.index],wasDown=f.knock>0;f.poseTime+=dt;for(const key of ['stun','blockStun','knock','rising','invuln','cooldown','slow','comboTime','dash','shieldTime'])f[key]=Math.max(0,f[key]-dt);if(wasDown&&!f.knock){f.rising=.20;f.invuln=Math.max(.28,f.invuln);}if(!f.shieldTime)f.shield=0;if(!f.comboTime)f.combo=0;if(!f.held.guard&&!f.stun&&!f.blockStun)f.guard=clamp(f.guard+16*dt,0,100);if(f.buffer?.until<m.clock)f.buffer=null;
 if(f.buffer&&!f.stun&&!f.knock&&!f.blockStun){const cancel=f.action?.hit&&f.action.t>=f.action.start+.07&&((f.action.key==='light'&&['heavy','skill','super','launcher','sweep','finisher'].includes(f.buffer.key))||(['heavy','sweep','launcher','air'].includes(f.action.key)&&['skill','super','launcher','finisher'].includes(f.buffer.key)));if(!f.action||cancel){const b=f.buffer;f.buffer=null;f.action=null;begin(m,f,b.key);}}
 if(!f.action&&!f.stun&&!f.blockStun&&!f.knock&&!f.rising){const direction=(f.held.right?1:0)-(f.held.left?1:0);if(!f.dash){const speed=c.speed*(f.slow?.62:1)*(f.y<FLOOR?.72:1);f.vx=f.held.guard||f.held.down?0:direction*speed;}f.facing=other.x>=f.x?1:-1;}
 if(f.action){const a=f.action;a.t+=dt;if(a.rush&&a.t>=a.start&&a.t<a.start+a.active&&!a.hit)f.vx=f.facing*a.rush;else if(f.y>=FLOOR)f.vx*=Math.exp(-dt*18);if(!a.fired&&a.t>=a.start)fire(m,f,a);const box=attackBox(f);if(box&&!a.hit&&overlaps(box,hurtBox(other))&&!(a.height==='throw'&&other.y<FLOOR-8)){a.hit=addDamage(m,f,other,a);m.training.lastBox=box;}if(a.t>=a.start+a.active+a.end){if(!a.hit&&!a.projectile&&!a.zone&&!a.shield&&!a.counter&&f.index===0){m.training.misses++;m.training.last='打空：向前接近，或選擇較長距離的招式';emit(m,'miss',{fighter:0,key:a.key});}if(f.action===a)f.action=null;}}
 f.x=clamp(f.x+f.vx*dt,64,WIDTH-64);if(f.stun||f.knock||f.blockStun)f.vx*=Math.exp(-dt*10);f.vy+=2400*dt;f.y=Math.min(FLOOR,f.y+f.vy*dt);if(f.y===FLOOR)f.vy=0;
}
function ai(m,dt){if(m.mode==='local'||m.demo)return;const f=m.fighters[1],p=m.fighters[0];if(m.mode==='training'){f.held={guard:m.dummy==='guard',down:m.dummy==='guard'&&p.action?.height==='low'};if(m.dummy!=='counter')return;}m.aiWait-=dt;m.aiAttackWait-=dt;if(m.aiWait>0)return;const d=m.difficulty==='hard'?2:m.difficulty==='easy'?0:1;m.aiWait=[.62,.38,.25][d]+m.rng()*.18;const distance=Math.abs(f.x-p.x),r=m.rng(),incoming=p.action&&p.action.t>.08&&distance<285||m.projectiles.some(b=>b.owner===0&&Math.abs(b.x-f.x)<270);f.held={};
 if(incoming&&r<[.20,.48,.67][d]){f.held.guard=true;f.held.down=p.action?.height==='low';if(f.id==='night'&&f.cooldown<=0&&r<.22)command(m,1,'skill');return;}
 if(f.stun||f.knock||f.blockStun)return;const ranged=['dream','hope','sadness'].includes(f.id),desired=ranged?320:165;if(distance>desired+35){f.held.left=p.x<f.x;f.held.right=p.x>f.x;}else if(distance<115&&r<.3){f.held.left=p.x>f.x;f.held.right=p.x<f.x;}
 if(m.aiAttackWait>0||r<[.4,.25,.1][d])return;let key=null;if(p.action&&p.action.t>p.action.start+p.action.active&&distance<260)key=r<.6?'heavy':'skill';else if(f.meter>=100&&distance<340&&r<.2)key='super';else if(f.cooldown<=0&&(distance<250||ranged)&&r<.34)key='skill';else if(distance<135&&p.held.guard&&r<.3)key='throw';else if(distance<220)key=r<.75?'light':'heavy';else if(r<.07)key='jump';if(key){command(m,1,key);m.aiAttackWait=[.92,.65,.42][d]+m.rng()*.28;}}
function endRound(m){if(m.roundEnded)return;m.roundEnded=true;const [a,b]=m.fighters,ratio=a.hp/a.maxHp-b.hp/b.maxHp,winner=Math.abs(ratio)<.0001?-1:ratio>0?0:1;if(winner>=0)m.wins[winner]++;m.phase='round';m.result={winner,reason:a.hp<=0||b.hp<=0?'KO':'TIME',matchOver:winner>=0&&m.wins[winner]>=m.target,round:m.round};m.projectiles=[];m.zones=[];for(const f of m.fighters){f.held={};f.buffer=null;f.action=null;f.vx=0;}emit(m,'round',m.result);}
export function nextRound(m){if(m.phase!=='round'||m.result.matchOver)return false;const old=m.fighters;m.fighters=old.map((f,i)=>({...makeFighter(f.id,i),meter:f.meter*.5}));m.round++;m.time=60;m.intro=2.1;m.phase='intro';m.roundEnded=false;m.result=null;m.aiWait=1;m.aiAttackWait=1;m.hitstop=0;return true;}
export function resetTraining(m,distance='close'){m.fighters=m.fighters.map((f,i)=>({...makeFighter(f.id,i),x:distance==='close'?(i?725:555):(i?850:430),meter:100}));m.projectiles=[];m.zones=[];m.hitstop=0;m.phase='fight';m.training={damage:0,maxCombo:0,hits:0,blocks:0,misses:0,last:'選擇招式開始練習',lastBox:null};m.bestCombo=[0,0];m.totalDamage=[0,0];m.demo=null;}
export function demonstration(m,key){resetTraining(m);if(key==='air'){command(m,0,'jump');m.demo={key,at:0,step:0};return true;}m.dummy='stand';if(key==='combo')m.demo={key,at:0,step:0};else{command(m,0,key);m.demo={key,at:0,step:99};}return true;}
export function step(m,dt=DT){if(!finite(dt,.00001,.05))return;m.clock+=dt;if(m.phase==='intro'){m.intro-=dt;if(m.intro<=0){m.phase='fight';emit(m,'fight',{round:m.round});}return;}if(m.phase!=='fight')return;if(m.hitstop>0){m.hitstop=Math.max(0,m.hitstop-dt);return;}if(m.mode!=='training')m.time=Math.max(0,m.time-dt);m.flash=Math.max(0,m.flash-dt);if(m.demo){m.demo.at+=dt;const f=m.fighters[0];if(m.demo.key==='skill'&&f.id==='night'&&m.demo.step===99&&m.demo.at>.18){command(m,1,'light');m.demo.step=100;}if(m.demo.key==='air'&&m.demo.step===0&&m.demo.at>.18){command(m,0,'air');m.demo.step=99;}if(m.demo.key==='combo'){
 const route=BY_ID[f.id].comboRoute,wanted=route[m.demo.step];
 if(wanted){if(m.demo.step===0||f.action?.hit||!f.action&&f.combo>0){
 if(wanted==='air'&&f.y>=FLOOR-12){command(m,0,'jump');}
 else if(command(m,0,wanted))m.demo.step++;
 }}
 }if(m.demo.at>3.5)m.demo=null;}ai(m,dt);
 for(const f of m.fighters)tick(m,f,dt);const[a,b]=m.fighters;if(overlaps(pushBox(a),pushBox(b))){const sign=a.x<=b.x?-1:1,overlap=94-Math.abs(a.x-b.x);a.x=clamp(a.x+sign*overlap/2,64,WIDTH-64);b.x=clamp(b.x-sign*overlap/2,64,WIDTH-64);if(Math.abs(a.x-b.x)<94){if(a.x===64||a.x===WIDTH-64)b.x=clamp(a.x-sign*94,64,WIDTH-64);else a.x=clamp(b.x+sign*94,64,WIDTH-64);}}
 for(const p of m.projectiles){p.x+=p.vx*dt;p.life-=dt;const target=m.fighters[1-p.owner],box={x:p.x-p.radius,y:p.y-p.radius,w:p.radius*2,h:p.radius*2};if(overlaps(box,hurtBox(target))&&addDamage(m,m.fighters[p.owner],target,p.spec))p.life=0;}m.projectiles=m.projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<WIDTH+100);
 for(const z of m.zones){z.delay-=dt;if(z.delay>0)continue;z.life-=dt;const box={x:z.x-z.radius,y:FLOOR-240,w:z.radius*2,h:240};if(!z.hit&&overlaps(box,hurtBox(m.fighters[1-z.owner])))z.hit=addDamage(m,m.fighters[z.owner],m.fighters[1-z.owner],z.spec);}m.zones=m.zones.filter(z=>z.delay>0||z.life>0);
 if(m.mode==='training'){for(const f of m.fighters){if(f.hp<=0||f.hp<f.maxHp&&!f.stun&&!f.knock&&!m.fighters[1-f.index].comboTime){f.hp=f.maxHp;f.recoverable=0;}f.meter=100;}return;}if(a.hp<=0||b.hp<=0||m.time<=0)endRound(m);
}
export function snapshot(m){return{version:2,mode:m.mode,stage:m.stage,difficulty:m.difficulty,options:m.options,time:m.time,clock:m.clock,phase:m.phase,intro:m.intro,round:m.round,wins:[...m.wins],target:m.target,roundEnded:m.roundEnded,result:m.result,dummy:m.dummy,bestCombo:[...m.bestCombo],totalDamage:[...m.totalDamage],training:{...m.training},rngState:m.rng.state(),aiWait:m.aiWait,aiAttackWait:m.aiAttackWait,hitstop:m.hitstop,flash:m.flash,nextId:m.nextId,fighters:m.fighters.map(f=>({...f,held:{},buffer:null,lastTap:{}})),projectiles:structuredClone(m.projectiles),zones:structuredClone(m.zones)};}
export function restore(raw){if(!raw||![1,2].includes(raw.version)||!['story','free','survival','training','local'].includes(raw.mode)||!STAGES.some(s=>s.id===raw.stage)||!['easy','normal','hard'].includes(raw.difficulty)||!Array.isArray(raw.fighters)||raw.fighters.length!==2||!raw.fighters.every((f,i)=>BY_ID[f.id]&&f.index===i&&finite(f.hp,0,BY_ID[f.id].hp)&&f.maxHp===BY_ID[f.id].hp&&finite(f.x,0,1400)&&finite(f.y,-2000,594)&&finite(f.meter,0,100))||!finite(raw.time,0,60)||!['intro','fight','round'].includes(raw.phase)||!Number.isInteger(raw.round)||raw.round<1||raw.round>10000||!Array.isArray(raw.wins)||raw.wins.length!==2||raw.wins.some(v=>!Number.isInteger(v)||v<0||v>2)||!finite(raw.clock)||raw.phase==='round'&&(!raw.result||![-1,0,1].includes(raw.result.winner)||typeof raw.result.matchOver!=='boolean'))throw Error('對戰紀錄不正確');
 const m=createMatch({mode:raw.mode,p1:raw.fighters[0].id,p2:raw.fighters[1].id,stage:raw.stage,difficulty:raw.difficulty});m.time=raw.time;m.clock=raw.clock;m.round=raw.round;m.wins=[...raw.wins];m.phase=raw.phase;m.intro=raw.phase==='intro'?2:0;m.result=raw.result?structuredClone(raw.result):null;m.roundEnded=raw.phase==='round';m.dummy=['stand','guard','counter'].includes(raw.dummy)?raw.dummy:'stand';m.bestCombo=Array.isArray(raw.bestCombo)&&raw.bestCombo.length===2&&raw.bestCombo.every(v=>Number.isInteger(v)&&v>=0&&v<=5)?[...raw.bestCombo]:[0,0];m.totalDamage=Array.isArray(raw.totalDamage)&&raw.totalDamage.length===2&&raw.totalDamage.every(v=>finite(v))?[...raw.totalDamage]:raw.fighters.map(f=>finite(f.damage)?f.damage:0);
 m.fighters=m.fighters.map((f,i)=>{const old=raw.fighters[i];Object.assign(f,{hp:old.hp,meter:old.meter,x:clamp(raw.version===1?old.x/1400*1280:old.x,64,1216),y:FLOOR,facing:[-1,1].includes(old.facing)?old.facing:f.facing});for(const key of ['guard','recoverable','healUses','cooldown','shield','shieldTime'])if(finite(old[key],0,key==='guard'?100:1e4))f[key]=old[key];if(raw.version===1){f.invuln=.35;return f;}
 for(const key of ['stun','blockStun','knock','rising','invuln','slow','comboTime','dash','poseTime','hits','blocked','damage','combo']){if(!finite(old[key],0,key==='combo'?5:1e8))throw Error('角色狀態不正確');f[key]=old[key];}
 for(const key of ['vx','vy','y']){if(!finite(old[key],key==='y'?-2000:-3000,key==='y'?FLOOR:3000))throw Error('動作位置不正確');f[key]=old[key];}
 if(old.action){const a=old.action;if(!['light','heavy','skill','super','throw','launcher','sweep','air','finisher'].includes(a.key)||!finite(a.t,0,4)||typeof a.hit!=='boolean'||typeof a.fired!=='boolean')throw Error('招式紀錄不正確');f.held.down=a.height==='low';f.y=a.air?Math.min(f.y,FLOOR-13):f.y;const spec=moveSpec(f,a.key);f.held={};if(a.t>spec.start+spec.active+spec.end+.05)throw Error('招式時間不正確');f.action={...spec,t:a.t,hit:a.hit,fired:a.fired};}return f;});
 if(raw.version===2){if(!Array.isArray(raw.projectiles)||!Array.isArray(raw.zones)||raw.projectiles.length>20||raw.zones.length>20)throw Error('場上攻擊紀錄不正確');const attack=s=>{if(!s||!['skill','super'].includes(s.key)||!finite(s.damage,0,400)||!finite(s.stun,0,2)||!finite(s.knock,0,200))throw Error('攻擊資料不正確');return structuredClone(s);};
 m.projectiles=raw.projectiles.map(p=>{if(![0,1].includes(p.owner)||!finite(p.x,-150,WIDTH+150)||!finite(p.y,-2000,FLOOR)||!finite(p.vx,-1500,1500)||!finite(p.life,0,3)||!finite(p.radius,1,100))throw Error('飛行攻擊位置不正確');return{...p,spec:attack(p.spec)};});
 m.zones=raw.zones.map(z=>{if(![0,1].includes(z.owner)||!finite(z.x,0,WIDTH)||!finite(z.delay,-5,2)||!finite(z.life,-.1,2)||!finite(z.radius,1,300)||typeof z.hit!=='boolean')throw Error('場地攻擊位置不正確');return{...z,spec:attack(z.spec)};});
 m.intro=finite(raw.intro,0,3)?raw.intro:0;m.hitstop=finite(raw.hitstop,0,.2)?raw.hitstop:0;m.flash=finite(raw.flash,0,.2)?raw.flash:0;m.aiWait=finite(raw.aiWait,-5,3)?raw.aiWait:.5;m.aiAttackWait=finite(raw.aiAttackWait,-1000,3)?raw.aiAttackWait:.5;m.rng=random(Number.isInteger(raw.rngState)?raw.rngState:Date.now());m.nextId=Number.isInteger(raw.nextId)?Math.max(0,raw.nextId):0;
 if(raw.training&&['damage','maxCombo','hits','blocks','misses'].every(k=>finite(raw.training[k])))m.training={...raw.training,last:String(raw.training.last).slice(0,200)};
 }else m.training={damage:m.totalDamage[0],maxCombo:m.bestCombo[0],hits:0,blocks:0,misses:0,last:'舊版進度已保留，依新規則接續回合',lastBox:null};return m;
}
