import {CONTROLS} from './cast.mjs?v=arcade1';
import {command,setHeld,clearInputs} from './core.mjs?v=arcade1';
const heldKeys=['left','right','down','guard'];
export class Input {
 constructor(stage,getMatch,active,settings,menu){this.stage=stage;this.getMatch=getMatch;this.active=active;this.settings=settings;this.menu=menu;this.sources=new Map();this.taps=[{},{}];this.gamepadPrevious=[];this.pointerMoves=new Map();this.stickId=null;this.bind=null;
 document.addEventListener('keydown',e=>this.key(e,true));document.addEventListener('keyup',e=>this.key(e,false));window.addEventListener('blur',()=>this.reset());
 stage.addEventListener('pointerdown',e=>this.pointer(e));window.addEventListener('pointermove',e=>this.move(e));window.addEventListener('pointerup',e=>this.release(e));window.addEventListener('pointercancel',e=>this.release(e));window.addEventListener('gamepaddisconnected',()=>this.reset());}
 merged(){const m=this.getMatch();if(!m)return;for(let i=0;i<2;i++)for(const key of heldKeys)setHeld(m,i,key,[...this.sources.values()].some(v=>v.i===i&&v.keys.includes(key)));}
 put(source,i,keys){if(keys.length)this.sources.set(source,{i,keys});else this.sources.delete(source);this.merged();}
 action(i,key){const m=this.getMatch();if(!this.active()||!m)return;const now=performance.now(),last=this.taps[i];if(['light','heavy'].includes(key)){const opposite=key==='light'?'heavy':'light';if(now-(last[opposite]||-1000)<105){command(m,i,'throw');last[opposite]=0;return;}last[key]=now;}command(m,i,key);}
 key(e,down){if(this.bind&&down){e.preventDefault();const fn=this.bind;this.bind=null;fn(e.code);return;}if(e.target.matches('input,select,textarea'))return;if(!this.active()){if(down&&!e.repeat)this.menu(e.code);return;}if(e.code==='Escape'){if(down&&!e.repeat)this.menu('Escape');return;}for(let i=0;i<2;i++){if(i===1&&this.getMatch()?.mode!=='local')continue;const map=this.settings().keys?.[i?'p2':'p1']||CONTROLS[i?'p2':'p1'];for(const[key,code]of Object.entries(map))if(code===e.code){e.preventDefault();if(heldKeys.includes(key)){this.put('key:'+code,i,down?[key]:[]);if(down&&!e.repeat&&['left','right'].includes(key)){const now=performance.now(),last=this.taps[i][key]||0;if(now-last<240)this.action(i,key==='left'?'dashLeft':'dashRight');this.taps[i][key]=now;}}else if(down&&!e.repeat)this.action(i,key);}}}
 pointer(e){const control=e.target.closest('[data-control],#joystick');if(!control||!this.active())return;e.preventDefault();control.setPointerCapture?.(e.pointerId);if(control.id==='joystick'){this.stickId=e.pointerId;this.moveStick(e);return;}const key=control.dataset.control;this.pointerMoves.set(e.pointerId,key);control.classList.add('pressed');if(heldKeys.includes(key))this.put('pointer:'+e.pointerId,0,[key]);else this.action(0,key);}
 moveStick(e){const el=this.stage.querySelector('#joystick');if(!el)return;const r=el.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width*.34),dy=(e.clientY-r.top-r.height/2)/(r.height*.34),length=Math.hypot(dx,dy),nx=dx/Math.max(1,length),ny=dy/Math.max(1,length);const keys=[];if(nx<-.28)keys.push('left');if(nx>.28)keys.push('right');if(ny>.40)keys.push('down');if(ny<-.70&&!this.stickJump)this.action(0,'jump');this.stickJump=ny<-.70;this.put('pointer:'+e.pointerId,0,keys);const knob=el.querySelector('.knob');knob.style.transform='translate('+nx*47+'px,'+ny*47+'px)';}
 move(e){if(e.pointerId===this.stickId)this.moveStick(e);}
 release(e){this.put('pointer:'+e.pointerId,0,[]);const key=this.pointerMoves.get(e.pointerId);this.pointerMoves.delete(e.pointerId);if(key&&!Array.from(this.pointerMoves.values()).includes(key))this.stage.querySelector('[data-control="'+key+'"]')?.classList.remove('pressed');if(e.pointerId===this.stickId){this.stickId=null;this.stickJump=false;const knob=this.stage.querySelector('.knob');if(knob)knob.style.transform='';}}
 poll(){const pads=Array.from(navigator.getGamepads?.()||[]).filter(Boolean).slice(0,2);for(let i=0;i<2;i++){const p=i===1&&this.getMatch()?.mode!=='local'?null:pads[i],previous=this.gamepadPrevious[i]||{};if(!p){this.put('pad:'+i,i,[]);this.gamepadPrevious[i]={};continue;}const b=n=>!!p.buttons[n]?.pressed,x=p.axes[0]||0,y=p.axes[1]||0,keys=[];if(x<-.3||b(14))keys.push('left');if(x>.3||b(15))keys.push('right');if(y>.4||b(13))keys.push('down');if(b(4)||b(6))keys.push('guard');const now={light:b(0),heavy:b(1),skill:b(2),jump:b(3)||b(12)||y<-.7,super:b(5)||b(7),pause:b(9),left:keys.includes('left'),right:keys.includes('right'),down:keys.includes('down')};if(this.active()){this.put('pad:'+i,i,keys);for(const k of ['light','heavy','skill','jump','super'])if(now[k]&&!previous[k])this.action(i,k);if(now.pause&&!previous.pause)this.menu('Escape');}else if(i===0){for(const[k,code]of [['left','ArrowLeft'],['right','ArrowRight'],['down','ArrowDown'],['jump','ArrowUp'],['light','Enter'],['heavy','Escape']])if(now[k]&&!previous[k])this.menu(code);}this.gamepadPrevious[i]=now;} }
 reset(){this.sources.clear();this.pointerMoves.clear();this.stickId=null;this.stickJump=false;this.taps=[{},{}];const m=this.getMatch();if(m)clearInputs(m);this.stage.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));const knob=this.stage.querySelector('.knob');if(knob)knob.style.transform='';}
}
