import {CAST,BY_ID,STAGES,ART} from './cast.mjs?v=arcade1';
import {WIDTH,HEIGHT,FLOOR,hurtBox,attackBox} from './core.mjs?v=arcade1';
export class Painter {
 constructor(canvas,settings){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.settings=settings;this.images=new Map();this.meta={};this.effects=[];this.seen=0;this.low=false;}
 async load(progress=()=>{}){const response=await fetch('./art/manifest.json?v=arcade1');if(!response.ok)throw Error('素材清單讀取失敗');this.meta=Object.fromEntries((await response.json()).assets.map(a=>[a.id,a]));const files=[...new Set([...Object.values(ART),...STAGES.map(s=>s.art),...CAST.flatMap(c=>Object.values(c.poses)),...CAST.map(c=>c.portrait)])];let n=0;await Promise.all(files.map(async src=>{const image=new Image();image.src=src;await image.decode();this.images.set(src,image);progress(++n,files.length);}));this.resize();}
 resize(){const quality=this.settings().quality,ratio=quality==='low'||this.low?1:Math.min(1.5,devicePixelRatio||1);this.canvas.width=WIDTH*ratio;this.canvas.height=HEIGHT*ratio;this.ctx.setTransform(ratio,0,0,ratio,0,0);}
 sprite(id,pose,x,y,height,facing=1,alpha=1){const src=BY_ID[id].poses[pose]||BY_ID[id].poses.idle,img=this.images.get(src);if(!img)return;const a=this.meta[id+'-'+pose],bounds=a?.bounds||{x:.05,y:.05,w:.9,h:.9},h=pose==='down'?height*.38:height,scale=h/(img.height*bounds.h),w=img.width*scale,fullH=img.height*scale,feet=a?.feet??.96,anchor=a?.anchorX??(bounds.x+bounds.w*.5);const ctx=this.ctx;ctx.save();ctx.translate(x,y);ctx.scale(facing,1);ctx.globalAlpha=alpha;ctx.drawImage(img,-w*anchor,-fullH*feet,w,fullH);ctx.restore();}
 pose(f,m){if(m.phase==='round'&&m.result?.winner===f.index)return 'victory';if(f.knock>0)return 'down';if(f.stun>0)return 'hurt';if(f.rising>0)return 'crouch';if(f.action){const a=f.action;if(a.t<a.start*.7)return a.key==='heavy'?'crouch':'guard';if(a.t>a.start+a.active+a.end*.55)return 'idle';if(a.key==='throw')return 'heavy';return a.key==='skill'?'skill':a.key;}if(f.y<FLOOR-8)return 'jump';if(f.held.guard||f.blockStun)return 'guard';if(f.held.down)return 'crouch';if(Math.abs(f.vx)>25)return Math.floor(f.poseTime*9)%2?'walk-a':'walk-b';return 'idle';}
 bitmap(src,x,y,w,h,alpha=1,flip=false){const img=this.images.get(src);if(!img)return;const b=this.meta[src.split('/').pop().replace('.webp','')]?.bounds||{x:0,y:0,w:1,h:1},c=this.ctx;c.save();c.globalAlpha=alpha;c.translate(flip?x+w:x,y);if(flip)c.scale(-1,1);c.drawImage(img,-w*b.x/b.w,-h*b.y/b.h,w/b.w,h/b.h);c.restore();}
 draw(m){const c=this.ctx;c.clearRect(0,0,WIDTH,HEIGHT);const stage=STAGES.find(s=>s.id===m.stage)||STAGES[0];this.bitmap(stage.art,0,0,WIDTH,HEIGHT);const events=m.events.filter(e=>e.id>this.seen);for(const e of events){this.seen=Math.max(this.seen,e.id);if(['hit','block','counter','shield'].includes(e.type))this.effects.push({...e,life:.25,max:.25});}
 c.save();const shake=!this.settings().reducedMotion&&m.hitstop>0?3:0;if(shake)c.translate(Math.sin(m.clock*93)*shake,0);
 for(const z of m.zones){const warning=z.delay>0;this.bitmap(warning?ART.block:ART.projectile,z.x-z.radius,FLOOR-250,z.radius*2,230,warning?.38:.8);}
 for(const f of [...m.fighters].sort((a,b)=>a.y-b.y)){const pose=this.pose(f,m),low=f.action?.height==='low'||f.held.down&&f.action;this.sprite(f.id,pose,f.x,f.y,BY_ID[f.id].height*(low?.72:1),f.facing,f.invuln>0&&Math.floor(m.clock*14)%2?.65:1);if(f.shield>0)this.bitmap(ART.block,f.x-90,f.y-220,180,230,.35);}
 for(const p of m.projectiles)this.bitmap(ART.projectile,p.x-p.radius*1.7,p.y-p.radius*1.7,p.radius*3.4,p.radius*3.4,1,p.vx<0);
 for(const e of this.effects){e.life-=1/60;const size=e.type==='hit'||e.type==='counter'?130:110;this.bitmap(e.type==='block'||e.type==='shield'?ART.block:ART.hit,e.x-size/2,e.y-size/2,size,size,Math.min(1,e.life/.08));}this.effects=this.effects.filter(e=>e.life>0);
 if(this.settings().hitboxes){for(const f of m.fighters){const h=hurtBox(f),a=attackBox(f);c.lineWidth=2;c.strokeStyle='#70ffcf';c.strokeRect(h.x,h.y,h.w,h.h);if(a){c.strokeStyle='#ff7357';c.strokeRect(a.x,a.y,a.w,a.h);}}}
 c.restore();for(let i=0;i<2;i++){const hit=[...m.events].reverse().find(e=>['hit','counter'].includes(e.type)&&e.fighter===i&&e.combo>1&&m.clock-e.at<.85);if(hit){c.font='900 italic 38px system-ui';c.fillStyle='#fff0b0';c.textAlign=i?'right':'left';c.fillText(hit.combo+' HITS',i?WIDTH-35:35,235);}}c.textAlign='left';}
 showcase(left,right,t=0){this.bitmap(ART.select,0,0,WIDTH,HEIGHT);this.sprite(left,'idle',235,494,BY_ID[left].height*1.02,1);this.sprite(right,'idle',1045,494,BY_ID[right].height*1.02,-1);}
 menu(t){this.bitmap(ART.menu,0,0,WIDTH,HEIGHT);this.sprite('growth',Math.floor(t*2)%2?'walk-a':'walk-b',255,605,375,1);this.sprite('luck','idle',1030,605,350,-1);}
 result(id,win){this.bitmap(ART.menu,0,0,WIDTH,HEIGHT);this.sprite(id,win?'victory':'hurt',285,615,400,1);}
}
