/* CxQ local game services. No account, telemetry or remote state. */
(() => {
  const base=new URL('.',document.currentScript.src),key='cxq-audio-v1';
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
  const raw=read(key,{})||{},settings={music:Number.isFinite(raw.music)?Math.max(0,Math.min(1,raw.music)):.25,sfx:Number.isFinite(raw.sfx)?Math.max(0,Math.min(1,raw.sfx)):.65};
  let unlocked=false,music=null,paused=false,controller=null,lastSound=0,countdownNode=null,countdownFrame=0;
  const files={tap:'click1',match:'switch4',miss:'switch15',flip:'rollover2',hit:'click3',win:'win',lose:'lose',upgrade:'switch8'};
  const pool=new Map();
  function playMusic(){if(unlocked&&music&&!paused&&!document.hidden&&settings.music>0){music.volume=settings.music;music.play().catch(()=>{})}}
  function sound(name='tap'){if(!unlocked||paused||document.hidden||!settings.sfx)return;const now=performance.now();if(now-lastSound<45)return;lastSound=now;const file=files[name]||files.tap;let a=pool.get(file);if(!a){a=new Audio(new URL('audio/'+file+(new Audio().canPlayType('audio/ogg; codecs=vorbis')?'.ogg':'.mp3'),base));pool.set(file,a)}a.volume=settings.sfx;a.currentTime=0;a.play().catch(()=>{})}
  function unlock(){unlocked=true;playMusic()}
  document.addEventListener('pointerdown',unlock,{passive:true});document.addEventListener('keydown',unlock);
  document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#cxq-audio-panel'))sound()});
  function hold(reason){cancelAnimationFrame(countdownFrame);countdownNode?.remove();countdownNode=null;paused=true;music?.pause();pool.forEach(a=>a.pause());controller?.pause?.(reason)}
  document.addEventListener('visibilitychange',()=>{if(document.hidden)hold('hidden')});
  addEventListener('pagehide',()=>{music?.pause();controller?.save?.()});
  window.CxQ={read,write,sound,hold,countdown(done){if(countdownNode)return;countdownNode=document.createElement('div');countdownNode.className='cxq-countdown';countdownNode.setAttribute('role','status');document.body.append(countdownNode);let left=1200,last=performance.now();function step(t){if(!countdownNode)return;left-=Math.min(50,t-last);last=t;countdownNode.textContent=Math.max(1,Math.ceil(left/400));if(left>0){countdownFrame=requestAnimationFrame(step)}else{countdownNode.remove();countdownNode=null;if(!document.hidden)done()}}countdownFrame=requestAnimationFrame(step)},resume(){paused=false;playMusic()},configure(options={}){controller=options;music?.pause();if(options.music){music=new Audio(new URL('audio/'+options.music+(new Audio().canPlayType('audio/ogg; codecs=vorbis')?'.ogg':'.mp3'),base));music.loop=true;music.preload='none';playMusic()}},orientation(required,active=true){const phone=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||navigator.maxTouchPoints>0||matchMedia('(pointer:coarse)').matches||innerWidth<600;const mismatch=active&&phone&&(required==='portrait'?innerWidth>innerHeight:innerHeight>innerWidth);let gate=document.getElementById('cxq-rotate');if(!gate){gate=document.createElement('div');gate.id='cxq-rotate';gate.className='cxq-cover';gate.innerHTML='<div><img class="cxq-guide" src="'+new URL('../whack/assets/normal.webp',base)+'" alt="森林夥伴為你保留進度"><div class="cxq-phone">↻</div><h2></h2><p>旅程已暫停，進度會為你保留。</p></div>';document.body.append(gate)}gate.hidden=!mismatch;gate.querySelector('h2').textContent=required==='portrait'?'請直拿手機繼續冒險':'請橫拿手機，讓夥伴都看得清楚';if(mismatch)hold('orientation');return mismatch}};
  addEventListener('DOMContentLoaded',()=>{const button=document.createElement('button');button.id='cxq-audio';button.setAttribute('aria-label','音樂與音效設定');button.textContent='♫';document.body.append(button);const panel=document.createElement('dialog');panel.id='cxq-audio-panel';panel.innerHTML='<form method="dialog"><h2>旅途的聲音</h2><p>輕輕調整，找到舒服的音量。</p><label>背景音樂 <input data-volume="music" type="range" min="0" max="1" step=".05"></label><label>遊戲音效 <input data-volume="sfx" type="range" min="0" max="1" step=".05"></label><a href="'+new URL('audio/CREDITS.md',base)+'" target="_blank">音樂與音效來源</a><button>收好設定</button></form>';document.body.append(panel);button.onclick=()=>{hold('settings');panel.showModal()};panel.addEventListener('close',()=>{if(!controller?.pause)CxQ.resume()});panel.querySelectorAll('input').forEach(el=>{el.value=settings[el.dataset.volume];el.oninput=()=>{settings[el.dataset.volume]=+el.value;write(key,settings);if(music){music.volume=settings.music;if(!settings.music)music.pause()}if(el.dataset.volume==='sfx'){paused=false;sound('match');paused=true}}})});
})();
