'use strict';
const C=document.getElementById('game'),X=C.getContext('2d');
document.documentElement.style.background='#071325';document.body.style.margin='0';document.body.style.overflow='hidden';document.body.style.background='#071325';C.style.display='block';C.style.width='100vw';C.style.height='100vh';C.style.touchAction='none';
const W=1600,H=900,OLD='../../fortune/assets/',A='assets/',V6='../v6/assets/';
const CF=['joy.png','dream.png','night.png','sadness.png','trust.png','memory.png','growth.png','healing.png','luck.png','hope.png'];
const CN=['慶典少女','星夢魔女','夜鈴米亞','雨音澄澄','鑰匙守護者','記憶偵探','森林旅人','棉糖汪汪','森鈴芽獸','希望旅人'];
const CT=['幸運型','骰控型','卡片型','防禦型','商店型','移動型','土地型','小遊戲型','收租型','特殊型'];
const I={};function load(k,u){const m=new Image();m.src=u;I[k]=m;return m}
load('bg',OLD+'backgrounds/destiny-village.png');load('house',OLD+'buildings/moon-tarot-cottage.png');CF.forEach((f,i)=>load('c'+i,OLD+'characters/'+f));
load('btnRed',V6+'btn_red.webp');load('btnBlue',V6+'btn_blue.webp');
['start','land','event','card','shop','minigame','npc'].forEach(k=>load('tile_'+k,A+'tile_'+k+'.webp'));
const S={scene:'home',buttons:[],seats:[{type:'human',char:0,diff:'standard'},{type:'ai',char:1,diff:'standard'},{type:'off',char:2,diff:'standard'},{type:'off',char:3,diff:'standard'}],activeSeat:0,money:300000,rounds:30,board:null,dice:1,moving:false,msg:'',help:false};
function resize(){const d=Math.min(devicePixelRatio||1,2);C.width=Math.round(innerWidth*d);C.height=Math.round(innerHeight*d)}addEventListener('resize',resize);resize();
function begin(){X.setTransform(C.width/W,0,0,C.height/H,0,0);X.clearRect(0,0,W,H);S.buttons=[]}
function txt(s,x,y,z=26,a='center',c='#fff',w=800,o=true){X.save();X.font=`${w} ${z}px system-ui,-apple-system,"Noto Sans TC",sans-serif`;X.textAlign=a;X.textBaseline='middle';if(o){X.lineWidth=Math.max(2,z/8);X.strokeStyle='rgba(25,13,21,.9)';X.strokeText(String(s),x,y)}X.fillStyle=c;X.fillText(String(s),x,y);X.restore()}
function contain(im,x,y,w,h,alpha=1){if(!im||!im.complete||!im.naturalWidth)return;const r=Math.min(w/im.naturalWidth,h/im.naturalHeight),iw=im.naturalWidth*r,ih=im.naturalHeight*r;X.save();X.globalAlpha=alpha;X.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih);X.restore()}
function cover(im,x,y,w,h,alpha=1){if(!im||!im.complete||!im.naturalWidth)return;const r=Math.max(w/im.naturalWidth,h/im.naturalHeight),iw=im.naturalWidth*r,ih=im.naturalHeight*r;X.save();X.globalAlpha=alpha;X.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih);X.restore()}
function btn(id,label,x,y,w,h,red=false,alpha=1,en=true){contain(red?I.btnRed:I.btnBlue,x,y,w,h,alpha*(en?1:.42));txt(label,x+w/2,y+h*.47,Math.min(30,h*.34),'center','#fff',900,true);S.buttons.push({id,x,y,w,h,en})}
function active(){return S.seats.map((s,i)=>s.type!=='off'?i:-1).filter(i=>i>=0)}function humans(){return S.seats.filter(s=>s.type==='human').length}
function assigned(ci){return active().find(i=>S.seats[i].char===ci)}function choose(ci){const a=S.activeSeat,b=assigned(ci);if(b!==undefined&&b!==a){const old=S.seats[a].char;S.seats[a].char=ci;S.seats[b].char=old}else S.seats[a].char=ci}
function title(){txt('CxQ',790,122,108,'center','#ffd767',1000,true);txt('童話大富翁',790,218,78,'center','#fff0b2',1000,true);txt('夢想王國資產大冒險',790,277,24,'center','#fff8dc',900,true)}
function home(){cover(I.bg,0,0,W,H);title();btn('start','開始遊戲',595,410,390,104,true);btn('continue','繼續遊戲',625,525,330,82,false,.9,!!localStorage.getItem('cxq_v7_save'));btn('help','遊戲說明',625,620,330,82,false,.9,true);contain(I.tile_start,1120,500,285,285,.96);txt('大地圖・獨立棋格・逐格移動',800,830,22,'center','#fff3cc',850,true)}
function charCard(i,x,y,w,h){const own=assigned(i),sel=S.seats[S.activeSeat].char===i;contain(I['c'+i],x,y,w,h-35,own!==undefined&&!sel?.55:1);if(sel)contain(I.tile_start,x+w*.28,y+h*.12,w*.44,w*.44,.22);txt(CN[i],x+w/2,y+h-18,15,'center','#fff',850,true);if(own!==undefined)txt((own+1)+'P',x+22,y+18,17,'center',['#ff6d69','#6db6ff','#7dcc75','#efc04f'][own],1000,true);S.buttons.push({id:'char'+i,x,y,w,h,en:true})}
function seat(i,x,y,w,h){const s=S.seats[i],selected=S.activeSeat===i;contain(I['c'+s.char],x+4,y+2,80,82,s.type==='off'?.35:1);txt((i+1)+'P',x+90,y+20,23,'left',selected?'#ffe57e':'#fff',1000,true);txt(s.type==='off'?'空席':CN[s.char],x+90,y+50,15,'left','#fff',750,true);btn('human'+i,'真人',x+0,y+78,72,39,false,s.type==='human'?1:.42);btn('ai'+i,'AI',x+75,y+78,64,39,true,s.type==='ai'?1:.42);btn('off'+i,'空席',x+142,y+78,72,39,false,s.type==='off'?1:.42);S.buttons.push({id:'seat'+i,x,y,w,h,en:true});if(s.type==='ai'){btn('diff'+i,s.diff==='easy'?'輕鬆':s.diff==='standard'?'標準':'聰明',x+218,y+78,86,39,false,.88)}}
function setup(){cover(I.bg,0,0,W,H);btn('back','返回',22,18,150,58,false);txt('角色選擇 / 玩家控制',800,52,38,'center','#fff0b6',1000,true);txt('每個席位直接選 真人 / AI / 空席；參賽人數由非空席自動計算',800,92,18,'center','#fff',750,true);const gx=58,gy=118,cw=184,ch=205,g=16;for(let i=0;i<10;i++)charCard(i,gx+(i%5)*(cw+g),gy+Math.floor(i/5)*(ch+g),cw,ch);const ci=S.seats[S.activeSeat].char;contain(I['c'+ci],1070,120,205,280);txt(CN[ci],1288,170,31,'left','#fff0b2',950,true);txt(CT[ci],1288,214,18,'left','#d9e8ff',800,true);txt('目前控制：'+(S.seats[S.activeSeat].type==='human'?'真人':S.seats[S.activeSeat].type==='ai'?'AI':'空席'),1288,258,20,'left','#fff',850,true);txt('參賽 '+active().length+' 人 / 真人 '+humans()+' 人',1288,300,18,'left','#fff',750,true);btn('money','起始 $'+S.money.toLocaleString(),1080,340,410,64,false);btn('rounds',S.rounds+' 回合',1080,416,410,64,false);btn('startGame','開始遊戲',1080,500,410,92,true,1,active().length>=2&&humans()>=1);for(let i=0;i<4;i++)seat(i,48+i*390,734,310,128)}
function boardPoints(){const p=[],L=420,R=3180,T=330,B=1870;const add=(x,y)=>p.push({x,y});for(let i=0;i<10;i++)add(L+i*(R-L)/9,B);for(let i=1;i<=5;i++)add(R,B-i*(B-T)/6);for(let i=1;i<10;i++)add(R-i*(R-L)/9,T);for(let i=1;i<=5;i++)add(L,T+i*(B-T)/6);return p}
const TYPES=['start','land','event','land','card','land','shop','land','event','land','minigame','land','npc','land','card','land','event','land','shop','land','npc','land','event','land','minigame','land','card','land','event','land'];
function makeBoard(){const pts=boardPoints();const tiles=pts.map((p,i)=>({x:p.x,y:p.y,type:TYPES[i%TYPES.length],owner:-1,level:0,price:9000+(i%6)*1800}));tiles[0].type='start';const ps=active().map((si,id)=>({id,seat:si,type:S.seats[si].type,char:S.seats[si].char,diff:S.seats[si].diff,cash:S.money,pos:0,cards:0,tickets:0}));S.board={worldW:3600,worldH:2200,tiles,players:ps,turn:0,round:1,cam:{x:0,y:0},popup:null};focus(true);localStorage.setItem('cxq_v7_save','1')}
function cp(){return S.board.players[S.board.turn]}function focus(now=false){const b=S.board,p=cp(),t=b.tiles[p.pos],tx=Math.max(0,Math.min(b.worldW-W,t.x-W/2)),ty=Math.max(0,Math.min(b.worldH-H,t.y-H/2));if(now){b.cam.x=tx;b.cam.y=ty}else b.cam.target={x:tx,y:ty}}
function mapBg(){const b=S.board;cover(I.bg,0,0,b.worldW,b.worldH)}
function drawTile(t,i){contain(I['tile_'+t.type],t.x-92,t.y-92,184,184,1);if(t.type==='land'&&t.owner>=0){txt((t.owner+1)+'P',t.x,t.y-76,16,'center',['#ff6d69','#6db6ff','#7dcc75','#efc04f'][t.owner],1000,true);if(t.level>0)contain(I.house,t.x-45,t.y-146,90,92,.96);txt('Lv'+t.level,t.x,t.y+68,14,'center','#fff4d2',850,true)}}
function drawPlayers(){const b=S.board;for(const p of b.players){const t=b.tiles[p.pos],o=(p.id-(b.players.length-1)/2)*28;contain(I['c'+p.char],t.x-54+o,t.y-147,108,120);txt((p.id+1)+'P',t.x+o,t.y-153,14,'center',['#ff6d69','#6db6ff','#7dcc75','#efc04f'][p.id],1000,true)}}
function hud(){const b=S.board,p=cp();btn('noop',`${p.id+1}P  ${CN[p.char]}   $${p.cash.toLocaleString()}`,18,16,540,70,false);btn('noop2',`第 ${b.round}/${S.rounds} 回合`,1220,16,355,70,false);btn('roll',S.moving?'移動中':'擲骰子',1285,756,270,106,true,.96,!S.moving&&!b.popup);txt('骰子 '+S.dice,1420,720,20,'center','#fff3ca',900,true);if(S.msg)txt(S.msg,800,847,20,'center','#fff3ca',900,true)}
function typeName(t){return {start:'起點',land:'土地',event:'事件',card:'卡片',shop:'商店',minigame:'小遊戲',npc:'NPC / 神明'}[t]||t}
function popup(){const b=S.board,p=cp(),t=b.popup;if(!t)return;contain(I['tile_'+t.type],590,142,420,420,.98);btn('noop3',typeName(t.type),600,485,400,72,false);if(t.type==='start'){txt('經過起點獎金 +2,000',800,578,25);btn('ok','確定',680,645,240,74,false);return}if(t.type==='land'){if(t.owner<0){txt('土地價格 $'+t.price.toLocaleString(),800,575,25);btn('buy','購買',610,640,240,76,true,1,p.cash>=t.price);btn('skip','略過',875,640,180,76,false)}else if(t.owner===p.id){txt('自己的土地・Lv'+t.level,800,575,25);btn('upgrade',t.level<3?'升級房屋':'已滿級',645,640,310,76,true,1,t.level<3&&p.cash>=Math.round(t.price*.7));btn('skip','繼續',690,730,220,62,false)}else{const r=Math.round(t.price*(.32+t.level*.22));txt(`支付 ${t.owner+1}P 租金 $${r.toLocaleString()}`,800,575,25);btn('pay','支付租金',650,645,300,76,true)}return}
const msg={event:'事件發生：本回合獲得 $3,000',card:'抽到一張童話卡片',shop:'商店補給：支付 $1,500 取得卡片',minigame:'小遊戲完成：獲得 2 點券',npc:'遇見星輝精靈：獲得 $2,000'}[t.type];txt(msg,800,575,23);btn('special','確定',675,645,250,76,false)}
function game(){const b=S.board;if(b.cam.target){b.cam.x+=(b.cam.target.x-b.cam.x)*.09;b.cam.y+=(b.cam.target.y-b.cam.y)*.09;if(Math.hypot(b.cam.target.x-b.cam.x,b.cam.target.y-b.cam.y)<1)delete b.cam.target}X.save();X.translate(-b.cam.x,-b.cam.y);mapBg();b.tiles.forEach(drawTile);drawPlayers();X.restore();hud();popup()}
function next(){const b=S.board;b.popup=null;b.turn++;if(b.turn>=b.players.length){b.turn=0;b.round++}focus();if(b.round>S.rounds){S.msg='遊戲結束';return}if(cp().type==='ai')setTimeout(roll,500)}
function land(){const b=S.board,p=cp(),t=b.tiles[p.pos];if(t.type==='start')p.cash+=2000;b.popup=t;if(p.type==='ai')setTimeout(aiResolve,450)}
function specialResolve(t,p){if(t.type==='event')p.cash+=3000;else if(t.type==='card')p.cards++;else if(t.type==='shop'){if(p.cash>=1500){p.cash-=1500;p.cards++}}else if(t.type==='minigame')p.tickets+=2;else if(t.type==='npc')p.cash+=2000}
function aiResolve(){const b=S.board,p=cp(),t=b.popup;if(t.type==='start')return next();if(t.type!=='land'){specialResolve(t,p);return next()}if(t.owner<0&&p.cash>t.price*1.5){p.cash-=t.price;t.owner=p.id;t.level=1}else if(t.owner===p.id&&t.level<3&&p.cash>t.price){p.cash-=Math.round(t.price*.7);t.level++}else if(t.owner>=0&&t.owner!==p.id){const r=Math.round(t.price*(.32+t.level*.22));p.cash-=r;b.players[t.owner].cash+=r}next()}
function roll(){if(S.moving||!S.board||S.board.popup)return;S.moving=true;S.dice=1+Math.floor(Math.random()*6);const p=cp();let n=0;const h=setInterval(()=>{p.pos=(p.pos+1)%S.board.tiles.length;if(p.pos===0)p.cash+=2000;n++;focus();if(n>=S.dice){clearInterval(h);S.moving=false;setTimeout(land,240)}},220)}
function click(id){if(S.scene==='home'){if(id==='start'||id==='continue'){S.scene='setup';return}if(id==='help'){S.help=!S.help;return}return}if(S.scene==='setup'){if(id==='back'){S.scene='home';return}if(id.startsWith('char')){choose(+id.slice(4));return}if(id.startsWith('seat')){S.activeSeat=+id.slice(4);return}for(const k of ['human','ai','off'])if(id.startsWith(k)){const i=+id.slice(k.length);S.seats[i].type=k==='human'?'human':k==='ai'?'ai':'off';S.activeSeat=i;return}if(id.startsWith('diff')){const i=+id.slice(4),s=S.seats[i];s.diff=s.diff==='easy'?'standard':s.diff==='standard'?'smart':'easy';return}if(id==='money'){S.money=S.money===300000?500000:S.money===500000?100000:300000;return}if(id==='rounds'){S.rounds=S.rounds===20?30:S.rounds===30?45:S.rounds===45?60:20;return}if(id==='startGame'&&active().length>=2&&humans()>=1){makeBoard();S.scene='game';if(cp().type==='ai')setTimeout(roll,500);return}}if(S.scene==='game'){const b=S.board,p=cp(),t=b.popup;if(id==='roll')return roll();if(!t)return;if(id==='ok'||id==='skip')return next();if(id==='special'){specialResolve(t,p);return next()}if(id==='buy'&&p.cash>=t.price){p.cash-=t.price;t.owner=p.id;t.level=1;return next()}if(id==='upgrade'&&t.level<3){const c=Math.round(t.price*.7);if(p.cash>=c){p.cash-=c;t.level++}return next()}if(id==='pay'){const r=Math.round(t.price*(.32+t.level*.22));p.cash-=r;b.players[t.owner].cash+=r;return next()}}}
function help(){if(!S.help)return;contain(I.tile_card,1120,350,300,300,.94);txt('玩法：擲骰 → 逐格移動 → 買地 / 收租 / 特殊格',800,705,23);btn('help','關閉說明',650,760,300,72,false)}
C.addEventListener('pointerup',e=>{const r=C.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;for(let i=S.buttons.length-1;i>=0;i--){const b=S.buttons[i];if(b.en&&x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h){click(b.id);break}}});
function loop(){begin();if(S.scene==='home'){home();help()}else if(S.scene==='setup')setup();else game();requestAnimationFrame(loop)}loop();