'use strict';const $=G.$,canvas=$('#canvas'),ctx=canvas.getContext('2d');let state=null,route=0,holding=false;const ground=292,routeNames=['森林郵路','雨露花園','月夜急件'],goals=[400,600,800],skills={0:'幸運採集：自動吸引附近 110 像素內的信件。',1:'安心毛毯：每局自動抵擋一次碰撞，之後短暫保護。',5:'月光緩行：按 X 或技能鈕，使障礙慢下來 3 秒；冷卻 20 秒。'};
const data=G.init({id:'dino',art:'art-v2',sounds:{"jump":"art-v2/jump.mp3","collect":"art-v2/collect.mp3"},music:'../storybook/audio/runner.mp3',orientation:'landscape',pause});data.route=G.clamp(Math.floor(data.route)||0,0,2);data.mail=G.clamp(Math.floor(data.mail)||0,0,1000000);data.hand=data.hand==='left'?'left':'right';$('#hand').value=data.hand;G.rolePicker('#roles',[0,1,5],id=>$('#skill-description').textContent=skills[id]);
function refresh(){ $('#routes').innerHTML=routeNames.map((n,i)=>'<button class="route-card" data-route="'+i+'" '+(i>data.route?'disabled':'')+' aria-pressed="'+(i===route)+'"><span>'+n+'<small>'+['跳過樹根，熟悉長短跳','箱件與低枝葉，練習跳滑切換','節奏較快，留意連續配送'][i]+'</small></span><span>'+goals[i]+' m</span></button>').join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=+b.dataset.route;refresh()});G.toast('累計收集 '+data.mail+' 封信。紀錄按角色與路線分開保存。') }refresh();
G.load(['art-v2/scene.webp','art-v2/rain.webp','art-v2/moon.webp','art-v2/kit.webp','art-v2/runner.webp','art-v2/cast-a.webp','art-v2/cast-b.webp']).catch(()=>{});
function start(){holding=false;$('#distance').textContent='0 m';$('#mail').textContent='0';state={running:true,paused:false,mode:$('#mode').value,route,role:data.role,time:0,distance:0,mail:0,y:ground,vy:0,jumpHeld:0,slide:0,slow:0,cool:0,shield:data.role===1?1:0,invul:0,next:1.6,obstacles:[],letters:[],countdown:1.2,crash:null};data.hand=$('#hand').value;G.save();document.body.classList.toggle('left-hand',data.hand==='left');$('#home').hidden=true;$('#play').hidden=false;$('#route-label').textContent=routeNames[route];$('#skill').disabled=data.role!==5;$('#skill').textContent=data.role===0?'幸運吸信':data.role===1?'毛毯守護':'月光緩行 X';G.playing(true);canvas.focus()}
function jump(){if(!state?.running||state.paused||state.countdown>0)return;holding=true;if(state.y>=ground-.5){state.slide=0;state.vy=-565;state.jumpHeld=0;G.sound('jump')}}
function slide(){if(!state?.running||state.paused||state.countdown>0)return;if(state.y>=ground-.5){state.slide=.7;G.sound('land')}}
function skill(){if(!state?.running||state.paused||state.countdown>0||state.role!==5||state.cool>0)return;state.slow=3;state.cool=20;G.sound('skill')}
function spawn(){let type=state.time<8?0:state.route===0?(Math.random()<.75?0:1):Math.random()<.35?2:Math.random()<.5?1:0;const o={x:1020,type,w:type===2?125:type===1?64:84,h:type===2?45:type===1?65:48,y:type===2?ground-103:ground-(type===1?65:48)};state.obstacles.push(o);state.letters.push({x:1020+(type===2?210:0),y:type===2?ground-45:ground-120,taken:false});state.next=state.time+1.7+Math.random()*.65}
function hit(){if(state.invul>0)return;if(state.mode==='practice'){state.invul=1.4;state.crash={x:160,y:state.y-45};G.sound('miss');G.toast('練習中：這裡碰到了障礙，再試試跳躍或下滑。');return}if(state.shield){state.shield=0;state.invul=1.7;G.sound('skill');return}state.crash={x:160,y:state.y-45};finish(false)}
function update(dt){if(!state?.running||state.paused)return;if(state.countdown>0){state.countdown-=dt;$('#status').textContent='出發倒數 '+Math.ceil(state.countdown);return}state.time+=dt;state.slide=Math.max(0,state.slide-dt);state.cool=Math.max(0,state.cool-dt);state.slow=Math.max(0,state.slow-dt);state.invul=Math.max(0,state.invul-dt);state.jumpHeld+=dt;const speed=(state.mode==='practice'?245:Math.min(460,290+state.route*30+state.time*2.2))*(state.slow>0?.55:1);state.distance+=speed*dt/10;const prev=state.y;state.vy+=(holding&&state.vy<0&&state.jumpHeld<.18?850:1700)*dt;state.y=Math.min(ground,state.y+state.vy*dt);if(state.y===ground){if(prev<ground-1)G.sound('land');state.vy=0;if(!state.slide)G.sound('step')}if(state.time>=state.next)spawn();const ph=state.slide>0?34:66,py=state.y-ph;for(const o of state.obstacles){o.x-=speed*dt;if(185>o.x+12&&135<o.x+o.w-12&&state.y-5>o.y+6&&py<o.y+o.h-6)hit();if(!state.running)return}for(const m of state.letters){m.x-=speed*dt;if(!m.taken&&Math.hypot(m.x-160,m.y-(state.y-42))<(state.role===0?110:42)){m.taken=true;state.mail++;G.sound('collect')}}state.obstacles=state.obstacles.filter(o=>o.x>-160);state.letters=state.letters.filter(o=>o.x>-60);$('#distance').textContent=Math.floor(state.distance)+' m';$('#mail').textContent=state.mail;$('#skill').disabled=state.role!==5||state.cool>0;$('#skill').textContent=state.role===5?(state.cool>0?'冷卻 '+Math.ceil(state.cool)+'s':'月光緩行 X'):state.role===1?(state.shield?'毛毯守護 1':'毛毯已使用'):'幸運吸信';$('#status').textContent=state.slow>0?'月光放慢了沿途的腳步。':state.mode==='mission'?'配送目標 '+goals[state.route]+' m':'跳過地面障礙，低枝葉用下滑。';if(state.mode==='mission'&&state.distance>=goals[state.route])finish(true)}
function draw(){ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,960,360);const bg=G.images['art-v2/'+(['scene','rain','moon'][state?.route??route])+'.webp'];if(bg){const shift=state?state.distance*2%960:0;const sh=bg.naturalWidth*360/960,sy=Math.max(0,bg.naturalHeight*((state?.route??route)===1?.745:.775)-ground*bg.naturalWidth/960);ctx.drawImage(bg,0,sy,bg.naturalWidth,sh,-shift,0,960,360);ctx.drawImage(bg,0,sy,bg.naturalWidth,sh,960-shift,0,960,360)}if(!state)return;const kit=G.images['art-v2/kit.webp'];for(const o of state.obstacles)G.trimTile(ctx,kit,o.type,3,2,o.x,o.y,o.w,o.h);for(const m of state.letters)if(!m.taken)G.tile(ctx,kit,3,3,2,m.x-22,m.y-22,44,44);const row=state.role===0?0:state.role===1?1:2,pose=state.slide>0?3:state.y<ground-1?2:Math.floor(state.time*9)%2;ctx.globalAlpha=state.invul>0&&Math.floor(state.time*12)%2?.45:1;G.tile(ctx,G.images['art-v2/runner.webp'],row*4+pose,4,3,110,state.y-100,100,100);ctx.globalAlpha=1;if(state.shield||state.slow>0)G.tile(ctx,kit,state.shield?5:4,3,2,130,state.y-135,55,55);if(state.countdown>0){ctx.fillStyle='#fff4bd';ctx.font='bold 34px serif';ctx.textAlign='center';ctx.fillText('準備出發',480,105)}if(state.crash){ctx.strokeStyle='#af5340';ctx.lineWidth=3;ctx.strokeRect(state.crash.x-25,state.crash.y-25,50,50)}}
function finish(win){if(!state.running)return;state.running=false;holding=false;G.playing(false);if(state.mode!=='practice'){data.mail+=state.mail;if(win){data.route=Math.max(data.route,Math.min(2,state.route+1));data.wins++}G.records(state.mode+'-'+state.route+'-'+state.role,Math.floor(state.distance));G.save()}G.sound(win?'win':'lose');G.dialog(win?'急件準時送達！':'先在路邊休息一下','<div class="dialog-stats"><span><b>'+Math.floor(state.distance)+'</b><small>公尺</small></span><span><b>'+state.mail+'</b><small>信件</small></span></div><p>'+G.roles[state.role]+' · '+routeNames[state.route]+'</p>',[['再跑一次',start],['回到快遞站',home]])}
function home(){holding=false;if(state)state.running=false;G.playing(false);G.resumeAudio();$('#home').hidden=false;$('#play').hidden=true;refresh()}
function pause(){holding=false;if(!state?.running||state.paused)return;state.paused=true;G.hold();G.dialog('快遞站替你保留路程','<p>角色、障礙及技能時間已暫停。</p>',[['繼續配送',()=>{state.paused=false;state.countdown=1;G.resumeAudio();G.orientation()}],['返回快遞站',home]])}
$('#start').onclick=start;$('#pause').onclick=pause;$('#jump').onpointerdown=e=>{e.preventDefault();jump()};canvas.onpointerdown=e=>{e.preventDefault();jump()};addEventListener('pointerup',()=>holding=false);addEventListener('pointercancel',()=>holding=false);$('#jump').onclick=e=>{if(e.detail===0){jump();holding=false}};$('#slide').onclick=slide;$('#skill').onclick=skill;addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(state?.running&&['Space','ArrowUp','ArrowDown','KeyX','Escape'].includes(e.code)){e.preventDefault();if(e.repeat)return;if(['Space','ArrowUp'].includes(e.code))jump();if(e.code==='ArrowDown')slide();if(e.code==='KeyX')skill();if(e.code==='Escape')pause()}});addEventListener('keyup',e=>{if(['Space','ArrowUp'].includes(e.code))holding=false});
$('#records').onclick=()=>G.dialog('這位夥伴的路程',G.recordHTML($('#mode').value+'-'+route+'-'+data.role,'公尺'),[['返回']]);$('#journal').onclick=()=>G.dialog('配送手帳','<p>累計 '+data.mail+' 封信 · '+data.wins+' 次送達</p>'+routeNames.map((n,i)=>'<article class="journal-row"><h3>'+n+'</h3><p>'+(i<=data.route?['森林的信：願每一次出發，都有人替你留燈。','雨後的信：不用跑得最快，也能把溫暖送到。','月夜的信：星光會記得，你走過的每一步。'][i]:'完成前一條路線後開啟')+'</p></article>').join(''),[['收好手帳']]);G.settings(["mode","hand"]);G.frame(update,draw);
