'use strict';const $=G.$,canvas=$('#canvas'),ctx=canvas.getContext('2d');let state=null,route=0,holding=false,ground=260;const routeNames=['森林郵路','雨露花園','月夜急件'],goals=[400,600,800],skills={2:'森林輕躍：成長的葉披風讓下落更輕緩，增加跨越障礙的時間。',0:'幸運採集：自動吸引附近 110 像素內的信件。',1:'安心毛毯：每局自動抵擋一次碰撞，之後短暫保護。',5:'月光緩行：按 X 或技能鈕，使障礙慢下來 3 秒；冷卻 20 秒。'};
const data=G.init({id:'dino',art:'art-v2',sounds:{"jump":"art-v2/jump.mp3","collect":"art-v2/collect.mp3"},music:'../storybook/audio/runner.mp3',orientation:'landscape',pause});data.route=G.clamp(Math.floor(data.route)||0,0,2);data.mail=G.clamp(Math.floor(data.mail)||0,0,1000000);data.hand=data.hand==='left'?'left':'right';$('#hand').value=data.hand;Object.assign(skills,{3:'回憶：每封信件算作 2 封。',4:'快樂：收集信件時短暫減緩障礙。',6:'信任：碰撞時自動保護一次。',7:'夢想：葉披風般的輕緩下落。',8:'悲傷：下滑維持更久，穿過低枝葉。',9:'希望：擴大信件收集範圍。'});G.rolePicker('#roles',G.roles.map((_,i)=>i),id=>{$('#skill-description').textContent=skills[id];});
function refresh(){route=0;$('#routes').replaceChildren();G.toast('選擇難度，跳過障礙，挑戰最遠距離。')}refresh();
const B='../storybook/art-20260920-batch/',M='../storybook/art-mobile24/',runnerNames={0:'luck',1:'healing',2:'growth',3:'memory',4:'joy',5:'night',6:'trust',7:'dream',8:'sadness',9:'hope'};function poseURL(id,p){return ([0,1,2,5].includes(id)?B:M)+runnerNames[id]+'-'+p+'.webp'}function loadRunner(id){return G.load(['run-0','run-1','jump','slide'].map(p=>poseURL(id,p)))}G.load([B+'dino-scene.webp']).catch(()=>{});const A='../storybook/art-20260914/';function art(name,x,y,w,h){const im=G.images[A+name+'.webp'];if(im?.naturalWidth)ctx.drawImage(im,x,y,w,h)}G.load(['dino-log','dino-crate','dino-branch','mail','gem-2','gem-3'].map(n=>A+n+'.webp')).catch(()=>{});

const silhouettes=new WeakMap();
function opaqueBounds(image){
  if(silhouettes.has(image))return silhouettes.get(image);
  const off=document.createElement('canvas');off.width=image.naturalWidth;off.height=image.naturalHeight;
  const context=off.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0);
  const pixels=context.getImageData(0,0,off.width,off.height).data;
  let left=off.width,right=0,top=off.height,bottom=0;
  for(let y=0;y<off.height;y++)for(let x=0;x<off.width;x++)if(pixels[(y*off.width+x)*4+3]>40){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}
  const bounds={left,top,right,bottom,width:Math.max(1,right-left+1),height:Math.max(1,bottom-top+1)};silhouettes.set(image,bounds);return bounds;
}
function runnerPose(){
  const action=state.slide>0?'slide':state.y<ground-1?'jump':'run-'+(Math.floor(state.time*9)%2);
  const image=G.images[poseURL(state.role,action)],standing=G.images[poseURL(state.role,'run-0')];
  if(!image?.naturalWidth||!standing?.naturalWidth)return null;
  const bounds=opaqueBounds(image),base=opaqueBounds(standing),scale=(state.role===4?136:112)/base.height;
  return {image,bounds,scale,width:bounds.width*scale,height:bounds.height*scale};
}
function playerHitbox(){
  const pose=runnerPose(),sliding=state.slide>0;
  // Use each pose's opaque body, excluding hats, capes and extended hands.
  const half=pose?Math.max(20,Math.min(sliding?35:29,pose.width*(sliding?.25:.23))):25;
  const height=pose?Math.min(sliding?46:76,pose.height*(sliding?.7:.68)):(sliding?34:66);
  return {left:160-half,right:160+half,top:state.y-height,bottom:state.y-5};
}

let starting=false;async function start(){if(starting)return;starting=true;try{await loadRunner(data.role);}catch{G.toast('角色動作未載入，請再試一次。');return;}finally{starting=false;}ground=[260,214,214][route];holding=false;$('#distance').textContent='0 m';$('#mail').textContent='0';state={running:true,paused:false,mode:'endless',difficulty:$('#difficulty').value,route,role:data.role,time:0,distance:0,mail:0,y:ground,vy:0,jumpHeld:0,slide:0,slow:0,cool:0,shield:[1,6].includes(data.role)?1:0,invul:0,next:1.6,obstacles:[],letters:[],countdown:1.2,jumpBuffer:0,crash:null};data.hand=$('#hand').value;G.save();document.body.classList.toggle('left-hand',data.hand==='left');$('#home').hidden=true;$('#play').hidden=false;$('#route-label').textContent=({easy:'簡單',normal:'普通',hard:'困難'})[state.difficulty]+' · 森林郵路';$('#skill').disabled=data.role!==5;$('#skill').textContent=({0:'幸運吸信',1:'毛毯守護',2:'森林輕躍',3:'雙倍信件',4:'歡樂緩行',5:'月光緩行 X',6:'信任守護',7:'夢想輕躍',8:'長效下滑',9:'希望採集'})[data.role];G.playing(true);canvas.focus({preventScroll:true})}
function jump(){if(window.CxQSession?.blocked()||!state?.running||state.paused||state.countdown>0)return;holding=true;state.jumpBuffer=.14;if(state.y>=ground-.5){state.slide=0;state.vy=-565;state.jumpHeld=0;state.jumpBuffer=0;G.sound('jump')}}
function slide(){if(window.CxQSession?.blocked()||!state?.running||state.paused||state.countdown>0)return;if(state.y>=ground-.5){state.slide=state.role===8?1:.7;G.sound('land')}}
function skill(){if(window.CxQSession?.blocked()||!state?.running||state.paused||state.countdown>0||state.role!==5||state.cool>0)return;state.slow=3;state.cool=20;G.sound('skill')}
function spawn(){let type=state.time<8?0:Math.random()<.28?2:Math.random()<.65?0:1;const o={x:canvas.width+60,type,w:type===2?125:type===1?64:84,h:type===2?45:type===1?65:48,y:type===2?ground-103:ground-(type===1?65:48)};state.obstacles.push(o);state.letters.push({x:canvas.width+60+(type===2?210:0),y:type===2?ground-45:ground-120,taken:false});state.next=state.time+({easy:2.1,normal:1.65,hard:1.35})[state.difficulty]+Math.random()*.55}
function hit(){if(state.invul>0)return;if(state.mode==='practice'){state.invul=1.4;state.crash={x:160,y:state.y-45};G.sound('miss');G.toast('練習中：這裡碰到了障礙，再試試跳躍或下滑。');return}if(state.shield){state.shield=0;state.invul=1.7;G.sound('skill');return}state.crash={x:160,y:state.y-45};finish(false)}
function update(dt){if(!state?.running||state.paused)return;if(state.countdown>0){state.countdown-=dt;$('#status').textContent='出發倒數 '+Math.ceil(state.countdown);return}state.time+=dt;state.jumpBuffer=Math.max(0,state.jumpBuffer-dt);state.slide=Math.max(0,state.slide-dt);state.cool=Math.max(0,state.cool-dt);state.slow=Math.max(0,state.slow-dt);state.invul=Math.max(0,state.invul-dt);state.jumpHeld+=dt;const speed=Math.min(({easy:350,normal:430,hard:510})[state.difficulty],({easy:230,normal:280,hard:330})[state.difficulty]+state.time*({easy:1,normal:1.6,hard:2.2})[state.difficulty])*(state.slow>0?.55:1);state.distance+=speed*dt/10;const prev=state.y;state.vy+=(holding&&state.vy<0&&state.jumpHeld<.18?850:[2,7].includes(state.role)?1450:1700)*dt;state.y=Math.min(ground,state.y+state.vy*dt);if(state.y===ground){if(prev<ground-1)G.sound('land');state.vy=0;if(!state.slide&&Math.floor(state.time*5)!==Math.floor((state.time-dt)*5))G.sound('step');if(state.jumpBuffer>0){state.slide=0;state.vy=-565;state.jumpHeld=0;state.jumpBuffer=0;G.sound('jump')}}if(state.time>=state.next)spawn();const box=playerHitbox();for(const o of state.obstacles){o.x-=speed*dt;if(box.right>o.x+12&&box.left<o.x+o.w-12&&box.bottom>o.y+6&&box.top<o.y+o.h-6)hit();if(!state.running)return}for(const m of state.letters){m.x-=speed*dt;if(!m.taken&&Math.hypot(m.x-160,m.y-(state.y-42))<(state.role===0?110:state.role===9?85:42)){m.taken=true;state.mail+=state.role===3?2:1;if(state.role===4)state.slow=Math.max(state.slow,.5);G.sound('collect')}}state.obstacles=state.obstacles.filter(o=>o.x>-160);state.letters=state.letters.filter(o=>o.x>-60);$('#distance').textContent=Math.floor(state.distance)+' m';$('#mail').textContent=state.mail;$('#skill').disabled=state.role!==5||state.cool>0;$('#skill').classList.toggle('passive-skill',state.role!==5);$('#skill').setAttribute('aria-label',skills[state.role]);$('#skill').textContent=state.role===5?(state.cool>0?'冷卻 '+Math.ceil(state.cool)+'s':'月光緩行 X'):[1,6].includes(state.role)?(state.shield?'守護 · 1 次':'守護已使用'):({0:'自動吸信',2:'輕緩下落',3:'雙倍信件',4:'歡樂緩行',7:'輕緩下落',8:'長效下滑',9:'希望採集'})[state.role];$('#slide').setAttribute('aria-pressed',String(state.slide>0));$('#slide').title=state.slide>0?'下滑剩餘 '+state.slide.toFixed(1)+' 秒':'下滑 0.7 秒';$('#status').textContent=state.slide>0?'下滑中 · '+state.slide.toFixed(1)+' 秒':state.slow>0?'月光緩行中 · '+Math.ceil(state.slow)+' 秒':state.mode==='mission'?'配送目標 '+goals[state.route]+' m':'跳過地面障礙，低枝葉用下滑。';if(state.mode==='mission'&&state.distance>=goals[state.route])finish(true)}
function draw(){ctx.imageSmoothingEnabled=true;ctx.clearRect(0,0,canvas.width,360);const bg=G.images[B+['dino-scene','dino-rain','dino-moon'][state?.route??route]+'.webp'];if(bg?.naturalWidth){const scroll=state?state.distance*.7:0,first=Math.floor(scroll/960),shift=scroll%960;for(let k=0,px=-shift;px<canvas.width;k++,px+=960){ctx.save();ctx.translate(px,0);if((first+k)%2){ctx.translate(960,0);ctx.scale(-1,1);}ctx.drawImage(bg,0,0,960,360);ctx.restore();}}if(!state)return;for(const o of state.obstacles)art(['dino-log','dino-crate','dino-branch'][o.type],o.x,o.y,o.w,o.h);for(const m of state.letters)if(!m.taken)art('mail',m.x-22,m.y-22,44,44);ctx.globalAlpha=state.invul>0&&Math.floor(state.time*12)%2?.45:1;ctx.save();ctx.translate(160,state.y);const pose=runnerPose();if(pose){const {image,bounds,scale}=pose;ctx.drawImage(image,-(bounds.left+bounds.width/2)*scale,-(bounds.bottom+1)*scale,image.naturalWidth*scale,image.naturalHeight*scale);}ctx.restore();ctx.globalAlpha=1;if(state.shield||state.slow>0)art(state.shield?'gem-2':'gem-3',130,state.y-135,55,55);if(state.countdown>0){ctx.fillStyle='#fff4bd';ctx.font='bold 34px serif';ctx.textAlign='center';ctx.fillText('準備出發',canvas.width/2,105)}if(state.crash)art('gem-2',state.crash.x-32,state.crash.y-32,64,64);}
function finish(win){if(!state.running)return;state.running=false;holding=false;G.playing(false);if(state.mode!=='practice'){data.mail+=state.mail;if(win){data.route=Math.max(data.route,Math.min(2,state.route+1));data.wins++}G.records('normal-'+state.difficulty+'-'+state.role,Math.floor(state.distance));G.save()}G.sound(win?'win':'lose');G.dialog(win?'急件準時送達！':'先在路邊休息一下','<div class="dialog-stats"><span><b>'+Math.floor(state.distance)+'</b><small>公尺</small></span><span><b>'+state.mail+'</b><small>信件</small></span></div><p>'+G.roles[state.role]+' · '+routeNames[state.route]+'</p>',[['再跑一次',start],['回到快遞站',home]])}
window.CxQGame={restart:start,home};
function home(){holding=false;if(state)state.running=false;G.playing(false);G.resumeAudio();$('#home').hidden=false;$('#play').hidden=true;refresh()}
function pause(){holding=false;if(!state?.running||state.paused)return;state.paused=true;G.hold();G.dialog('快遞站替你保留路程','<p>角色、障礙及技能時間已暫停。</p>',[['繼續配送',()=>{state.paused=false;state.countdown=1;G.resumeAudio();G.orientation()}],['返回快遞站',home]])}
$('#start').onclick=start;$('#pause').onclick=pause;$('#jump').onpointerdown=e=>{e.preventDefault();jump()};canvas.onpointerdown=e=>{e.preventDefault();jump()};addEventListener('pointerup',()=>holding=false);addEventListener('pointercancel',()=>holding=false);$('#jump').onclick=e=>{if(e.detail===0){jump();holding=false}};$('#slide').onclick=slide;$('#skill').onclick=skill;addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(state?.running&&['Space','ArrowUp','ArrowDown','KeyX','Escape'].includes(e.code)){e.preventDefault();if(e.repeat)return;if(['Space','ArrowUp'].includes(e.code))jump();if(e.code==='ArrowDown')slide();if(e.code==='KeyX')skill();if(e.code==='Escape')pause()}});addEventListener('keyup',e=>{if(['Space','ArrowUp'].includes(e.code))holding=false});
$('#records').onclick=()=>G.dialog('這位夥伴的路程',G.recordHTML('normal-'+$('#difficulty').value+'-'+data.role,'公尺'),[['返回']]);$('#journal').onclick=()=>G.dialog('配送手帳','<p>累計 '+data.mail+' 封信 · '+data.wins+' 次送達</p>'+routeNames.map((n,i)=>'<article class="journal-row"><h3>'+n+'</h3><p>'+(i<=data.route?['森林的信：願每一次出發，都有人替你留燈。','雨後的信：不用跑得最快，也能把溫暖送到。','月夜的信：星光會記得，你走過的每一步。'][i]:'完成前一條路線後開啟')+'</p></article>').join(''),[['收好手帳']]);G.settings(["difficulty","hand"]);G.frame(update,draw);
function fitRunner(){if(innerWidth<innerHeight||$('#play').hidden)return;const play=$('#play');canvas.width=Math.round(360*play.clientWidth/Math.max(120,play.clientHeight-148));}
new ResizeObserver(fitRunner).observe($('#play'));addEventListener('resize',fitRunner);
