import {cycleReadings} from './cycles.mjs';
import {validateBackup} from './storage.mjs';
import {modes,topics,signs,houses,tarot,runes,hexagrams,numbers,characters,lots} from './content.mjs';
import {taiwanDay,birthday,coinCast,readHex,drawTarot,shuffleTarot,drawRunes,drawLot,drawCharacter,zodiac,spreads,contextual} from './engine.mjs';
const root=document.getElementById('app'),legacy=new URLSearchParams(location.search).has('legacy');
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=id=>'seven-v3/art/'+id+'.webp',charArt=id=>'../../assets/mascot-motion-v2/'+id+'-idle.webp';
const KEY='cxq-oracle-seven-v3';let journal=window.CxQ.read(KEY,[]);if(!Array.isArray(journal))journal=[];journal=journal.filter(r=>r&&typeof r.id==='string'&&typeof r.title==='string'&&Array.isArray(r.sections)).slice(0,100);
let state={view:'home',mode:'tarot',topic:'self',question:'',spread:'single',count:1,sign:0,weekly:false,birth:'',lines:[],draw:[],result:null,busy:false,error:'',deleteId:null};
let astronomyPromise;
function astronomy(){return astronomyPromise??=new Promise((resolve,reject)=>{if(window.Astronomy)return resolve(window.Astronomy);const script=document.createElement('script');script.src='seven-v3/vendor/astronomy.browser.min.js';const timer=setTimeout(()=>{script.remove();astronomyPromise=null;reject(Error('星象載入逾時，請確認連線後再按一次閱讀星象。'));},10000);script.onload=()=>{clearTimeout(timer);resolve(window.Astronomy);};script.onerror=()=>{clearTimeout(timer);script.remove();astronomyPromise=null;reject(Error('星象計算程式未載入，請確認連線後重試。'));};document.head.append(script);});}
function header(){return `<header class="oracle-nav"><button data-action="home" class="oracle-brand"><small>CxQ</small><b>占卜館</b></button><nav aria-label="占卜導覽"><button data-action="journal">占卜手帳 <span>${journal.length}</span></button><a class="website-return" href="../../" aria-label="返回網站首頁"><img src="${art('return')}" alt="返回網站首頁" width="220" height="82"></a></nav></header>`;}
function home(){return `<div class="oracle-home"><section class="oracle-hero"><div><p class="eyebrow">${taiwanDay()} · 靜下來，選一種探索方式</p><h1>CxQ 占卜館</h1><p class="hero-title">讓心裡的問題，<br>有不同的入口。</p><p>七種占卜，七種觀看生活的角度。<br>從此刻的好奇開始，慢慢讀懂自己的選擇。</p><a class="oracle-primary" href="#oracle-modes">選擇占卜種類</a></div><figure><img src="${art('tarot')}" alt="月光、花葉與占卜牌" fetchpriority="high" width="900" height="600"><figcaption>象徵是思考的起點，選擇仍在你手中。</figcaption></figure></section><section id="oracle-modes"><div class="section-label"><p class="eyebrow">SEVEN WAYS TO REFLECT</p><h2>今天，想從哪裡開始？</h2></div><div class="oracle-modes">${modes.map((m,i)=>`<button data-mode="${m.id}"><img src="${art(m.id)}" alt="${m.name}專屬插畫" width="900" height="600" loading="${i<2?'eager':'lazy'}"><div><small>${m.tag}</small><h3>${m.name}</h3><p>${m.desc}</p><span>${m.action} →</span></div></button>`).join('')}</div></section><section class="oracle-legacy"><div><h2>熟悉的每日小提醒</h2><p>原本的今日、感情、工作、二選一與心情測驗，以及舊手帳仍完整保留。</p></div><a href="?legacy=1">打開原有占卜 →</a></section><details class="oracle-method"><summary>關於解讀、資料與保存</summary><p>所有中文解讀由 CxQ 編寫。塔羅沿用傳統 78 張與正逆位架構；易經採三錢法；盧恩採 24 枚古弗薩克，現代象徵解讀不等同古代史實。籤詩與角色牌為 CxQ 原創，不冒稱廟宇籤系。</p><p>星座使用 Astronomy Engine 實際計算地心黃道位置，以熱帶黃道、太陽星座整宮方式閱讀；是一般星座解讀，不是個人出生星盤。星體位置是天文計算，運勢文字是象徵詮釋。</p><p>生日、問題與手帳只在這台裝置處理。結果是自我探索的提示，不代表事件一定發生。</p><a href="seven-v3/CREDITS.md" target="_blank" rel="noopener">內容、規則與素材來源</a></details></div>`;}
function options(items,selected){return Object.entries(items).map(([id,name])=>`<option value="${id}" ${String(selected)===id?'selected':''}>${esc(name)}</option>`).join('');}
function prepare(){const m=modes.find(m=>m.id===state.mode);let controls='';
 if(state.mode==='tarot')controls=`<label>選擇牌陣<select aria-label="選擇牌陣" name="spread">${options({single:'單張・當下提醒',three:'三張・處境／阻力／方向',relationship:'關係・自己／互動／調整',choice:'選擇・A 課題／B 課題／共同提醒'},state.spread)}</select></label><p class="field-help">完整 78 張牌，不重複抽取；正逆位分開解讀。選擇牌陣不替你判定哪個選項必然成功。</p><div class="option-pair" ${state.spread==='choice'?'':'hidden'}><label>選項 A（選擇牌陣用）<input name="optionA" maxlength="80" value="${esc(state.optionA||'')}" placeholder="例如：留在目前的位置"></label><label>選項 B（選擇牌陣用）<input name="optionB" maxlength="80" value="${esc(state.optionB||'')}" placeholder="例如：嘗試新方向"></label></div>`;
 if(state.mode==='zodiac')controls=`<label>太陽星座<select aria-label="太陽星座" name="sign">${options(Object.fromEntries(signs.map((s,i)=>[i,s])),state.sign)}</select></label><label>閱讀範圍<select aria-label="閱讀範圍" name="weekly">${options({day:'每日運勢',week:'每週運勢（週一至週日）'},state.weekly?'week':'day')}</select></label><p class="field-help">按台灣時間自動更新；每日取中午星象，每週計算七天。同一日期與星座的內容一致，不需要每年重新編寫。</p>`;
 if(state.mode==='numbers')controls=`<label>出生日期<input type="date" name="birth" min="1900-01-01" max="${taiwanDay()}" value="${esc(state.birth)}" required></label><p class="field-help">生命靈數：將完整生日數字相加，保留主數 11、22、33。個人年採曆年制，個人月隨月份更新；這是本站採用的數字學慣例。</p>`;
 if(state.mode==='iching')controls='<p class="field-help">每次擲三枚錢幣，正面 3、反面 2。共六次，由下往上成卦；6 與 9 為動爻。顯示本卦、動爻與之卦，並提供 CxQ 白話卦義。</p>';
 if(state.mode==='lots')controls='<p class="field-help">24 首專為 CxQ 寫作的籤詩，包含原創詩文、白話、吉／平／慎提醒與行動方向。並非任何廟宇的正式籤詩，也不以吉凶保證結果。</p>';
 if(state.mode==='runes')controls=`<label>符文陣<select aria-label="符文陣" name="count">${options({1:'單符文・當下提醒',3:'三符文・力量／阻力／方向'},state.count)}</select></label><p class="field-help">24 枚古弗薩克，不加入空白符文、不使用逆位。名稱與象徵分別列出；占卜意義為現代詮釋。</p>`;
 if(state.mode==='characters')controls='<p class="field-help">十位角色與小箱子本人，各有代表詞與專屬訊息。代表詞是象徵，不是角色的名字；所有內容為 CxQ 原創。</p>';
 return `<section class="oracle-session"><button class="text-back" data-action="home">← 返回占卜館</button><div class="session-grid"><figure><img src="${art(state.mode)}" alt="${m.name}專屬美術" width="900" height="600"><figcaption>${m.tag}</figcaption></figure><form id="oracle-form"><p class="eyebrow">${m.tag}</p><h1>${m.name}</h1><p>${m.desc}</p>${controls}${state.mode!=='zodiac'&&state.mode!=='numbers'?`<label>想探索的主題<select aria-label="想探索的主題" name="topic">${options(Object.fromEntries(Object.entries(topics).map(([k,v])=>[k,v.name])),state.topic)}</select></label><label>你的問題（可留白）<textarea name="question" maxlength="280" placeholder="例如：我該怎麼理解目前的處境？">${esc(state.question)}</textarea></label>`:''}<button type="button" data-action="library">查看本類內容與牌義</button><p class="privacy-copy">不需登入，輸入內容不會上傳。完成後可儲存至本機手帳。</p><p class="form-error" role="alert">${esc(state.error)}</p><button class="oracle-primary" type="submit" ${state.busy?'disabled':''}>${state.busy?'正在計算星象…':m.action}</button></form></div></section>`;}
function ritual(){const mode=state.mode;let content='';
 if(mode==='iching'){content=`<h1>擲下第 ${state.lines.length+1} 次錢幣</h1><p>六爻由下往上，已完成 ${state.lines.length}／6 次。</p><div class="coin-stage"><img src="${art('iching')}" alt="三枚起卦錢幣"><div class="cast-progress" aria-live="polite">${state.lines.slice().reverse().map((n,i)=>`<div>${n%2?'━━━━━━':'━━　━━'} <small>第 ${state.lines.length-i} 爻・${n}${n===6||n===9?'・動':''}</small></div>`).join('')||'等待第一爻'}</div></div><button class="oracle-primary" data-action="cast">擲三枚錢幣</button>`;}
 else if(mode==='tarot'||mode==='runes'){const total=mode==='tarot'?spreads[state.spread].length:state.count,drawn=state.draw.length,isTarot=mode==='tarot';content=`<h1>${isTarot?'洗牌之後，選擇吸引你的牌。':'把手伸進符文袋，取出一枚。'}</h1><p aria-live="polite">已抽取 ${drawn}／${total} ${isTarot?'張牌':'枚符文'}；每次抽取不重複。</p><div class="draw-stage ${isTarot?'tarot-fan':''}">${Array.from({length:isTarot?7:total},(_,i)=>{const selected=isTarot?state.draw.find(c=>c.id===state.deck[i].id):state.draw[i];return `<button data-action="draw" data-draw-index="${i}" ${isTarot?(selected?'disabled':''):(i!==drawn?'disabled':'')} aria-label="抽取第 ${i+1} ${isTarot?'張牌':'枚符文'}" class="draw-object ${selected?'opened':''}"><img src="${isTarot?(selected?cardArt(selected.id):'assets/ritual-v2/oracle-back.webp'):art('runes')}" alt="${isTarot?(selected?esc(selected.name):'占卜牌背'):'符文袋'}"><span>${selected?esc(selected.name):isTarot?'選這張牌':i===drawn?'點擊抽取':'等待抽取'}</span></button>`;}).join('')}</div><button class="text-back" data-action="shuffle">重新${isTarot?'洗牌':'整理符文袋'}</button>`;}
 else content=`<h1>${mode==='lots'?'搖籤，讓一首詩與你相遇。':'打開一封角色寄來的信。'}</h1><p>先安靜想著自己的問題，再點擊${mode==='lots'?'籤筒':'信封'}。</p><button class="ritual-illustration" data-action="open" aria-label="${mode==='lots'?'搖動籤筒':'打開角色信封'}"><img src="${art(mode)}" alt="${mode==='lots'?'木製籤筒':'角色信封'}"><span>${mode==='lots'?'點擊搖籤筒':'點擊打開信封'}</span></button>`;
 return `<section class="oracle-ritual"><button class="text-back" data-action="prepare">← 重新設定</button><p class="eyebrow">${modes.find(m=>m.id===mode).name}</p>${content}</section>`;}
function positionText(position,card={}){if(position.includes('阻力'))return card.reversed?'在阻力位，先辨認上面提到的失衡如何影響你的問題；調整做法比責怪自己更有用。':'在阻力位，請問自己：「'+(card.keywords||card.key||'這股力量')+'」是否不足、使用過度，或欠缺合適的支持與界線？正向象徵也可能提示尚未運用的資源。';if(position.includes('方向')||position.includes('調整'))return card.reversed?'在方向位，先照顧這項失衡，再把牌義轉成可承受的小步驟。':'在方向位，把這個象徵轉成接下來可以實踐的調整。';if(position.includes('選項 A'))return '針對 A「'+(state.optionA||'尚未命名')+'」，思考它要求你面對的課題。';if(position.includes('選項 B'))return '針對 B「'+(state.optionB||'尚未命名')+'」，思考它要求你面對的課題。';return '從這個位置觀看目前的狀態，並與實際經驗對照。';}
function createResult(){const mode=state.mode,ctx=contextual(state.topic);let title='',summary='',sections=[],visuals=[],meta='';
 if(mode==='tarot'){title=state.draw.map(c=>c.name).join('・');summary=state.draw.length===1?'這張牌是本次問題的觀看角度。':'這個牌陣依序呈現「'+spreads[state.spread].join(' → ')+'」。各位置互相補充，不把不同訊息硬合成單一吉凶。';sections=state.draw.map(c=>({title:c.position+'｜'+c.name+'・'+(c.reversed?'逆位':'正位'),text:(c.reversed?c.down:c.up)+' '+positionText(c.position,c),action:c.action}));visuals=state.draw.map(c=>({kind:'tarot',name:c.name,id:c.id,reversed:c.reversed}));meta='傳統 78 張架構・CxQ 中文解讀';}
 if(mode==='runes'){title=state.draw.map(r=>r.name).join('・');summary='古弗薩克符文的現代象徵閱讀；本次不使用逆位或空白符文。';sections=state.draw.map(r=>({title:r.position+'｜'+r.name+'・'+r.key,text:r.meaning+' '+positionText(r.position,r),action:r.action}));visuals=state.draw.map(r=>({kind:'rune',glyph:r.glyph,name:r.name}));meta='24 枚古弗薩克・現代占卜詮釋';}
 if(mode==='iching'){const h=readHex(state.lines);title='第 '+h.primary.id+' 卦・'+h.primary.name+(h.relating?' → '+h.relating.name:'');summary='本卦「'+h.primary.key+'」描述目前的觀看角度。'+(h.relating?'之卦提供變化後可參照的另一種處境，不代表必然發生。':'本次沒有動爻，先專注本卦的整體提醒。');sections=[{title:'本卦｜'+h.primary.name+'・'+h.primary.key,text:h.primary.meaning+' '+h.primary.caution,action:h.primary.action},...h.moving.map(n=>({title:'第 '+n+' 爻為動爻',text:['起點與根基：觀察改變是否準備充分。','內在執行：留意日常做法能否支撐方向。','內外交界：跨出熟悉範圍前先核對條件。','接近外部：確認合作與責任的界線。','核心決策：衡量影響並承擔選擇。','階段盡頭：避免過度，檢視是否需要收束。'][n-1]+' 本爻 '+state.lines[n-1]+'，'+(state.lines[n-1]===6?'陰轉陽':'陽轉陰')+'。這是 CxQ 爻位提示，不冒充經文爻辭。'})),...(h.relating?[{title:'之卦｜'+h.relating.name+'・'+h.relating.key,text:h.relating.meaning+' '+h.relating.caution,action:h.relating.action}]:[])];visuals=[{kind:'hex',name:h.primary.name,bits:h.primary.bits,moving:h.moving},...(h.relating?[{kind:'hex',name:h.relating.name,bits:h.relating.bits,moving:[]}]:[])];meta='三錢法・由下往上：'+state.lines.join('、');}
 if(mode==='lots'){const r=state.lot;title='第 '+r.id+' 籤・'+r.title;summary=r.meaning;sections=[{title:'CxQ 原創籤詩｜'+r.grade,text:r.poem},{title:'白話解籤',text:r.meaning,action:r.action}];visuals=[{kind:'image',src:art('lots'),name:'原創籤詩'}];meta='CxQ 原創 24 籤・非廟宇籤系';}
 if(mode==='characters'){const r=state.character;title=r.name+'的信・'+r.key;summary=r.meaning;sections=[{title:r.name+'想告訴你',text:r.meaning,action:r.action},{title:'代表詞與名字',text:'「'+r.key+'」是'+r.name+'這張角色牌的象徵主題，不是名字。你可以接受這個提醒，也可以記下不同的感受。'}];visuals=[{kind:'image',src:charArt(r.id),name:r.name}];meta='CxQ 原創角色牌・十位角色與小箱子';}
 if(mode==='numbers'){const r=birthday(state.birth);title='生命靈數 '+r.life+'・'+r.detail[0].key;summary=r.detail[0].meaning;sections=r.detail.map((n,i)=>({title:['生命靈數 '+r.life,r.year+' 個人年 '+r.personalYear,r.month+' 月個人月 '+r.personalMonth][i]+'｜'+n.key,text:i===0?n.meaning+' '+n.caution:cycleReadings[n.value-1][i-1],action:n.action}));sections.push({title:'計算方式',text:'生日各位數總和 '+r.sum+' → '+r.life+'（保留 11、22、33）。個人年＝出生月＋出生日＋今年年份，各自化簡後再加總至個位數；個人月＝個人年＋目前月份再化簡。本站採 1 月 1 日換個人年的曆年制。'});visuals=[{kind:'number',name:'生命靈數',value:r.life},{kind:'number',name:'個人年',value:r.personalYear},{kind:'number',name:'個人月',value:r.personalMonth}];meta='西方數字學慣例・不作科學人格測驗';}
 if(mode==='zodiac'){const r=state.sky;title=r.sign+'・'+(r.weekly?'每週運勢':'每日運勢');summary=r.start+(r.weekly?' 至 '+r.end:'')+'（台灣時間）。以太陽星座為第一宮的整宮方式，閱讀七顆星體帶來的主題。';sections=r.entries.map(e=>({title:e.title,text:e.text,action:houses[e.house][1]}));sections.push(...r.aspects.slice(0,3).map(a=>({title:a.a+' × '+a.b+'・'+a.name,text:a.tone+' 與精確相位差 '+a.orb.toFixed(2)+'°。週運相位以週一起始日為基準。'})));if(r.weekly)sections.push(...r.tracks.map(t=>{const moon=t.positions.find(p=>p.body==='Moon');return {title:t.day+'｜月亮在'+signs[moon.sign],text:r.entries.find(e=>e.body==='Moon').theme+'：'+houses[moon.house][0]+'。'+houses[moon.house][1]};}));sections.push({title:'星象計算依據',text:r.entries.map(e=>e.name+'：'+signs[e.sign]+' '+(e.lon%30).toFixed(2)+'°').join('；')+'。每日取台灣中午，週運取七天每日中午位置。相位容許度 5°；運勢為 CxQ 象徵解讀，不是事件機率。'});visuals=[{kind:'image',src:art('zodiac'),name:r.sign}];meta='Astronomy Engine・熱帶黃道・太陽星座整宮';}
 if(!['numbers','zodiac'].includes(mode))sections.push({title:ctx.name+'的對照問題',text:ctx.prompt,action:ctx.action});
 return {id:crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join(''),kind:mode,mode:modes.find(m=>m.id===mode).name,title,summary,sections,visuals,meta,question:state.question,topic:ctx.name,created:new Date().toISOString(),note:''};
}
function cardArt(id){return id<22?art('major-'+id):art('minor-'+(id-22));}
function visual(v){if(v.kind==='tarot')return `<figure class="tarot-face"><img class="${v.reversed?'reversed':''}" src="${cardArt(v.id)}" alt="${esc(v.name)}象徵插畫"><figcaption>${esc(v.name)}・${v.reversed?'逆位':'正位'}</figcaption></figure>`;if(v.kind==='rune')return `<figure class="rune-face"><img src="${art('runes')}" alt="符文石插畫"><b>${esc(v.glyph)}</b><figcaption>${esc(v.name)}</figcaption></figure>`;if(v.kind==='hex')return `<figure class="hex-face"><div>${v.bits.split('').map((b,i)=>`<p class="${v.moving.includes(i+1)?'moving':''}">${b==='1'?'━━━━━━':'━━　━━'}${v.moving.includes(i+1)?'<i>動</i>':''}</p>`).reverse().join('')}</div><figcaption>${esc(v.name)}卦</figcaption></figure>`;if(v.kind==='number')return `<figure class="number-face"><b>${v.value}</b><figcaption>${esc(v.name)}</figcaption></figure>`;return `<figure class="image-face"><img src="${esc(v.src)}" alt="${esc(v.name)}"><figcaption>${esc(v.name)}</figcaption></figure>`;}
function result(){const r=state.result,saved=journal.some(j=>j.id===r.id);return `<section class="oracle-result"><button class="text-back" data-action="prepare">← 返回設定</button><div class="result-heading"><p class="eyebrow">${esc(r.mode)} · ${esc(r.meta)}</p><h1>${esc(r.title)}</h1><p>${esc(r.summary)}</p>${r.question?`<p class="question-echo">你問的是：${esc(r.question)}</p>`:''}</div><div class="reading-visuals">${r.visuals.map(visual).join('')}</div><div class="reading-sections">${r.sections.map(s=>`<article><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p>${s.action?`<aside><small>可以嘗試</small><p>${esc(s.action)}</p></aside>`:''}</article>`).join('')}</div><section class="reflection"><label>留給自己的筆記<textarea id="oracle-note" maxlength="1000" placeholder="哪些內容與你的實際經驗相近？哪些不同？">${esc(r.note)}</textarea></label><div class="result-actions"><button class="oracle-primary" data-action="save">${saved?'更新手帳筆記':'儲存至占卜手帳'}</button><button data-action="journal">打開手帳</button><button data-action="prepare">重新探索</button></div><p id="save-status" aria-live="polite">${saved?'這則結果已儲存在這台裝置。':'只有按下儲存才會收進新手帳。'}</p></section></section>`;}
function journalView(){return `<section class="oracle-journal"><button class="text-back" data-action="home">← 返回占卜館</button><p class="eyebrow">只保存在這台裝置・最多 100 則</p><h1>占卜手帳</h1><p>保存完整牌陣與解讀，讓未來的自己讀到當時的想法。</p><div class="journal-toolbar"><button data-action="export">匯出備份</button><label class="import-label">匯入備份<input id="journal-import" type="file" accept="application/json,.json"></label><a href="?legacy=1">查看舊版手帳</a></div><p class="form-error" role="status">${esc(state.error)}</p>${journal.length?journal.map(r=>`<article class="journal-record"><small>${esc(new Date(r.created).toLocaleString('zh-TW'))} · ${esc(r.mode)}</small><h2>${esc(r.title)}</h2><p>${esc(r.summary)}</p><div><button data-read="${esc(r.id)}">閱讀完整解讀</button><button data-delete="${esc(r.id)}">刪除紀錄</button></div>${state.deleteId===r.id?`<div class="delete-confirm"><p>確定刪除這一則？</p><button data-confirm-delete="${esc(r.id)}">確定刪除</button><button data-action="cancel-delete">保留</button></div>`:''}</article>`).join(''):'<div class="journal-empty-new">還沒有紀錄。完成任何一種占卜後，都可以把結果收進來。</div>'}</section>`;}
function library(){const collections={tarot:tarot.map(c=>({name:c.name,key:c.keywords,text:'正位：'+c.up+'\n逆位：'+c.down+'\n行動：'+c.action})),runes:runes.map(r=>({name:r.glyph+' '+r.name,key:r.key,text:r.meaning+'\n行動：'+r.action})),iching:hexagrams.map(h=>({name:h.id+'・'+h.name,key:h.key,text:h.meaning+'\n'+h.caution+'\n行動：'+h.action})),lots:lots.map(r=>({name:r.id+'・'+r.title,key:r.grade,text:r.poem+'\n白話：'+r.meaning+'\n行動：'+r.action})),characters:characters.map(r=>({name:r.name,key:r.key,text:r.meaning+'\n行動：'+r.action})),numbers:numbers.map(n=>({name:String(n.value),key:n.key,text:n.meaning+'\n留意：'+n.caution+'\n行動：'+n.action})),zodiac:signs.map((name,i)=>({name,key:'太陽星座整宮閱讀',text:'選擇'+name+'時，以此星座為第一宮，依序分配十二個生活領域。每日與每週的星體位置由本機星曆計算，不是固定抽取運勢文。'}))};return `<section class="oracle-library"><button class="text-back" data-action="prepare">← 返回設定</button><p class="eyebrow">內容可自由查閱</p><h1>${modes.find(m=>m.id===state.mode).name}・內容手冊</h1><label>搜尋名稱或主題<input id="library-search" type="search" placeholder="輸入名稱或關鍵字"></label><div class="library-entries">${collections[state.mode].map(r=>`<details data-library-entry><summary>${esc(r.name)} <small>${esc(r.key)}</small></summary><p>${esc(r.text)}</p></details>`).join('')}</div></section>`;}
function render(scroll=false){if(legacy)return;document.title='CxQ 占卜館';root.innerHTML=`<main class="oracle-app">${header()}${state.view==='home'?home():state.view==='prepare'?prepare():state.view==='ritual'?ritual():state.view==='result'?result():state.view==='library'?library():journalView()}<footer class="oracle-footer">把象徵留作提醒，把決定留給自己。<a href="../../">CxQ 網站首頁</a></footer></main>`;if(scroll)scrollTo({top:0,behavior:'instant'});}
function complete(){state.result=createResult();state.view='result';window.CxQ.sound('win');render(true);}
async function submit(e){e.preventDefault();if(state.busy)return;const f=new FormData(e.target);state.topic=f.get('topic')||'self';state.question=String(f.get('question')||'').slice(0,280);state.spread=f.get('spread')||'single';state.count=+(f.get('count')||1);state.sign=+(f.get('sign')||0);state.weekly=f.get('weekly')==='week';state.birth=String(f.get('birth')||'');state.optionA=String(f.get('optionA')||'').slice(0,80);state.optionB=String(f.get('optionB')||'').slice(0,80);state.error='';state.lines=[];state.draw=[];
 try{if(state.mode==='numbers'){birthday(state.birth);complete();return;}if(state.mode==='zodiac'){state.busy=true;render();const A=await astronomy();state.sky=zodiac(state.sign,taiwanDay(),state.weekly,A);state.busy=false;complete();return;}state.deck=state.mode==='tarot'?shuffleTarot():state.mode==='runes'?drawRunes(state.count):[];state.view='ritual';render(true);}catch(err){state.error=err.message;state.busy=false;render();}}
function save(){state.result.note=root.querySelector('#oracle-note').value.slice(0,1000);const next=[state.result,...journal.filter(r=>r.id!==state.result.id)].slice(0,100);if(window.CxQ.write(KEY,next)){journal=next;root.querySelector('#save-status').textContent='完整解讀與筆記已儲存。';root.querySelector('[data-action="save"]').textContent='更新手帳筆記';}else root.querySelector('#save-status').textContent='裝置儲存空間不足或無法存取，請先複製筆記，勿關閉頁面。';}
function exportJournal(){const blob=new Blob([JSON.stringify({format:'cxq-oracle-seven-v3',version:1,entries:journal},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='CxQ-占卜手帳-'+taiwanDay()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if(!legacy){CxQ.configure({music:'heavenly'});root.addEventListener('input',e=>{if(e.target.id==='library-search'){const query=e.target.value.trim().toLocaleLowerCase();root.querySelectorAll('[data-library-entry]').forEach(row=>{row.hidden=!row.textContent.toLocaleLowerCase().includes(query);});}});root.addEventListener('submit',e=>{if(e.target.id==='oracle-form')submit(e)});root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.mode){state={...state,mode:b.dataset.mode,view:'prepare',error:'',busy:false};render(true);return;}if(b.dataset.read){state.result=structuredClone(journal.find(r=>r.id===b.dataset.read));state.mode=state.result.kind;state.view='result';render(true);return;}if(b.dataset.delete){state.deleteId=b.dataset.delete;render();return;}if(b.dataset.confirmDelete){const next=journal.filter(r=>r.id!==b.dataset.confirmDelete);if(CxQ.write(KEY,next)){journal=next;state.deleteId=null;}else state.error='無法刪除，請確認裝置儲存權限。';render();return;}const a=b.dataset.action;if(!a)return;if(a==='save'){save();return;}if(a==='export'){exportJournal();return;}if(a==='home'||a==='journal'||a==='prepare'||a==='library'){if(state.busy)return;if(a==='library'){const form=root.querySelector('#oracle-form');if(form){const f=new FormData(form);for(const key of ['question','topic','spread','birth','optionA','optionB'])if(f.has(key))state[key]=String(f.get(key));if(f.has('sign'))state.sign=+f.get('sign');if(f.has('count'))state.count=+f.get('count');if(f.has('weekly'))state.weekly=f.get('weekly')==='week';}}state.view=a;state.error='';render(true);return;}if(a==='cancel-delete'){state.deleteId=null;render();return;}if(a==='shuffle'){state.draw=[];state.deck=state.mode==='tarot'?shuffleTarot():drawRunes(state.count);render();return;}if(a==='draw'){if(state.mode==='tarot'){const c=state.deck[+b.dataset.drawIndex];if(state.draw.some(r=>r.id===c.id))return;state.draw.push({...c,position:spreads[state.spread][state.draw.length]});}else state.draw.push(state.deck[state.draw.length]);CxQ.sound('flip');if(state.draw.length===(state.mode==='tarot'?spreads[state.spread].length:state.count))complete();else render();return;}if(a==='cast'){state.lines.push(coinCast());CxQ.sound('flip');if(state.lines.length===6)complete();else render();return;}if(a==='open'){if(state.busy)return;state.busy=true;b.disabled=true;b.classList.add('is-opening');CxQ.sound('flip');setTimeout(()=>{state.busy=false;if(state.mode==='lots')state.lot=drawLot();else state.character=drawCharacter();complete();},650);}});
 root.addEventListener('change',async e=>{if(e.target.name==='spread'){root.querySelector('.option-pair').hidden=e.target.value!=='choice';return;}if(e.target.id!=='journal-import')return;try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('備份檔過大（上限 2 MB）。');const entries=validateBackup(JSON.parse(await file.text())),merged=[...new Map([...journal,...entries].map(r=>[r.id,r])).values()].sort((a,b)=>Date.parse(b.created)-Date.parse(a.created)).slice(0,100);if(!CxQ.write(KEY,merged))throw Error('裝置無法保存，沒有匯入資料。');journal=merged;state.error='備份已合併，重複紀錄不會增加。';}catch(err){state.error=err.message;}render();});render();}
