'use strict';
const C=document.getElementById('game'),X=C.getContext('2d');
document.documentElement.style.background='#071325';document.body.style.margin='0';document.body.style.overflow='hidden';document.body.style.background='#071325';C.style.display='block';C.style.width='100vw';C.style.height='100vh';C.style.touchAction='none';
const W=1600,H=900,OLD='../../fortune/assets/',A='assets/';
const CF=['joy.png','dream.png','night.png','sadness.png','trust.png','memory.png','growth.png','healing.png','luck.png','hope.png'];
const CN=['慶典少女','星夢魔女','夜鈴米亞','雨音澄澄','鑰匙守護者','記憶偵探','森林旅人','棉糖汪汪','森鈴芽獸','希望旅人'];
const CT=['幸運型','骰控型','卡片型','防禦型','商店型','移動型','土地型','小遊戲型','收租型','特殊型'];
const I={};function load(k,u){const m=new Image();m.src=u;I[k]=m;return m;}
load('bg',OLD+'backgrounds/destiny-village.png');CF.forEach((f,i)=>load('c'+i,OLD+'characters/'+f));load('btnRed',A+'btn_red.webp');load('btnBlue',A+'btn_blue.webp');load('tileStart',A+'tile_start.webp');load('tileLand',A+'tile_land.webp');
const S={scene:'home',buttons:[],seats:[{type:'human',char:0},{type:'ai',char:1},{type:'off',char:2},{type:'off',char:3}],activeSeat:0,money:300000,rounds:30,board:null,dice:1,moving:false,msg:''};
function resize(){const d=Math.min(devicePixelRatio||1,2);C.width=Math.round(innerWidth*d);C.height=Math.round(innerHeight*d)}addEventListener('resize',resize);resize();
function begin(){X.setTransform(C.width/W,0,0,C.height/H,0,0);X.clearRect(0,0,W,H);S.buttons=[]}
function txt(s,x,y,z=26,a='center',c='#fff',w=800,o=true){X.save();X.font=`${w} ${z}px system-ui,-apple-system,"Noto Sans TC",sans-serif`;X.textAlign=a;X.textBaseline='middle';if(o){X.lineWidth=Math.max(2,z/8);X.strokeStyle='rgba(25,13,21,.9)';X.strokeText(String(s),x,y)}X.fillStyle=c;X.fillText(String(s),x,y);X.restore()}
function contain(im,x,y,w,h,alpha=1){if(!im||!im.complete||!im.naturalWidth)return;const r=Math.min(w/im.naturalWidth,h/im.naturalHeight),iw=im.naturalWidth*r,ih=im.naturalHeight*r;X.save();X.globalAlpha=alpha;X.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih);X.restore()}
function cover(im,x,y,w,h,alpha=1){if(!im||!im.complete||!im.naturalWidth)return;const r=Math.max(w/im.naturalWidth,h/im.naturalHeight),iw=im.naturalWidth*r,ih=im.naturalHeight*r;X.save();X.globalAlpha=alpha;X.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih);X.restore()}
function bg(dim=.13){cover(I.bg,0,0,W,H);X.fillStyle=`rgba(4,11,24,${dim})`;X.fillRect(0,0,W,H)}
function btn(id,label,x,y,w,h,red=false,alpha=1,en=true){contain(red?I.btnRed:I.btnBlue,x,y,w,h,alpha);txt(label,x+w/2,y+h*.46,Math.min(30,h*.34),'center','#fff',900,true);S.buttons.push({id,x,y,w,h,en})}
function active(){return S.seats.map((s,i)=>s.type!=='off'?i:-1).filter(i=>i>=0)}
function humans(){return S.seats.filter(s=>s.type==='human').length}
function assigned(ci){return active().find(i=>S.seats[i].char===ci)}
function choose(ci){const a=S.activeSeat,b=assigned(ci);if(b!==undefined&&b!==a){const old=S.seats[a].char;S.seats[a].char=ci;S.seats[b].char=old}else S.seats[a].char=ci}
function title(){txt('CxQ',345,115,86,'center','#ffd76b',1000,true);txt('童話大富翁',345,190,68,'center','#fff0b1',1000,true);txt('大富翁4式回合競賽・手機版',345,246,21,'center','#fff',800,true)}
function home(){bg(.06);title();contain(I.c4,885,75,310,400,.95);contain(I.c0,650,340,290,390);contain(I.c1,900,350,285,385);contain(I.c2,1130,330,300,400);contain(I.c8,1360,490,180,230,.96);btn('start','開始遊戲',100,330,390,105,true);btn('continue','繼續遊戲',100,455,390,86,false,.65,!!localStorage.getItem('cxq_v6_first'));btn('help','遊戲說明',100,558,390,86,false);txt('第一批正式素材：AI按鈕 + 起點格 + 土地格',800,850,20,'center','#fff3cf',800,true)}
function charCard(i,x,y,w,h){const own=assigned(i),sel=S.seats[S.activeSeat].char===i;contain(I['c'+i],x,y,w,h-40,own!==undefined&&!sel?.68:1);if(sel){X.save();X.strokeStyle='#ffe27c';X.lineWidth=6;X.beginPath();X.arc(x+w/2,y+(h-40)/2,Math.min(w,h)*.42,0,Math.PI*2);X.stroke();X.restore()}txt(CN[i],x+w/2,y+h-18,15,'center','#fff',850,true);if(own!==undefined)txt((own+1)+'P',x+22,y+18,17,'center',['#ff6d69','#6db6ff','#7dcc75','#efc04f'][own],1000,true);S.buttons.push({id:'char'+i,x,y,w,h,en:true})}
function seat(i,x,y,w,h){const s=S.seats[i],selected=S.activeSeat===i;contain(I['c'+s.char],x+6,y+4,82,88,s.type==='off'?.38:1);txt((i+1)+'P',x+90,y+22,23,'left',selected?'#ffe57e':'#fff',1000,true);txt(s.type==='off'?'空席':CN[s.char],x+90,y+52,15,'left','#fff',750,true);btn('human'+i,'真人',x+5,y+82,70,38,false,s.type==='human'?1:.42);btn('ai'+i,'AI',x+80,y+82,63,38,true,s.type==='ai'?1:.42);btn('off'+i,'空席',x+148,y+82,70,38,false,s.type==='off'?1:.42);S.buttons.push({id:'seat'+i,x,y,w,h,en:true})}
function setup(){bg(.2);btn('back','返回',25,22,150,58,false);txt('角色選擇 / 玩家控制方式',800,54,38,'center','#fff0b6',1000,true);txt('先點下方席位，再直接選角色；每席位都有 真人 / AI / 空席',800,94,18,'center','#fff',750,true);const gx=66,gy=126,cw=182,ch=214,g=18;for(let i=0;i<10;i++)charCard(i,gx+(i%5)*(cw+g),gy+Math.floor(i/5)*(ch+g),cw,ch);const ci=S.seats[S.activeSeat].char;contain(I['c'+ci],1060,130,205,285);txt(CN[ci],1280,180,32,'left','#fff0b2',950,true);txt(CT[ci],1280,224,19,'left','#d9e8ff',800,true);txt('目前控制：'+(S.seats[S.activeSeat].type==='human'?'真人':S.seats[S.activeSeat].type==='ai'?'AI':'空席'),1280,270,21,'left','#fff',850,true);txt('參賽 '+active().length+' 人 / 真人 '+humans()+' 人',1280,316,18,'left','#fff',750,true);btn('money','起始 $'+S.money.toLocaleString(),1080,360,410,65,false);btn('rounds',S.rounds+' 回合',1080,438,410,65,false);btn('startGame','開始遊戲',1080,525,410,90,true,1,active().length>=2&&humans()>=1);for(let i=0;i<4;i++)seat(i,70+i*380,735,225,130)}
function boardPoints(){const p=[],cx=1600,cy=900,rx=1180,ry=620,n=32;for(let i=0;i<n;i++){const a=Math.PI/2+i*Math.PI*2/n;p.push({x:cx+Math.cos(a)*rx,y:cy+Math.sin(a)*ry})}return p}
function makeBoard(){const pts=boardPoints();const tiles=pts.map((p,i)=>({x:p.x,y:p.y,type:i===0?'start':'land',owner:-1,level:0,price:9000+(i%6)*1800}));const ps=active().map((si,id)=>({id,seat:si,type:S.seats[si].type,char:S.seats[si].char,cash:S.money,pos:0}));S.board={worldW:3200,worldH:1800,tiles,players:ps,turn:0,round:1,cam:{x:0,y:0},popup:null};focus(true)}
function cp(){return S.board.players[S.board.turn]}
function focus(now=false){const b=S.board,p=cp(),t=b.tiles[p.pos],tx=Math.max(0,Math.min(b.worldW-W,t.x-W/2)),ty=Math.max(0,Math.min(b.worldH-H,t.y-H/2));if(now){b.cam.x=tx;b.cam.y=ty}else b.cam.target={x:tx,y:ty}}
function mapBg(){const b=S.board;cover(I.bg,0,0,b.worldW,b.worldH);X.fillStyle='rgba(12,22,30,.08)';X.fillRect(0,0,b.worldW,b.worldH)}
function drawTile(t,i){contain(t.type==='start'?I.tileStart:I.tileLand,t.x-88,t.y-88,176,176,1);if(t.owner>=0){txt((t.owner+1)+'P',t.x,t.y-76,16,'center',['#ff6d69','#6db6ff','#7dcc75','#efc04f'][t.owner],1000,true);txt('Lv'+t.level,t.x,t.y+65,14,'center','#fff4d2',850,true)}}
function players(){const b=S.board;for(const p of b.players){const t=b.tiles[p.pos],o=(p.id-(b.players.length-1)/2)*25;contain(I['c'+p.char],t.x-53+o,t.y-132,106,115);txt((p.id+1)+'P',t.x+o,t.y-140,14,'center',['#ff6d69','#6db6ff','#7dcc75','#efc04f'][p.id],1000,true)}}
function hud(){const b=S.board,p=cp();btn('dummy',`${p.id+1}P  ${CN[p.char]}   $${p.cash.toLocaleString()}`,20,18,520,70,false);btn('dummy2',`第 ${b.round}/${S.rounds} 回合`,1220,18,350,70,false);btn('roll',S.moving?'移動中':'擲骰子',1280,760,270,105,false,.95,!S.moving&&!b.popup);txt('骰子 '+S.dice,1415,728,20,'center','#fff3ca',900,true);if(S.msg)txt(S.msg,800,846,20,'center','#fff3ca',900,true)}
function popup(){const b=S.board,p=cp(),t=b.popup;if(!t)return;btn('dummy3',t.type==='start'?'起點':'土地',520,250,560,70,false);if(t.type==='start'){txt('起點獎金 +2,000',800,360,28,'center','#fff',900,true);btn('ok','確定',680,450,240,75,false)}else if(t.owner<0){txt('土地價格 $'+t.price.toLocaleString(),800,350,26,'center','#fff',900,true);btn('buy','購買',610,430,240,78,true,1,p.cash>=t.price);btn('skip','略過',875,430,180,78,false)}else if(t.owner===p.id){txt('自己的土地・Lv'+t.level,800,350,26,'center','#fff',900,true);btn('upgrade',t.level<3?'升級房屋':'已滿級',650,430,300,78,true,1,t.level<3&&p.cash>=Math.round(t.price*.7));btn('skip','繼續',690,525,220,68,false)}else{const r=Math.round(t.price*(.32+t.level*.22));txt(`支付 ${t.owner+1}P 租金 $${r.toLocaleString()}`,800,350,26,'center','#fff',900,true);btn('pay','支付租金',650,440,300,78,true)}}
function game(){const b=S.board;if(b.cam.target){b.cam.x+=(b.cam.target.x-b.cam.x)*.09;b.cam.y+=(b.cam.target.y-b.cam.y)*.09;if(Math.hypot(b.cam.target.x-b.cam.x,b.cam.target.y-b.cam.y)<1)delete b.cam.target}X.save();X.translate(-b.cam.x,-b.cam.y);mapBg();b.tiles.forEach(drawTile);players();X.restore();hud();popup()}
function next(){const b=S.board;b.popup=null;b.turn++;if(b.turn>=b.players.length){b.turn=0;b.round++}focus();if(cp().type==='ai')setTimeout(roll,550)}
function land(){const b=S.board,p=cp(),t=b.tiles[p.pos];if(t.type==='start')p.cash+=2000;b.popup=t;if(p.type==='ai')setTimeout(aiResolve,450)}
function aiResolve(){const b=S.board,p=cp(),t=b.popup;if(t.type==='start')return next();if(t.owner<0&&p.cash>t.price*1.6){p.cash-=t.price;t.owner=p.id;t.level=1}else if(t.owner===p.id&&t.level<3&&p.cash>t.price){p.cash-=Math.round(t.price*.7);t.level++}else if(t.owner>=0&&t.owner!==p.id){const r=Math.round(t.price*(.32+t.level*.22));p.cash-=r;b.players[t.owner].cash+=r}next()}
function roll(){if(S.moving||S.board.popup)return;S.moving=true;S.dice=1+Math.floor(Math.random()*6);const p=cp();let n=0;const h=setInterval(()=>{p.pos=(p.pos+1)%S.board.tiles.length;if(p.pos===0)p.cash+=2000;n++;focus();if(n>=S.dice){clearInterval(h);S.moving=false;setTimeout(land,240)}},240)}
function click(id){if(S.scene==='home'){if(id==='start'){S.scene='setup';return}if(id==='continue'){S.scene='setup';return}return}if(S.scene==='setup'){if(id==='back'){S.scene='home';return}if(id.startsWith('char')){choose(+id.slice(4));return}if(id.startsWith('seat')){S.activeSeat=+id.slice(4);return}for(const k of ['human','ai','off'])if(id.startsWith(k)){const i=+id.slice(k.length);S.seats[i].type=k==='human'?'human':k==='ai'?'ai':'off';S.activeSeat=i;return}if(id==='money'){S.money=S.money===300000?500000:S.money===500000?100000:300000;return}if(id==='rounds'){S.rounds=S.rounds===20?30:S.rounds===30?45:S.rounds===45?60:20;return}if(id==='startGame'&&active().length>=2&&humans()>=1){makeBoard();S.scene='game';localStorage.setItem('cxq_v6_first','1');return}return}if(S.scene==='game'){const b=S.board,p=cp(),t=b.popup;if(id==='roll'){roll();return}if(!t)return;if(id==='ok'||id==='skip'){next();return}if(id==='buy'){p.cash-=t.price;t.owner=p.id;t.level=1;S.msg='購地成功';next();return}if(id==='upgrade'){p.cash-=Math.round(t.price*.7);t.level++;S.msg='土地升級 Lv'+t.level;next();return}if(id==='pay'){const r=Math.round(t.price*(.32+t.level*.22));p.cash-=r;b.players[t.owner].cash+=r;S.msg='支付租金 $'+r.toLocaleString();next();return}}
}
function render(){begin();if(S.scene==='home')home();else if(S.scene==='setup')setup();else game();requestAnimationFrame(render)}render();
function pos(e){const r=C.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
C.addEventListener('pointerup',e=>{const p=pos(e),b=[...S.buttons].reverse().find(q=>q.en&&p.x>=q.x&&p.x<=q.x+q.w&&p.y>=q.y&&p.y<=q.y+q.h);if(b&&!b.id.startsWith('dummy'))click(b.id)});