'use strict';
const $=G.$,canvas=$('#canvas'),ctx=canvas.getContext('2d'),{Engine,Bodies,Body,Composite,Events}=Matter;
const companionSkills=['換一顆球','清除最小球','輕推球堆','回到上一步','升級預備球','整理落點','重置警戒','交換預備球','放慢落球','再選下一球'];
let state=null,engine=null,queue=[],undoStack=[],aim=200,acc=0;const radii=[15,19,23,28,34,41,48,56,65,75,85,95],names=['幸運四葉草','療癒愛心','小小鈴鐺','森林葉帽','回憶照片','慶典氣球','月夜星光','守護鑰匙','心光夢線','雨露收藏','星願信封','圓滿心光'];
const data=G.init({id:'merge',art:'art-v2',sounds:{"drop":"art-v2/drop.mp3","merge":"art-v2/merge.mp3"},music:'art-v2/music.mp3',orientation:'portrait',pause});
data.highTier=G.clamp(Math.floor(data.highTier)||0,0,11);$('#theme').options[1].disabled=data.highTier<6;if(data.highTier>=6)$('#theme').options[1].textContent='月光工坊';
G.rolePicker('#roles',undefined,id=>{$('#companion').innerHTML=G.sprite(id);$('#greeting').textContent=G.roles[id]+'：今天也一起收好小小的幸運。'});
$('#mode').onchange=()=>$('#mission-row').hidden=$('#mode').value!=='mission';
const artRoot='../storybook/art-20260914/';const orbFiles=Array.from({length:12},(_,i)=>i===4?'../storybook/art-20260920-batch/merge-ball-memory.webp':artRoot+'merge-ball-'+i+'.webp');function orb(index,x,y,w,h){const img=G.images[orbFiles[index]];if(img?.naturalWidth)ctx.drawImage(img,x,y,w,h)}G.load([artRoot+'merge-panel.webp',artRoot+'explosion.webp',...orbFiles]).catch(()=>{});
function balls(){return Composite.allBodies(engine.world).filter(b=>Number.isInteger(b.tier))}
function make(t,x,y,vel){const b=Bodies.circle(x,y,radii[t],{restitution:.12,friction:.12,frictionAir:.008,density:.001,slop:.03});b.tier=t;state.max=Math.max(state.max,t);b.born=state.time;if(vel)Body.setVelocity(b,vel);Composite.add(engine.world,b);return b}
function resetEngine(){engine=Engine.create({enableSleeping:true});engine.gravity.y=1;Composite.add(engine.world,[Bodies.rectangle(200,525,440,30,{isStatic:true}),Bodies.rectangle(32,315,24,650,{isStatic:true}),Bodies.rectangle(368,315,24,650,{isStatic:true})]);Events.on(engine,'collisionStart',ev=>{for(const p of ev.pairs)if(Number.isInteger(p.bodyA.tier)&&p.bodyA.tier===p.bodyB.tier)queue.push([p.bodyA,p.bodyB])});queue=[];acc=0}
function start(){$('#score').textContent='0';$('#tier').textContent='1';state={running:true,paused:false,mode:'classic',target:+$('#mission').value,time:0,score:0,max:0,current:Math.random()*3|0,next:Math.random()*3|0,cool:0,overflow:0,helpUsed:false,countdown:1,effects:[]};resetEngine();undoStack=[];aim=200;$('#home').hidden=true;$('#play').hidden=false;document.body.classList.toggle('night',$('#theme').value==='night');$('#play-role').innerHTML=G.sprite(data.role);$('#role-line').textContent=G.roles[data.role]+'陪你慢慢整理。';$('#mission-info').textContent=state.mode==='mission'?'任務：合成'+names[state.target]:state.mode==='practice'?'自由練習，不列入挑戰紀錄。':'相同收藏球相遇就會升階。';$('#undo').hidden=state.mode!=='practice';$('#ability').hidden=false;$('#ability').disabled=false;$('#ability').textContent=companionSkills[data.role]+'（一次）';$('#undo').disabled=true;G.playing(true);canvas.focus({preventScroll:true});draw()}
function snapshot(){return {balls:balls().map(b=>({t:b.tier,x:b.position.x,y:b.position.y,v:{...b.velocity},a:b.angle,av:b.angularVelocity})),score:state.score,max:state.max,current:state.current,next:state.next}}
function drop(){if(window.CxQSession?.blocked()||!state?.running||state.paused||state.countdown>0||state.cool>0)return;undoStack.push(snapshot());if(undoStack.length>30)undoStack.shift();make(state.current,G.clamp(aim,44+radii[state.current],356-radii[state.current]),65);state.current=state.next;state.next=Math.random()*4|0;state.cool=.55;$('#undo').disabled=false;G.sound('drop')}
function undo(){if(window.CxQSession?.blocked()||!state?.running||state.paused||!undoStack.length)return;const snap=undoStack.pop();resetEngine();Object.assign(state,{score:snap.score,max:snap.max,current:snap.current,next:snap.next,overflow:0,cool:.5,effects:[]});for(const b of snap.balls){const body=make(b.t,b.x,b.y,b.v);Body.setAngle(body,b.a);Body.setAngularVelocity(body,b.av)}$('#undo').disabled=!undoStack.length;G.toast('已還原投球前的魔法箱。')}
function mergePairs(){const live=new Set(balls()),used=new Set();for(const [a,b]of queue){if(!live.has(a)||!live.has(b)||used.has(a)||used.has(b))continue;used.add(a);used.add(b);const tier=a.tier+1,x=(a.position.x+b.position.x)/2,y=Math.min(500-radii[Math.min(tier,11)],(a.position.y+b.position.y)/2);Composite.remove(engine.world,[a,b]);if(tier<12)make(tier,G.clamp(x,44+radii[tier],356-radii[tier]),y);state.score+=2**tier*5;state.max=Math.max(state.max,Math.min(11,tier));state.effects.push({x,y,t:.6,tier:Math.min(tier,11)});G.sound('merge',1+Math.min(tier,6)*.06);if(state.mode!=='practice'){data.highTier=Math.max(data.highTier,state.max);if(!data.collection.includes(Math.min(tier,11)))data.collection.push(Math.min(tier,11));G.save()}if(state.mode==='mission'&&tier>=state.target){finish(true);break}}queue=[]}
function update(dt){if(!state?.running||state.paused)return;if(state.countdown>0){state.countdown-=dt;return}state.time+=dt;state.cool=Math.max(0,state.cool-dt);acc+=dt;while(acc>=1/60){Engine.update(engine,1000/60);mergePairs();acc-=1/60;if(!state.running)break}state.effects=state.effects.filter(e=>(e.t-=dt)>0);if(state.slowUntil&&state.time<state.slowUntil)engine.timing.timeScale=.5;else engine.timing.timeScale=1;const danger=state.time>=(state.safeUntil||0)&&balls().some(b=>state.time-b.born>1.6&&b.position.y-radii[b.tier]<115&&Math.abs(b.velocity.y)<1.3);state.overflow=danger?state.overflow+dt:0;$('#status').textContent=state.overflow?'收納線上停留過久！還有 '+Math.max(0,3-state.overflow).toFixed(1)+' 秒。':state.cool?'等這顆落穩，再放下一顆。':'左右選擇落點，放開投下。';if(state.overflow>=3)finish(false);$('#score').textContent=state.score;$('#tier').textContent=state.max+1}
function draw(){ctx.clearRect(0,0,400,590);const panel=G.images[artRoot+'merge-panel.webp'];if(panel)ctx.drawImage(panel,0,0,400,590);if(!state)return;ctx.save();ctx.strokeStyle=state.overflow?'#ae4534':'#9d9470';ctx.lineWidth=2;ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(44,115);ctx.lineTo(356,115);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#f4e4ba';ctx.font='bold 16px sans-serif';ctx.fillText('收納線',48,108);for(const b of balls()){const r=radii[b.tier]/.96;ctx.save();ctx.translate(b.position.x,b.position.y);ctx.rotate(b.angle);const age=state.time-b.born;if(age<.35){const squash=Math.sin(age/.35*Math.PI)*.12;ctx.scale(1+squash,1-squash);}orb(b.tier,-r,-r,2*r,2*r);ctx.restore()}if(state.running){const r=radii[state.current]/.96,x=G.clamp(aim,44+radii[state.current],356-radii[state.current]);if($('#guide').checked){ctx.setLineDash([3,6]);ctx.beginPath();ctx.moveTo(x,80);ctx.lineTo(x,510);ctx.strokeStyle='#8d795a88';ctx.stroke();ctx.setLineDash([])}orb(state.current,x-r,62-r,2*r,2*r);if($('#preview').checked){ctx.fillText('下一顆',310,35);orb(state.next,322,42,38,38)}}for(const e of state.effects){ctx.globalAlpha=e.t/.6;const glow=G.images[artRoot+"explosion.webp"],size=65+(1-e.t/.6)*55;if(glow?.naturalWidth)ctx.drawImage(glow,e.x-size/2,e.y-size/2,size,size);ctx.fillStyle='#ffecad';ctx.font='bold 20px serif';ctx.fillText('+'+2**(e.tier+0)*5,e.x-15,e.y-(.6-e.t)*40)}ctx.globalAlpha=1;if(state.countdown>0){ctx.fillStyle='#fff0b9';ctx.font='bold 40px serif';ctx.textAlign='center';ctx.fillText('準備',200,290)}ctx.restore()}
function finish(win){if(!state.running)return;data.resume=null;G.save();state.running=false;G.playing(false);if(win){data.wins++;G.save()}if(state.mode!=='practice')G.records(state.mode+(state.mode==='mission'?state.target:''),state.score);G.sound(win?'win':'lose');G.dialog(win?'今天的收藏完成了！':'把這次的心光收好','<div class="dialog-stats"><span><b>'+state.score+'</b><small>心光</small></span><span><b>'+(state.max+1)+'</b><small>最高階</small></span></div><p>'+names[state.max]+' · '+(state.mode==='practice'?'練習不列入紀錄':'已儲存在這台裝置')+'</p>',[['再開一箱',start],['回到合成工坊',home]])}
window.CxQGame={restart:start,home};
function home(){data.resume=null;G.save();if(state)state.running=false;G.playing(false);G.resumeAudio();$('#home').hidden=false;$('#play').hidden=true;$('#theme').options[1].disabled=data.highTier<6;if(data.highTier>=6)$('#theme').options[1].textContent='月光工坊'}
function pause(){if(!state?.running||state.paused)return;state.paused=true;G.hold();G.dialog('魔法箱等你回來','<p>球球和時間都停好了。</p>',[['繼續整理',()=>{state.paused=false;state.countdown=.8;G.resumeAudio();G.orientation()}],['回到合成工坊',home]])}
$('#start').onclick=start;$('#pause').onclick=pause;$('#drop').onclick=drop;$('#undo').onclick=undo;$('#ability').onclick=()=>{if(window.CxQSession?.blocked()||!state?.running||state.paused||state.helpUsed)return;if((data.role===1&&!balls().length)||(data.role===3&&!undoStack.length)){$('#status').textContent='先投下一顆球，再請夥伴幫忙。';return;}state.helpUsed=true;$('#ability').disabled=true;const bs=balls();switch(data.role){case 0:state.current=(state.current+1)%4;break;case 1:if(bs.length)Composite.remove(engine.world,bs.sort((a,b)=>a.tier-b.tier)[0]);break;case 2:bs.forEach((b,i)=>Body.setVelocity(b,{x:i%2?.8:-.8,y:-1}));break;case 3:undo();break;case 4:state.current=Math.min(4,state.current+1);break;case 5:aim=200;state.current=0;break;case 6:state.safeUntil=state.time+6;break;case 7:[state.current,state.next]=[state.next,state.current];break;case 8:state.slowUntil=state.time+6;break;case 9:state.next=(state.next+1)%4;break;}state.overflow=0;G.sound('skill')};
function position(e){const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/400,r.height/590),left=r.left+(r.width-400*scale)/2;aim=G.clamp((e.clientX-left)/scale,50,350)}canvas.onpointerdown=e=>{position(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(e.buttons)position(e)};canvas.onpointercancel=()=>{};canvas.onpointerup=e=>{position(e);drop()};addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(['ArrowLeft','ArrowRight','Space','Escape'].includes(e.code)&&state?.running){e.preventDefault();if(e.code==='ArrowLeft')aim-=15;if(e.code==='ArrowRight')aim+=15;if(e.code==='Space')drop();if(e.code==='Escape')pause();aim=G.clamp(aim,50,350)}});
$('#collection').onclick=()=>G.dialog('你的心光收藏架','<div class="collection">'+names.map((n,i)=>'<div><img class="ball-preview" src="'+orbFiles[i]+'" alt="'+n+'" style="object-fit:contain;background:none;opacity:'+(i===0||data.collection.includes(i)?1:.2)+'"><small>'+(i===0||data.collection.includes(i)?n:'尚未發現')+'</small></div>').join('')+'</div>',[['收好收藏']]);$('#records').onclick=()=>G.dialog('合成工坊紀錄',G.recordHTML($('#mode').value+($('#mode').value==='mission'?$('#mission').value:'')),[['返回']]);$('#help').onclick=()=>{if(!state?.running)return;state.paused=true;G.hold();G.dialog('把小小心光放在一起','<p>左右移動選落點，放開或按投球。相同球碰在一起會升階；球在收納線上停留三秒就會結束。</p><p>鍵盤：左右方向鍵瞄準，空白鍵投球。練習可撤回，任務可用一次夥伴協助。</p>',[['繼續整理',()=>{state.paused=false;state.countdown=.8;G.resumeAudio();G.orientation()}],['回合成工坊',home]])};G.settings(["guide","preview"]);G.frame(update,draw);
