/* Depends on this game's existing state/physics helpers; never restores executable data. */
(() => {
  const finite=n=>typeof n==='number'&&Number.isFinite(n);
  function valid(s){return s?.version===1&&['classic','mission','practice'].includes(s.mode)&&Number.isInteger(s.target)&&s.target>=0&&s.target<12&&finite(s.time)&&s.time>=0&&finite(s.score)&&s.score>=0&&Number.isInteger(s.max)&&s.max>=0&&s.max<12&&[s.current,s.next].every(t=>Number.isInteger(t)&&t>=0&&t<5)&&Array.isArray(s.balls)&&s.balls.length<=200&&s.balls.every(b=>Number.isInteger(b.t)&&b.t>=0&&b.t<12&&finite(b.x)&&b.x>=0&&b.x<=400&&finite(b.y)&&b.y>=-120&&b.y<=590&&finite(b.a)&&finite(b.av)&&finite(b.v?.x)&&finite(b.v?.y));}
  function preserve(){if(!state?.running||!engine)return;const snap=snapshot();data.resume={version:1,...snap,mode:state.mode,target:state.target,time:state.time,helpUsed:state.helpUsed};G.save();}
  function restore(saved){start();resetEngine();Object.assign(state,{mode:'classic',target:saved.target,time:saved.time,score:saved.score,max:saved.max,current:saved.current,next:saved.next,helpUsed:!!saved.helpUsed,countdown:1.5});for(const b of saved.balls){const body=make(b.t,b.x,b.y,{x:G.clamp(b.v.x,-20,20),y:G.clamp(b.v.y,-20,20)});Body.setAngle(body,b.a);Body.setAngularVelocity(body,G.clamp(b.av,-1,1));body.born=state.time-2;}$('#ability').disabled=state.helpUsed;$('#score').textContent=state.score;$('#tier').textContent=state.max+1;}
  $('#start').onclick=()=>{if(!valid(data.resume)){data.resume=null;start();return;}const saved=data.resume;G.dialog('繼續上次的合成？','<p>上次已累積 '+Math.floor(saved.score)+' 心光，收藏球的位置已保存。</p>',[['接著整理',()=>{ $('#mode').value='classic';$('#mission').value=saved.target;restore(saved);}],['開始新的一局',()=>{data.resume=null;G.save();start();}],['先不開始',()=>{}]]);};
  setInterval(()=>{if(!document.hidden&&!window.CxQSession?.blocked())preserve();},2000);
  document.addEventListener('visibilitychange',()=>{if(document.hidden)preserve();});addEventListener('pagehide',preserve);
})();
