document.addEventListener('DOMContentLoaded',()=>{
 const $=s=>document.querySelector(s), historyKey='star2048History';
 const home=document.createElement('section'); home.className='home-screen'; home.innerHTML=`<div class="home-card"><img class="home-character" src="assets/characters/light-weaver.png" alt="光線編織者"><h1 class="home-title">星願 2048</h1><p class="home-sub">讓相同的星光夥伴相遇，完成 2048 的願望</p><div class="home-actions"><button class="btn primary" id="homeStart">開始新遊戲</button><button class="btn" id="homeContinue">繼續遊戲</button><div class="home-links"><button class="btn" id="homeHow">玩法</button><button class="btn" id="homeGallery">圖鑑</button><button class="btn" id="homeRank">排行榜</button></div></div></div>`; document.body.append(home);
 const makeModal=(id,title)=>{let o=document.createElement('div');o.className='overlay';o.id=id;o.style.zIndex='80';o.innerHTML=`<div class="modal"><h2>${title}</h2><div class="modalBody"></div><button class="btn primary wide" data-home-close>返回</button></div>`;document.body.append(o);o.querySelector('[data-home-close]').onclick=()=>{o.classList.remove('show');home.classList.remove('hidden')};return o};
 const how=makeModal('howModal','玩法說明');how.querySelector('.modalBody').innerHTML='<p>向上下左右滑動棋盤。兩個相同數字相遇時會合成更高一級的角色；嘗試合成 2048。手機可直接滑動，電腦可使用方向鍵。每局可復原一次上一步。</p>';
 const rank=makeModal('rankModal','歷史紀錄排行榜');
 function rows(){let a=JSON.parse(localStorage.getItem(historyKey)||'[]');rank.querySelector('.modalBody').innerHTML=a.length?`<div class="rank-list">${a.map((r,i)=>`<div class="rank-row"><b>${i+1}</b><span>${r.score.toLocaleString()} 分<small>${r.date} · 最大 ${r.max}</small></span><strong>${r.result}</strong></div>`).join('')}</div><button class="btn wide" id="clearRank">清除紀錄</button>`:'<div class="empty-rank">還沒有完成的遊戲紀錄</div>';let c=$('#clearRank');if(c)c.onclick=()=>{localStorage.removeItem(historyKey);rows()}}
 $('.hero').setAttribute('role','button');$('.hero').setAttribute('aria-label','返回首頁');$('.hero').onclick=()=>home.classList.remove('hidden');$('#homeStart').onclick=()=>{home.classList.add('hidden');setTimeout(()=>$('#new').click(),0)};$('#homeContinue').onclick=()=>home.classList.add('hidden');$('#homeHow').onclick=()=>{home.classList.add('hidden');how.classList.add('show')};$('#homeGallery').onclick=()=>{home.classList.add('hidden');$('#gallery').click()};$('#homeRank').onclick=()=>{home.classList.add('hidden');rows();rank.classList.add('show')};
 let recorded=false;new MutationObserver(()=>{let result=$('#result');if(!result.classList.contains('show')){recorded=false;return}if(recorded)return;recorded=true;let score=+($('#score').textContent||0), max=Math.max(0,...[...document.querySelectorAll('.num')].map(x=>+x.textContent));let a=JSON.parse(localStorage.getItem(historyKey)||'[]');a.push({score,max,result:$('#resultTitle').textContent.includes('完成')?'完成':'結束',date:new Date().toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})});a.sort((x,y)=>y.score-x.score);localStorage.setItem(historyKey,JSON.stringify(a.slice(0,30)))}).observe($('#result'),{attributes:true,attributeFilter:['class']});
});