const EVENTS=[
['王國節慶','獲得 $6,000',p=>p.cash+=6000],['突發修繕','支付 $3,500',p=>p.cash-=3500],['精靈贈禮','獲得一張卡片',p=>drawCard(p)],['幸運噴泉','獲得 $4,500',p=>p.cash+=4500],['迷路','下一回合暫停一次',p=>p.skip+=1],['市場熱潮','獲得 $5,000',p=>p.cash+=5000],['惡作劇','損失 $2,000',p=>p.cash-=2000],['旅人委託','獲得 2 點券',p=>p.tickets+=2],['守護祝福','得到一次護盾',p=>p.shield+=1],['稅務日','支付資產稅 $4,000',p=>p.cash-=4000],['星光雨','獲得 $7,000',p=>p.cash+=7000],['交換市集','免費抽兩張卡',p=>{drawCard(p);drawCard(p)}],['道路施工','下一回合骰子最多 3 點',p=>p.slow=1],['王國補助','獲得 $3,000',p=>p.cash+=3000],['失物招領','獲得 $2,500',p=>p.cash+=2500],['魔法失控','隨機損失一張卡',p=>{if(p.cards.length)p.cards.splice(Math.floor(Math.random()*p.cards.length),1)}]
];
const CARD_POOL=['精準骰子','護身符','加速靴','財富卡','地產折價券','幸運符'];
function drawCard(p){p.cards.push(CARD_POOL[Math.floor(Math.random()*CARD_POOL.length)])}
const NPCS=[
['財神','獲得 $8,000',p=>p.cash+=8000],['窮神','損失 $5,000',p=>p.cash-=5000],['福神','獲得 2 張卡片',p=>{drawCard(p);drawCard(p)}],['衰神','下一回合骰子最多 3 點',p=>p.slow=1],['土地公','隨機免費升級一塊自己的土地',p=>{const a=S.board.tiles.filter(t=>t.owner===p.id&&t.level<3);if(a.length)a[Math.floor(Math.random()*a.length)].level++}],['天使','替一塊自己的土地加蓋一層',p=>{const a=S.board.tiles.filter(t=>t.owner===p.id&&t.level<3);if(a.length)a[Math.floor(Math.random()*a.length)].level++;else p.cash+=3000}],['惡魔','隨機拆除一層房屋',p=>{const a=S.board.tiles.filter(t=>t.owner===p.id&&t.level>0);if(a.length)a[Math.floor(Math.random()*a.length)].level--}],['死神','失去所有卡片',p=>p.cards=[]],['乞丐','施捨 $1,000',p=>p.cash-=1000],['惡犬','休息 3 回合',p=>p.skip+=3]
];
function addLog(s){S.board.log.push(s);if(S.board.log.length>8)S.board.log.shift();S.msg=s}
function openPopup(kind,data={}){S.board.popup={kind,...data}}
function popup(){const b=S.board,p=cp(),q=b.popup;if(!q)return;const t=q.tile;if(q.kind==='tile'){contain(IM['tile_'+t.type],590,105,420,420,.98);btn('noop3',typeName(t.type),600,460,400,70,false);if(t.type==='start'){txt('經過起點可獲得 $5,000',800,555,24);btn('ok','確定',680,630,240,74,false);return}if(t.type==='land'){if(t.owner<0){txt(REGION_NAMES[t.region]+'・土地價格 $'+t.price.toLocaleString(),800,550,23);btn('buy','購買',600,620,245,78,true,1,p.cash>=t.price);btn('skip','略過',870,620,190,78,false)}else if(t.owner===p.id){const cost=Math.round(t.price*.65);txt('自己的土地・Lv'+t.level+' / 3',800,548,23);btn('upgrade',t.level<3?'升級 $'+cost.toLocaleString():'已滿級',620,620,360,78,true,1,t.level<3&&p.cash>=cost);btn('skip','繼續',690,715,220,62,false)}else{let rent=Math.round(t.price*(.25+t.level*.22));if(regionOwned(t.owner,t.region))rent=Math.round(rent*1.5);txt(`支付 ${t.owner+1}P 租金 $${rent.toLocaleString()}`,800,550,23);btn('pay','支付租金',650,625,300,78,true)}return}btn('special','查看結果',665,625,270,78,false);return}
if(q.kind==='event'){contain(IM.tile_event,610,105,380,380);txt(q.name,800,525,30,'center','#ffe58a',1000,true);txt(q.desc,800,570,22);btn('eventOk','確定',680,640,240,74,false);return}
if(q.kind==='npc'){contain(IM.tile_npc,610,105,380,380);txt(q.name,800,525,30,'center','#ffe58a',1000,true);txt(q.desc,800,570,22);btn('npcOk','確定',680,640,240,74,false);return}
if(q.kind==='shop'){contain(IM.tile_shop,610,90,380,380);txt('童話商店',800,500,30,'center','#ffe58a',1000,true);txt('支付 $2,500 隨機取得一張卡片',800,548,21);btn('shopBuy','購買卡片',620,615,300,76,true,1,p.cash>=2500);btn('skip','離開',940,615,170,76,false);return}
if(q.kind==='carddraw'){contain(IM.tile_card,610,90,380,380);txt('抽到：'+q.card,800,520,28,'center','#ffe58a',1000,true);btn('cardOk','收下',680,620,240,76,false);return}
if(q.kind==='cards'){contain(IM.tile_card,95,120,290,290,.95);txt('持有卡片',450,132,28,'left','#ffe58a',1000,true);if(!p.cards.length){txt('目前沒有卡片',450,195,22,'left');btn('closeCards','返回',1120,700,240,70,false);return}p.cards.slice(0,6).forEach((c,i)=>btn('useCard'+i,c,440,180+i*78,450,62,i===0));btn('closeCards','返回',1120,700,240,70,false);return}
if(q.kind==='mini'){contain(IM.tile_minigame,610,90,380,380);txt('星光停格挑戰',800,495,30,'center','#ffe58a',1000,true);txt('看準時機按下「停！」，越接近中央獎勵越高',800,540,20);const m=b.mini;const x=515,y=590,w=570;X.fillStyle='rgba(10,18,38,.75)';X.fillRect(x,y,w,28);X.fillStyle='#ffe37a';X.fillRect(x+w*.44,y,w*.12,28);X.fillStyle='#fff';X.fillRect(x+m.pos*w-5,y-8,10,44);btn('miniStop','停！',660,655,280,78,true);return}
if(q.kind==='winner'){txt('本局結束',800,270,54,'center','#ffe58a',1000,true);txt(q.text,800,360,34,'center','#fff',1000,true);btn('home','回到首頁',630,500,340,88,true);return}}
function rentFor(t){let r=Math.round(t.price*(.25+t.level*.22));if(t.owner>=0&&regionOwned(t.owner,t.region))r=Math.round(r*1.5);return r}
function resolveTile(){const b=S.board,p=cp(),t=b.tiles[p.pos];if(t.type==='start'){p.cash+=5000;addLog(`${p.id+1}P 經過起點，獲得 $5,000`)}openPopup('tile',{tile:t});if(p.type==='ai')setTimeout(aiResolve,420)}
function applySpecial(t,p){if(t.type==='event'){const e=EVENTS[Math.floor(Math.random()*EVENTS.length)];e[2](p);openPopup('event',{name:e[0],desc:e[1]});addLog(`${p.id+1}P：${e[0]}・${e[1]}`)}else if(t.type==='card'){drawCard(p);const c=p.cards[p.cards.length-1];openPopup('carddraw',{card:c});addLog(`${p.id+1}P 抽到 ${c}`)}else if(t.type==='shop'){openPopup('shop');addLog(`${p.id+1}P 進入童話商店`)}else if(t.type==='npc'){const n=NPCS[Math.floor(Math.random()*NPCS.length)];n[2](p);openPopup('npc',{name:n[0],desc:n[1]});addLog(`${p.id+1}P 遇到${n[0]}：${n[1]}`)}else if(t.type==='minigame'){if(p.type==='ai'){p.tickets+=2;p.cash+=2500;addLog(`${p.id+1}P 完成小遊戲，獲得 $2,500 與 2 點券`)}else{b.mini={pos:0,dir:1,last:performance.now()};openPopup('mini')}}}
function ensureSolvent(p){if(p.cash>=0)return;const houses=S.board.tiles.filter(t=>t.owner===p.id&&t.level>0).sort((a,b)=>b.level-a.level);for(const t of houses){while(t.level>0&&p.cash<0){p.cash+=Math.round(t.price*.32);t.level--;addLog(`${p.id+1}P 變賣房屋籌措資金`)}}const lands=S.board.tiles.filter(t=>t.owner===p.id);for(const t of lands){if(p.cash>=0)break;p.cash+=Math.round(t.price*.55);t.owner=-1;t.level=0;addLog(`${p.id+1}P 出售土地籌措資金`)}if(p.cash<0){p.bankrupt=true;p.cash=0;S.board.tiles.forEach(t=>{if(t.owner===p.id){t.owner=-1;t.level=0}});addLog(`${p.id+1}P 破產退場！`)}}
function finishAction(){const p=cp();ensureSolvent(p);S.board.popup=null;S.board.mini=null;saveGame();nextTurn()}
function nextTurn(){const b=S.board;if(living().length<=1){const w=living()[0];b.winner=w;openPopup('winner',{text:w?`${w.id+1}P ${CHAR_NAMES[w.char]} 獲勝！`:'本局結束'});return}let guard=0;do{b.turn++;if(b.turn>=b.players.length){b.turn=0;b.round++}guard++}while((cp().bankrupt)&&guard<10);if(b.round>S.rounds){const sorted=living().slice().sort((a,b)=>netWorth(b)-netWorth(a)),w=sorted[0];b.winner=w;openPopup('winner',{text:`${w.id+1}P ${CHAR_NAMES[w.char]} 資產第一！`});return}const p=cp();if(p.skip>0){p.skip--;addLog(`${p.id+1}P 本回合暫停`);setTimeout(nextTurn,650);return}focus();if(p.type==='ai')setTimeout(rollDice,700)}
function netWorth(p){let v=p.cash;S.board.tiles.forEach(t=>{if(t.owner===p.id)v+=t.price+Math.round(t.price*.65*t.level)});return v}
function moveSteps(steps){const b=S.board,p=cp();S.rolling=true;let n=0;const step=()=>{if(n>=steps){S.rolling=false;resolveTile();return}const old=p.pos;p.pos=(p.pos+1)%b.tiles.length;if(p.pos===0&&old!==0){p.cash+=5000;addLog(`${p.id+1}P 通過起點 +$5,000`)}n++;focus();setTimeout(step,175)};step()}
function rollDice(){if(S.rolling||!S.board||S.board.popup||S.board.winner)return;const p=cp();S.rolling=true;let spins=0;const timer=setInterval(()=>{S.dice=1+Math.floor(Math.random()*6);spins++;if(spins>=9){clearInterval(timer);let d=S.forcedDice||S.dice;S.forcedDice=0;if(p.slow){d=Math.min(d,3);p.slow=0}S.dice=d;S.rolling=false;addLog(`${p.id+1}P 擲出 ${d} 點`);setTimeout(()=>moveSteps(d),180)}},70)}
function aiResolve(){const b=S.board,p=cp(),q=b.popup;if(!q)return;const smart=p.diff==='smart',easy=p.diff==='easy';if(q.kind==='tile'){const t=q.tile;if(t.type==='land'){if(t.owner<0){const reserve=easy?70000:smart?25000:45000;if(p.cash-t.price>reserve){p.cash-=t.price;t.owner=p.id;addLog(`${p.id+1}P 購買 ${REGION_NAMES[t.region]} 土地`)}finishAction();return}if(t.owner===p.id){const cost=Math.round(t.price*.65);const want=t.level<3&&p.cash-cost>(easy?90000:smart?30000:55000);if(want){p.cash-=cost;t.level++;addLog(`${p.id+1}P 將土地升到 Lv${t.level}`)}finishAction();return}const r=rentFor(t);if(p.shield>0){p.shield--;addLog(`${p.id+1}P 使用護盾免除租金`)}else{p.cash-=r;const o=b.players.find(x=>x.id===t.owner);if(o&&!o.bankrupt)o.cash+=r}finishAction();return}if(['event','card','shop','minigame','npc'].includes(t.type)){applySpecial(t,p);if(t.type==='minigame'){finishAction();return}setTimeout(aiResolve,360);return}finishAction();return}if(q.kind==='shop'){if(p.cash>50000){p.cash-=2500;drawCard(p);addLog(`${p.id+1}P 在商店買了一張卡片`)}finishAction();return}if(['event','npc','carddraw'].includes(q.kind)){finishAction();return}}
function useCard(i){const p=cp(),c=p.cards[i];if(!c)return;p.cards.splice(i,1);if(c==='精準骰子'){S.forcedDice=6;addLog(`${p.id+1}P 使用精準骰子，下次固定 6 點`);S.board.popup=null}else if(c==='護身符'){p.shield++;addLog(`${p.id+1}P 獲得一次租金護盾`);S.board.popup=null}else if(c==='加速靴'){S.board.popup=null;addLog(`${p.id+1}P 使用加速靴前進 3 格`);moveSteps(3);return}else if(c==='財富卡'){p.cash+=5000;addLog(`${p.id+1}P 使用財富卡 +$5,000`);S.board.popup=null}else if(c==='地產折價券'){p.discount=1;addLog(`${p.id+1}P 下一次購地享有折價`);S.board.popup=null}else{p.cash+=2500;addLog(`${p.id+1}P 使用幸運符 +$2,500`);S.board.popup=null}saveGame()}
function saveGame(){if(!S.board)return;try{localStorage.setItem(SAVE,JSON.stringify({seats:S.seats,money:S.money,rounds:S.rounds,board:S.board}))}catch(e){}}
function loadGame(){try{const d=JSON.parse(localStorage.getItem(SAVE));if(!d||!d.board)return false;S.seats=d.seats||S.seats;S.money=d.money||S.money;S.rounds=d.rounds||S.rounds;S.board=d.board;S.board.popup=null;S.board.mini=null;S.scene='game';focus(true);if(cp().type==='ai')setTimeout(rollDice,700);return true}catch(e){return false}}
function game(){const b=S.board;if(b.cam&&b.cam.target){b.cam.x+=(b.cam.target.x-b.cam.x)*.11;b.cam.y+=(b.cam.target.y-b.cam.y)*.11;if(Math.hypot(b.cam.target.x-b.cam.x,b.cam.target.y-b.cam.y)<1)b.cam.target=null}X.save();X.translate(-b.cam.x,-b.cam.y);drawMap();X.restore();hud();popup();if(b.mini&&b.popup&&b.popup.kind==='mini'){const now=performance.now(),dt=Math.min(.04,(now-b.mini.last)/1000);b.mini.last=now;b.mini.pos+=b.mini.dir*dt*.82;if(b.mini.pos>=1){b.mini.pos=1;b.mini.dir=-1}if(b.mini.pos<=0){b.mini.pos=0;b.mini.dir=1}}}
function help(){cover(IM.home,0,0,W,H,.48);txt('遊戲說明',800,95,48,'center','#ffe58a',1000,true);const lines=['擲骰子逐格前進，購買土地、升級 Lv1～Lv3 房屋並向對手收租。','同一區域土地全數持有時，該區租金會提高。','事件、卡片、商店、小遊戲與 NPC / 神明會改變局勢。','資金不足會自動變賣房屋與土地；仍無法償付則破產退場。','真人與 AI 可自由配置 2～4 名參賽者，AI 有輕鬆／標準／聰明三種難度。'];lines.forEach((l,i)=>txt(l,800,230+i*82,23,'center','#fff',800,true));btn('home','回到首頁',630,690,340,86,true)}
function settings(){cover(IM.home,0,0,W,H,.48);txt('設定',800,110,48,'center','#ffe58a',1000,true);txt('目前製作版：手機橫向優先・自動存檔・繁體中文',800,245,24);txt('橫向手機操作・自動存檔・真人與 AI 可混合參賽。',800,320,21);btn('home','回到首頁',630,640,340,86,true)}
function action(id){if(!id)return;if(id==='start'){S.scene='setup';return}if(id==='continue'){if(!loadGame())S.scene='setup';return}if(id==='help'){S.scene='help';return}if(id==='settings'){S.scene='settings';return}if(id==='home'){S.scene='home';S.board=null;return}if(id==='back'){S.scene='home';return}if(S.scene==='setup'){if(id.startsWith('char')){chooseChar(+id.slice(4));return}if(id.startsWith('human')){const i=+id.slice(5);S.seats[i].type='human';S.activeSeat=i;return}if(id.startsWith('ai')&&!id.startsWith('diff')){const i=+id.slice(2);S.seats[i].type='ai';S.activeSeat=i;return}if(id.startsWith('off')){const i=+id.slice(3);S.seats[i].type='off';if(S.activeSeat===i){const a=activeSeatIds();if(a.length)S.activeSeat=a[0]}return}if(id.startsWith('seat')){S.activeSeat=+id.slice(4);return}if(id.startsWith('diff')){const i=+id.slice(4),d=S.seats[i].diff;S.seats[i].diff=d==='easy'?'standard':d==='standard'?'smart':'easy';return}if(id==='money'){const a=[100000,200000,300000,500000],i=a.indexOf(S.money);S.money=a[(i+1)%a.length];return}if(id==='rounds'){const a=[20,30,45,60],i=a.indexOf(S.rounds);S.rounds=a[(i+1)%a.length];return}if(id==='startGame'){makeBoard();S.scene='game';if(cp().type==='ai')setTimeout(rollDice,700);return}}
if(S.scene==='game'&&S.board){const b=S.board,p=cp(),q=b.popup;if(id==='roll'){rollDice();return}if(id==='cards'){openPopup('cards');return}if(id==='closeCards'){b.popup=null;return}if(id.startsWith('useCard')){useCard(+id.slice(7));return}if(id==='buy'){const t=q.tile;let cost=t.price;if(p.discount){cost=Math.round(cost*.75);p.discount=0}if(p.cash>=cost){p.cash-=cost;t.owner=p.id;addLog(`${p.id+1}P 購買 ${REGION_NAMES[t.region]} 土地`)}finishAction();return}if(id==='upgrade'){const t=q.tile,cost=Math.round(t.price*.65);if(t.level<3&&p.cash>=cost){p.cash-=cost;t.level++;addLog(`${p.id+1}P 將土地升到 Lv${t.level}`)}finishAction();return}if(id==='pay'){const t=q.tile,r=rentFor(t);if(p.shield>0){p.shield--;addLog(`${p.id+1}P 使用護盾免除租金`)}else{p.cash-=r;const o=b.players.find(x=>x.id===t.owner);if(o&&!o.bankrupt)o.cash+=r;addLog(`${p.id+1}P 支付 $${r.toLocaleString()} 租金`)}finishAction();return}if(id==='skip'||id==='ok'){finishAction();return}if(id==='special'){applySpecial(q.tile,p);return}if(id==='eventOk'||id==='npcOk'||id==='cardOk'){finishAction();return}if(id==='shopBuy'){if(p.cash>=2500){p.cash-=2500;drawCard(p);addLog(`${p.id+1}P 購買卡片：${p.cards[p.cards.length-1]}`)}finishAction();return}if(id==='miniStop'){const dist=Math.abs((b.mini?.pos??0)-.5),reward=dist<.07?7000:dist<.18?4500:2200;p.cash+=reward;p.tickets+=dist<.18?2:1;addLog(`${p.id+1}P 小遊戲獲得 $${reward.toLocaleString()}`);finishAction();return}}
}
C.addEventListener('pointerup',e=>{const r=C.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H,b=hit(x,y);if(b)action(b.id)});
function frame(){begin();if(S.scene==='home')home();else if(S.scene==='setup')setup();else if(S.scene==='game'&&S.board)game();else if(S.scene==='help')help();else if(S.scene==='settings')settings();requestAnimationFrame(frame)}requestAnimationFrame(frame);
