'use strict';
const EVENTS=[
['王國節慶','獲得 $6,000',p=>cashGain(p,6000)],['突發修繕','支付 $3,500',p=>p.cash-=3500],['精靈贈禮','獲得一張卡片',p=>drawCard(p)],['幸運噴泉','獲得 $4,500',p=>cashGain(p,4500)],['迷路','下一回合暫停一次',p=>p.skip+=1],['市場熱潮','獲得 $5,000',p=>cashGain(p,5000)],['惡作劇','損失 $2,000',p=>p.cash-=2000],['旅人委託','獲得 2 點券',p=>p.tickets+=2],['守護祝福','得到一次護盾',p=>p.shield+=1],['稅務日','支付資產稅 $4,000',p=>p.cash-=4000],['星光雨','獲得 $7,000',p=>cashGain(p,7000)],['交換市集','免費抽兩張卡',p=>{drawCard(p);drawCard(p)}],['道路施工','下一回合骰子最多 3 點',p=>p.slow=1],['王國補助','獲得 $3,000',p=>cashGain(p,3000)],['失物招領','獲得 $2,500',p=>cashGain(p,2500)],['魔法失控','隨機損失一張卡',p=>{if(p.cards.length)p.cards.splice(Math.floor(Math.random()*p.cards.length),1)}],['月光紅利','獲得 $5,500',p=>cashGain(p,5500)],['森林迷霧','後退 2 格',p=>p.pos=(p.pos-2+S.board.tiles.length)%S.board.tiles.length],['雲端順風','前進 2 格',p=>p.pos=(p.pos+2)%S.board.tiles.length],['商會回饋','獲得 $4,000',p=>cashGain(p,4000)],['卡片遺失','隨機失去一張卡',p=>{if(p.cards.length)p.cards.splice(Math.floor(Math.random()*p.cards.length),1)}],['幸運日','獲得護盾與 1 點券',p=>{p.shield++;p.tickets++}],['土地維護','支付 $2,500',p=>p.cash-=2500],['精靈加護','免費升級一塊自己的土地',p=>upgradeRandomLand(p)]
];
const CARD_POOL=['精準骰子','遙控骰子','護身符','加速靴','財富卡','地產折價券','幸運符','免費升級卡','租金加倍卡','交換卡','瞬移卡','停留卡'];
const NPC_DEFS=[
{name:'財神',desc:'獲得 $8,000',apply:p=>cashGain(p,8000)},
{name:'窮神',desc:'損失 $5,000',apply:p=>p.cash-=5000},
{name:'福神',desc:'獲得 2 張卡片',apply:p=>{drawCard(p);drawCard(p)}},
{name:'衰神',desc:'下一回合骰子最多 3 點',apply:p=>p.slow=1},
{name:'土地公',desc:'隨機免費升級一塊自己的土地',apply:p=>upgradeRandomLand(p)},
{name:'天使',desc:'加蓋一層並跟隨 7 回合',apply:p=>{upgradeRandomLand(p);attachEffect(p,'天使',7)}},
{name:'惡魔',desc:'拆除一層並跟隨 7 回合',apply:p=>{downgradeRandomLand(p);attachEffect(p,'惡魔',7)}},
{name:'死神',desc:'失去所有卡片並跟隨 13 回合',apply:p=>{p.cards=[];attachEffect(p,'死神',13)}},
{name:'乞丐',desc:'施捨 $1,000',apply:p=>p.cash-=1000},
{name:'惡犬',desc:'休息 3 回合',apply:p=>p.skip+=3}
];
const ROUTE=[[1450,1590],[1260,1620],[1080,1595],[910,1530],[770,1435],[665,1310],[610,1165],[620,1015],[690,875],[800,755],[940,660],[1090,590],[1250,535],[1420,500],[1595,492],[1770,510],[1940,555],[2095,625],[2230,720],[2335,835],[2410,970],[2445,1110],[2435,1250],[2375,1380],[2270,1490],[2130,1570],[1970,1610],[1800,1605],[1645,1555],[1515,1465],[1415,1345],[1340,1210],[1260,1100],[1135,1040],[1010,1075],[955,1215]];
const TYPE_PATTERN=['start','land','event','land','card','land','shop','land','event','land','minigame','land','npc','land','card','land','event','land','shop','land','npc','land','event','land','minigame','land','card','land','event','land','npc','land','event','land','card','land'];
function cashGain(p,n){p.cash+=p.char===0?Math.round(n*1.2):n}
function attachEffect(p,kind,turns){p.effects=p.effects||[];const e=p.effects.find(x=>x.kind===kind);if(e)e.turns=Math.max(e.turns,turns);else p.effects.push({kind,turns})}
function tickEffects(p){p.effects=(p.effects||[]).map(e=>({...e,turns:e.turns-1})).filter(e=>e.turns>0)}
function upgradeRandomLand(p){const a=S.board?.tiles.filter(t=>t.owner===p.id&&t.level<3)||[];if(a.length)a[Math.floor(Math.random()*a.length)].level++}
function downgradeRandomLand(p){const a=S.board?.tiles.filter(t=>t.owner===p.id&&t.level>0)||[];if(a.length)a[Math.floor(Math.random()*a.length)].level--}
function drawCard(p){p.cards.push(CARD_POOL[Math.floor(Math.random()*CARD_POOL.length)]);if(p.char===2&&Math.random()<.22)p.cards.push(CARD_POOL[Math.floor(Math.random()*CARD_POOL.length)])}
function addLog(s){S.board.log.push(s);if(S.board.log.length>8)S.board.log.shift();S.msg=s}
function openPopup(kind,data={}){S.board.popup={kind,...data}}
function typeName(t){return({start:'起點',land:'土地',event:'事件',card:'卡片',shop:'商店',minigame:'小遊戲',npc:'神明／NPC'}[t]||t)}
function activePlayers(){return S.board.players.filter(p=>!p.bankrupt)}
function cp(){return S.board.players[S.board.turn]}
function living(){return activePlayers()}
function regionOwned(pid,reg){const lands=S.board.tiles.filter(t=>t.type==='land'&&t.region===reg);return lands.length>0&&lands.every(t=>t.owner===pid)}
function buyCost(p,t){let c=t.price;if(p.char===6)c=Math.round(c*.9);if(p.discount)c=Math.round(c*.75);return c}
function shopCost(p){return p.char===4?2000:2500}
function rentFor(t,payer=null){let r=Math.round(t.price*(.25+t.level*.22));if(t.owner>=0&&regionOwned(t.owner,t.region))r=Math.round(r*1.5);const owner=S.board.players.find(x=>x.id===t.owner);if(owner?.char===8)r=Math.round(r*1.15);if(owner?.rentBoost){r=Math.round(r*1.5);owner.rentBoost=0}if(payer?.char===3)r=Math.round(r*.8);return r}
function netWorth(p){let v=p.cash;S.board.tiles.forEach(t=>{if(t.owner===p.id)v+=t.price+Math.round(t.price*.65*t.level)});return v}
function focus(now=false){const b=S.board,p=cp(),t=b.tiles[p.pos],tx=Math.max(0,Math.min(MW-W,t.x-W/2)),ty=Math.max(0,Math.min(MH-H,t.y-H/2));if(now){b.cam.x=tx;b.cam.y=ty;b.cam.target=null}else b.cam.target={x:tx,y:ty}}
function spawnNPCs(){const b=S.board,bankrupt=b.players.some(p=>p.bankrupt),pool=NPC_DEFS.filter(n=>bankrupt||n.name!=='乞丐');const chosen=[];while(chosen.length<3){const d=pool[Math.floor(Math.random()*pool.length)];if(!chosen.some(x=>x.name===d.name))chosen.push({name:d.name,pos:2+Math.floor(Math.random()*(b.tiles.length-3))})}b.npcs=chosen}
function moveNPCs(){const b=S.board;if(!b.npcs)return;for(const n of b.npcs)n.pos=(n.pos+1+Math.floor(Math.random()*3))%b.tiles.length}
function makeBoard(){const tiles=ROUTE.map((p,i)=>({x:p[0],y:p[1],type:TYPE_PATTERN[i],owner:-1,level:0,region:Math.floor(i/9)%4,price:9000+(i%7)*1800}));const players=activeSeatIds().map((si,id)=>({id,seat:si,type:S.seats[si].type,char:S.seats[si].char,diff:S.seats[si].diff,cash:S.money+(S.seats[si].char===9?2000:0),pos:0,cards:[],tickets:0,skip:0,shield:0,bankrupt:false,effects:[],hopeUsed:false,rentBoost:0,discount:0,slow:0}));S.board={worldW:MW,worldH:MH,tiles,players,turn:0,round:1,cam:{x:650,y:900,target:null},popup:null,mini:null,log:['遊戲開始！'],winner:null,npcs:[]};spawnNPCs();focus(true);saveGame()}
function npcAt(pos){return S.board.npcs?.find(n=>n.pos===pos)}
function applyNPCByName(name,p){const n=NPC_DEFS.find(x=>x.name===name);if(!n)return;n.apply(p);openPopup('npc',{name:n.name,desc:n.desc});addLog(`${p.id+1}P 遇到${n.name}：${n.desc}`)}
function resolveTile(){const b=S.board,p=cp(),t=b.tiles[p.pos],n=npcAt(p.pos);if(n){applyNPCByName(n.name,p);if(p.type==='ai')setTimeout(aiResolve,420);return}if(t.type==='start'){cashGain(p,5000);addLog(`${p.id+1}P 經過起點，獲得 $5,000`)}openPopup('tile',{tile:t});if(p.type==='ai')setTimeout(aiResolve,420)}
function applySpecial(t,p){if(t.type==='event'){const e=EVENTS[Math.floor(Math.random()*EVENTS.length)];e[2](p);openPopup('event',{name:e[0],desc:e[1]});addLog(`${p.id+1}P：${e[0]}・${e[1]}`)}else if(t.type==='card'){drawCard(p);const c=p.cards[p.cards.length-1];openPopup('carddraw',{card:c});addLog(`${p.id+1}P 抽到 ${c}`)}else if(t.type==='shop'){openPopup('shop');addLog(`${p.id+1}P 進入童話商店`)}else if(t.type==='npc'){const pool=NPC_DEFS.filter(n=>S.board.players.some(x=>x.bankrupt)||n.name!=='乞丐'),n=pool[Math.floor(Math.random()*pool.length)];n.apply(p);openPopup('npc',{name:n.name,desc:n.desc});addLog(`${p.id+1}P 遇到${n.name}：${n.desc}`)}else if(t.type==='minigame'){if(p.type==='ai'){p.tickets+=2;cashGain(p,p.char===7?3200:2500);addLog(`${p.id+1}P 完成小遊戲，獲得獎勵`)}else{const names=['星光停格','月兔節拍','雲梯反應','精靈採集','寶箱時機','魔法指針','彩星追蹤','森林露珠'];S.board.mini={pos:0,dir:1,last:performance.now(),name:names[Math.floor(Math.random()*names.length)]};openPopup('mini',{name:S.board.mini.name})}}}
function ensureSolvent(p){if(p.cash>=0)return;const houses=S.board.tiles.filter(t=>t.owner===p.id&&t.level>0).sort((a,b)=>b.level-a.level);for(const t of houses){while(t.level>0&&p.cash<0){p.cash+=Math.round(t.price*.32);t.level--;addLog(`${p.id+1}P 變賣房屋籌措資金`)}}const lands=S.board.tiles.filter(t=>t.owner===p.id);for(const t of lands){if(p.cash>=0)break;p.cash+=Math.round(t.price*.55);t.owner=-1;t.level=0;addLog(`${p.id+1}P 出售土地籌措資金`)}if(p.cash<0&&p.char===9&&!p.hopeUsed){p.hopeUsed=true;p.cash=10000;addLog(`${p.id+1}P 的希望之力避免破產，恢復 $10,000`)}if(p.cash<0){p.bankrupt=true;p.cash=0;S.board.tiles.forEach(t=>{if(t.owner===p.id){t.owner=-1;t.level=0}});addLog(`${p.id+1}P 破產退場！`);spawnNPCs()}}
function finishAction(){const p=cp();ensureSolvent(p);S.board.popup=null;S.board.mini=null;saveGame();nextTurn()}
function nextTurn(){const b=S.board;if(living().length<=1){const w=living()[0];b.winner=w;openPopup('winner',{text:w?`${w.id+1}P ${CHAR_NAMES[w.char]} 獲勝！`:'本局結束'});return}let wrapped=false,guard=0;do{b.turn++;if(b.turn>=b.players.length){b.turn=0;b.round++;wrapped=true}guard++}while(cp().bankrupt&&guard<10);if(wrapped)moveNPCs();if(b.round>S.rounds){const sorted=living().slice().sort((a,b)=>netWorth(b)-netWorth(a)),w=sorted[0];b.winner=w;openPopup('winner',{text:`${w.id+1}P ${CHAR_NAMES[w.char]} 資產第一！`});return}const p=cp();tickEffects(p);if(p.skip>0){p.skip--;addLog(`${p.id+1}P 本回合暫停`);setTimeout(nextTurn,650);return}focus();if(p.type==='ai')setTimeout(rollDice,700)}
function moveSteps(steps){const b=S.board,p=cp();S.rolling=true;let n=0;const step=()=>{if(n>=steps){S.rolling=false;resolveTile();return}const old=p.pos;p.pos=(p.pos+1)%b.tiles.length;if(p.pos===0&&old!==0){cashGain(p,5000);addLog(`${p.id+1}P 通過起點 +$5,000`)}n++;focus();setTimeout(step,175)};step()}
function rollDice(){if(S.rolling||!S.board||S.board.popup||S.board.winner)return;const p=cp();S.rolling=true;let spins=0;const timer=setInterval(()=>{S.dice=1+Math.floor(Math.random()*6);spins++;if(spins>=9){clearInterval(timer);let d=S.forcedDice||S.dice;S.forcedDice=0;if(p.char===1&&d===1&&Math.random()<.5)d=2;if(p.char===5&&d<=2&&Math.random()<.3)d=3;if(p.slow){d=Math.min(d,3);p.slow=0}S.dice=d;S.rolling=false;addLog(`${p.id+1}P 擲出 ${d} 點`);setTimeout(()=>moveSteps(d),180)}},70)}
function aiResolve(){const b=S.board,p=cp(),q=b.popup;if(!q)return;const smart=p.diff==='smart',easy=p.diff==='easy';if(q.kind==='tile'){const t=q.tile;if(t.type==='land'){if(t.owner<0){const cost=buyCost(p,t),reserve=easy?70000:smart?25000:45000;if(p.cash-cost>reserve){p.cash-=cost;if(p.discount)p.discount=0;t.owner=p.id;addLog(`${p.id+1}P 購買 ${REGION_NAMES[t.region]} 土地`)}finishAction();return}if(t.owner===p.id){const cost=Math.round(t.price*.65),want=t.level<3&&p.cash-cost>(easy?90000:smart?30000:55000);if(want){p.cash-=cost;t.level++;addLog(`${p.id+1}P 將土地升到 Lv${t.level}`)}finishAction();return}const r=rentFor(t,p);if(p.shield>0){p.shield--;addLog(`${p.id+1}P 使用護盾免除租金`)}else{p.cash-=r;const o=b.players.find(x=>x.id===t.owner);if(o&&!o.bankrupt)o.cash+=r}finishAction();return}if(['event','card','shop','minigame','npc'].includes(t.type)){applySpecial(t,p);if(t.type==='minigame'){finishAction();return}setTimeout(aiResolve,360);return}finishAction();return}if(q.kind==='shop'){const c=shopCost(p);if(p.cash>(easy?70000:35000)){p.cash-=c;drawCard(p);addLog(`${p.id+1}P 在商店買了一張卡片`)}finishAction();return}if(['event','npc','carddraw'].includes(q.kind)){finishAction();return}}
function useCard(i){const p=cp(),c=p.cards[i];if(!c)return;p.cards.splice(i,1);if(c==='精準骰子')S.forcedDice=6;else if(c==='遙控骰子')S.forcedDice=3;else if(c==='護身符')p.shield++;else if(c==='加速靴'){S.board.popup=null;moveSteps(3);return}else if(c==='財富卡')cashGain(p,5000);else if(c==='地產折價券')p.discount=1;else if(c==='幸運符')cashGain(p,2500);else if(c==='免費升級卡')upgradeRandomLand(p);else if(c==='租金加倍卡')p.rentBoost=1;else if(c==='交換卡'){const o=living().filter(x=>x.id!==p.id).sort((a,b)=>b.cash-a.cash)[0];if(o){const z=p.pos;p.pos=o.pos;o.pos=z;focus()}}else if(c==='瞬移卡'){S.board.popup=null;moveSteps(6);return}else if(c==='停留卡'){const o=living().filter(x=>x.id!==p.id).sort((a,b)=>b.cash-a.cash)[0];if(o)o.skip++}addLog(`${p.id+1}P 使用 ${c}`);S.board.popup=null;saveGame()}
function saveGame(){if(!S.board)return;try{localStorage.setItem(SAVE,JSON.stringify({seats:S.seats,money:S.money,rounds:S.rounds,settings:S.settings,board:S.board}))}catch(e){}}
function loadGame(){try{const d=JSON.parse(localStorage.getItem(SAVE));if(!d||!d.board)return false;S.seats=d.seats||S.seats;S.money=d.money||S.money;S.rounds=d.rounds||S.rounds;S.board=d.board;S.board.popup=null;S.board.mini=null;S.board.npcs=S.board.npcs||[];S.board.players.forEach(p=>{p.effects=p.effects||[]});S.scene='game';focus(true);if(cp().type==='ai')setTimeout(rollDice,700);return true}catch(e){return false}}
function game(){const b=S.board;if(b.cam&&b.cam.target){b.cam.x+=(b.cam.target.x-b.cam.x)*.11;b.cam.y+=(b.cam.target.y-b.cam.y)*.11;if(Math.hypot(b.cam.target.x-b.cam.x,b.cam.target.y-b.cam.y)<1)b.cam.target=null}X.save();X.translate(-b.cam.x,-b.cam.y);drawMap();X.restore();hud();popup();if(b.mini&&b.popup&&b.popup.kind==='mini'){const now=performance.now(),dt=Math.min(.04,(now-b.mini.last)/1000);b.mini.last=now;b.mini.pos+=b.mini.dir*dt*.82;if(b.mini.pos>=1){b.mini.pos=1;b.mini.dir=-1}if(b.mini.pos<=0){b.mini.pos=0;b.mini.dir=1}}}
function cycleVal(v,arr){const i=arr.indexOf(v);return arr[(i+1)%arr.length]}
function action(id){if(!id)return;if(id==='start'){S.scene='setup';return}if(id==='continue'){if(!loadGame())S.scene='setup';return}if(id==='help'){S.scene='help';return}if(id==='settings'){S.scene='settings';return}if(id==='home'){S.scene='home';S.board=null;return}if(id==='back'){S.scene='home';return}
if(S.scene==='settings'){if(id==='master')S.settings.master=cycleVal(S.settings.master,[0,25,50,75,100]);else if(id==='bgm')S.settings.bgm=cycleVal(S.settings.bgm,[0,25,50,75,100]);else if(id==='sfx')S.settings.sfx=cycleVal(S.settings.sfx,[0,25,50,75,100]);else if(id==='vibrate')S.settings.vibrate=!S.settings.vibrate;else if(id==='graphics')S.settings.graphics=cycleVal(S.settings.graphics,['low','medium','high','ultra']);else if(id==='lang')S.settings.lang=cycleVal(S.settings.lang,['zh-Hant','zh-Hans','en']);savePrefs();return}
if(S.scene==='setup'){if(id.startsWith('char')){chooseChar(+id.slice(4));return}if(id.startsWith('human')){const i=+id.slice(5);S.seats[i].type='human';S.activeSeat=i;return}if(id.startsWith('ai')&&!id.startsWith('diff')){const i=+id.slice(2);S.seats[i].type='ai';S.activeSeat=i;return}if(id.startsWith('off')){const i=+id.slice(3);S.seats[i].type='off';if(S.activeSeat===i){const a=activeSeatIds();if(a.length)S.activeSeat=a[0]}return}if(id.startsWith('seat')){S.activeSeat=+id.slice(4);return}if(id.startsWith('diff')){const i=+id.slice(4);S.seats[i].diff=cycleVal(S.seats[i].diff,['easy','standard','smart']);return}if(id==='money'){S.money=cycleVal(S.money,[100000,200000,300000,500000]);return}if(id==='rounds'){S.rounds=cycleVal(S.rounds,[20,30,45,60]);return}if(id==='startGame'){makeBoard();S.scene='game';if(cp().type==='ai')setTimeout(rollDice,700);return}}
if(S.scene==='game'&&S.board){const b=S.board,p=cp(),q=b.popup;if(id==='roll'){rollDice();return}if(id==='cards'){openPopup('cards');return}if(id==='closeCards'){b.popup=null;return}if(id.startsWith('useCard')){useCard(+id.slice(7));return}if(id==='buy'){const t=q.tile,cost=buyCost(p,t);if(p.cash>=cost){p.cash-=cost;if(p.discount)p.discount=0;t.owner=p.id;addLog(`${p.id+1}P 購買 ${REGION_NAMES[t.region]} 土地`)}finishAction();return}if(id==='upgrade'){const t=q.tile,cost=Math.round(t.price*.65);if(t.level<3&&p.cash>=cost){p.cash-=cost;t.level++;addLog(`${p.id+1}P 將土地升到 Lv${t.level}`)}finishAction();return}if(id==='pay'){const t=q.tile,r=rentFor(t,p);if(p.shield>0){p.shield--;addLog(`${p.id+1}P 使用護盾免除租金`)}else{p.cash-=r;const o=b.players.find(x=>x.id===t.owner);if(o&&!o.bankrupt)o.cash+=r;addLog(`${p.id+1}P 支付 $${r.toLocaleString()} 租金`)}finishAction();return}if(id==='skip'||id==='ok'){finishAction();return}if(id==='special'){applySpecial(q.tile,p);return}if(id==='eventOk'||id==='npcOk'||id==='cardOk'){finishAction();return}if(id==='shopBuy'){const c=shopCost(p);if(p.cash>=c){p.cash-=c;drawCard(p);addLog(`${p.id+1}P 購買卡片：${p.cards[p.cards.length-1]}`)}finishAction();return}if(id==='miniStop'){const dist=Math.abs((b.mini?.pos??0)-.5),base=dist<.07?7000:dist<.18?4500:2200,reward=p.char===7?Math.round(base*1.25):base;p.cash+=reward;p.tickets+=dist<.18?2:1;addLog(`${p.id+1}P 小遊戲獲得 $${reward.toLocaleString()}`);finishAction();return}}
}
C.addEventListener('pointerup',e=>{const p=pointerToGame(e),b=hit(p.x,p.y);if(b)action(b.id)});
function frame(){begin();if(S.scene==='home')home();else if(S.scene==='setup')setup();else if(S.scene==='game'&&S.board)game();else if(S.scene==='help')help();else if(S.scene==='settings')settings();requestAnimationFrame(frame)}requestAnimationFrame(frame);
