'use strict';const $=G.$,canvas=$('#canvas'),ctx=canvas.getContext('2d');let state=null;
const data=G.init({id:'flappy',art:'art-v2',music:'../shared/audio/sherwood.mp3',orientation:'portrait',pause});data.mail=G.clamp(Math.floor(data.mail)||0,0,1000000);data.stage=G.clamp(Math.floor(data.stage)||1,1,6);
G.rolePicker('#roles',undefined,i=>{$('#pilot').innerHTML=G.sprite(i);$('#pilot-label').textContent='飛行角色：'+G.roles[i]+'（點此更換）'});
function refresh(){ $('#stage').innerHTML=Array.from({length:6},(_,i)=>'<option value="'+(i+1)+'" '+(i+1>data.stage?'disabled':'')+'>第 '+(i+1)+' 站'+(i+1>data.stage?' · 尚未抵達':'')+'</option>').join('');$('#stage').value=data.stage;$('#route').options[1].disabled=data.mail<10;$('#route').options[2].disabled=data.mail<25;$('#vehicle').options[1].disabled=data.mail<5;$('#vehicle').options[2].disabled=data.mail<15;$('#trail').options[1].disabled=data.mail<10;G.toast('累計送達 '+data.mail+' 封信。不同角色的操作與碰撞範圍完全相同。') }refresh();$('#mode').onchange=()=>$('#stage').disabled=$('#mode').value!=='mission';
G.load(['art-v2/moon.webp','art-v2/scene.webp','art-v2/kit.webp','art-v2/cast-a.webp','art-v2/cast-b.webp','art-v2/forest.webp']).catch(()=>{});
function start(){$('#score').textContent='0';$('#mail').textContent='0';state={running:true,paused:false,mode:$('#mode').value,stage:+$('#stage').value,route:$('#route').value,vehicle:+$('#vehicle').value,trail:+$('#trail').value,y:290,vy:0,x:110,time:0,score:0,mail:0,pipes:[],next:1.7,center:300,countdown:1.2,crash:null};$('#home').hidden=true;$('#play').hidden=false;G.playing(true);canvas.focus()}
function flap(){if(!state?.running||state.paused||state.countdown>0)return;state.vy=-285;G.sound('jump',1.2)}
function spawn(){const easy=state.mode==='practice',gap=easy?240:Math.max(165,207-state.stage*5-Math.min(state.score,20));state.center=G.clamp(state.center+(Math.random()-.5)*125,150+gap/2,525-gap/2);state.pipes.push({x:440,top:state.center-gap/2,bottom:state.center+gap/2,passed:false,taken:false})}
function update(dt){if(!state?.running||state.paused)return;if(state.countdown>0){state.countdown-=dt;$('#status').textContent='準備起飛 '+Math.ceil(state.countdown);return}state.time+=dt;state.vy+=820*dt;state.y+=state.vy*dt;const speed=state.mode==='practice'?110:Math.min(190,128+state.score*1.4+state.stage*3);if(state.time>=state.next){spawn();state.next=state.time+(state.mode==='practice'?2.2:1.9)}let crash=state.y-12<0||state.y+12>620;for(const p of state.pipes){p.x-=speed*dt;const near=state.x+12>p.x+8&&state.x-12<p.x+60;if(near&&(state.y-12<p.top-4||state.y+12>p.bottom+4)){crash=true;state.crash={x:state.x,y:state.y}}if(!p.taken&&Math.hypot(p.x+34-state.x,(p.top+p.bottom)/2-state.y)<36){p.taken=true;state.mail++;G.sound('collect')}if(!p.passed&&p.x+68<state.x-12){p.passed=true;state.score++;G.sound('flip');if(state.mode==='mission'&&state.score>=5+state.stage*2){finish(true);return}}}state.pipes=state.pipes.filter(p=>p.x>-90);$('#score').textContent=state.score;$('#mail').textContent=state.mail;$('#status').textContent=state.mode==='mission'?'第 '+state.stage+' 站 · 目標 '+(5+state.stage*2)+' 個郵站':'輕點上升，留意下一個開口。';if(crash){state.crash??={x:state.x,y:G.clamp(state.y,15,575)};finish(false)}}
function draw(){ctx.clearRect(0,0,400,620);const bg=G.images[state?.route==='forest'?'art-v2/forest.webp':state?.route==='moon'?'art-v2/moon.webp':'art-v2/scene.webp'];if(bg)ctx.drawImage(bg,0,0,400,620);if(!state)return;const kit=G.images['art-v2/kit.webp'];for(const p of state.pipes){ctx.save();ctx.translate(p.x,p.top);ctx.scale(1,-1);G.trimTile(ctx,kit,3,3,2,0,0,68,p.top);ctx.restore();G.trimTile(ctx,kit,3,3,2,p.x,p.bottom,68,620-p.bottom);if(!p.taken)G.tile(ctx,kit,4,3,2,p.x+15,(p.top+p.bottom)/2-20,38,38)}if(state.trail)for(let i=1;i<5;i++){ctx.globalAlpha=(5-i)*.13;G.tile(ctx,kit,5,3,2,state.x-30-i*16,state.y-8+Math.sin(state.time*5-i)*7,23,23)}ctx.globalAlpha=1;ctx.save();ctx.translate(state.x,state.y);ctx.rotate(G.clamp(state.vy/1100,-.25,.55));G.drawRole(ctx,data.role,-29,-40,58,58);G.tile(ctx,kit,state.vehicle,3,2,-37,-1,74,42);ctx.restore();if(state.crash){ctx.strokeStyle='#b3563d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(state.crash.x,state.crash.y,17,0,Math.PI*2);ctx.stroke()}if(state.countdown>0){ctx.fillStyle='#395371';ctx.font='bold 38px serif';ctx.textAlign='center';ctx.fillText('準備起飛',200,210)}}
function finish(win){if(!state.running)return;state.running=false;G.playing(false);if(state.mode!=='practice'){data.mail+=state.mail;if(win&&state.mode==='mission'){data.stage=Math.min(6,Math.max(data.stage,state.stage+1));data.wins++}G.records(state.mode+'-'+state.route,state.score);G.save()}G.sound(win?'win':'lose');G.dialog(win?'信件平安送達！':'在這裡歇一下翅膀','<div class="dialog-stats"><span><b>'+state.score+'</b><small>郵站</small></span><span><b>'+state.mail+'</b><small>信件</small></span></div><p>'+(state.mode==='practice'?'練習不列入收藏與紀錄。':win?'下一段天空郵路正在等你。':'航道已標出碰撞位置。下一次，再試一次。')+'</p>',[['立即重飛',start],['回到出發月台',home]])}
function home(){if(state)state.running=false;G.playing(false);G.resumeAudio();$('#home').hidden=false;$('#play').hidden=true;refresh()}
function pause(){if(!state?.running||state.paused)return;state.paused=true;G.hold();G.dialog('停靠雲端休息站','<p>飛行速度、障礙與信件已暫停。</p>',[['繼續飛行',()=>{state.paused=false;state.countdown=1;state.vy=0;G.resumeAudio();G.orientation()}],['回到月台',home]])}
$('#start').onclick=start;$('#pause').onclick=pause;canvas.onpointerdown=e=>{e.preventDefault();flap()};addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(state?.running&&['Space','ArrowUp','Escape'].includes(e.code)){e.preventDefault();if(e.code==='Escape')pause();else if(!e.repeat)flap()}});
$('#records').onclick=()=>G.dialog('航程紀錄',G.recordHTML($('#mode').value+'-'+$('#route').value,'個郵站'),[['返回月台']]);
const letters=[['第一封問候','謝謝你讓等待的人，聽見敲門聲。'],['森林的回信','沿路的鈴聲，都是替你留下的路標。'],['雨後的約定','今天沒有晴天，也可以慢慢前進。'],['月光的地址','信封裡裝著一句：你已經做得很好了。'],['星願的旅程','每一小段路，都讓彼此更靠近。'],['未完的故事','下一次出發，還有新的相遇。']];$('#letters').onclick=()=>G.dialog('郵件收藏 · '+data.mail+' 封','<div class="collected-grid">'+letters.map((l,i)=>'<article class="letter-card">'+G.sprite(i)+'<h3>'+(data.mail>=i*5+1?l[0]:'尚未收到')+'</h3><p>'+(data.mail>=i*5+1?l[1]:'累計 '+(i*5+1)+' 封解鎖')+'</p></article>').join('')+'</div>',[['把信收好']]);G.settings(["mode","stage","route","vehicle","trail"]);G.frame(update,draw);
