import {CAST,BY_ID,STAGES,ENDINGS,CONTROLS,ACTION_NAMES,VERSION} from './cast.mjs?v=20261007-duel3';
import {createMatch,step,DT,restore,nextRound,clearInputs} from './core.mjs?v=20261007-duel3';
import {storage} from './save.mjs?v=20261007-duel3';
import {renderer} from './render.mjs?v=20261007-duel3';
import {input} from './input.mjs?v=20261007-duel3';
const root=document.querySelector('#app'),modal=document.querySelector('#modal'),db=storage(),$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let page='home',selected={mode:'story',p1:'growth',p2:'luck',stage:'festival',difficulty:'normal',player:0},match=null,run=null,paint=null,paused=false,loading=false,handledRound=0,eventCursor=0,lastSave=0,messageUntil=0,messageText='',inputHistory=[],resumeAt=0,bindTarget=null;
let music=null,musicId='',audioUnlocked=false,soundContext=null,soundAt=0,frameCount=0,fpsTime=0,fps=0,lowWindows=0,lastFrame=performance.now(),accumulator=0,hudAt=0;
const prefs=()=>db.get().settings;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function button(text,action,extra='',className=''){return`<button class="${className}" data-action="${action}" ${extra}>${text}</button>`;}
function topbar(){return`<header class="topbar"><a class="brand" href="../../?v=${VERSION}">CxQ 心光對決</a><nav>${button('玩法','guide')}${button('設定','settings')}${button('存檔','saves')}</nav></header>`;}
function applyPreferences(){const p=prefs();document.body.classList.toggle('reduced',p.reducedMotion);document.documentElement.style.setProperty('--button-size',p.buttonSize);document.documentElement.style.setProperty('--button-opacity',p.opacity);document.documentElement.style.setProperty('--control-x',p.offsetX+'px');document.documentElement.style.setProperty('--control-y',p.offsetY+'px');paint?.resize();syncAudio();}
function home(){const saved=db.get().active||db.get().run;return`<main class="shell">${topbar()}<section class="hero"><img class="cover" src="art/cover.webp" alt="森芽與鈴可參加心光武鬥祭"><div class="hero-copy"><span class="eyebrow">CXQ · HEARTLIGHT DUEL</span><h1>心光對決</h1><p class="lead">十位夥伴，各自的力量。<br>在童話武鬥祭，打出你的節奏。</p><p>原創 1 對 1 格鬥 · 六鍵操作 · 三戰兩勝</p><div class="actions">${saved?button('繼續上次對戰','resume-save','','primary'):button('開始遊戲','mode','data-mode="story"','primary')}${button('認識十位夥伴','collection')}</div></div></section><div class="modes">${[['story','故事闖關','五場旅程與角色專屬結局'],['free','自由對戰','自由選角色、場地與難度'],['training','訓練場','傷害、連段、判定與輸入紀錄'],['survival','生存挑戰','保留生命，挑戰連勝紀錄'],['local','本機雙人','兩組鍵盤／兩支手把']].map(([mode,name,desc])=>button(`<b>${name}</b><small>${desc}</small>`,'mode',`data-mode="${mode}"`,'mode')).join('')}</div><div class="actions">${button('對戰紀錄','records')}${button('招式與操作','guide')}<a href="../../?v=${VERSION}">返回 CxQ 網站</a></div><p class="footer-note">角色全部開放 · 收藏不影響戰鬥能力 · 進度保存於此裝置${db.healthy()?'':' · 本機儲存暫時不可用，請下載備份'}</p></main>`;}
function preview(id,index){const c=BY_ID[id],selectable=selected.mode==='free'||selected.mode==='local'||selected.mode==='training';return`<article class="fighter-preview" style="--accent:${c.color}35"><img src="${c.poses.ready}" alt="${c.name}的戰鬥蓄勢"><div><span class="eyebrow">${index===0?'你的夥伴':selected.mode==='local'?'第二位玩家':'對手'}</span><h2>${c.name}</h2><span class="badge">${c.style} · ${'★'.repeat(c.difficulty)}</span><p>${c.title} · 代表詞：${c.word}</p><p>${c.tip}</p>${selectable?button(index===0?'更換玩家一':'更換對手','pick-side',`data-index="${index}"`,selected.player===index?'primary':'subtle'):''}</div></article>`;}
function selection(){const names={story:'故事闖關',free:'自由對戰',training:'訓練場',survival:'生存挑戰',local:'本機雙人'};return`<main class="shell">${topbar()}<span class="eyebrow">${names[selected.mode]}</span><h1>選擇你的心光夥伴</h1><div class="selection-layout">${preview(selected.p1,0)}${preview(selected.p2,1)}</div><div class="role-grid" aria-label="十位角色">${CAST.map(c=>button(`<img src="${c.portrait}" alt=""><b>${c.name}</b>`,'pick-role',`data-role="${c.id}" aria-pressed="${selected[selected.player?'p2':'p1']===c.id}"`,selected[selected.player?'p2':'p1']===c.id?'role-card selected':'role-card')).join('')}</div><div class="selection-options"><label>對手難度<select id="difficulty"><option value="easy" ${selected.difficulty==='easy'?'selected':''}>入門 · 留出反應空間</option><option value="normal" ${selected.difficulty==='normal'?'selected':''}>標準 · 防守與連段</option><option value="hard" ${selected.difficulty==='hard'?'selected':''}>挑戰 · 預判與反擊</option></select></label><label>場地<select id="stage">${STAGES.map(s=>`<option value="${s.id}" ${selected.stage===s.id?'selected':''}>${s.name}</option>`).join('')}</select></label>${button('返回','home')}${button(selected.mode==='training'?'進入訓練場':'準備對戰','begin','','primary')}</div><div class="stage-tiles">${STAGES.map(s=>button(`<img src="${s.art}" alt="${s.name}">${s.name}`,'stage',`data-stage="${s.id}"`,s.id===selected.stage?'stage-tile selected':'stage-tile')).join('')}</div><p class="footer-note">${selected.mode==='local'?'玩家一：A D S、空白鍵、J K L I U｜玩家二：方向鍵、數字鍵盤 1 2 3 0 5；亦可使用兩支手把。':selected.mode==='story'?'五場對戰各採三戰兩勝，旅程與中途對戰均可保存。':selected.mode==='survival'?'每場一回合；勝利保留剩餘生命並恢復 20%，連勝越多難度越高。':'六個按鈕直接出招；按住格擋防守，向下移動搭配格擋防低段。'}</p></main>`;}
const icons={light:'<path d="M6 19l-2-7 3-2 2 3V5h3v7-8h3v8-6h3v8l2-3 2 2-4 7z"/>',heavy:'<path d="M4 16l4-7h8l4 7-4 5H8zM8 9V4h8v5M2 6l3 2M20 3l-2 4"/>',skill:'<path d="M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z"/>',jump:'<path d="M5 18l7-13 7 13M12 5v17"/>',guard:'<path d="M12 2l9 4v6c0 5-6 9-9 10-3-1-9-5-9-10V6zM7 12l3 3 7-7"/>',super:'<path d="M12 3c-6-5-15 3 0 17C27 6 18-2 12 3zM8 11l4-5-1 7h5l-4 5"/>'};
function fighterHud(f){const c=BY_ID[f.id];return`<div class="fighter-hud ${f.index?'right':''}"><div class="hud-name"><img src="${c.portrait}" alt=""><b>${c.name}</b><small>${c.style}</small></div><div class="bar" role="progressbar" aria-label="${c.name}生命" aria-valuemin="0" aria-valuemax="${f.maxHp}" aria-valuenow="${Math.round(f.hp)}" id="life-${f.index}"><i></i></div><div class="bar guard" aria-label="${c.name}防守值" id="guard-${f.index}"><i></i></div><div class="round-pips" id="wins-${f.index}"></div></div>`;}
function battle(){return`<main class="battle-page"><div class="battle-board"><canvas id="fight-canvas" width="1400" height="788" aria-label="${BY_ID[match.fighters[0].id].name}對戰${BY_ID[match.fighters[1].id].name}"></canvas><div class="hud">${fighterHud(match.fighters[0])}<div class="timer"><span id="round-time">60</span><small id="round-label">ROUND 1</small></div>${fighterHud(match.fighters[1])}</div><div class="battle-tools">${button('暫停','pause')}${match.mode==='training'?button('招式表','moves')+button('訓練設定','training-tools'):''}<span class="fps" id="fps">測量中</span></div><div class="combo-label" id="combo-label"></div><div class="combat-message" id="combat-message"></div><div class="meters">${match.fighters.map(f=>`<div><div class="meter-label">${BY_ID[f.id].name} · 必殺能量 <span id="energy-${f.index}">0</span></div><div class="bar meter" id="meter-${f.index}"><i style="width:0%"></i></div></div>`).join('')}</div>${match.mode==='training'?`<div class="training-panel"><p id="training-stats">累計傷害 0 · 最長連段 0</p><div class="input-log" id="input-log"></div><div class="actions">${button('站立','dummy','data-dummy="stand"')}${button('格擋','dummy','data-dummy="guard"')}${button('反擊','dummy','data-dummy="counter"')}${button('重置','reset-training')}${button('近距離','training-close')}${button('遠距離','training-far')}${button('判定','hitboxes')}</div></div>`:''}<div class="touch-controls"><button class="joystick" data-control="stick" aria-label="方向控制：左右移動，向下蹲下"><span class="stick-knob"></span></button><div class="attack-pad">${['light','heavy','skill','jump','guard','super'].map(a=>`<button class="control-button" data-control="${a}" aria-label="${ACTION_NAMES[a]}"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[a]}</svg><span>${ACTION_NAMES[a]}</span></button>`).join('')}</div></div><div class="load-panel" id="load-panel"><div><h2>夥伴準備上場</h2><p>載入本場兩位角色的動作與場景…</p></div></div></div><div class="rotate-gate" id="rotate-gate" hidden><div><b>↻ 請橫向遊玩</b><p>對戰已暫停。旋轉手機後，再按繼續，招式和按鍵才能完整顯示。</p>${button('返回選角','leave')}</div></div></main>`;}
function render(){paint?.dispose();paint=null;if(page==='battle')root.innerHTML=battle();else if(page==='select')root.innerHTML=selection();else if(page==='result')root.innerHTML=resultPage();else if(page==='collection')root.innerHTML=collectionPage();else if(page==='records')root.innerHTML=recordsPage();else root.innerHTML=home();applyPreferences();if(page==='select'){ $('#difficulty').onchange=e=>selected.difficulty=e.target.value;$('#stage').onchange=e=>{selected.stage=e.target.value;render();};}if(page==='battle'){paint=renderer($('#fight-canvas'),prefs);loading=true;paint.prepare(match).then(()=>{if(page!=='battle')return;loading=false;$('#load-panel').hidden=true;checkOrientation();fpsTime=performance.now();frameCount=0;}).catch(e=>{loading=true;$('#load-panel').innerHTML=`<div><h2>素材暫時未能載入</h2><p>${esc(e.message)}</p><div class="actions">${button('重試','retry-load','','primary')}${button('返回選角','leave')}</div></div>`;});}}
function dialog(title,html){modal.innerHTML=`<div class="dialog-head"><h2>${title}</h2>${button('關閉','close')}</div>${html}`;if(!modal.open)modal.showModal();}
function pause(reason='manual'){if(page!=='battle'||loading)return;paused=true;controls.reset();accumulator=0;syncAudio();if(reason==='orientation')return;dialog('對戰暫停',`<p>目前回合、生命與能量已保留。</p><div class="actions">${button('繼續對戰','unpause','','primary')}${button('招式表','moves')}${button('操作設定','settings')}${button('返回選角並保存','leave')}</div>`);capture();}
function unpause(){if(page!=='battle')return;modal.close();if(checkOrientation())return;paused=true;resumeAt=performance.now()+1200;fpsTime=performance.now();frameCount=0;controls.reset();messageText='準備繼續';messageUntil=Infinity;}
function checkOrientation(){if(page!=='battle')return false;const gate=$('#rotate-gate'),wrong=innerHeight>innerWidth&&(innerWidth<700||navigator.maxTouchPoints>0);gate.hidden=!wrong;if(wrong){pause('orientation');resumeAt=0;}return wrong;}
function capture(){if(match&&page==='battle')db.capture(match,run);}
function chooseMode(mode){capture();match=null;run=null;paused=false;modal.close();selected.mode=mode;selected.player=0;page='select';render();}
function journey(){const hero=selected.p1;const available=CAST.filter(c=>c.id!==hero).map(c=>c.id);const offset=CAST.findIndex(c=>c.id===hero);const opponents=Array.from({length:5},(_,i)=>available[(offset+i*2)%available.length]);return{mode:selected.mode,hero,index:0,opponents,difficulty:selected.difficulty,stage:selected.stage,wins:0,health:null};}
function optionsForRun(){const opponent=run.mode==='story'?run.opponents[run.index]:CAST.filter(c=>c.id!==run.hero)[run.index%9].id;return{mode:run.mode,p1:run.hero,p2:opponent,stage:STAGES[(STAGES.findIndex(s=>s.id===run.stage)+run.index)%4].id,difficulty:run.mode==='survival'&&run.index>=4?'hard':run.difficulty};}
function begin(){run=['story','survival'].includes(selected.mode)?journey():null;start(run?optionsForRun():{...selected});}
function start(options,restored=null){controls.reset();selected={...selected,...options,player:0};match=restored||createMatch(options);if(run?.mode==='survival'&&run.health!==null&&!restored)match.fighters[0].hp=Math.max(1,Math.min(match.fighters[0].maxHp,run.health));page='battle';paused=false;handledRound=0;eventCursor=0;messageUntil=0;resumeAt=0;accumulator=0;inputHistory=[];render();db.capture(match,run);syncAudio();}
function resumeSave(){try{const s=db.get();run=s.run;if(!s.active&&run){start(optionsForRun());return;}const m=restore(s.active);start(m.options,m);paused=true;if(m.phase==='round')roundDialog();else dialog('繼續上次對戰',`<p>${BY_ID[m.fighters[0].id].name} 對 ${BY_ID[m.fighters[1].id].name} · 第 ${m.round} 回合</p><div class="actions">${button('繼續','unpause','','primary')}${button('返回選角','leave')}</div>`);}catch(e){toast(e.message);}}
function roundDialog(){paused=true;controls.reset();handledRound=match.round;const r=match.result,name=r.winner<0?'雙方平手':BY_ID[match.fighters[r.winner].id].name+'拿下回合';dialog(r.reason==='KO'?'回合結束':'時間到',`<h3>${name}</h3><p>比分 ${match.wins[0]}：${match.wins[1]}${r.winner<0?' · 同分重賽，未增加勝場':''}</p><div class="actions">${button(r.matchOver?'查看本場結果':'下一回合',r.matchOver?'finish':'next-round','','primary')}${button('保存並返回選角','leave')}</div>`);capture();sound('round');}
let finalRecord=null;
function finish(){modal.close();const win=match.result.winner===0;finalRecord={hero:match.fighters[0].id,opponent:match.fighters[1].id,win,mode:match.mode,wins:[...match.wins],damage:Math.round(match.fighters[0].damage),combo:match.training.maxCombo,rounds:match.round,stage:match.stage,journey:run?{...run}:null};
 if(run&&win){run.wins++;if(run.mode==='survival'){run.health=Math.min(match.fighters[0].maxHp,match.fighters[0].hp+match.fighters[0].maxHp*.2);run.index++;}else{run.index++;const best=db.get().story[run.hero]||{cleared:0,completed:false};best.cleared=Math.max(best.cleared,run.index);best.completed=best.completed||run.index>=5;db.get().story[run.hero]=best;}}
 db.finish(finalRecord);if(run&&win&&(run.mode==='survival'||run.index<5)){db.get().run=structuredClone(run);db.save();}else{run=null;}
 page='result';paused=false;render();syncAudio();sound(win?'win':'lose');}
function resultPage(){const r=finalRecord,c=BY_ID[r.hero],winner=BY_ID[r.win?r.hero:r.opponent],completed=r.win&&r.journey?.mode==='story'&&r.journey.index===4;return`<main class="shell">${topbar()}<section class="result"><span class="eyebrow">${completed?'STORY COMPLETE':'HEARTLIGHT FESTIVAL'}</span><h1>${completed?c.name+'的心光旅程':r.win?'勝利':'再練一次，也會更靠近'}</h1><div class="result-stage"><img src="${winner.poses.victory}" alt="${winner.name}的勝利動作"><h2>${winner.name} · ${winner.title}</h2>${completed?`<p>${ENDINGS[c.id]}</p>`:`<p>${r.journey?.mode==='survival'?`本次連勝 ${r.journey.wins+(r.win?1:0)} 場`:r.journey?.mode==='story'?`故事旅程 ${r.journey.index+1}／5 場`:''} ${r.wins[0]}：${r.wins[1]}</p>`}<div class="result-stats"><span>最長連段 ${r.combo}</span><span>本回合傷害 ${r.damage}</span></div>${r.win?'<span class="badge">已收藏角色勝利徽章</span>':''}</div><div class="actions">${run&&r.win?button(run.mode==='story'?'前往下一場':'繼續生存挑戰','journey-next','','primary'):button('再戰一次','rematch','','primary')}${button('換角色','select')}${button('返回首頁','home')}</div></section></main>`;}
function collectionPage(){return`<main class="shell">${topbar()}<h1>十位心光夥伴</h1><p>每位角色全部開放。勝利徽章只作紀念，不增加能力。</p><div class="collection">${CAST.map(c=>`<article><img src="${c.portrait}" alt="${c.name}"><h3>${c.name}</h3><p>${c.title} · ${c.word}</p><p>${c.style}</p><span class="badge">${db.get().unlocks.includes(c.id)?'已獲得勝利徽章':'等待第一場勝利'}</span><p>故事 ${db.get().story[c.id]?.cleared||0}／5</p>${button('招式介紹','character-guide',`data-role="${c.id}"`)}</article>`).join('')}</div><div class="actions">${button('返回首頁','home')}</div></main>`;}
function recordsPage(){return`<main class="shell">${topbar()}<h1>武鬥祭紀錄</h1><div class="record-list">${db.get().records.length?db.get().records.map(r=>`<article class="record"><span>${BY_ID[r.hero]?.name||'夥伴'} 對 ${BY_ID[r.opponent]?.name||'夥伴'} · ${r.win?'勝利':'落敗'}<br><small>${new Date(r.at).toLocaleString('zh-TW')}</small></span><b>${r.wins?.join('：')||''}<br><small>連段 ${r.combo||0}</small></b></article>`).join(''):'<p>第一場心光對決正在等你。</p>'}</div><div class="actions">${button('返回首頁','home')}</div></main>`;}
function guide(){if(page==='battle')pause();dialog('武鬥祭手冊',`<div class="guide-grid"><article><b>移動與防守</b><p>方向盤左右移動、向下蹲下。跳躍使用獨立按鈕；按住格擋防正面攻擊。低段需蹲下格擋，空中攻擊需站立格擋。</p></article><article><b>出招與連段</b><p>輕攻擊快，重攻擊收招較慢。輕擊命中後可接下一招，連段傷害逐次降低；五次命中會強制擊倒並給予起身保護。</p></article><article><b>投技與破防</b><p>近距離同按輕攻擊和重攻擊施放投技，不能被格擋。防守值耗盡會短暫破防，停止格擋後逐漸恢復。</p></article><article><b>技能與必殺</b><p>技能有獨立冷卻。攻擊與有效防守累積必殺能量，滿 100 才能施放必殺。打空的大招有明顯反擊空間。</p></article><article><b>鍵盤與手把</b><p>玩家一：A D 移動、S 蹲下、空白跳躍、J K L 攻擊、I 格擋、U 必殺。手把：左搖桿、A 跳、X 輕、Y 重、B 技能、LB 格擋、RB 必殺、Start 暫停。</p></article><article><b>公平與存檔</b><p>AI 依已出現的招式判斷，難度影響反應時間。外觀收藏不增加能力；中途存檔可接續回合。切到背景或旋轉手機會暫停。</p></article></div><div class="actions">${button('角色招式表','moves')}${page==='battle'?button('返回對戰','unpause','','primary'):button('知道了','close','','primary')}</div>`);}
function moves(id=match?.fighters[0].id||selected.p1){const c=BY_ID[id];if(page==='battle')pause();dialog(c.name+'的招式表',`<p>${c.title} · 代表詞：${c.word} · ${c.style}</p><div class="guide-grid"><article><b>專屬技能 · ${c.skill}</b><p>${c.tip}</p><p>技能冷卻：${c.id==='healing'?'4':'2.5'} 秒</p></article><article><b>必殺技 · ${c.superName}</b><p>消耗 100 能量。強力招式可被防守或避開，收招時要留意反擊。</p></article><article><b>共通招式</b><p>輕攻擊、重攻擊、空中攻擊、近距離投技；雙擊方向鍵短距離衝刺。</p></article><article><b>練習重點</b><p>先確認招式距離，再練習格擋後反擊。訓練場可以開啟攻擊與受擊判定。</p></article></div><div class="actions">${page==='battle'?button('繼續練習','unpause','','primary'):button('返回','close','','primary')}</div>`);}
function settings(){if(page==='battle')pause();const p=prefs();dialog('操作與畫面設定',`<label>畫質<select data-setting="quality">${[['auto','自動'],['high','高畫質'],['low','效能模式']].map(([v,t])=>`<option value="${v}" ${p.quality===v?'selected':''}>${t}</option>`).join('')}</select></label>${[['buttonSize','按鈕大小',.8,1.15,.05],['opacity','按鈕透明度',.45,1,.05],['offsetX','左右控制區內移',0,36,2],['offsetY','控制區上移',0,24,2],['volume','音量',0,1,.05]].map(([k,label,min,max,step])=>`<label>${label}<input type="range" data-setting="${k}" min="${min}" max="${max}" step="${step}" value="${p[k]}"></label>`).join('')}${[['reducedMotion','減少閃光與震動'],['showFps','顯示實際 FPS'],['music','背景音樂'],['sound','攻擊音效']].map(([k,label])=>`<label>${label}<input type="checkbox" data-setting="${k}" ${p[k]?'checked':''}></label>`).join('')}<h3>自訂鍵盤</h3><p>點按鍵後，按下要使用的新按鍵。兩位玩家的按鍵不能重複。</p><div class="key-grid">${['p1','p2'].flatMap((group,i)=>Object.keys(CONTROLS[group]).map(action=>`<label>${i+1}P ${ACTION_NAMES[action]}${button(esc(p.keys[group][action].replace('Key','')),'bind-key',`data-group="${group}" data-key="${action}"`)}</label>`)).join('')}</div><div class="actions">${button('還原操作設定','reset-controls')}${page==='battle'?button('繼續對戰','unpause','','primary'):button('完成','close','','primary')}</div>`);}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function saves(){if(page==='battle')pause();dialog('存檔與備份',`<p>存檔包含角色故事、對戰紀錄、操作設定與未完成的對戰。匯入前會保存目前的有效存檔為備援。</p><p>${db.healthy()?'本機存檔正常':'本機儲存暫時不可用，請下載備份'}</p><div class="actions">${button('下載完整備份','export','','primary')}${button('匯入備份','import')}${button('關閉','close')}</div>`);}
function syncAudio(){if(!audioUnlocked)return;const p=prefs(),stage=STAGES.find(s=>s.id===(match?.stage||selected.stage))||STAGES[0],id=stage.music==='space'?'sherwood':'heavenly';if(musicId!==id){music?.pause();musicId=id;music=new Audio('../shared/audio/'+id+'.mp3');music.loop=true;}music.volume=p.volume;if(p.music&&!paused&&!document.hidden)music.play().catch(()=>{});else music.pause();}
function sound(type){if(!audioUnlocked||!prefs().sound)return;const now=performance.now();if(now-soundAt<45)return;soundAt=now;try{soundContext??=new (window.AudioContext||window.webkitAudioContext)();const o=soundContext.createOscillator(),g=soundContext.createGain();o.connect(g);g.connect(soundContext.destination);o.type=type==='block'?'triangle':'sine';o.frequency.setValueAtTime(type==='hit'?150:type==='super'?380:type==='win'?660:290,soundContext.currentTime);o.frequency.exponentialRampToValueAtTime(type==='hit'?65:100,soundContext.currentTime+.1);g.gain.setValueAtTime(prefs().volume*.18,soundContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,soundContext.currentTime+.12);o.start();o.stop(soundContext.currentTime+.13);}catch{}}
const controls=input({getMatch:()=>match,active:()=>page==='battle'&&!paused&&!loading&&!modal.open,onPause:()=>pause(),preferences:prefs,onAction:(i,a)=>{if(!i){inputHistory.push(ACTION_NAMES[a]);inputHistory=inputHistory.slice(-6);}}});
document.addEventListener('pointerdown',()=>{audioUnlocked=true;syncAudio();soundContext?.resume().catch(()=>{});},{once:true});document.addEventListener('keydown',()=>{audioUnlocked=true;syncAudio();},{once:true});
document.addEventListener('change',e=>{const key=e.target.dataset.setting;if(key){prefs()[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value;db.save();applyPreferences();}});
document.addEventListener('input',e=>{const key=e.target.dataset.setting;if(key&&e.target.type==='range'){prefs()[key]=Number(e.target.value);applyPreferences();}});
document.addEventListener('keydown',e=>{if(!bindTarget)return;e.preventDefault();e.stopImmediatePropagation();if(e.code==='Escape'){bindTarget=null;settings();return;}if(Object.entries(prefs().keys).some(([group,keys])=>Object.entries(keys).some(([k,v])=>v===e.code&&(group!==bindTarget.group||k!==bindTarget.key)))){toast('這個按鍵已被使用，請選其他按鍵');return;}prefs().keys[bindTarget.group][bindTarget.key]=e.code;bindTarget=null;db.save();settings();},true);
root.addEventListener('click',dispatch);modal.addEventListener('click',dispatch);
async function dispatch(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;sound('tap');
 if(a==='mode')chooseMode(b.dataset.mode);
 else if(a==='home'){capture();controls.reset();page='home';paused=false;modal.close();match=null;render();syncAudio();}
 else if(a==='select'||a==='leave'){capture();controls.reset();page='select';paused=false;modal.close();render();syncAudio();}
 else if(a==='pick-side'){selected.player=Number(b.dataset.index);render();}
 else if(a==='pick-role'){selected[selected.player?'p2':'p1']=b.dataset.role;if(['story','survival'].includes(selected.mode)&&selected.p1===selected.p2)selected.p2=CAST.find(c=>c.id!==selected.p1).id;render();}
 else if(a==='stage'){selected.stage=b.dataset.stage;render();}
 else if(a==='begin')begin();
 else if(a==='retry-load')render();
 else if(a==='resume-save')resumeSave();
 else if(a==='pause')pause();
 else if(a==='unpause')unpause();
 else if(a==='close'){bindTarget=null;modal.close();if(page==='battle')pause();}
 else if(a==='guide')guide();
 else if(a==='settings')settings();
 else if(a==='moves'||a==='character-guide')moves(b.dataset.role);
 else if(a==='saves')saves();
 else if(a==='export'){capture();download(db.export(),'CxQ-心光對決-'+Date.now()+'.json');toast('備份已下載');}
 else if(a==='import')$('#import-file').click();
 else if(a==='next-round'){modal.close();nextRound(match);paused=false;handledRound=0;controls.reset();capture();syncAudio();}
 else if(a==='finish')finish();
 else if(a==='training-tools'){pause();dialog('訓練場工具',`<p>選擇對手行為或練習距離；累計數據保留。</p><div class="actions">${button('站立','dummy','data-dummy="stand"')}${button('格擋','dummy','data-dummy="guard"')}${button('反擊','dummy','data-dummy="counter"')}${button('近距離','training-close')}${button('遠距離','training-far')}${button('顯示／隱藏判定','hitboxes')}${button('重置訓練','reset-training')}${button('繼續練習','unpause','','primary')}</div>`);}
 else if(a==='training-close'||a==='training-far'){controls.reset();match.fighters.forEach((f,i)=>{f.x=a==='training-close'?(i?760:650):(i?1000:400);f.y=594;f.vx=0;f.vy=0;f.action=null;f.stun=0;f.knock=0;});if(modal.open)unpause();}
 else if(a==='journey-next'){if(run)start(optionsForRun());}
 else if(a==='rematch'){selected.p1=finalRecord.hero;selected.p2=finalRecord.opponent;selected.mode=finalRecord.mode;if(finalRecord.journey?.mode==='story'){run=structuredClone(finalRecord.journey);start(optionsForRun());}else begin();}
 else if(a==='collection'||a==='records'){page=a;render();}
 else if(a==='dummy'){match.dummy=b.dataset.dummy;toast('對手模式：'+b.textContent);if(modal.open)unpause();}
 else if(a==='reset-training'){modal.close();const dummy=match.dummy;start({...match.options,dummy});}
 else if(a==='hitboxes'){prefs().hitboxes=!prefs().hitboxes;db.save();toast(prefs().hitboxes?'已顯示判定範圍':'已隱藏判定範圍');}
 else if(a==='bind-key'){bindTarget={group:b.dataset.group,key:b.dataset.key};b.textContent='請按新按鍵…';}
 else if(a==='reset-controls'){Object.assign(prefs(),{keys:structuredClone(CONTROLS),buttonSize:1,opacity:.85,offsetX:0,offsetY:0});db.save();applyPreferences();settings();}
}
$('#import-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2e6)throw Error('備份檔案過大');const raw=await file.text();db.replace(raw);modal.close();page='home';match=null;run=null;controls.reset();render();toast('備份已匯入');}catch(error){toast(error.message);}e.target.value='';};
modal.addEventListener('cancel',e=>{bindTarget=null;if(page==='battle'){e.preventDefault();pause();}});
function updateHud(t){if(t-hudAt<33)return;hudAt=t;for(const f of match.fighters){const i=f.index;$('#life-'+i+' i').style.width=(f.hp/f.maxHp*100)+'%';$('#life-'+i).setAttribute('aria-valuenow',Math.round(f.hp));$('#guard-'+i+' i').style.width=f.guard+'%';$('#meter-'+i+' i').style.width=f.meter+'%';$('#energy-'+i).textContent=Math.round(f.meter);$('#wins-'+i).textContent='●'.repeat(match.wins[i])+'○'.repeat(Math.max(0,match.target-match.wins[i]));}$('#round-time').textContent=match.mode==='training'?'∞':Math.ceil(match.time);$('#round-label').textContent='ROUND '+match.round;$('#fps').hidden=!prefs().showFps;$('#fps').textContent=(fps||'…')+' FPS'+(prefs().quality==='low'?' · 效能':'');$('#fps').dataset.value=String(fps);
 const p=match.fighters[0];const skill=$('[data-control="skill"]'),superButton=$('[data-control="super"]');skill.classList.toggle('unavailable',p.cooldown>0);skill.querySelector('span').textContent=p.cooldown>0?p.cooldown.toFixed(1)+'s':'技能';superButton.classList.toggle('ready',p.meter>=100);superButton.classList.toggle('unavailable',p.meter<100);
 $('#combo-label').textContent=p.combo>=2?p.combo+' HIT COMBO':match.fighters[1].combo>=2?match.fighters[1].combo+' HIT · 對手':'';
 const message=$('#combat-message');if(resumeAt){message.textContent='準備 '+Math.max(1,Math.ceil((resumeAt-t)/400));}else if(match.phase==='intro'){message.innerHTML=`第 ${match.round} 回合<small>${BY_ID[match.fighters[0].id].name} VS ${BY_ID[match.fighters[1].id].name}</small>`;}else if(match.phase==='round'){message.innerHTML=`${match.result.reason}<small>${match.result.winner<0?'平手':BY_ID[match.fighters[match.result.winner].id].name+'勝出'}</small>`;}else if(match.clock<messageUntil)message.textContent=messageText;else message.textContent='';
 if(match.mode==='training'){$('#training-stats').textContent=`累計傷害 ${Math.round(match.training.damage)} · 最長連段 ${match.training.maxCombo}`;$('#input-log').textContent=inputHistory.join(' → ');}
}
function frame(t){const elapsed=Math.min(.25,(t-lastFrame)/1000);lastFrame=t;
 if(page==='battle'&&match){if(resumeAt&&t>=resumeAt){resumeAt=0;paused=false;messageUntil=0;syncAudio();}if(!paused&&!loading&&!document.hidden){controls.poll();accumulator+=elapsed;let steps=0;while(accumulator>=DT&&steps++<15){step(match);accumulator-=DT;}}else accumulator=0;
  if(!loading){paint?.draw(match,accumulator/DT);frameCount++;if(t-fpsTime>=1000){fps=Math.round(frameCount*1000/(t-fpsTime));frameCount=0;fpsTime=t;if(!paused&&fps<40){lowWindows++;if(prefs().quality==='auto'&&lowWindows>=3){prefs().quality='low';applyPreferences();db.save();toast('已切換效能模式，保留完整戰鬥判定');}}else lowWindows=0;}updateHud(t);}
  for(const event of match.events){if(event.id<=eventCursor)continue;eventCursor=event.id;if(['hit','block','counter','super','heal'].includes(event.type))sound(event.type);if(event.type==='break'){messageText='防守崩解';messageUntil=match.clock+.8;}if(event.type==='super'){messageText=event.name;messageUntil=match.clock+.75;}if(event.type==='round')match.uiRoundAt=performance.now();}
  if(match.phase==='round'&&handledRound!==match.round&&t-(match.uiRoundAt||t)>.9*1000&&!modal.open)roundDialog();
  if(t-lastSave>5000&&!loading){capture();lastSave=t;}
 }
 requestAnimationFrame(frame);
}
window.addEventListener('resize',()=>{const wasBlocked=page==='battle'&&!$('#rotate-gate').hidden;const blocked=checkOrientation();if(wasBlocked&&!blocked)pause();paint?.resize();});document.addEventListener('visibilitychange',()=>{if(document.hidden){capture();pause('hidden');}syncAudio();});window.addEventListener('pagehide',()=>{capture();controls.reset();music?.pause();});
if(db.damaged()){root.innerHTML=`<main class="shell"><h1>先找回武鬥祭紀錄</h1><p>原始存檔已保留。請匯入先前下載的備份，避免覆蓋你的進度。</p>${button('匯入備份','import')}${button('下載原始紀錄','damaged-export')}</main>`;root.addEventListener('click',e=>{if(e.target.closest('[data-action="damaged-export"]'))download(db.damaged(),'心光對決-原始紀錄.json');});}else render();
requestAnimationFrame(frame);
