import {CONTROLS} from './cast.mjs?v=20261007-duel6';
import {command,setHeld,clearInputs} from './core.mjs?v=20261007-duel6';
export function input({getMatch,active,preferences,onPause,onAction}){const pressed=new Set(),pointers=new Map(),padPrevious=[{},{}];let destroyed=false;
 function set(index,action,value){const m=getMatch();if(!m||!active())return;if(['left','right','down','guard'].includes(action))setHeld(m,index,action,value);if(value&&['jump','light','heavy','skill','super'].includes(action)){if((action==='light'&&pressed.has(keyFor(index,'heavy')))||(action==='heavy'&&pressed.has(keyFor(index,'light'))))command(m,index,'throw');else command(m,index,action);onAction?.(index,action);} }
 const mapping=()=>preferences().keys||CONTROLS;
 function keyFor(index,action){return mapping()[index?'p2':'p1'][action];}
 function keydown(e){if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;if(e.code==='Escape'){e.preventDefault();onPause();return;}if(!active())return;const m=getMatch();for(let index=0;index<(m?.mode==='local'?2:1);index++){for(const[action,key]of Object.entries(mapping()[index?'p2':'p1']))if(e.code===key){e.preventDefault();if(!pressed.has(key)){pressed.add(key);set(index,action,true);if(action==='left'||action==='right'){const f=m.fighters[index],last=f.lastTap[action]??-100;if(m.clock-last<.24)command(m,index,action==='left'?'dashLeft':'dashRight');f.lastTap[action]=m.clock;}}}} }
 function keyup(e){pressed.delete(e.code);const m=getMatch();if(m)for(let i=0;i<2;i++)for(const[action,key]of Object.entries(mapping()[i?'p2':'p1']))if(e.code===key)setHeld(m,i,action,false);}
 function pointerdown(e){const target=e.target.closest('[data-control]');if(!target||!active())return;e.preventDefault();target.setPointerCapture(e.pointerId);const action=target.dataset.control;pointers.set(e.pointerId,{action,target});target.classList.add('pressed');if(action==='stick'){updateStick(e,target);}else{const current=[...pointers.values()].filter(p=>p.action!=='stick').map(p=>p.action);if(current.includes('light')&&current.includes('heavy'))command(getMatch(),0,'throw');else set(0,action,true);} }
 function updateStick(e,target){const r=target.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width*.35),dy=(e.clientY-r.top-r.height/2)/(r.height*.35),m=getMatch();if(!m)return;const direction=dx<-.32?'left':dx>.32?'right':null;if(e.type==='pointerdown'&&direction){const f=m.fighters[0],last=f.lastTap[direction]??-100;if(m.clock-last<.24)command(m,0,direction==='left'?'dashLeft':'dashRight');f.lastTap[direction]=m.clock;}setHeld(m,0,'left',dx<-.32);setHeld(m,0,'right',dx>.32);setHeld(m,0,'down',dy>.45);const knob=target.querySelector('.stick-knob');if(knob)knob.style.transform=`translate(${Math.max(-1,Math.min(1,dx))*25}px,${Math.max(-1,Math.min(1,dy))*25}px)`;}
 function pointermove(e){const p=pointers.get(e.pointerId);if(p?.action==='stick')updateStick(e,p.target);}
 function pointerup(e){const p=pointers.get(e.pointerId);if(!p)return;pointers.delete(e.pointerId);p.target.classList.remove('pressed');const m=getMatch();if(m){if(p.action==='stick'){for(const a of ['left','right','down'])setHeld(m,0,a,false);const knob=p.target.querySelector('.stick-knob');if(knob)knob.style.transform='';}else if(![...pointers.values()].some(v=>v.action===p.action))setHeld(m,0,p.action,false);} }
 function reset(){pressed.clear();for(const p of pointers.values()){p.target.classList.remove('pressed');const knob=p.target.querySelector('.stick-knob');if(knob)knob.style.transform='';}pointers.clear();const m=getMatch();if(m)clearInputs(m);for(let i=0;i<2;i++)padPrevious[i]={};}
 function poll(){if(!active()||destroyed)return;const pads=[...(navigator.getGamepads?.()||[])].filter(Boolean);const m=getMatch();for(let i=pads.length;i<2;i++){if(Object.keys(padPrevious[i]).length){m.fighters[i].held={};padPrevious[i]={};}}for(let i=0;i<Math.min(pads.length,m.mode==='local'?2:1);i++){const p=pads[i],last=padPrevious[i],state={left:p.axes[0]<-.3||p.buttons[14]?.pressed,right:p.axes[0]>.3||p.buttons[15]?.pressed,down:p.axes[1]>.4||p.buttons[13]?.pressed,guard:p.buttons[4]?.pressed||p.buttons[6]?.pressed,jump:p.buttons[0]?.pressed,light:p.buttons[2]?.pressed,heavy:p.buttons[3]?.pressed,skill:p.buttons[1]?.pressed,super:p.buttons[5]?.pressed};for(const[a,v]of Object.entries(state)){if(['left','right','down','guard'].includes(a))setHeld(m,i,a,!!v);else if(v&&!last[a])command(m,i,a);}if(p.buttons[9]?.pressed&&!last.pause)onPause();state.pause=p.buttons[9]?.pressed;padPrevious[i]=state;} }
 document.addEventListener('keydown',keydown);document.addEventListener('keyup',keyup);document.addEventListener('pointerdown',pointerdown,{passive:false});document.addEventListener('pointermove',pointermove,{passive:true});for(const event of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,pointerup);window.addEventListener('blur',reset);
 return{poll,reset,dispose(){destroyed=true;reset();document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',keyup);document.removeEventListener('pointerdown',pointerdown);document.removeEventListener('pointermove',pointermove);for(const event of ['pointerup','pointercancel','lostpointercapture'])document.removeEventListener(event,pointerup);window.removeEventListener('blur',reset);}};
}
