import {BY_ID,CONTROLS,STAGES} from './cast.mjs?v=20261007-duel5';
import {restore,snapshot} from './core.mjs?v=20261007-duel5';
export const KEY='cxq-heartlight-duel-v1';
const fresh=()=>({version:1,settings:{quality:'auto',reducedMotion:false,sound:true,music:true,volume:.25,buttonSize:1,opacity:.85,offsetX:0,offsetY:0,showFps:true,hitboxes:false,keys:structuredClone(CONTROLS)},story:{},records:[],unlocks:[],active:null,run:null,revision:0,savedAt:0});
function check(s){if(!s||s.version!==1||!s.settings||!['auto','high','low'].includes(s.settings.quality)||!Number.isFinite(s.settings.volume)||s.settings.volume<0||s.settings.volume>1||!s.story||typeof s.story!=='object'||Array.isArray(s.story)||!Array.isArray(s.records)||s.records.length>50||!Array.isArray(s.unlocks)||s.unlocks.some(k=>!BY_ID[k])||!Number.isInteger(s.revision)||s.revision<0)throw Error('存檔格式不正確');
 const p=s.settings;for(const[k,min,max]of [['buttonSize',.8,1.15],['opacity',.45,1],['offsetX',0,36],['offsetY',0,24]])if(!Number.isFinite(p[k])||p[k]<min||p[k]>max)throw Error('操作設定不正確');for(const k of ['reducedMotion','sound','music','showFps','hitboxes'])if(typeof p[k]!=='boolean')throw Error('設定不正確');
 for(const group of ['p1','p2']){const keys=p.keys?.[group];if(!keys||Object.keys(CONTROLS[group]).some(k=>typeof keys[k]!=='string'||!/^[A-Za-z0-9]{1,24}$/.test(keys[k])))throw Error('按鍵設定不正確');}
 for(const[id,v]of Object.entries(s.story))if(!BY_ID[id]||!Number.isInteger(v?.cleared)||v.cleared<0||v.cleared>5||typeof v.completed!=='boolean')throw Error('故事紀錄不正確');
 for(const r of s.records)if(!BY_ID[r.hero]||!BY_ID[r.opponent]||typeof r.win!=='boolean'||!Number.isFinite(r.at)||!Number.isFinite(r.combo)||r.combo<0||!Array.isArray(r.wins)||r.wins.length!==2||r.wins.some(n=>!Number.isInteger(n)||n<0||n>2))throw Error('對戰紀錄不正確');
 if(s.active)restore(s.active);if(s.run&&(!['story','survival'].includes(s.run.mode)||!BY_ID[s.run.hero]||!Number.isInteger(s.run.index)||s.run.index<0||s.run.index>(s.run.mode==='story'?4:10000)||!['easy','normal','hard'].includes(s.run.difficulty)||!STAGES.some(t=>t.id===s.run.stage)||!Number.isInteger(s.run.wins)||s.run.wins<0||!(s.run.health===null||Number.isFinite(s.run.health)&&s.run.health>0&&s.run.health<=BY_ID[s.run.hero].hp)||!Array.isArray(s.run.opponents)||s.run.opponents.length!==5||s.run.opponents.some(k=>!BY_ID[k])))throw Error('旅程紀錄不正確');return s;}
const checksum=s=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(16);};
export function pack(s){const payload=JSON.stringify(check(s));return JSON.stringify({format:'CxQ-HeartlightDuel',checksum:checksum(payload),payload});}
export function unpack(raw){const p=JSON.parse(raw);if(p.format!=='CxQ-HeartlightDuel'||typeof p.payload!=='string'||p.checksum!==checksum(p.payload))throw Error('備份完整性檢查未通過');return check(JSON.parse(p.payload));}
export function storage(){let s=fresh(),damaged=null,healthy=true;try{const raw=localStorage.getItem(KEY);if(raw)s=unpack(raw);}catch(e){try{s=unpack(localStorage.getItem(KEY+'-backup'));}catch{damaged=localStorage.getItem(KEY);healthy=false;}}
 function save(){if(damaged)return false;s.revision++;s.savedAt=Date.now();try{const raw=pack(s),old=localStorage.getItem(KEY);if(old){try{unpack(old);localStorage.setItem(KEY+'-backup',old);}catch{}}localStorage.setItem(KEY,raw);healthy=true;return true;}catch{healthy=false;return false;}}
 return{get:()=>s,save,healthy:()=>healthy,damaged:()=>damaged,replace(raw){const incoming=unpack(raw);s=incoming;damaged=null;save();return s;},capture(m,run){s.active=m?snapshot(m):null;s.run=run?structuredClone(run):null;save();},finish(record){s.active=null;s.run=null;s.records=[{...record,at:Date.now()},...s.records].slice(0,50);if(record.win&&!s.unlocks.includes(record.hero))s.unlocks.push(record.hero);save();},export:()=>pack(s)};
}
