/* Reconstruct trusted card data; never restore HTML or delayed callbacks. */
(()=>{'use strict';
function valid(v){if(!v||v.version!==1||!['4','6','8'].includes(v.settings?.diff)||!names[v.settings.mode]||!itemNames[v.settings.deck]||!['moon','forest','letter'].includes(v.settings.back)||!Number.isInteger(v.moves)||v.moves<0||!Number.isInteger(v.elapsed)||v.elapsed<0||v.elapsed>10000000||!Array.isArray(v.cards)||v.cards.length!==Number(v.settings.diff)**2)return false;const counts=new Map(),matched=new Map();for(const c of v.cards){if(!Number.isInteger(c.index)||c.index<0||c.index>15||typeof c.matched!=='boolean')return false;counts.set(c.index,(counts.get(c.index)||0)+1);if(c.matched)matched.set(c.index,(matched.get(c.index)||0)+1);}return [...counts.values()].every(n=>n%2===0)&&[...matched.values()].every(n=>n%2===0)&&v.cards.some(c=>!c.matched)&&(v.settings.mode!=='time'||v.elapsed<({'4':90,'6':190,'8':420})[v.settings.diff]);}
function preserve(){if(!state.playing||state.finished||state.lock||delays.length)return;const now=pausedAt||Date.now();data.resume={version:1,settings:{...data.settings},cards:state.cards.map(c=>({index:c.index,matched:c.matched})),moves:state.moves,elapsed:Math.max(0,Math.floor((now-state.start)/1000))};save();}
const button=document.createElement('button');button.className=document.getElementById('start').className;button.textContent='繼續上次的回憶';button.hidden=!valid(data.resume);document.getElementById('start').after(button);
button.onclick=()=>{const v=data.resume;if(!valid(v)){button.hidden=true;return;}data.settings={...data.settings,...v.settings};start();epoch++;delays=[];clearTimeout(previewTimer);pausedAt=0;state.cards=v.cards.map((c,id)=>({id,index:c.index,key:data.settings.deck+'-'+c.index,name:itemNames[data.settings.deck][c.index],matched:c.matched,up:c.matched,wrong:false,newMatch:false}));Object.assign(state,{first:null,second:null,lock:false,moves:v.moves,matched:v.cards.filter(c=>c.matched).length/2,elapsed:v.elapsed,start:Date.now()-v.elapsed*1000});renderAll();hud();say('已恢復卡片、步數與時間');};
const finishBefore=finish;finish=function(win){data.resume=null;save();button.hidden=true;return finishBefore(win)};
setInterval(()=>{preserve();button.hidden=!valid(data.resume)},2000);addEventListener('pagehide',preserve);document.addEventListener('visibilitychange',()=>{if(document.hidden)preserve()});
})();
