'use strict';
const G=(()=>{
 const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),roles=['四葉草鈴鐺','療癒毛毯','森林葉帽','回憶照片','慶典氣球','月夜貓頭鷹','守護鑰匙','心光夢線','雨露花傘','星願信封'];
 let cfg={},data={},music,unlocked=false,held=false,active=false,pauseFn=()=>{},lastSfx={},pool=new Map();const images={};
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
 function save(){try{localStorage.setItem('cxq-'+cfg.id+'-v1',JSON.stringify(data));return true}catch{toast('瀏覽器無法儲存，這次仍可繼續遊玩。');return false}}
 const sprite=(i,cls='')=>{i=clamp(Math.floor(i)||0,0,9);if(cfg.art){const c=i%5;return '<span aria-hidden="true" class="role-art styled-cast '+(i<5?'cast-a':'cast-b')+' '+cls+'" style="--x:'+(c%3*50)+'%;--y:'+(c>2?100:0)+'%"></span>'}const c=i%5;return '<span aria-hidden="true" class="role-art '+(i<5?'cast-a':'cast-b')+' '+cls+'" style="--x:'+c%3*50+'%;--y:'+(c>2?100:0)+'%"></span>'};
 function toast(t){let n=$('#notice');if(n)n.textContent=t}
 function init(options){cfg=options;const raw=read('cxq-'+cfg.id+'-v1',{});data=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};data.role=clamp(Math.floor(data.role)||0,0,9);data.music=Number.isFinite(data.music)?clamp(data.music,0,1):.23;data.sfx=Number.isFinite(data.sfx)?clamp(data.sfx,0,1):.55;data.records=data.records&&typeof data.records==='object'&&!Array.isArray(data.records)?data.records:{};data.collection=Array.isArray(data.collection)?[...new Set(data.collection.filter(x=>Number.isInteger(x)&&x>=0&&x<100))]:[];data.wins=clamp(Math.floor(data.wins)||0,0,100000);pauseFn=cfg.pause;
 music=new Audio(cfg.music);music.loop=true;music.preload='none';
 const audio=document.createElement('button');audio.id='sound';audio.className='audio-button';audio.setAttribute('aria-label','音樂與音效設定');audio.textContent='聲音';document.body.append(audio);audio.onclick=()=>{if(active)pauseFn();held=true;music.pause();const d=$('#audio-dialog');d.showModal()};
 const dialog=document.createElement('dialog');dialog.id='audio-dialog';dialog.className='paper';dialog.innerHTML='<form method="dialog"><h2>調整旅途的聲音</h2><label>背景音樂<input aria-label="背景音樂音量" type="range" data-sound="music" min="0" max="1" step=".05"></label><label>遊戲音效<input aria-label="遊戲音效音量" type="range" data-sound="sfx" min="0" max="1" step=".05"></label><button type="button" id="mute">全部靜音</button><button>收好設定</button><p><a href="../storybook/CREDITS.html" target="_blank" rel="noopener">素材與音樂來源</a></p></form>';document.body.append(dialog);dialog.querySelectorAll('input').forEach(e=>{e.value=data[e.dataset.sound];e.oninput=()=>{data[e.dataset.sound]=+e.value;music.volume=data.music;save()}});$('#mute').onclick=()=>{data.music=data.sfx=0;dialog.querySelectorAll('input').forEach(e=>e.value=0);music.pause();save()};dialog.onclose=()=>{if(!active)resumeAudio()};
 document.addEventListener('pointerdown',unlock,{passive:true});document.addEventListener('keydown',unlock);document.addEventListener('visibilitychange',()=>{if(document.hidden){music.pause();pool.forEach(a=>a.pause());if(active)pauseFn()}else if(!active)playMusic()});addEventListener('pagehide',()=>{music.pause();save()});
 addEventListener('resize',()=>orientation());return data;
 }
 function unlock(){unlocked=true;playMusic()}function playMusic(){if(unlocked&&!held&&!document.hidden&&data.music>0){music.volume=data.music;music.play().catch(()=>{})}}function resumeAudio(){held=false;playMusic()}
 const soundFiles={tap:'click1',flip:'rollover2',flag:'switch4',merge:'merge',drop:'drop',jump:'jump',step:'step',land:'land',collect:'collect',skill:'skill',miss:'switch15',win:'win',lose:'lose'};
 function sound(name='tap',rate=1){if(!unlocked||document.hidden||!data.sfx||held)return;const now=performance.now();if(now-(lastSfx[name]||0)<(name==='step'?180:65))return;lastSfx[name]=now;let a=pool.get(name);if(!a){if(cfg.sounds?.[name]){a=new Audio(cfg.sounds[name]);pool.set(name,a)}const local=['merge','drop','jump','step','land','collect','skill'].includes(name);if(!a)a=new Audio((local?'../storybook/audio/':'../shared/audio/')+soundFiles[name]+'.mp3');pool.set(name,a)}a.volume=data.sfx*(name==='step'?.35:.7);a.playbackRate=clamp(rate,.65,1.6);a.preservesPitch=false;a.currentTime=0;a.play().catch(()=>{})}
 function dialog(title,body,actions){let d=$('#game-dialog');if(!d){d=document.createElement('dialog');d.id='game-dialog';d.className='paper';document.body.append(d)}d.innerHTML=sprite(data.role,'dialog-role')+'<h2>'+title+'</h2>'+body+'<div class="dialog-actions"></div>';for(const [label,fn]of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{d.close();fn?.()};d.querySelector('.dialog-actions').append(b)}d.oncancel=e=>{e.preventDefault()};if(!d.open)d.showModal();return d}
 function rolePicker(sel,allowed=roles.map((_,i)=>i),onChange=()=>{}){if(!allowed.includes(data.role))data.role=allowed[0];const n=$(sel);n.innerHTML=allowed.map(i=>'<button class="role-choice" data-role="'+i+'" aria-pressed="'+(i===data.role)+'">'+sprite(i)+'<span>'+roles[i]+'</span></button>').join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{data.role=+b.dataset.role;save();n.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));sound('tap');onChange(data.role)});onChange(data.role)}
 async function load(names){const start=$('#start');if(start){start.disabled=true;start.dataset.label=start.textContent;start.textContent='準備美術中…'}try{await Promise.all(names.map(src=>new Promise((resolve,reject)=>{if(images[src])return resolve();const i=new Image();i.onload=()=>{images[src]=i;resolve()};i.onerror=reject;i.src=src})));if(start){start.disabled=false;start.textContent=start.dataset.label}return images}catch(e){if(start){start.disabled=false;start.textContent='重新載入圖片';start.onclick=()=>location.reload()}toast('部分圖片沒有載入，請重新載入後再開始。');throw e}}
 function tile(ctx,img,index,cols,rows,x,y,w,h){if(!img?.naturalWidth)return;const sw=img.naturalWidth/cols,sh=img.naturalHeight/rows;ctx.drawImage(img,index%cols*sw,Math.floor(index/cols)*sh,sw,sh,x,y,w,h)}
 const trims=new WeakMap();function trimTile(ctx,img,index,cols,rows,x,y,w,h){if(!img?.naturalWidth)return;let a=trims.get(img);if(!a){a={};trims.set(img,a)}if(!a[index]){const sw=Math.round(img.naturalWidth/cols),sh=Math.round(img.naturalHeight/rows),c=document.createElement("canvas");c.width=sw;c.height=sh;const t=c.getContext("2d");t.drawImage(img,index%cols*sw,Math.floor(index/cols)*sh,sw,sh,0,0,sw,sh);const d=t.getImageData(0,0,sw,sh).data;let l=sw,r=0,u=sh,b=0;for(let yy=0;yy<sh;yy++)for(let xx=0;xx<sw;xx++)if(d[(yy*sw+xx)*4+3]>120){l=Math.min(l,xx);r=Math.max(r,xx);u=Math.min(u,yy);b=Math.max(b,yy)}a[index]=[index%cols*sw+l,Math.floor(index/cols)*sh+u,Math.max(1,r-l+1),Math.max(1,b-u+1)]}ctx.drawImage(img,...a[index],x,y,w,h)}
 function drawRole(ctx,id,x,y,w,h){if(cfg.art){tile(ctx,images[cfg.art+'/cast-'+(id<5?'a':'b')+'.webp'],id%5,3,2,x,y,w,h);return}tile(ctx,images['../storybook/assets/cast-'+(id<5?'a':'b')+'.webp'],id%5,3,2,x,y,w,h)}
 function settings(ids){let p=data.preferences;if(!p||typeof p!=='object'||Array.isArray(p))p=data.preferences={};for(const id of ids){const e=$('#'+id);if(!e)continue;const v=p[id];if(e.type==='checkbox'){if(typeof v==='boolean')e.checked=v}else if(v!==undefined){if(e.tagName==='SELECT'){if([...e.options].some(o=>o.value===String(v)&&!o.disabled))e.value=String(v)}else if(Number.isFinite(Number(v))){const n=Number(v),min=e.min===''?-Infinity:+e.min,max=e.max===''?Infinity:+e.max;if(n>=min&&n<=max)e.value=String(n)}}e.dispatchEvent(new Event('change'));e.addEventListener('change',()=>{p[id]=e.type==='checkbox'?e.checked:e.value;save()})}}
 function records(bucket,score,extra={}){const list=Array.isArray(data.records[bucket])?data.records[bucket].filter(r=>r&&Number.isFinite(r.score)):[];list.push({score:Math.max(0,Math.round(score)),date:Date.now(),...extra});data.records[bucket]=list.sort((a,b)=>b.score-a.score).slice(0,10);save();return data.records[bucket][0].score}
 function recordHTML(bucket,unit='分'){const a=Array.isArray(data.records[bucket])?data.records[bucket].filter(r=>r&&Number.isFinite(r.score)):[];return a.length?'<ol>'+a.map(r=>'<li>'+Math.round(r.score)+' '+unit+' · '+new Date(Number(r.date)||0).toLocaleDateString()+'</li>').join(''):'<p>第一次冒險正在等你。</p>'}
 function orientation(){const req=typeof cfg.orientation==='function'?cfg.orientation():cfg.orientation;const mobile=innerWidth<600||navigator.maxTouchPoints>0||/Android|iPhone|Mobile/.test(navigator.userAgent);const wrong=active&&mobile&&req&&(req==='portrait'?innerWidth>innerHeight:innerHeight>innerWidth);let gate=$('#rotate');if(!gate){gate=document.createElement('div');gate.id='rotate';gate.hidden=true;gate.innerHTML='<div class="paper">'+sprite(data.role,'dialog-role')+'<h2></h2><p>遊戲已暫停，進度會保留。</p></div>';document.body.append(gate)}gate.hidden=!wrong;if(wrong){gate.querySelector('h2').textContent=req==='portrait'?'請直拿手機，讓工作區完整展開':'請橫拿手機，讓路線完整展開';pauseFn();const d=$('#game-dialog');if(d?.open){d.querySelector('h2').textContent=gate.querySelector('h2').textContent;const p=d.querySelector('p');if(p)p.textContent='遊戲已暫停。旋轉手機後，按繼續即可保留目前進度。'}}}
 function playing(value){active=value;document.body.classList.toggle("in-game",value);if(value)resumeAudio();orientation()}function hold(){held=true;music.pause();pool.forEach(a=>a.pause())}
 function frame(update,draw){let last=0;function tick(t){const dt=last?Math.min(.035,(t-last)/1000):0;last=t;update(dt);draw(t);requestAnimationFrame(tick)}requestAnimationFrame(tick)}
 return {$,clamp,roles,sprite,init,save,sound,toast,dialog,rolePicker,load,tile,trimTile,drawRole,records,recordHTML,orientation,playing,settings,hold,resumeAudio,frame,images,get data(){return data}};
})();
