/* Mobile game lobby: illustrated art is separate from touch controls and saved game state. */
(()=>{'use strict';
const id=location.pathname.split('/').find(s=>['merge','flappy','dino','mines'].includes(s)),q=s=>document.querySelector(s),home=q('#home');
const config={
 merge:{title:'球球融合',start:'開始合成',collection:'collection',collectionName:'收藏',tag:'把小心光變成大驚喜',fields:[],settings:['guide','preview']},
 flappy:{title:'星願飛行郵差',start:'起飛囉！',collection:'letters',collectionName:'信件',tag:'帶著你的角色，飛向下一站',fields:['vehicle','route'],settings:[]},
 dino:{title:'森林急件快遞',start:'出發！',collection:'journal',collectionName:'手帳',tag:'跳起來，把心意送到！',fields:['difficulty'],settings:['hand']},
 mines:{title:'四葉草探險地圖',start:'開始探險',collection:'tutorial',collectionName:'玩法',tag:'跟夥伴一起找出安全路線',fields:['mode','preset'],settings:['contrast','timer','longpress']}
}[id];if(!config||!home)return;
document.body.dataset.game=id;
const icon=(i,cls='')=>'<img aria-hidden="true" class="menu-icon '+cls+'" src="../storybook/art-20260914/'+['merge-ball-0','icon-trophy','mail','merge-ball-7','icon-gear','icon-arrow'][i]+'.webp" alt="" style="object-fit:contain;background:none">';
const source=document.createElement('div');source.id='menu-sources';source.hidden=true;while(home.firstChild)source.append(home.firstChild);document.body.append(source);
home.className='mobile-home director-home home-'+id;home.innerHTML='<header class="home-title"><small>CxQ · '+({merge:'收藏工坊',flappy:'天空出發站',dino:'森林跑酷',mines:'探險準備室'})[id]+'</small><h1>'+({dino:'斷網恐龍',flappy:'Flappy Bird',mines:'踩地雷',merge:'球球融合'})[id]+'</h1><p>'+config.tag+'</p></header><div class="cast-stage"><button class="cast-arrow previous" aria-label="上一位角色">'+icon(5)+'</button><button class="cast-hero" aria-label="選擇角色"></button><button class="cast-arrow next" aria-label="下一位角色">'+icon(5)+'</button></div><div class="cast-caption"><strong></strong><small></small></div><button class="mode-ticket" aria-label="選擇模式與冒險">'+icon(3)+'<span><b></b><small>點選冒險</small></span></button><nav class="lobby-dock" aria-label="遊戲選單"></nav>';
const play=q('#start');play.classList.add('lobby-start');play.dataset.label=config.start;if(!play.disabled)play.textContent=config.start;home.append(play);
const sheets=[];
function sheet(title){const d=document.createElement('dialog');d.className='menu-sheet paper';d.innerHTML='<header class="sheet-header"><h2>'+title+'</h2><button class="sheet-close" aria-label="關閉'+title+'">完成</button></header><div class="sheet-content"></div>';document.body.append(d);d.querySelector('.sheet-close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.addEventListener('close',()=>update());sheets.push(d);return d}
function open(d){update();d.showModal();d.querySelector('.sheet-content').scrollTop=0;G.sound('tap')}
const castSheet=sheet('選一位夥伴'),adventure=sheet(id==='dino'?'準備出勤':'選擇冒險'),settings=sheet('遊玩設定');
castSheet.id='character-sheet';adventure.id='adventure-sheet';settings.id='play-settings-sheet';
const roles=q('#roles');castSheet.querySelector('.sheet-content').append(roles);
const detail=document.createElement('p');detail.className='character-detail';castSheet.querySelector('.sheet-content').append(detail);
const allowed=[...roles.querySelectorAll('[data-role]')].map(b=>+b.dataset.role);
const skillText={2:'森林輕躍 · 葉披風讓下落更輕緩',0:'幸運吸信 · 靠近信件就能收集',1:'毛毯守護 · 抵擋一次碰撞',5:'月光緩行 · 放慢沿途障礙',3:'回憶信箋 · 每封信件算兩封',4:'快樂節奏 · 收信時短暫緩行',6:'信任守護 · 抵擋一次碰撞',7:'夢想輕躍 · 下落更輕緩',8:'雨中滑行 · 下滑維持一秒',9:'希望採集 · 擴大收信範圍'};
function choose(delta){const n=allowed.indexOf(G.data.role);roles.querySelector('[data-role="'+allowed[(n+delta+allowed.length)%allowed.length]+'"]').click();update()}
q('.cast-arrow.previous').onclick=()=>choose(-1);q('.cast-arrow.next').onclick=()=>choose(1);
let touch=null,swiped=false;const hero=q('.cast-hero');hero.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY}});hero.addEventListener('pointerup',e=>{if(touch&&Math.abs(e.clientX-touch.x)>40&&Math.abs(e.clientY-touch.y)<65){choose(e.clientX<touch.x?1:-1);swiped=true}touch=null});hero.addEventListener('pointercancel',()=>touch=null);hero.onclick=()=>{if(swiped){swiped=false;return}open(castSheet)};
roles.addEventListener('click',()=>update());q('.mode-ticket').onclick=()=>open(adventure);
const dock=q('.lobby-dock');function dockButton(label,i,fn,existing){const b=existing||document.createElement('button');b.classList.add('dock-button');b.innerHTML=icon(i)+'<span>'+label+'</span>';b.setAttribute('aria-label',label);if(fn)b.onclick=fn;dock.append(b);return b}
dockButton('夥伴',0,()=>open(castSheet));if(id!=='dino')dockButton(config.collectionName,2,null,q('#'+config.collection));dockButton('紀錄',1,null,q('#records'));dockButton('設定',4,()=>open(settings));
const labels={difficulty:'選擇難度',mode:'想怎麼玩？',mission:'這次收集什麼？',theme:'工坊外觀',stage:'選擇郵站',route:'想飛去哪裡？',vehicle:'選擇飛行載具',trail:'飛行尾跡',preset:'選一張地圖',hand:'慣用操作',guide:'落點提示',preview:'下一顆預覽',contrast:'清楚數字',timer:'顯示計時',longpress:'長按插旗時間'};
const names={classic:'經典合成',mission:id==='merge'?'收藏任務':id==='flappy'?'送信闖關':'配送闖關',practice:id==='mines'?'提示練習':'輕鬆練習',endless:id==='flappy'?'一般模式':'無盡挑戰',standard:'經典探險',logic:'推理解謎',easy:'小小探險',medium:'森林尋寶',hard:'秘境挑戰',custom:'自己畫地圖',warm:'翡翠工坊',night:'月光工坊',sky:'晨光雲海',forest:'森林郵路',moon:'月夜郵路',left:'左手跳躍',right:'右手跳躍'};
const fields=[];
const quickStops=[];if(false){const stops=document.createElement('div');stops.className='map-stops';stops.setAttribute('aria-label','選擇地圖大小');for(const [value,label]of [['easy','初級'],['medium','中級'],['hard','高級']]){const b=document.createElement('button');b.innerHTML=icon(3)+'<span>'+label+'</span>';b.dataset.preset=value;b.onclick=()=>{q('#preset').value=value;q('#preset').dispatchEvent(new Event('change'));G.sound('tap');update()};stops.append(b);quickStops.push(b)}home.append(stops)}
function field(selectId,parent){const select=q('#'+selectId);if(!select)return;const section=document.createElement('section');section.className='choice-section';section.dataset.field=selectId;section.innerHTML='<h3>'+labels[selectId]+'</h3><div class="choice-grid"></div>';parent.append(section);fields.push({select,section});select.addEventListener('change',update);return section}
config.fields.forEach(x=>field(x,adventure.querySelector('.sheet-content')));

if(id==='mines'){const custom=q('#custom');custom.className='custom-map';adventure.querySelector('.sheet-content').append(custom);for(const input of custom.querySelectorAll('input')){const wrap=document.createElement('span');wrap.className='number-stepper';input.replaceWith(wrap);const minus=document.createElement('button'),plus=document.createElement('button');minus.textContent='−';plus.textContent='＋';minus.type=plus.type='button';wrap.append(minus,input,plus);minus.onclick=()=>{input.stepDown();input.dispatchEvent(new Event('change'))};plus.onclick=()=>{input.stepUp();input.dispatchEvent(new Event('change'))}}}
for(const key of config.settings){const el=q('#'+key);if(el.tagName==='SELECT'){field(key,settings.querySelector('.sheet-content'));continue}const section=document.createElement('section');section.className='choice-section';if(el.type==='checkbox'){const b=document.createElement('button');b.className='toggle-choice';b.innerHTML=icon(5)+'<span>'+labels[key]+'</span><b></b>';const sync=()=>{b.setAttribute('aria-pressed',el.checked);b.querySelector('b').textContent=el.checked?'開':'關'};b.onclick=()=>{el.checked=!el.checked;el.dispatchEvent(new Event('change'));sync();G.sound('tap')};sync();section.append(b)}else{section.innerHTML='<h3>'+labels[key]+'</h3>';section.append(el);section.append(q('#longpress-label'))}settings.querySelector('.sheet-content').append(section)}
const soundShortcut=document.createElement('button');soundShortcut.className='sound-shortcut';soundShortcut.innerHTML=icon(4)+'音樂與音效';soundShortcut.onclick=()=>{settings.close();q('#sound').click()};settings.querySelector('.sheet-content').append(soundShortcut);
const tip=document.createElement('p');tip.className='sheet-tip';tip.textContent=id==='merge'?'移動手指選落點，放開就投球。':id==='flappy'?'點一下往上飛，放開慢慢降落。':id==='dino'?'橫拿手機：短按跳躍、長按跳高，低枝葉用下滑。':'點格子探索，長按插旗；第一格和周圍都安全。';settings.querySelector('.sheet-content').append(tip);
const originalBack=q('.topbar a');
if(originalBack){
  originalBack.remove();
  originalBack.setAttribute('aria-label','回到網站首頁');
}
const topbarHint=q('.topbar small');
if(topbarHint){topbarHint.textContent='';}
const sound=q('#sound');sound.innerHTML=icon(4);sound.classList.add('mobile-sound');
function optionArt(key,option,index){if(key==='route'){const file={sky:'scene',forest:'forest',moon:'moon'}[option.value];return '<img class="choice-scene" src="../storybook/art-20260920-batch/flappy-'+file+'.webp" alt="">'}if(key==='theme')return '<img class="choice-scene" src="art-v2/'+(option.value==='night'?'night':'scene')+'.webp" alt="">';if(key==='vehicle')return '<img class="vehicle-art" src="'+(window.CxQFlightArt?.(G.data.role,Number(option.value))||'../storybook/art-20260920-batch/flight-hope.webp')+'" alt="">';if(key==='stage')return '<span class="stage-number">'+option.value+'</span>';return icon(key==='mode'?(index===0?5:index===1?3:2):3)}
function update(){document.body.classList.toggle('lobby-open',!home.hidden);const r=G.data.role;hero.innerHTML=id==='flappy'?'<img class="role-art" src="'+window.CxQFlightArt(r,Number(q('#vehicle').value))+'" alt="'+G.roles[r]+'">':G.sprite(r);q('.cast-caption strong').textContent=G.roles[r];q('.cast-caption small').textContent=id==='dino'?skillText[r]:id==='merge'?companionSkills[r]+' · 每局一次':'左右切換 · 點角色更換';detail.textContent=id==='dino'?skillText[r]:id==='merge'?companionSkills[r]+'：經典合成中可使用一次。':'已選擇 '+G.roles[r]+'，會陪你一起冒險。';q('.mode-ticket').hidden=id==='merge';q('.mode-ticket').setAttribute('aria-label',id==='dino'?'選擇難度':id==='flappy'?'選擇載具與航線':'選擇難度與棋盤');q('.mode-ticket b').textContent=id==='dino'?q('#difficulty').selectedOptions[0].textContent:id==='flappy'?q('#vehicle').selectedOptions[0].textContent:id==='mines'?q('#preset').selectedOptions[0].textContent.split(' · ').slice(0,2).join(' · '):'經典合成';q('.mode-ticket small').textContent=id==='dino'?'正常玩法 · 不需解鎖':id==='flappy'?'更換載具與航線':id==='mines'?'設定棋盤與玩法':'相同球碰撞即可合成';
for(const b of quickStops){b.disabled=q('#preset').disabled;b.setAttribute('aria-pressed',q('#preset').value===b.dataset.preset)}
for(const {select,section}of fields){section.hidden=select.id==='mission'&&q('#mode').value!=='mission';const grid=section.querySelector('.choice-grid');grid.innerHTML='';[...select.options].forEach((o,i)=>{const b=document.createElement('button');b.type='button';b.className='choice-card';b.dataset.option=o.value;b.disabled=o.disabled||select.disabled;b.setAttribute('aria-pressed',select.value===o.value);let title=select.id==='difficulty'?o.textContent:names[o.value]||o.textContent.split(' · ')[0];if(select.id==='stage')title='第 '+o.value+' 站';if(select.id==='mission')title=o.textContent.replace('合成','').split(' · ')[0];b.innerHTML=optionArt(select.id,o,i)+'<strong></strong><small></small>';b.querySelector('strong').textContent=title;b.querySelector('small').textContent=b.disabled?(select.disabled?'此模式不使用':'尚未解鎖'):select.value===o.value?'已選擇':'選這個';b.onclick=()=>{select.value=o.value;select.dispatchEvent(new Event('change'));G.sound('tap');update();section.querySelector('[data-option="'+o.value+'"]')?.focus()};grid.append(b)})}}
new MutationObserver(update).observe(home,{attributes:true,attributeFilter:['hidden']});new MutationObserver(()=>{if(!home.hidden)update()}).observe(roles,{attributes:true,subtree:true,attributeFilter:['aria-pressed']});
if(id==='dino'){q('#jump').innerHTML=icon(5)+'<span>跳躍</span>';q('#slide').innerHTML=icon(5)+'<span>下滑</span>'}
if(id==='merge'){q('.mobile-drop').before(q('#ability'));q('#ability').classList.add('companion-ability');}
if(id==='mines'){q('#hint').textContent='提示';q('#pause').textContent='暫停';for(const input of q('#custom').querySelectorAll('input')){const label={rows:'列數',cols:'欄數',mines:'陷阱數'}[input.id],buttons=input.parentElement.querySelectorAll('button');buttons[0].setAttribute('aria-label','減少'+label);buttons[1].setAttribute('aria-label','增加'+label)}}
if(id==='mines'){q('#reveal-mode').textContent='翻格';q('#flag-mode').textContent='插旗';const help=q('#hint').onclick;q('#hint').onclick=()=>{help();q('.field-notes').classList.add('show-hint')};new MutationObserver(()=>{if(!home.hidden)q('.field-notes').classList.remove('show-hint')}).observe(home,{attributes:true,attributeFilter:['hidden']})}
const feedback=document.createElement('p');feedback.className='menu-feedback';feedback.setAttribute('role','alert');feedback.hidden=true;adventure.querySelector('.sheet-content').prepend(feedback);new MutationObserver(()=>{const text=q('#notice').textContent;if(text.startsWith('自訂地圖：')){feedback.textContent=text;feedback.hidden=false;if(!adventure.open)open(adventure)}}).observe(q('#notice'),{childList:true,characterData:true,subtree:true});
if(id==='mines')q('#custom').addEventListener('input',()=>{feedback.hidden=true});
update();
})();
