const TT=['start','land','land','event','land','card','land','mini','land','shop','land','event','land','npc','land','card','land','mini','land','event','land','shop','land','npc','land','event','land','card','land','mini','land','event','land','shop','land','npc'];const TL={start:'起點',land:'土地',event:'事件',card:'卡片',mini:'小遊戲',shop:'商店',npc:'奇遇'};
function makeBoard(){const pts=[];for(let i=0;i<10;i++)pts.push([400+i*285,1690]);for(let i=1;i<=5;i++)pts.push([2965,1690-i*275]);for(let i=1;i<=10;i++)pts.push([2965-i*255,315]);for(let i=1;i<=5;i++)pts.push([415,315+i*275]);for(let i=1;i<=6;i++)pts.push([415+i*360,1690]);const path=pts.slice(0,36).map((p,i)=>({x:p[0],y:p[1],type:TT[i],owner:-1,lv:0,price:9000+(i%5)*1800,rent:1200+(i%4)*550}));const players=actives().map((si,id)=>({id,seat:si,type:S.seats[si].type,char:S.seats[si].char,cash:S.money,pos:0,alive:true}));S.board={worldW:3500,worldH:2050,path,players,turn:0,round:1,cam:{x:0,y:0},moving:null,popup:null,target:null};focus(true);S.msg='輪到 '+(players[0].id+1)+'P';}
function cp(){return S.board.players[S.board.turn]}
function focus(instant=false){const b=S.board,p=cp(),t=b.path[p.pos],tx=Math.max(0,Math.min(b.worldW-W,t.x-W/2)),ty=Math.max(0,Math.min(b.worldH-H,t.y-H/2));if(instant){b.cam.x=tx;b.cam.y=ty}else b.target={x:tx,y:ty};}
function tcol(t){return {start:'#e2ad2f',land:'#6c9f69',event:'#c76274',card:'#5277b9',mini:'#9169bd',shop:'#cb8248',npc:'#4f9b98'}[t]||'#777'}
function tileIcon(type){X.save();X.lineWidth=5;X.strokeStyle='#fff8df';X.fillStyle='rgba(255,250,224,.18)';if(type==='start'){X.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?12:25,px=Math.cos(a)*r,py=Math.sin(a)*r;i?X.lineTo(px,py):X.moveTo(px,py);}X.closePath();X.fill();X.stroke();}else if(type==='land'){X.beginPath();X.moveTo(-26,3);X.lineTo(0,-22);X.lineTo(26,3);X.lineTo(22,3);X.lineTo(22,25);X.lineTo(-22,25);X.lineTo(-22,3);X.closePath();X.fill();X.stroke();}else if(type==='event'){X.beginPath();X.arc(0,0,25,0,Math.PI*2);X.fill();X.stroke();txt('!',0,2,30,'center','#fff',1000,false);}else if(type==='card'){rr(-25,-20,38,50,5);X.fill();X.stroke();rr(-10,-28,38,50,5);X.fill();X.stroke();}else if(type==='mini'){rr(-30,-20,60,40,14);X.fill();X.stroke();X.beginPath();X.moveTo(-18,0);X.lineTo(-6,0);X.moveTo(-12,-6);X.lineTo(-12,6);X.stroke();X.beginPath();X.arc(14,-5,4,0,Math.PI*2);X.arc(22,5,4,0,Math.PI*2);X.fill();}else if(type==='shop'){X.beginPath();X.moveTo(-28,-10);X.lineTo(-20,-26);X.lineTo(20,-26);X.lineTo(28,-10);X.closePath();X.fill();X.stroke();rr(-24,-8,48,34,5);X.fill();X.stroke();}else if(type==='npc'){X.beginPath();X.arc(0,-9,13,0,Math.PI*2);X.fill();X.stroke();X.beginPath();X.arc(0,28,25,Math.PI,0);X.fill();X.stroke();}X.restore();}
function drawTile(t,i){X.save();X.translate(t.x,t.y);X.shadowColor='rgba(0,0,0,.40)';X.shadowBlur=10;rr(-82,-46,164,92,17);X.fillStyle=tcol(t.type);X.fill();X.shadowColor='transparent';X.lineWidth=5;X.strokeStyle=t.owner>=0?['#df4a56','#4088da','#56a261','#d1a032'][t.owner]:'#f5dfa2';X.stroke();X.globalAlpha=.30;rr(-72,-36,144,72,13);X.fillStyle='#fff';X.fill();X.globalAlpha=1;X.save();X.translate(0,-5);X.scale(.72,.72);tileIcon(t.type);X.restore();txt(i===0?'START':TL[t.type],0,30,13,'center','#fff',900,true);if(t.owner>=0){X.fillStyle=['#df4a56','#4088da','#56a261','#d1a032'][t.owner];X.fillRect(-82,-46,164,9);txt((t.owner+1)+'P Lv.'+(t.lv||1),0,-35,11,'center','#fff',900,false);}X.restore();}
function world(){const b=S.board;if(I.bg.complete&&I.bg.naturalWidth){for(let xx=0;xx<b.worldW;xx+=1600)for(let yy=0;yy<b.worldH;yy+=900)X.drawImage(I.bg,xx,yy,1600,900);}else{X.fillStyle='#89bd91';X.fillRect(0,0,b.worldW,b.worldH);}}
function drawGame(){const b=S.board,p=cp();if(b.target){b.cam.x+=(b.target.x-b.cam.x)*.09;b.cam.y+=(b.target.y-b.cam.y)*.09;if(Math.hypot(b.target.x-b.cam.x,b.target.y-b.cam.y)<1)b.target=null;}X.save();X.translate(-b.cam.x,-b.cam.y);world();for(let i=0;i<b.path.length;i++){const t=b.path[i];drawTile(t,i);if(t.type==='land'&&t.lv>0)contain(I.house,t.x-68,t.y-178,136,116,1);}for(const q of b.players){if(!q.alive)continue;const t=b.path[q.pos],off=(q.id-(b.players.length-1)/2)*35;contain(I['c'+q.char],t.x-60+off,t.y-158,120,120,1);}X.restore();panel(20,18,340,88*b.players.length+22,24,'rgba(18,26,43,.9)','rgba(235,195,102,.7)',3);b.players.forEach((q,i)=>{const y=38+i*86;contain(I['c'+q.char],32,y,62,62,1);txt((q.id+1)+'P '+(q.type==='ai'?'AI':'玩家'),106,y+19,17,'left',['#ff7279','#6caeff','#78cf81','#ffd166'][q.id],900,true);txt('$'+Math.floor(q.cash).toLocaleString(),106,y+51,17,'left','#fff',800,false);});panel(618,20,364,68,24,'rgba(20,28,48,.9)','rgba(236,197,104,.7)',3);txt('第 '+b.round+' / '+S.rounds+' 回合',800,54,26,'center','#fff1bf',900,true);btn('exitGame','選角',1370,25,190,58,{kind:'dark',size:22});btn('roll','擲骰子',1260,735,285,104,{kind:'gold',size:35,enabled:p.type==='human'&&!b.moving&&!b.popup&&!S.rolling});dice(1184,788,82,S.dice);txt(S.msg||('輪到 '+(p.id+1)+'P'),800,842,22,'center','#fff',850,true);if(b.popup)drawPopup();}
function drawPopup(){const b=S.board,p=cp(),t=b.path[p.pos];X.fillStyle='rgba(4,8,18,.62)';X.fillRect(0,0,W,H);panel(465,260,670,370,32,'rgba(24,28,44,.98)','rgba(245,202,103,.92)',5);if(b.popup==='land'){const mine=t.owner===p.id,free=t.owner<0;txt(free?'發現可購買土地':mine?'自己的土地':'需要支付租金',800,318,34,'center','#fff0bb',1000,true);txt('土地價值 $'+t.price.toLocaleString(),800,378,23,'center','#fff',800,false);if(free){btn('buy','購買土地',570,482,220,72,{kind:'green',size:25,enabled:p.cash>=t.price});btn('skipBuy','略過',810,482,220,72,{kind:'dark',size:25});}else if(mine){const cost=Math.round(t.price*.45);txt('升級費用 $'+cost.toLocaleString(),800,425,21,'center','#fff',750,false);btn('upgrade','升級房屋',570,492,220,72,{kind:'gold',size:25,enabled:t.lv<3&&p.cash>=cost});btn('skipBuy','完成',810,492,220,72,{kind:'dark',size:25});}else{const amt=t.rent*(1+Math.max(0,t.lv-1));txt('租金 $'+amt.toLocaleString(),800,425,21,'center','#fff',750,false);btn('payRent','支付租金',690,500,220,72,{kind:'red',size:25});}}else{txt('事件觸發',800,325,36,'center','#fff0bb',1000,true);txt(S.msg,800,410,24,'center','#fff',800,false);btn('eventOk','確定',690,500,220,72,{kind:'blue',size:25});}}
function land(){const b=S.board,p=cp(),t=b.path[p.pos];if(t.type==='land'){b.popup='land';return;}if(t.type==='event'){const d=Math.random()<.5?3000:-2000;p.cash+=d;S.msg=(d>0?'幸運事件 +$':'突發支出 $')+Math.abs(d).toLocaleString();b.popup='event';return;}if(t.type==='card'){p.cash+=1200;S.msg='獲得卡片獎勵 +$1,200';b.popup='event';return;}if(t.type==='mini'){p.cash+=1800;S.msg='小遊戲快速結算 +$1,800';b.popup='event';return;}if(t.type==='shop'){S.msg='商店本層將在下一輪美術重建';b.popup='event';return;}if(t.type==='npc'){const d=Math.random()<.5?2500:-1500;p.cash+=d;S.msg=(d>0?'遇到好運精靈 +$':'遇到搗蛋精靈 -$')+Math.abs(d).toLocaleString();b.popup='event';return;}next();}
function next(){const b=S.board;b.popup=null;b.turn++;if(b.turn>=b.players.length){b.turn=0;b.round++;}if(b.round>S.rounds){S.msg='本局回合結束';return;}focus(false);S.msg='輪到 '+(cp().id+1)+'P';save();if(cp().type==='ai')setTimeout(ai,700);}
function roll(){if(S.rolling||S.board.moving)return;S.rolling=true;let n=0;const timer=setInterval(()=>{S.dice=1+Math.floor(Math.random()*6);if(++n>8){clearInterval(timer);S.rolling=false;move(S.dice);}},70);}
function move(steps){const b=S.board,p=cp();b.moving={left:steps};function one(){if(!b.moving||b.moving.left<=0){b.moving=null;land();return;}p.pos=(p.pos+1)%b.path.length;if(p.pos===0)p.cash+=5000;b.moving.left--;focus(false);setTimeout(one,210);}one();}
function ai(){const b=S.board;if(!b||cp().type!=='ai'||b.popup)return;S.dice=1+Math.floor(Math.random()*6);setTimeout(()=>move(S.dice),380);}
function save(){if(!S.board)return;try{localStorage.setItem('cxq_v4_save',JSON.stringify({settings:{seats:S.seats,money:S.money,rounds:S.rounds},board:S.board}));}catch(e){}}
function guide(){S.overlay='guide'}function settings(){S.overlay='settings'}
function drawOverlay(){if(!S.overlay)return;X.fillStyle='rgba(4,8,18,.72)';X.fillRect(0,0,W,H);panel(430,215,740,470,34,'rgba(26,29,47,.98)','rgba(243,201,101,.92)',5);txt(S.overlay==='guide'?'遊戲說明':'設定',800,270,42,'center','#fff0bb',1000,true);if(S.overlay==='guide'){['擲骰逐格前進','購買土地並升級房屋','對手踩到時收取租金','卡片、事件、NPC與神明改變局勢','回合結束後以總資產排名'].forEach((a,i)=>txt('• '+a,520,350+i*55,24,'left','#fff',750,false));}else{txt('這一層先完成首頁、選角與開局流程。',800,382,24,'center','#fff',750,false);txt('音效、三語系、畫質與完整設定會逐層接回。',800,435,21,'center','#dbe2f2',700,false);}btn('close','關閉',650,585,300,66,{kind:'violet',size:25});}
function click(id){if(id==='homeStart'){S.scene='select';S.msg='';}else if(id==='homeContinue'){S.scene='select';}else if(id==='homeGuide')guide();else if(id==='homeSettings')settings();else if(id==='close')S.overlay=null;else if(id==='selBack')S.scene='home';else if(id.startsWith('char'))pick(+id.slice(4));else if(id.startsWith('seat'))S.activeSeat=+id.slice(4);else if(id.startsWith('human')){const i=+id.slice(5);S.activeSeat=i;S.seats[i].type='human';S.msg=(i+1)+'P 已設為真人';}else if(id.startsWith('ai')){const i=+id.slice(2);S.activeSeat=i;S.seats[i].type='ai';S.msg=(i+1)+'P 已設為 AI';}else if(id.startsWith('off')){const i=+id.slice(3);S.activeSeat=i;S.seats[i].type='off';S.msg=(i+1)+'P 已設為空席';}else if(id==='diffEasy')S.seats[S.activeSeat].diff='easy';else if(id==='diffStandard')S.seats[S.activeSeat].diff='standard';else if(id==='diffSmart')S.seats[S.activeSeat].diff='smart';else if(id==='money'){S.money=S.money===300000?500000:S.money===500000?100000:300000;}else if(id==='move'){S.move=S.move==='擲骰前進'?'雙骰模式':'擲骰前進';}else if(id==='land'){S.land=S.land==='無限制'?'區域限制':'無限制';}else if(id==='rounds'){S.rounds=S.rounds===20?30:S.rounds===30?45:S.rounds===45?60:20;}else if(id==='win'){S.win=S.win==='總資產最高'?'最後存活':'總資產最高';}else if(id==='startMatch'){if(!ready()){S.msg='至少需要 2 名參賽者，且至少 1 名真人';return;}makeBoard();S.scene='game';setTimeout(()=>{if(cp().type==='ai')ai()},500);}else if(id==='exitGame')S.scene='select';else if(id==='roll')roll();else if(id==='skipBuy'||id==='eventOk')next();else if(id==='buy'){const p=cp(),t=S.board.path[p.pos];if(p.cash>=t.price){p.cash-=t.price;t.owner=p.id;t.lv=1;}next();}else if(id==='upgrade'){const p=cp(),t=S.board.path[p.pos],c=Math.round(t.price*.45);if(t.lv<3&&p.cash>=c){p.cash-=c;t.lv++;}next();}else if(id==='payRent'){const p=cp(),t=S.board.path[p.pos],amt=t.rent*(1+Math.max(0,t.lv-1)),own=S.board.players[t.owner];p.cash-=amt;own.cash+=amt;next();}}
C.addEventListener('pointerup',e=>{const r=C.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*W,py=(e.clientY-r.top)/r.height*H,b=[...S.buttons].reverse().find(z=>z.en&&px>=z.x&&px<=z.x+z.w&&py>=z.y&&py<=z.y+z.h);if(b)click(b.id);});
function loop(){frame();S.t+=1/60;if(S.scene==='home')drawHome();else if(S.scene==='select')drawSelect();else if(S.scene==='game')drawGame();drawOverlay();requestAnimationFrame(loop);}loop();
